### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by Tsyklop** [MrTJP/ProjectRed#1000]
crash when trying to create a world:

Crash: http://pastebin.com/tgv6xGvT
log file: [fml-client-latest.txt](https://github.com/MrTJP/ProjectRed/files/135790/fml-client-latest.txt)

ProjectRed-1.7.10-4.7.0pre12.95

**Comment by MrTJP** [comment]
ProjectRed is not mentioned anywhere in that crash report. Something called 'WeatherSystem' is the likely cause.
