### ISSUE TITLE
Auto crafter using wrong oredict entries

### ISSUE THREAD

**Issue by kas-luthor** [MrTJP/ProjectRed#1002]
When using the auto crafter with recipes having oredict items the wrong items get used to create the crafting output if there's more than one recipe that uses an item with a generic oredict name

In this specific case I was trying to create orange illumar with vanilla orange dye (registered as "dyeOrange" and "dye") and glowstone. I also had recipes for other variants of illumar installed. When the recipe cycling hit the recipe for magenta illumar the orange dye was consumed and magenta illumar was crafted.

![2016-02-23_08 09 35](https://cloud.githubusercontent.com/assets/16035731/13248482/d8592c1c-da1e-11e5-8cb8-9faeee109faa.png)
![2016-02-23_08 09 55](https://cloud.githubusercontent.com/assets/16035731/13248481/d7d58f6a-da1e-11e5-819a-ff251a927372.png)
![2016-02-23_08 10 03](https://cloud.githubusercontent.com/assets/16035731/13248479/d77e0f42-da1e-11e5-9172-c2ecbded800c.png)

**Comment by MrTJP** [comment]
Will look into this...
