### ISSUE TITLE
Config file overwritten everytime

### ISSUE THREAD

**Issue by DinnerBuffet** [MrTJP/ProjectRed#1003]
It seems a build after v4.7.0pre9 broke the config files (probably v4.7.0pre10). I had an issue on my client where the config file would be overwritten every time I tried to start the game. This was an issue because I also had Mariculture installed, which has a conflicting enchantment ID. Doesn't seem to happen on the server.

Steps to reproduce:

1) Install Mariculture and ProjectRed on a fresh client profile (using forge-1.7.10-10.13.4.1614-1.7.10)
2) Start the game
3) Error: conflicting enchantment ID: 80
4) Change the enchantment ID in the config file to 101.
5) Start the game again
6) Error: conflicting enchantment ID: 80

Reverting back to v4.7.0pre9 fixes the problem.

**Comment by MrTJP** [comment]
Is the config file fresh? Or are you still using the same one from old versions?

**Comment by DinnerBuffet** [comment]
Ah you called it. I was copying an old file and didn't think about other changes. My apologies.
