### ISSUE TITLE
silver ignot

### ISSUE THREAD

**Issue by nailfor** [MrTJP/ProjectRed#1004]
I'm installed the mod project red in my server(base, compat, integration, lighting), this mod registred silver ignot. Now i'm can't infuse Covetous Coin from WitchingGadgets, because there is not silver ingot and world haven't silver ore
Please, unregistered silver ignot, they don't use of any crafts

**Comment by MrTJP** [comment]
The silver ingot is properly registered in the dictionary, and PR adds its own ore, which is configurable. No reason you can't work around whatever issue you are having.
