### ISSUE TITLE
Crash on specific location (ProjectRed Exploration)

### ISSUE THREAD

**Issue by TeroBlaZe** [MrTJP/ProjectRed#1005]
Can someone tell me please what exactly heppened? I stuck on this location.

http://pastebin.com/P61gvjjE

**Comment by bookerthegeek** [comment]
First, edit your post and post the log to pastebin and place the link in your edited post.

**Comment by TeroBlaZe** [comment]
@bookerthegeek Sorry, my bad. So?

**Comment by TeroBlaZe** [comment]
I found several Barrels which caused server to crash using McEdit. After deleting broken tiles I at last was able to join a game. Placement of new Barrels at the same spots didn't caused crash anymore. The reason is still unknown. [Screenshot](http://i.imgur.com/sh0Te2O.png)

**Comment by MrTJP** [comment]
The cause is because the barrel had contained a mod item that has since been removed from the game. This will be fixed in the next version.

**Comment by TeroBlaZe** [comment]
@MrTJP Thanks. BTW Item NBT Inspector shows no difference between broken and normal barrels. One thing which contained in one of 3 broken barrels was minecraft:log.

As soon as it will be fixed I'll test the issue again later.
