### ISSUE TITLE
Crash when loading Project red

### ISSUE THREAD

**Issue by ihatenoobss422** [MrTJP/ProjectRed#1006]
(Does not happen when running without Mechanical)
[crash-2016-03-07_16.10.13-client.txt](https://github.com/MrTJP/ProjectRed/files/162334/crash-2016-03-07_16.10.13-client.txt)

**Comment by DonDidDon** [comment]
Got exact same problem, Without this, it runs smoothly.
Mechanical is a rather important part of P-Red, IMO. Tho' WE got loads more mods on our game.

**Comment by MrTJP** [comment]
I think there is an accidental dependency on Integration. Install that for now, I'll fix it for the next version.

**Comment by DonDidDon** [comment]
I got integration installed too, still get an Error, Not sure why. I even tried pre10.xxx but that caused MORE errors (which i kinda knew, but hoped would still work :P )

**Comment by ihatenoobss422** [comment]
The update fixed the issue. Thanks!
