### ISSUE TITLE
Tinker's Construct integration breaks Signalum/Smeltery recipe

### ISSUE THREAD

**Issue by Almagnus1** [MrTJP/ProjectRed#1009]
I'm in the process of integration testing for a modpack I'm going to be hosting on Curse, and I believe this is coming from the 1.7.10 version of Redstone Compatilbity (currently 4.7.0 pre12.95 in the modpack), and noticed that your Tinker's Smeltery recipe is replacing the Thermal Foundation's Destabilized Redstone with the Project Red version of Liquid Redstone.

This leads me to my question: Why not just use Destabilized Redstone instead of Liquid Redstone?

**Comment by MrTJP** [comment]
Because then Thermal Foundation would need to be installed for this Tinker's Construct integration would no longer just be Tinker's Construct.

For now, just use the configs to disable the Tinker's Construct integration.
