### ISSUE TITLE
Tinker's/Thermal Integration Suggestion

### ISSUE THREAD

**Issue by Almagnus1** [MrTJP/ProjectRed#1010]
When the ProjectRed compatibility flags for Tinker's Construct and Thermal Foundation are enabled, would be it be possible to migrate from Liquid Redstone to Destabilized Redstone in the smeltery?

This will prevent the issue with Thermal Foundation's where the Signalum smeltery recipe (and also anything that requires filling of destabilized redstone), while also allowing for the other metal recipes to be used from ProjectRed.

**Comment by AnrDaemon** [comment]
I've resolved recipes for myself using MineTweaker. Destabilized redstone requires a bit of glowstone for me, to warrant higher temps, and thus the use of Blazing Pyrotheum.

**Comment by covers1624** [comment]
Tinkers integration has been removed as of 1.10.
