### ISSUE TITLE
Crash when adding "Mechanical" Module of Project Red

### ISSUE THREAD

**Issue by DonDidDon** [MrTJP/ProjectRed#1011]
Here is my Crash Report, maybe Mr TJP or someone else can see what's up.
I guess it's a mod conflict more then anything else.
I'd just like to know that at the very least.

[crash-2016-03-17_16.37.21-client.txt](https://github.com/MrTJP/ProjectRed/files/178175/crash-2016-03-17_16.37.21-client.txt)

Hopefully someone can track down what goes on.

Which of Project Red Modules add the Timer and the Toggle switch thingies? cause it's actually the only things we use aside from the cables. We got other mods that does nearly everything else as well.

**Comment by WhiteFireDaemon** [comment]
I've recently discovered that Mechanical seems to conflict with the Runic Dungeons mod.
