### ISSUE TITLE
Blender files are included in downloads

### ISSUE THREAD

**Issue by immibis** [MrTJP/ProjectRed#1012]
As the title says - the end-user downloads for Project Red components include the .blend files that were used to create the .obj models.

These files are presumably unnecessary for Minecraft, and they are not small - around 500-600kB each, or 70-80kB each after being compressed in the JAR.

Integration's JAR is about 2.5MB bigger than it needs to be because of this - about 2/3 of its compressed size is used for Blender files!

Lighting also includes about 350kB (compressed) and Mechanical includes 180kB (compressed). I didn't check any other modules.

This is probably a low-priority thing to fix.

**Comment by MrTJP** [comment]
Resolved.
