### ISSUE TITLE
Can't craft the null-logic chips

### ISSUE THREAD

**Issue by diamondpumpkin** [MrTJP/ProjectRed#1014]
The recipe can't be shown in NEI and when I look on the website for the recipe, it's not even there. How exactly do I get the upgrade chips?

**Comment by diamondpumpkin** [comment]
It also seems I can't craft the Routed Crafting pipes and I also can't open the router utility thing.

**Comment by diamondpumpkin** [comment]
I'm using:
Forge: 10.13.4.1614

**Comment by CarsonF** [comment]
Chip upgrades were disabled a while ago. I think the default now is what the best upgrades would give you, but don't quote me on that.

**Comment by MrTJP** [comment]
Correct. The system is still undergoing further simplifications.
