### ISSUE TITLE
Unhandled exception when using Filtered Importer

### ISSUE THREAD

**Issue by aradian** [MrTJP/ProjectRed#1015]
[crash-2016-03-27_20.58.41-server.txt](https://github.com/MrTJP/ProjectRed/files/191315/crash-2016-03-27_20.58.41-server.txt)

I'm using the FTB Infinity Evolved v2.4.2 modpack. Placing a Filtered Importer in the world, then connecting any type of item extracting pipe to it causes an immediate ArrayIndexOutOfBoundsException (tried EnderIO item conduit, BC extraction pipe, and ProjRed interface pipe). This also makes the world unusable until the pipe or importer is deleted with MCEdit or similar.

Attached is the crash report using native ProjectRed interface pipe.

**Comment by covers1624** [comment]
Shouldn't be an issue in 1.12 anymore.
