### ISSUE TITLE
Request: IC gate Comparator input

### ISSUE THREAD

**Issue by SFort** [MrTJP/ProjectRed#1016]
It would be nice if the comparator functionality(Detecting how full a inv. is) could be implemented as a input (inside Integrated circuits)(it would be very useful)

**Comment by CarsonF** [comment]
Completely agree. Literally half the time I'm using gates it's a comparator for this purpose. Would love to see a gate with configurable upper and lower bound.

**Comment by MrTJP** [comment]
There will not be an actual comparator tile for use within an IC, but there will be an input type that acts as a comparator.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
