### ISSUE TITLE
ConcurrentModificationException on TileAutoCrafter.refreshRecipe

### ISSUE THREAD

**Issue by ZornTaov** [MrTJP/ProjectRed#1017]
http://pastebin.com/svbgPkZK

Getting this when I log into my world now and I have just one of your autocrafters with the recipes to compress stone, gravel, sand, and dust a single time each. I'm playing on FTB Infinity Evolved 2.4.2 with ProjectRed-1.7.10-4.7.0pre12.95.

**Comment by ZornTaov** [comment]
I think I have a lead on why this is happening.  I'm playing Expert Mode on Infinity Evolved and that changes recipes all over the place, so I'm wondering if it's crashing because minetweaker is changing the recipe on world load

**Comment by AbdielKavash** [comment]
I'm getting the same crash as well.

FTB Infinity Evolved v2.5.0
Project Red 1.1.10-4.7.0pre12.95

http://pastebin.com/aXdQ5yHX

**Comment by AbdielKavash** [comment]
Alright, after some further testing: the bug doesn't depend on Expert mode or any particular configuration of the crafting table to occur. There are certain circumstances which make the bug occur more frequently (Expert mode, multiple recipes in one crafter), but it is still there even in Normal mode, even on crafters only set to craft one recipe. It seems to be very unpredictable (as concurrency bugs tend to be unfortunately).

I don't know if it's PR itself, Fastcraft, interaction with some other mod, or what, but right now the Auto Crafting Bench is effectively unusable in Infinity Evolved. I haven't tested to see if it affects the skyblock version as well, but I would assume so.

**Comment by MrTJP** [comment]
This bug would occur when mods try and change the recipe list when the auto-crafter is doing its thing. This SHOULD NOT happen under any circumstances. The ONLY time the recipe list should be changed is during initialization.
