### ISSUE TITLE
Firewall dupe

### ISSUE THREAD

**Issue by gamecraft45** [MrTJP/ProjectRed#1021]
Place item into firewall and twice click on item in inventory.

https://www.youtube.com/watch?v=6wUEz29FWns

**Comment by Eufranio** [comment]
Confirm.

**Comment by BlayzerQ** [comment]
Whats news?

**Comment by ct-klein** [comment]
Looking for the fix to this, I've used minetweaker to temporarily remove the item but have already had it run rampant on two servers, infinity skyblock and infinity expert, and because the now banned group of people 'shared' a lot of items a lot of folks feel po'd and have left.

**Comment by MrTJP** [comment]
Fixed as of 13fdc5ceb954cd59d0ea95831fc2afb99be99c26

**Comment by Eufranio** [comment]
ah, 1.10

**Comment by bookerthegeek** [comment]
Fixed is fixed, who cares the version. Thank you mod makers!
