### ISSUE TITLE
Unable to place Pipes

### ISSUE THREAD

**Issue by Naddox** [MrTJP/ProjectRed#1024]
The Routed Crafting Pipe and Routed Extension Pipe cannot be placed in current version. Tried with fresh install with only P:R mods.

**Comment by Bjornalf** [comment]
I'm having this problem as well. Using the latest version on curse.

**Comment by MrTJP** [comment]
These pipes have been replaced with chips a long time ago. Just use the chips inside of normal interface pipes.
