### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrTJP/ProjectRed#1025]
Hey, I'm not sure if you are still on 1.7.10, but if yes, is it possible to separate pipes from other machinery ? I love pipes but I don't really need all that machinery thing >.<

**Comment by Carbon-Ghost** [comment]
as a module, is possible

**Comment by CarsonF** [comment]
This is already the case. Pipes are in the `ProjectRed Transportation` mod and machines are in the `ProjectRed Expansion` mod.

**Comment by Carbon-Ghost** [comment]
Nope, not in newer versions :/

**Comment by Carbon-Ghost** [comment]
@MrTJP : Is this true or no ?

**Comment by MrTJP** [comment]
They are part of the same download file and they rely on eachother's code. Cannot separate them...

**Comment by Carbon-Ghost** [comment]
Aow :/
