### ISSUE TITLE
Request: Generate volcanoes at world creation, not chunk creation

### ISSUE THREAD

**Issue by Zsashas** [MrTJP/ProjectRed#1028]
I'll be exploring, and find something interesting like a village, then suddenly BAM volcano everywhere, no more village. Also, if the volcano overwrites a special structure (Thaumcraft Obelisks, ChromatiCraft Pylons) it doesn't update them like it should (they still think they're intact).

**Comment by Paul17041993** [comment]
For reference; to generate the volcanoes in such a manner would involve quite a fair amount of complex map code that barely works well with minecraft in the first place, in basic terms it involves creating a custom biome heightmap system specifically for the volcano surface, with or without adding an additional biome type.

Short answer; nearly impossible to pull off well.

**Comment by Zsashas** [comment]
At the very least, what about simply not overwriting any blocks?

**Comment by Paul17041993** [comment]
Which blocks are being overwritten? The volcanoes generally leave ground blocks intact but will clear above ground blocks as you would not expect there to be any.

It's not really possible to allow villages to remain without also allowing trees as they both use logs...

**Comment by Chicken-Bones** [comment]
Why not make volcanoes a biome? If I had time I'd come back specifically to take a look at this and do it well, because I've always wanted to learn about worldgen, but alas

**Comment by Paul17041993** [comment]
Making a dedicated biome for them is not a bad idea, however neither is it a simple one due to minecraft's nature. Additionally there's compatibility with other biome mods to look at.

A half-way option however may be to make a barren-like biome and allow volcanoes to only generate there and in oceans, however it may take a bit to get the gen chances correct between the two. Or make an island biome too.

**Comment by MrTJP** [comment]
The generator is very careful about which blocks it replaces. I'll consider moving volcanoes to their own biome, if I can come up with a good way to implement this.

**Comment by Zsashas** [comment]
The last time a volcano overwrote something, it was a Chromaticraft Pylon. Some of the base and one of the pillars was gone, which breaks the pylon itself.

**Comment by MrTJP** [comment]
Worldgen is a deceptively tricky business. Its hard to account for EVERYTHING that other mods may generate. I will definitely look into this though.

**Comment by Zsashas** [comment]
Maybe have a whitelist of things it can override instead of a blacklist? Just include vanilla blocks that are usually found on the surface. Dirt, stone, logs, etc.

**Comment by AnrDaemon** [comment]
IMO, biome route would be best. Considering the nature of 'em. Also may be a good idea to review the feature list ;)

**Comment by covers1624** [comment]
1.13 is rewriting world generation, it might be more possible for this to be a thing then. But for now, gonna close this, added it to the todo list.
