### ISSUE TITLE
Bug: Toggle Latch Issues

### ISSUE THREAD

**Issue by BaneOfSerenity** [MrTJP/ProjectRed#1029]
The toggle latch as set-up in the attached image. Power from the right 'in' side does not toggle the switch. The leading redstone path on the gate lights up when the conduit next to it sends redstone but nothing happens to the gate. Right clicking the gate switches perfectly fine. flipping the gate 180 degrees has the same effect.
Version: ProjectRed-1.7.10-4.7.0pre12.95
![2016-05-08_11 04 49](https://cloud.githubusercontent.com/assets/2280933/15099538/a94e8380-150c-11e6-9e4e-78bf929a75dd.png)

**Comment by bosto2** [comment]
I assume that they are simply incompatible
And since I don't know how difficult it would be to make them compatible and the dev has a lot of bugs and implementations to take care of I would suggest using  the wires provided by the mod

**Comment by DeathCorps69** [comment]
Sorry for the late reply, i did just try it with the Red Alloy Wire on both 'IN' side, still doesn't toggle the latch.

**Comment by MrTJP** [comment]
Nope. Works fine. Gates don't connect to conduits. Thats like trying to connect framed wires to gates. Not gonna work.
