### ISSUE TITLE
1.8/1.9 update

### ISSUE THREAD

**Issue by tambry** [MrTJP/ProjectRed#1030]
There seems to be no progress towards it, neither any discussion about it. Are there any plans to update to a newer Forge and thus a Minecraft version? What is the main thing blocking the upgrade? I wouldn't mind helping out with the update, as I've made and maintained Minecraft mods before. (although I've mostly stopped using Java and use C++ instead as my main language)

**Comment by simon816** [comment]
The first step is to get ChickenBones' mods updated. Since CB doesn't seem to be active, there is currently an effort called [TheCBProject](https://github.com/TheCBProject)

**Comment by tambry** [comment]
Seems like a new Maven repository would need to be setup or he would need to update his old one.
Also...
@Chicken-Bones Are you alive?

**Comment by MrTJP** [comment]
For the time being, ChickenBones is no longer maintaining his mods. TheCBProject is where his mods are being updated currently. FMP is being updated by me at the moment. Once that is done, PR will move to 1.9

**Comment by tambry** [comment]
Sorry for bothering, but has there been any progress?
