### ISSUE TITLE
[Feature Request] Item to store Gate Settings

### ISSUE THREAD

**Issue by GeoDoX** [MrTJP/ProjectRed#1032]
Would it be possible to add an Item to Copy and Paste Gate Settings? Would be useful for larger projects that use the same gate settings.

**Comment by CarsonF** [comment]
It's not exactly the same, but you can configure multiple chips at the same time if they are stacked.

**Comment by GeoDoX** [comment]
How do you configure them in the inventory?

**Comment by CarsonF** [comment]
Right click with the item stack selected in world

**Comment by GeoDoX** [comment]
Is this a post 1.7.10 thing? Not working for me?

**Comment by MrTJP** [comment]
This is not a feature yet. @CarsonF is talking about Pipe Chips, not Gates.

**Comment by GeoDoX** [comment]
Planned?

**Comment by MrTJP** [comment]
I like the idea. Planned for 1.9 update.

**Comment by CarsonF** [comment]
Ahh sorry for the confusion.

**Comment by GeoDoX** [comment]
I'd make a PR but I'm not familiar with scala. Thanks TJP.

Not a problem CarsonF

**Comment by CarsonF** [comment]
> I'd make a PR but I'm not familiar with scala.

Yeah same here :/

**Comment by MrTJP** [comment]
Reprioritizing things right now and I don't think this is a worthwhile addition. It doesn't take much effort to change the settings on the gate yourself compared to the code backend i'd have to change to make this possible.
