### ISSUE TITLE
Data cell fails to update in one tick when clocked with red alloy wire

### ISSUE THREAD

**Issue by UncleCrusty** [MrTJP/ProjectRed#1034]
- MC 1.7.10
- Forge 10.13.4.1558
- Only mods installed are the latest TJP & PR on Curse as of this post.

**Setup**
1. Generate a 2 (redstone) tick / 5Hz clock signal with a not gate or invert cell.
2. Feed this signal to the enable input of a data cell.
3. Apply a 'on' signal to the data input of the data cell; it won't be propagated to the output.

**Extra information**
- It works as expected when ordinary redstone is used for the clock signal.
- Red alloy wire will work if the clock signal was generated with a not gate and only travels through **one** wire length to reach the data cell. Perhaps a condition for it to occur is that the signal strength be less than the maximum.
- Transparent latches work as expected with red alloy wire.

**Comment by MrTJP** [comment]
Nope. Works fine for me. Cant reproduce this issue.
