### ISSUE TITLE
not gate texture rotated (the red overlay part)

### ISSUE THREAD

**Issue by swinfi2** [MrTJP/ProjectRed#1035]
this bug is occurring on infintech2 modpack (in ftb launcher)
![2016-05-28_11 54 51](https://cloud.githubusercontent.com/assets/19647465/15646694/04c4cc3c-2657-11e6-9063-a171369da985.png)
![2016-05-28_11 55 19](https://cloud.githubusercontent.com/assets/19647465/15646695/04c62780-2657-11e6-8dba-5396c3683bce.png)
![2016-05-29_21 11 54](https://cloud.githubusercontent.com/assets/19647465/15646696/04c69814-2657-11e6-97aa-ad2ec76a0f9b.png)

**Comment by ranger135xp** [comment]
I can confirm that I have the same issue with the NOT gate and the NOR gate is rotated properly, but the inputs don't match the location. #1080

**Comment by MrTJP** [comment]
Texture pack problem. Refer to #1080.
