### ISSUE TITLE
ProjectRed Wiki - Can't create account

### ISSUE THREAD

**Issue by rihlsul** [MrTJP/ProjectRed#1036]
Figured I'd try to reach the Wiki admin through here.   You can't create a new account.  It tells you invalid or missing Captcha, but there is no Captcha in the sign up form.

Referring to here in case I'm unclear:  http://projectredwiki.com/wiki/Main_Page

**Comment by Mastergalen** [comment]
Thanks for reporting this.

The account creation form has been fixed.

Create an account [http://projectredwiki.com/w/index.php?title=Special:UserLogin&type=signup&returnto=Transmission&returntoquery=action%3Dedit](here)

@MrTJP Please close this issue
