### ISSUE TITLE
Better bundled I/O for ICs

### ISSUE THREAD

**Issue by Sasszem** [MrTJP/ProjectRed#1037]
I know that You're re-writing the ICs. I think that it opens a lot of possibilities if we have an other I/O _for bundled bus_. I mean, if we want to have a bundled I/O featuring all the 16 wires, we need to create 16 IO pins, then configure them. Isn't it mutch easier to have a direct IO for that?

**Comment by MrTJP** [comment]
In the new engine it is not possible for gates inside the IC system to have bundled connections (including the gates for IOs). I will come back to this if the wire net calculations are ever changed to handle this but it's still pretty new and untested to really justify doing that yet.
