### ISSUE TITLE
Server lag related to block update

### ISSUE THREAD

**Issue by LemADEC** [MrTJP/ProjectRed#1039]
As found on our public server using FTB Inventions 1.0.1, there's 10 to 40% load on an event handler related to ProjectRed. See below screenshot at 17% from a  626 seconds profiling:
![image](https://cloud.githubusercontent.com/assets/4776032/15992902/06c3e1ea-30d8-11e6-9dd1-f0020827a4ef.png)
On shorter period, the same event handler can take 40 % of the load by itself.

Related mods version are:
Forge 1614
ProjectRed-1.7.10-4.7.0pre12.95
MrTJPCore-1.1.0.33

**Comment by vadimyer** [comment]
@LemADEC Did you found a solution to this? Seems like some sort of regeneration.

**Comment by vadimyer** [comment]
@MrTJP please.

**Comment by LemADEC** [comment]
What do you mean by regeneration?
The issue is related to the core mod reproducing vanilla 'random ticks' to apply custom effects on every chunks. There's apparently a memory leak as it reload chunks (about 2% direct impact, way more in practice). More importantly, the core of the function takes a lot of time to scan each chunk, so there might be too many handlers registered or some filtering issue involved, etc.

**Comment by ReikaKalseki** [comment]
I get this issue too; we resorted to ASMing out the ticker entirely. We have retrogen and mossy spread off.

**Comment by AnrDaemon** [comment]
>.< Seems like ProjectRed inherited way too much of RedPower.
Could definitely get away without inheriting its famous lagodrom…

**Comment by InuYasha86000** [comment]
I would like to know if this issue has been fixed as i'm running a modded server with PR on it and one of my IC chips has a traffic light sequence built in and I want to make sure that it won't lag if too many are placed within one world.

**Comment by MrTJP** [comment]
This bit of code causing this issue will no longer be in service in 1.10

**Comment by AnrDaemon** [comment]
Who cares about 1.10?…
