### ISSUE TITLE
Electrotine Generator does not accept oredicted electrotine

### ISSUE THREAD

**Issue by mtesseracttech** [MrTJP/ProjectRed#1041]
Gregtech has oredicted versions of most materials and electrotine is one of them, by default it unifies to its own electrotine in this case but the generator is not accepting it. it might be a good idea to check all other machines that accept materials that could be oredicted for compatibility.

**Comment by Sasszem** [comment]
And accept oredicted elektrotine BLOCKS.

**Comment by MrTJP** [comment]
I will add the blocks, but I don't intend to allow other mods to add to my power system. I'm going to be removing Electrotine from the dictionary.
