### ISSUE TITLE
Auto Crafting Bench consumes inconsumable items in recipes

### ISSUE THREAD

**Issue by Eufranio** [MrTJP/ProjectRed#1045]
When trying make a recipe with a "infinite" item (like Pam's Harvestcraft saucepan or other stuff) it consumes the item. 
Steps to reproduce:
1. Make a recipe with a saucepan and a sugar (or whatever recipe with these special items you want)
2. Watch your tool disappear :V

**Comment by Sasszem** [comment]
It only returns the product, no other things(like empty buckets).

**Comment by bookerthegeek** [comment]
That would be good to know as a tool tip on the item.

**Comment by Sasszem** [comment]
I think it's a bug, so they havn't planned as this. Anyway, I've disabled this item in my modpack via Minetweaker.

**Comment by bookerthegeek** [comment]
Why? Just add a tool tip to it saying the automation destroys any excess items other than the final product.

**Comment by Sasszem** [comment]
Becouse I had Magneticraft, which has a better one.

**Comment by bookerthegeek** [comment]
Makes sense.

**Comment by Eufranio** [comment]
No reply? :/

**Comment by MrTJP** [comment]
Fixed here cebd8b393cdb0449287c656d65c1f53e00b90f41
