### ISSUE TITLE
[Feature Request] Bundled cable cells

### ISSUE THREAD

**Issue by Whodundid** [MrTJP/ProjectRed#1046]
Here's a concept idea for some gate cells that could be really useful, especially in ICs. I hope you might consider adding these at some point down the road.

Their function would be the same of how a normal null cell would work, just now incorporating bundled cables instead of the red alloy wire.

![bundled alloy cell concept](https://cloud.githubusercontent.com/assets/16334910/16551367/1935197c-4175-11e6-8bc4-627f48cd5508.png)
![bundled cell](https://cloud.githubusercontent.com/assets/16334910/16551369/1d89dfee-4175-11e6-92cc-71a14c2beb68.png)

**Comment by Sasszem** [comment]
Would be awesome.

**Comment by evg-zhabotinsky** [comment]
Duplicate of #843, more or less.
And if IC backend reimplementation is still planned, not going to see these earlier.

**Comment by MrTJP** [comment]
Duplicate of #843
