### ISSUE TITLE
Backpack Duplication

### ISSUE THREAD

**Issue by kyle-mathis** [MrTJP/ProjectRed#1047]
So I am not sure how this happens because I am playing on a server and don't have access to all the info.

But basically what happened is that I have(had) two backpacks in my inventory - one white, one blue. At some point the white bag overwrote the data for the blue one duping all the items from the white to the blue.

If you need more information i can put y'all in touch with someone who the admin team of the server(Frozensoul) who can explain the specifics. Or if there is a fix to stop this from happening I would love to know.

**Comment by MrTJP** [comment]
A few issues with backpacks were resolved a while ago, this may have been one of them. However without a way to reproduce this I cannot help.
