### ISSUE TITLE
The Auto Workbench from ProjectRed Expansion

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#1048]
It uses and consumes items it shouldn't while auto-crafting, like iron buckets, and more from other mods, which makes auto crafting recipes using such items - useless.

**Comment by Sasszem** [comment]
Yeah, it loses the byproducts and only outputs the crafted item.

**Comment by xJon** [comment]
The same bug is happening in the Project Bench.

**Comment by m0nkm0nk** [comment]
Ye, hope this can be patched. I'm wasting iron on buckets xD

**Comment by MrTJP** [comment]
Attempted fix here cebd8b393cdb0449287c656d65c1f53e00b90f41
Reopen if its still an issue here

**Comment by m0nkm0nk** [comment]
I bet this is only for MC 1.xx right?

**Comment by covers1624** [comment]
Yes

**Comment by Sasszem** [comment]
I've met it in 1.7.10, my pack stuck here because some other mods.
