### ISSUE TITLE
NOT-EXACTLY-A-BUG ( but intriguing )

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrTJP/ProjectRed#1049]
Hey, @MrTJP , long time no see, I just wanted to ask you a VERY important question, I ran into a problem earlier today with a modpack, when launched with MultiMC, it does a weird thing searching for "dummy mods" and then outputs me Forge Multiparts, and Project Red is the only mod I have that contains it, do you have any idea what may cause this ? Here is the log : 

Sorry to waste your time, and REALLY sorry if it's a derp from my side.
Have a nice day. ^_^
http://paste.ee/p/8pLii

**Comment by MrTJP** [comment]
No idea, that paste is no longer available.

**Comment by CarbonGhost** [comment]
@Carbon-Ghost 
Would you happen to own the "CarbonGhost" Minecraft account?
