### ISSUE TITLE
routed interface pipes visual bug

### ISSUE THREAD

**Issue by Jacob5122** [MrTJP/ProjectRed#1055]
Lately I've been playing with ProjectRed. for a while I didn't have any problem but lately I see these, which I think are the bubbles when a item passes through a routed interface pipe.

![2016-08-01_22 17 00](https://cloud.githubusercontent.com/assets/20780558/17307611/41a12cac-5836-11e6-831d-b955983f63f5.png)
![2016-08-01_22 22 36](https://cloud.githubusercontent.com/assets/20780558/17307649/7b9aacc6-5836-11e6-97c0-f7a56a43b0a3.png)
![2016-08-01_22 22 38](https://cloud.githubusercontent.com/assets/20780558/17307650/7b9e4110-5836-11e6-8229-b3b69c54dd71.png)

 Can anybody tell why is it?

**Comment by MrTJP** [comment]
Hehe this is indeed a particle effect gone way out of control and blown up like 1000x size. Not sure what caused it, but I am going to be taking a look at the FX Library soon...

**Comment by covers1624** [comment]
This doesn't happen in 1.12. It might be fixed.

**Comment by MrTJP** [comment]
Happened due to floating point error. Was fixed a while back.
