### ISSUE TITLE
Item Barrel does not cancel item transactions when contains more 1 stack

### ISSUE THREAD

**Issue by Ghostlyr** [MrTJP/ProjectRed#1056]
Found out glitch with item barrel from PR:World. Item transactions out of him can't be canceled, when it filled more then 1 stack of item.

Vanilla example:
![-1](https://cloud.githubusercontent.com/assets/8511068/17333368/ee9b11d0-58f3-11e6-8c68-a49bc80c12e2.gif)

I do not understand why it does not affect the first stack, but for some unknown reasons, It seems that when transaction is performes checking only to see whether the movable container is filled with the same item as in barrel.

In another case, if the slots are free, but the event should be canceled, the items themselves are not transferred, but the contents of the barrel is empties. The same happens in the case any other way to cancel the event interaction with the content, for example, bukkit events. This can be used for grief on servers.

Last version of PR.
MC 1.7.10 Forge 1614.

**Comment by MrTJP** [comment]
Barrels are slated to be removed so this is no longer an issue.
