### ISSUE TITLE
Crash when trying to break a Inverted lamp microblock

### ISSUE THREAD

**Issue by Seyeght** [MrTJP/ProjectRed#1057]
Was able to craft the block without a problem, but once placed into the world it can only be broken in Creative mode. Also, as a microblock it doesnt seem to emit very much light, I dont know if it isnt getting the redstone or if it is and just isnt emitting very much light.

Crash report has a lot of other mods, but I can get another report with just those 2 mods if you'd like.
http://pastebin.com/TzvuRhqF

**Comment by eagle0042** [comment]
I can also reproduce this crash when using a diamond pickaxe. But breaking a inverted lamp microblock with hands it doesn't crash. Maybe that will help narrow down the issue, or at least provides a temporary work around.

**Comment by mgwerner** [comment]
I Have the same issue.  I can break an inverted lamp microblock panel by hand, and the item is returned.  However, using Iridium Drill from IC2 EXP causes crash.

[crash-2016-11-13_11.49.21-client.txt](https://github.com/MrTJP/ProjectRed/files/587574/crash-2016-11-13_11.49.21-client.txt)

**Comment by MrTJP** [comment]
This no longer happens. Fixed in the port.
