### ISSUE TITLE
Pipe and tube incomaptibility with Rotarycraft's Extractor

### ISSUE THREAD

**Issue by Paul17041993** [MrTJP/ProjectRed#1063]
Both the pipes and tubes, including their associated machinery, are unable to pull from the out inventories in the extractor, however they can still insert into the intake inventory (index 0).

I presume the code behind it is falsely expecting inventory index 1 as being the output, or alternatively is capped in its search lower than that of the inventories contained, in this case 5 (and 6 if it's a separate inventory) are the outward slots.

This possibly also affects other >2 inventory machines, however it's not to be confused with machines that provide multiple slots on either of their inventories.

**Comment by MrTJP** [comment]
Then these blocks are not properly set up to be ISidedInventories, most likely.

**Comment by Paul17041993** [comment]
@ReikaKalseki you make use of said interface at all in your API?

**Comment by ReikaKalseki** [comment]
The Extractor does not allow automation in all slots. This is not a bug.

**Comment by Paul17041993** [comment]
The problem was just the output slots from what I remember, projred could be making a false assumption that the bottom face is the only output? (which would be both unhelpful and completely impossible in this case)

**Comment by ReikaKalseki** [comment]
I cannot speak for tubes, but all other item automation - EiO, ThermalDynamics, Translocator, CC, etc - work fine with extractors.
