### ISSUE TITLE
BlockBreaker looses block updates

### ISSUE THREAD

**Issue by chrisbecke** [MrTJP/ProjectRed#1064]
I have a BlockBreaker set up like this - to be a cobble gen on a FTB Infinity Evolved: Expert Mode Skyblock world:

http://i.imgur.com/Sy2mOLz.png

While the screenshot shows evidence of it operating, after breaking a few hundred cobble it will stop, until I cycle the redstone signal.
This happens both on SSP, and playing on a craftbukkit server.

**Comment by MrTJP** [comment]
This happens when the next stone forms too quickly and the breaker never has a chance to 'reset' before getting the next signal. This is just how the breaker works. You need to make your cobble gen differently.

**Comment by chrisbecke** [comment]
And yet the OpenBlocks block breaker, setup identically, works just fine. Although I am intrigued how one would "make a cobble gen differently" in a way that could fix this: you pretty much always have lava flowing into a space adjacent to water.
