### ISSUE TITLE
1.9/1.10 Progress

### ISSUE THREAD

**Issue by Bedrockbreaker** [MrTJP/ProjectRed#1066]
There was an issue a while back about this same topic, and I believe that the chickenbones mods have updated to the newer versions. If they all are, is there any progress towards updating this mod to 1.9 or 1.10?

**Comment by MrTJP** [comment]
It is currently being updated to 1.10, alongside FMP.

**Comment by Shybella** [comment]
Still getting updated?

**Comment by MrTJP** [comment]
Yes

**Comment by Shybella** [comment]
Awesome, thank you very much!

**Comment by Gaelan** [comment]
Just out of curiosity, why FMP over MCMP?
