### ISSUE TITLE
Bundled cable signal strength...?

### ISSUE THREAD

**Issue by goldenpansy** [MrTJP/ProjectRed#1069]
![image](https://cloud.githubusercontent.com/assets/19321989/19214044/2c37e066-8d7b-11e6-83f1-feeb04e93903.png)

I built this cluster of registers with this mod, but apparently when I enable the selected register for releasing the signal to the data bus (white bundled), the signal seems to travel only for a while and not reach the exit of the cluster.

For some reason the signal can travel all the route and get in the register, but not travel out.

Edit:
I am using Feed The Beast modpack Inventions on Minecraft 1.7.10

**Comment by MrTJP** [comment]
Is it exceeding 255 blocks?
