### ISSUE TITLE
[Mekanism] Unable to power Project Red blocks using Mekanism universal power system

### ISSUE THREAD

**Issue by pwnage-pineapple** [MrTJP/ProjectRed#1070]
It seems that it is not currently possible to power Project Red's blocks using power from Mekanism. While I'm posting the issue here, to keep discussion in one place, please reply to the issue I've posted with Mekanism [here](https://github.com/aidancbrady/Mekanism/issues/3892).

**Comment by MrTJP** [comment]
Project Red's power system is to be kept in-house. Any potential integration to be offered will be on PR's side with emphasis on balance.
