### ISSUE TITLE
Routed Request Pipe

### ISSUE THREAD

**Issue by Eliteneet** [MrTJP/ProjectRed#1072]
Routed Request pipes are only showing a single stack at a time.
The pipe is connected to a drawer controller from the Storage Drawers mod.
![2016-11-04_00 14 36](https://cloud.githubusercontent.com/assets/2501786/19997435/bbe10d2a-a223-11e6-9fe7-b450b5737fc0.png)

It has a Item Responder Chip and a Item Broadcaster Chip.
![2016-11-04_00 14 42](https://cloud.githubusercontent.com/assets/2501786/19997457/e918e1e6-a223-11e6-9fd5-97a14bc3614f.png)

The Item Responder Chip is set to hide nothing.
![2016-11-04_00 14 54](https://cloud.githubusercontent.com/assets/2501786/19997466/f840cf62-a223-11e6-9172-d43cf5378c71.png)

Yet the Routed Request Pipe only shows one stack.
![2016-11-04_00 09 23](https://cloud.githubusercontent.com/assets/2501786/19997479/0f21434c-a224-11e6-9a1d-845b6f56c282.png)

However there is more than one stack in the system.
![2016-11-04_00 09 56](https://cloud.githubusercontent.com/assets/2501786/19997485/1d195b7e-a224-11e6-924f-ccc97345ce97.png)

**Comment by MrTJP** [comment]
This is an API issue. I'll have to see what kind of interface StorageDrawers is using.

**Comment by MrTJP** [comment]
Closing due to this now being handled by capabilities.
