### ISSUE TITLE
Auto-Crafting on request

### ISSUE THREAD

**Issue by MasterInventor99** [MrTJP/ProjectRed#1075]
After doing extensive research to figure out the auto crafting system within the transportation module I finally figured out I needed an auto crafting table, available in the latest version of project red.  After updating it has removed crafting pipes from my word and doesn't allow them to be placed back down, regardless of what they connect to.  (including the auto-crafting bench in project red)

I also noticed that the "diamond block breaker" has yet to be added to the compiled mod downloads at "http://projectredwiki.com/wiki/Version_archive#Downloads"

**Comment by MrTJP** [comment]
Crafting pipes have been removed in favor of Crafting Chips that can now be used in any Interface pipe.
