### ISSUE TITLE
[Render Bug] Redstone Paths on Gates 1.7.10

### ISSUE THREAD

**Issue by ranger135xp** [MrTJP/ProjectRed#1080]
I left an issue for this about a year ago (issue #963) and I apologize because I had quit MC in that time. I mentioned how the integration circuits appear to be rotated one step clockwise visually but not functionally. For me, the redstone lines do not line up with the actual block functions of in and out. The issue occurs with Faithful 32 enabled and disabled. I did manage to get it fixed at one point with no clear explanation how, but now it's continuing and I cannot get it to go back to normal.
![2016-12-22_21 50 33](https://cloud.githubusercontent.com/assets/15115164/21446198/091c7a32-c891-11e6-992e-36dab9139520.png)

I thought it may have been isolated but then a quick Google before posting found this,
http://infitech.enjin.com/forum/m/26910956/viewthread/27313587-project-red-gate-functiong-correctly/post/86335153

To further display the issue, here's a photo with no redstone signal to the IN and you can see that visually, the OUTs are rotated but functionally they work as expected:
![2016-12-22_21 55 43](https://cloud.githubusercontent.com/assets/15115164/21446240/a5bf3e56-c891-11e6-89ec-7fc5dd863805.png)

Here's an image of a redstone signal being given to the IN and the OUTs being off as expected, but visually it is still turned one-step clockwise:
![2016-12-22_21 56 02](https://cloud.githubusercontent.com/assets/15115164/21446247/c7c89af6-c891-11e6-8a22-4edfaceac753.png)

As you can imagine, this makes tweaking the OUTs on and off rather difficult as the visual doesn't match the functionality. Thank you for looking into this :). If you need any further info, I'll be actively checking this time around.

EDIT:\\ The item in creative and NEI or the inventory is even rotated:
![2016-12-22_22 03 06](https://cloud.githubusercontent.com/assets/15115164/21446309/9248d43a-c892-11e6-91af-4dae57b89f09.png)

Here's what I found from the NOR Gate:
![2016-12-22_22 12 10](https://cloud.githubusercontent.com/assets/15115164/21446431/f07c91da-c893-11e6-85d2-fc09dab69639.png)

I'm using ProjectRed version 4.7.0pre12.95 and MrTJPCore 1.1.0.33

**Comment by MrTJP** [comment]
This is likely a texture pack error, where the texture pack author is still using the old naming convention of the sides. This is not happening in either that same build you have or the 1.10 build I am working on. Please remove all texture packs and report back.

**Comment by ranger135xp** [comment]
Okay so here's the madness. If I load the game with no texture pack, and then add the texture pack, the blocks display as intended. If I load the game with the texture pack active and I either, A) leave it on, or B) switch back to default, the block is messed up like you see here.

It's weird because I also have the latest F32 pack. I'm noticing form their site, http://www.f32.me/, that if you click the individual mod support to download each mod texture pack independently, yours is ProjectRed 1.6. Did you make the naming convention change between 1.6.4 and 1.7.10?

**Comment by MrTJP** [comment]
Yes. Before, the sides of the gates started at 0 for south, incremented by 1 counter-clock-wise around the gate. Now, it starts at 0 at north. The wires on the gates are generated by special black and white texture files in the "surface" folder. The texture pack maker should leave them alone and let the default textures load, because these files only influence the positions of the wires, not how they look. The actual appearance of the wires can be retextured via the base, bordermatte, and wirematte textures, also inside the surface folder. These three are fair game.

**Comment by ranger135xp** [comment]
Looking into the pack's files, they didn't leave them alone. Those files are 32x32. I'm looking into whether the orientation is messed up. In example, the NOT gate has files NOT-0.png through NOT-3.png. Should I see if the NOT-0.png is the north portion of the gate within the game? Also, do you have a ZIP of the default "special" textures? If so, I can simply replace these and all should be fine.

**Comment by MrTJP** [comment]
They already were 32x32 by default. Like I said, they aren't normal textures and shouldn't really be altered by texture packs. Removing them from the texture pack should fix all your troubles

**Comment by ranger135xp** [comment]
I get your point. If they are just helper files, then there's no need to include them in a texture pack because if you make any changes later, the TP will have the old masks instead of the new/current.

**Comment by MrTJP** [comment]
Yes. TPs can change wire masks, but the file names are being remapped for cleanup right now. I have included them in the directory in case for whatever incredibly weird reason that a pack maker may find it necessary to change the wire paths, theres an option to do so. But I have yet to release any instructions on how this can be done, so it shouldn't be done for now.

**Comment by ranger135xp** [comment]
Thank you so much! This has been driving me batty for a while. I reordered the files so from north to east in counter-clockwise, I changed the NOT-x.png masks to match accordingly. This yielded promising visual results but functionally, east and west were reversed. I'm going to delete all these files from the pack save for the ones you mentioned. I'll let you know if it works.

**Comment by ranger135xp** [comment]
All is well by leaving only

    base.png
    bordermatte.png
    wirematte-OFF.png
    wirematte-ON.png

Thank you! I really appreciate your help with this! Happy new year :)

**Comment by MrTJP** [comment]
If you see any other texture pack doing this, please direct them to this ticket.

Happy new year!

**Comment by ranger135xp** [comment]
I'll help where I can. I mostly only use Faithful 32. I do appreciate that you gave us a good RedPower2 replacement!
