### ISSUE TITLE
Permission to Reference Code

### ISSUE THREAD

**Issue by nfcopier** [MrTJP/ProjectRed#1083]
I am currently developing a mod that will be written in Scala and use Forge Multipart as a dependency. Would it be okay if I used this repository as a reference on how to setup the Gradle build and dependencies?

**Comment by covers1624** [comment]
I don't see any issues with you doing that, unless TJ has any objections.

**Comment by simon816** [comment]
If you want more information on using ForgeGradle there's documentation available here: https://forgegradle.readthedocs.io/en/latest/
Also forge's MDK has a template for getting started https://github.com/MinecraftForge/MinecraftForge/tree/1.11.x/mdk

**Comment by MrTJP** [comment]
Go ahead. No problem
