### ISSUE TITLE
[1.10] Crash with bundled cable.

### ISSUE THREAD

**Issue by mrAppleXZ** [MrTJP/ProjectRed#1085]
I'm just looked on a bundled cable :D.
Crash-report: http://pastebin.com/RGqBY2rj
latest.log: http://pastebin.com/aJedX5nb
fml-client-latest.log: https://gist.github.com/mrAppleXZ/460cd1e86405b73f94745029a15ec3c8

**Comment by MrTJP** [comment]
Fixed in latest commit to FMP
