### ISSUE TITLE
Microblock crash

### ISSUE THREAD

**Issue by WaterXCubic** [MrTJP/ProjectRed#1086]
Hello, I am having crashes when I tries to mine a microblock of the inverted lamp, I tried it on version
ProjectRed-1.7.10-4.7.0pre10 and ProjectRed-1.7.10-4.7.0pre12.95, they both crashed my client.

May I know how do I fix this?

Crash log : http://pastebin.com/mpcHHnMP

**Comment by MrTJP** [comment]
This is addressed in the 1.10 version.
