### ISSUE TITLE
[1.10.2] Crash when using PR with rftools

### ISSUE THREAD

**Issue by Morpheus1101** [MrTJP/ProjectRed#1087]
Crash log @ https://puu.sh/tAo7x/c09400ab94.txt

**Comment by MrTJP** [comment]
What causes this to happen?

**Comment by Morpheus1101** [comment]
Umm, a good question to which i dont remember now, i spoke to covers at the time when it happend.

**Comment by Xiaminou** [comment]
Sorry to hijack the thread, but, should we start reporting things that are not working or just crash report?

**Comment by MrTJP** [comment]
Anything relevant that I need to take a look at should be reported.

**Comment by MrTJP** [comment]
Fixed via f1aa20a925bf05ee956d2c7c6fab9c511eed7f4e
