### ISSUE TITLE
"mrtjp.core.world.BlockUpdateHandler$.onTick" Server crashed with MrTJPCore 1.1.0.32

### ISSUE THREAD

**Issue by ShageJack** [MrTJP/ProjectRed#1088]
Crash-report:http://pastebin.com/eq8EnzFZ

Server runs for 20 hours with out any problem but suddenly it crashed.
And I don't sure will it happen twice.

Should I update to 1.1.0.33?

**Comment by MrTJP** [comment]
This should no longer be the case in 1.10+. If you would like a temporary solution for older versions, disable spreading moss generation in the configs.
