### ISSUE TITLE
[1.10.2] Red Alloy Wires do not render their connection to Redstone Lamps and Hoppers

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1089]
![2017-01-31_18 14 57](https://cloud.githubusercontent.com/assets/8670392/22476188/ba87f1e2-e7e1-11e6-9c52-f0c23f80f5ae.png)
![2017-01-31_19 34 36](https://cloud.githubusercontent.com/assets/8670392/22478972/60d96ecc-e7ec-11e6-88ee-039bc76bef8c.png)
![2017-01-31_18 15 13](https://cloud.githubusercontent.com/assets/8670392/22476189/ba994816-e7e1-11e6-90df-31577ff24fc0.png)

Update: Looks like it's only Redstone Lamps and Hoppers, may not be a bug after all?

Environment: Singleplayer
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742656/list.txt)

**Comment by MrTJP** [comment]
This is normal, if normal Redstone Dust does not connect in this way neither will Red Alloy Wire.
