### ISSUE TITLE
[1.10.2] Wires breaking particles do not render properly.

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1090]
![2017-01-31_18 15 18](https://cloud.githubusercontent.com/assets/8670392/22476346/4c546646-e7e2-11e6-8b3c-dac1ca3e597c.png)

Update: This bug isn't happening in my main modpack, don't know why it's happening on the testing one.

Environment: Singleplayer
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742656/list.txt)

**Comment by covers1624** [comment]
Update CCL to the latest from: http://chickenbones.net/Pages/links.html

**Comment by Xiaminou** [comment]
"CodeChickenLib-1.10.2-2.5.2.198-universal.jar" Looks like I've already got the lasted. Automatically installed by Curse.

**Comment by covers1624** [comment]
Latest not recommended from CB's site

**Comment by Xiaminou** [comment]
Oh, right, well for my defense it was 3am.

**Comment by Xiaminou** [comment]
Fixed.
