### ISSUE TITLE
[1.10.2] Missing Recipes (compatibility with FMP?)

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1092]
![2017-01-31_18 39 57](https://cloud.githubusercontent.com/assets/8670392/22476996/b9b03196-e7e4-11e6-9db8-85ab86cf9f8f.png)

Silicon, Draw Plate, and Framed Wires don't have recipes. Because they use items from FMP?

Environment: Singleplayer
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742656/list.txt)

**Comment by MrTJP** [comment]
Fixed via c1d62c28c48feeb222010fed10958c2cbc9b355e
