### ISSUE TITLE
[1.10.2] Armor values are wrong?

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1093]
Too much toughness, vanilla's diamond armor has 2 when Project:Red's Period has 10, Leggings have more armor than chestplates.

Environment: Singleplayer
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742656/list.txt)

**Comment by MrTJP** [comment]
Fixed with c1d62c28c48feeb222010fed10958c2cbc9b355e. This must've been there since Armor was added to PR haha.
