### ISSUE TITLE
[1.10.2] Crash when placing a P:R Red Caged Lamp

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1094]
Crash Report: [crash-2017-01-31_19.42.07-client.txt](https://github.com/MrTJP/ProjectRed/files/742855/crash-2017-01-31_19.42.07-client.txt)

Environment: Server
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742860/list.txt)

**Comment by MrTJP** [comment]
I'm not getting this problem, what caused it?

**Comment by qazzz789** [comment]
Crash Report: [crash-2017-02-03_22.26.35-server.txt](https://github.com/MrTJP/ProjectRed/files/751986/crash-2017-02-03_22.26.35-server.txt)

Enviroment: Single player
Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185
MrTJPCore: 1.10.2-2.0.0.12
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/751989/list.txt)
