### ISSUE TITLE
Installs wrong Multipart/CodeChickenCore

### ISSUE THREAD

**Issue by Silvrus** [MrTJP/ProjectRed#1095]
Thank you for bring this over to 1.10.2. I installed all the modules and found I couldn't launch. Checking out the dependencies I discovered Forge Multipart and CodeChickenCore 1.7.10 versions. I already had the 1.10.2 CodeChickenCore, deleted the 1.7.10 versions and installed Forge Multipart 1.10.2 and was able to launch the game. Not sure if something derped on my end or if the the mod pulled the wrong versions.

**Comment by al132** [comment]
Same issue here

**Comment by covers1624** [comment]
Both ccl and fmp should never be auto downloaded, both are under my projects on curse forge(on phone atm don't have links) would I be able to get your full fml log please?

**Comment by CitiesXL2815** [comment]
here my log
[fml-client-latest.txt](https://github.com/MrTJP/ProjectRed/files/752074/fml-client-latest.txt)

**Comment by Silvrus** [comment]
This is where it hangs on CodeChickenCore-1.7.10-1.0.7.47-universal.jar http://pastebin.com/sQS0Jvmh and this is after I removed that version of CodeChickenCore, where it hung on ForgeMultipart-1.7.10-1.2.0.345-universal.jar http://pastebin.com/WNbGjbcf

**Comment by aemxdp** [comment]
What is "Forge Multipart 1.10.2"? Is this "MCMultiPart"?

**Comment by MrTJP** [comment]
Fixed
