### ISSUE TITLE
Fatal Connection

### ISSUE THREAD

**Issue by NillerUdenDild** [MrTJP/ProjectRed#1097]
Hey! I installed projectRed on my server an hour or two ago, and I got a fatal connection every time I joined it.

[Crashlog](http://pastebin.com/yqNH7G43)

Do say if you need additional info, I'll do my best to get it :)

**Comment by MrTJP** [comment]
Fixed with FMP commit   TheCBProject/ForgeMultipart@0d37988c13bc35c4bc5db195f3943258ba58b6d2
