### ISSUE TITLE
[1.10.2] Graphical glitch when breaking PR stuff

### ISSUE THREAD

**Issue by Lukas45** [MrTJP/ProjectRed#1098]
Whenever I break PR stuff, graphical glitches occurs during the breaking process.
![2017-02-04_15 19 36](https://cloud.githubusercontent.com/assets/4707702/22619271/84bdea54-eaf1-11e6-82a1-93593fabd83d.png)
![2017-02-04_15 19 31](https://cloud.githubusercontent.com/assets/4707702/22619270/84bcffa4-eaf1-11e6-8507-5bf2331acd72.png)
Tested on a local testing server.
Tried with and without Foamfix (no Optifine installed)

**Comment by covers1624** [comment]
Download the latest ccl from cb's site.
