### ISSUE TITLE
[1.10.2] CurseForge Dependencies is still set to 1.7.10's Forge Multi Part

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1099]
So when you install Project Red via Curse Launcher it installs 1.7.10 FMP, CCL, CCC.

**Comment by NillerUdenDild** [comment]
Same issue as #1095

**Comment by Xiaminou** [comment]
oh, I really should read before opening new issues, oh well.

**Comment by MrTJP** [comment]
Fixed
