### ISSUE TITLE
crash with rendering items and blocks

### ISSUE THREAD

**Issue by Hypsellis** [MrTJP/ProjectRed#1100]
I get crash when I try to display blocks and items from ProjectRed. I got the first one when I clicked on the creative tab of project red lighting parts, the second with the creative tab of project red mechanical, and the third when I tried to display the project red items and blocks on JEI. It doesn't come from my memory, I allocate 16Gb for my modpack, and I have 32Gb of memory.
http://pastebin.com/aDw76zny
http://pastebin.com/kxXcK1D6
http://pastebin.com/D1ZwAnT9

**Comment by Ommina** [comment]
I would imagine the standard question applies whenever one encounters a rendering issue: does it continue to happen without Optifine?

**Comment by covers1624** [comment]
Yeah.. try this without optifine.. either way can you open an issue referencing this over at github.com/TheCBProject/CodeChickenLib

**Comment by covers1624** [comment]
Please attempt the issue again with this version of CCL, http://chickenbones.net/maven/codechicken/CodeChickenLib/1.10.2-2.5.2.213/

**Comment by Hypsellis** [comment]
Yay it works now thanks. ^w^

**Comment by covers1624** [comment]
Roger, new build of ccl will be on curse some time soon, next day or so.

**Comment by Hypsellis** [comment]
I think the new version provocated another bug, now all blocks when broke have purple missing textures particles.
