### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by ARatfat** [MrTJP/ProjectRed#1101]
hello, 

I've a startup Crash with a very basic pack 

This is crash report : http://pastebin.com/h0aEpXHS
This is contente of the pack : https://puu.sh/tPnnj/91beea25fa.png

**Comment by seph86** [comment]
Already known at #1095  

Switch out CodeChickenCore with the Minecraft 1.10 compatible version.

**Comment by MrTJP** [comment]
Sorry, dependencies have been fixed now.
