### ISSUE TITLE
Crash with Install and Startup

### ISSUE THREAD

**Issue by RobertLSnead** [MrTJP/ProjectRed#1102]
When installing through curse the following files are installed and should not be:

ForgeMultipart-1.7.10-1.2.0.345-universal.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar

Might want to look at your dependencies for 1.10.2!

**Comment by MrTJP** [comment]
Has been fixed already

**Comment by RobertLSnead** [comment]
oh...has the files been posted yet?  Curse does not reflect this fix at the moment.

**Comment by tachometer74** [comment]
When installing the Project Red mods Curse is "forcing" the install of the chickenbones versions of Forge Multipart & CodeChicken (sorry I didn't note if it was the Lib or Core).  

I can work around this by grabbing the covers1624 versions (ForgeMultipart-1.10.2-2.0.0.24-universal & again apologize for not noting if it was CodeChickenLib or Core).

If you launch using the chickenbones versions Minecraft crashes.  With the covers1624 version all is well!
