### ISSUE TITLE
Client DC when changing timer setting

### ISSUE THREAD

**Issue by jerry1333** [MrTJP/ProjectRed#1104]
Hi, 
installed server with ProjectRed, when you place Timer and try to change it's setting it will crash client connection with this error: http://pastebin.com/1pFMRaYL
Works fine in single player (and single opened to lan).

Versions:
MC 1.10.2
MrTJPCore-1.10.2-2.0.0.12-universal
ProjectRed-1.10.2-4.8.0.17 (all modules)
CodeChickenCore-1.10.2-2.4.0.101-universal
CodeChickenLib-1.10.2-2.5.2.198-universal
ForgeMultipart-1.10.2-2.0.0.24-universal

**Comment by MrTJP** [comment]
Fixed via 423ef5ad0f44290a28b1e2fa29ed08bafa7585b4
