### ISSUE TITLE
Making Electrotine blocks causes crash 

### ISSUE THREAD

**Issue by RiC0MD** [MrTJP/ProjectRed#1106]
When making electrotine into blocks the client seems to crash with

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.12-universal.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.5r.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/8/17 2:02 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:117)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:324)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:627)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_184098_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:15)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:501)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:117)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:324)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:627)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_184098_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:15)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:501)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RiC0MD'/58565, l='MpServer', x=549.62, y=71.00, z=252.32]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (256,64,256), Chunk: (at 0,4,0 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6130062 game time, 4480009 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityCow['Cow'/58626, l='MpServer', x=527.70, y=62.34, z=300.13], EntityItemFrame['entity.ItemFrame.name'/58564, l='MpServer', x=561.50, y=72.50, z=246.03], EntityPlayerSP['RiC0MD'/58565, l='MpServer', x=549.62, y=71.00, z=252.32], EntityItem['item.item.egg'/58693, l='MpServer', x=563.59, y=66.00, z=277.87], EntityCow['Cow'/58694, l='MpServer', x=559.91, y=66.00, z=273.60], EntityChicken['Chicken'/58695, l='MpServer', x=563.64, y=66.00, z=277.00], EntityHorse['Horse'/58568, l='MpServer', x=492.01, y=74.00, z=284.17], EntityCow['Cow'/58696, l='MpServer', x=554.55, y=66.00, z=277.86], EntityItem['item.item.egg'/58633, l='MpServer', x=555.26, y=66.00, z=273.96], EntityChicken['Chicken'/58697, l='MpServer', x=555.42, y=66.00, z=277.95], EntityItem['item.item.egg'/58634, l='MpServer', x=554.98, y=66.00, z=279.21], EntityChicken['Chicken'/58698, l='MpServer', x=561.55, y=66.00, z=274.23], EntityChicken['Chicken'/58635, l='MpServer', x=553.82, y=66.00, z=278.09], EntityChicken['Chicken'/58699, l='MpServer', x=563.06, y=66.00, z=273.14], EntityChicken['Chicken'/58636, l='MpServer', x=559.15, y=66.00, z=273.11], EntityChicken['Chicken'/58700, l='MpServer', x=560.57, y=66.00, z=275.21], EntityItem['item.item.egg'/58637, l='MpServer', x=553.75, y=66.00, z=275.69], EntityBat['Bat'/58701, l='MpServer', x=559.84, y=31.10, z=320.25], EntityItem['item.item.egg'/58638, l='MpServer', x=555.43, y=66.00, z=277.32], EntityCreeper['Creeper'/58702, l='MpServer', x=555.50, y=19.00, z=321.08], EntityCow['Cow'/58639, l='MpServer', x=554.87, y=66.00, z=276.93], EntityChicken['Chicken'/58640, l='MpServer', x=554.12, y=66.00, z=273.73], EntityChicken['Chicken'/58641, l='MpServer', x=560.08, y=66.00, z=275.57], EntityItem['item.item.egg'/58642, l='MpServer', x=556.26, y=66.00, z=273.75], EntityCow['Cow'/58643, l='MpServer', x=554.83, y=66.00, z=273.85], EntityChicken['Chicken'/58644, l='MpServer', x=563.13, y=66.00, z=278.50], EntityBat['Bat'/58581, l='MpServer', x=479.80, y=51.37, z=314.93], EntityChicken['Chicken'/58645, l='MpServer', x=553.82, y=66.00, z=279.17], EntitySkeleton['Skeleton'/58591, l='MpServer', x=484.50, y=55.00, z=324.50], EntityZombie['Zombie'/58606, l='MpServer', x=509.50, y=13.00, z=321.50], EntityChicken['Chicken'/58607, l='MpServer', x=498.74, y=67.00, z=327.89], EntitySheep['Sheep'/58609, l='MpServer', x=525.55, y=62.02, z=179.08], EntitySkeleton['Skeleton'/58740, l='MpServer', x=628.50, y=31.00, z=242.50], EntityBat['Bat'/58685, l='MpServer', x=566.99, y=25.86, z=320.02], EntityBat['Bat'/58687, l='MpServer', x=573.20, y=33.08, z=320.11]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1657649936 bytes (1580 MB) / 3974070272 bytes (3789 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJA	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJA	NotEnoughItems{2.1.3.199} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.199-universal.jar) 
	UCHIJA	OpenComputers|Core{1.6.1.6} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	ForgeEndertech{1.1.1.1} [Forge Endertech] (ForgeEndertech-1.10.2-1.1.1.1.jar) 
	UCHIJA	AdHooks{1.10.2-1.0.0.2} [Advanced Hook Launchers] (AdHooks-1.10.2-1.0.0.2.jar) 
	UCHIJA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2142} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar) 
	UCHIJA	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCHIJA	CodeChickenLib{2.5.2.198} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar) 
	UCHIJA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UCHIJA	cookingforblockheads{4.2.29} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.29.jar) 
	UCHIJA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJA	JEI{3.14.3.403} [Just Enough Items] (jei_1.10.2-3.14.3.403.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3d.jar) 
	UCHIJA	hammercore{1.2.3} [Hammer Core] (HammerCore_1.10.2-1.2.3.jar) 
	UCHIJA	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	immersiveengineering{0.10-55} [Immersive Engineering] (ImmersiveEngineering-0.10-55.jar) 
	UCHIJA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.22} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.22.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	journeymap{1.10.2-5.4.4} [JourneyMap] (journeymap-1.10.2-5.4.4.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	Mekanism{9.2.1} [Mekanism] (MekanismAll-1.10.2-9.2.1.thommy101_dev.040117.jar) 
	UCHIJA	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismAll-1.10.2-9.2.1.thommy101_dev.040117.jar) 
	UCHIJA	MekanismTools{9.2.1} [MekanismTools] (MekanismAll-1.10.2-9.2.1.thommy101_dev.040117.jar) 
	UCHIJA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJA	MrTJPCoreMod{2.0.0.12} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.12-universal.jar) 
	UCHIJA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHIJA	OpenComputers{1.6.1.6} [OpenComputers] (OpenComputers-MC1.10.2-1.6.1.6.jar) 
	UCHIJA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJA	forgemultipartcbe{2.0.0.24} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar) 
	UCHIJA	projectred-core{4.8.0.17} [ProjectRed Core] (ProjectRed-1.10.2-4.8.0.17-Base.jar) 
	UCHIJA	projectred-integration{4.8.0.17} [ProjectRed integration] (ProjectRed-1.10.2-4.8.0.17-integration.jar) 
	UCHIJA	projectred-transmission{4.8.0.17} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.0.17-integration.jar) 
	UCHIJA	projectred-illumination{4.8.0.17} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.0.17-lighting.jar) 
	UCHIJA	projectred-expansion{4.8.0.17} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.0.17-mechanical.jar) 
	UCHIJA	projectred-tansportation{1.0} [projectred-tansportation] (ProjectRed-1.10.2-4.8.0.17-mechanical.jar) 
	UCHIJA	projectred-exploration{4.8.0.17} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.0.17-world.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	solarfluxreborn{2.5r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.5r.jar) 
	UCHIJA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJA	microblockcbe{2.0.0.24} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar) 
	UCHIJA	minecraftmultipartcbe{2.0.0.24} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
CorePlugin (MrTJPCore-1.10.2-2.0.0.12-universal.jar)
  
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
SFRCore (SolarFluxReborn_1.10.2-2.5r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
  codechicken.nei.asm.NEITransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Colt.BITBUCKETSOL/AppData/Roaming/.minecraft/mods/SolarFluxReborn_1.10.2-2.5r.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2221
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz

Doesn't seem to matter the crafting table used, the second you attempt to pull the block from the craft, client crashes with the above.

**Comment by covers1624** [comment]
This seems to be an NEI issue, luckily im the dev now, can you whack this crash report and link to this issue over at https://github.com/TheCBProject/NotEnoughItems

**Comment by covers1624** [comment]
Never mind what i said, this is infact a project red issue, just double checking.

**Comment by RiC0MD** [comment]
Whoops, I already opened it on the NEI side, so I guess nuke it when you get a moment, thanks!
