### ISSUE TITLE
[1.10.2] ProjectRed on curse launcher downloads the wrong multipart mod that is 1.7, causing instant crash.

### ISSUE THREAD

**Issue by JAWSAWN** [MrTJP/ProjectRed#1110]
You need to correct the dependincies for the 1.10.2 for the curse launcher. It crashes on launch because it dowloads 1.7 versions of the chickenlib and forge multiparts. 
Seen like this on the mods folder: https://i.gyazo.com/d1d55a15f32b18eee1d7b6a23fad5f6d.png
Please fix this issue.

**Comment by MrTJP** [comment]
This was already fixed on Curse a long time ago. I dont know why the launcher keeps installing 1.7 versions, but its a curse issue. Perhaps when I push the next release version it will 'refresh'...
