### ISSUE TITLE
[1.10.2] Add ProjectE container support (Alchemical chest and Energy Condensers)

### ISSUE THREAD

**Issue by JAWSAWN** [MrTJP/ProjectRed#1111]
That would be lovely. Currently any pipes interract with projectE containers.

**Comment by piedpipr314** [comment]
The pipes support hoppers, and so does Project E in a pinch.  You might be able to do this with some other inventory management in-between.  It's not the fastest in the world, but it works.

**Comment by covers1624** [comment]
This was likely due to ProjectRed not supporting the new Capability system and has since been resolved in 1.12.
