### ISSUE TITLE
[1.10.2] Crashed while tinkering with ProjectRed

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1117]
Crashed after pressing one of the buttons on the Bus Input Panel.

[Crash Report](https://github.com/MrTJP/ProjectRed/files/781551/crash-2017-02-16_22.04.46-client.txt)

![2017-02-16_22 12 20](https://cloud.githubusercontent.com/assets/8670392/23041564/8eb185e0-f495-11e6-876c-3a5e10736e62.png)

Note: Only happened once, I was able to relog and press buttons without crashing.

**Comment by MrTJP** [comment]
I think this was a concurrency issue, may have been fixed with the latest FMP commit.

**Comment by Xiaminou** [comment]
Most likely, yes, as it never happened again.
