### ISSUE TITLE
Invalid curse/automatic download

### ISSUE THREAD

**Issue by 23Link89** [MrTJP/ProjectRed#1118]
When I downloaded ProjectRed for the first time, it installed both 1.7.10 ForgeMultipart and 1.7.10 Code Chicken Core. A small bug, but a bug none the less. It can be fixed by uninstalling the older versions and installing the newer ones, this happened in 1.10.2 best of luck.

**Comment by covers1624** [comment]
New versions will be uploaded to "refresh" curses cache soon.
