### ISSUE TITLE
[1.10.2] Client crash when trying to mine basalt with digital miner from mekanism.

### ISSUE THREAD

**Issue by sybershot** [MrTJP/ProjectRed#1119]
Here's a crash log that might help.
https://paste.ee/p/06Yr5
Also, for some reason basalt doesn't have oreDict name, as opposed to marble. And it doesn't drop when you mine it with pickaxe.

**Comment by MrTJP** [comment]
Fixed via f1aa20a925bf05ee956d2c7c6fab9c511eed7f4e
