### ISSUE TITLE
The "microblocks.cfg" configuration file is not creating extra microblocks.

### ISSUE THREAD

**Issue by crosenquist** [MrTJP/ProjectRed#1121]
**Forge Multipart: 2.0.0.24**
**Minecraft: 1.10.2**

The "microblocks.cfg" configuration file is not creating extra microblocks when I provide the proper information in the required format.

For example, I've attempted to create microblocks from AbyssalCraft blocks by following the directions given in the config file. With the name and meta of the desired block, the entry within the file should look like this:
`"abyssalcraft:darkstone":0`

Unfortunately, though, it doesn't appear to be working.

I've used ForgeMultipart since it Chickenbones first created it and I now consider Minecraft essentially unplayable without its microblock functionality. Has anyone else experienced this issue? If so, did you find a solution? Or, is this a currently known issue and is being fixed?

Best

**Comment by covers1624** [comment]
The file is currently dissabled, can you please open the issue over at https://github.com/TheCBProject/ForgeMultipart
