### ISSUE TITLE
Buttons removed?

### ISSUE THREAD

**Issue by D3nnis3n** [MrTJP/ProjectRed#1123]
Hey,
have the illumar buttons been removed? Can't find them in game anywhere despite having all available modules installed. They were there when i last played on 1.7.10. Since then most mods couldn't agree to update so i didn't play until now. (If you removed them in one of the versions for those game-versions)

We had used them extensivley for our systems, am i dumb or are they gone?

**Comment by HybridAir** [comment]
I can also confirm that this problem exists on 1.10.2.

**Comment by MrTJP** [comment]
They were removed on purpose, but now they are ready for use. 0378c7a5a9f2b7d297deadb5c4e730a0f7b1261f
