### ISSUE TITLE
[1.10.2] Console spam

### ISSUE THREAD

**Issue by Wadimich** [MrTJP/ProjectRed#1124]
Hello! Some users on my server made some things with ProjectE and now i receive constantly every 12 or 14 seconds this thing: http://pastebin.com/S4cJ8d02

I'm on SpongeForge 2178, Forge 2221, builded mod by myself without any code modifications (to fix timer bug at least).

**Comment by MrTJP** [comment]
Fixed with cd93b0c26f97d8a094553b6f415e466669f1e943.
