### ISSUE TITLE
[1.10.2] Placing a torch in a torch (multipart) disconnects client (no crash)

### ISSUE THREAD

**Issue by DeadSix27** [MrTJP/ProjectRed#1127]
Stacktrace: http://pastebin.com/gn79xcW6

**Comment by MrTJP** [comment]
This is a FMP issue. It has been addressed.

**Comment by DeadSix27** [comment]
@MrTJP You mean in this commit?: https://github.com/TheCBProject/ForgeMultipart/commit/3d4619edb8af4e78f0e30058fec87006c5744e88
