### ISSUE TITLE
Instant Crash after Installing ProjectRed [1.10.2]

### ISSUE THREAD

**Issue by Zedrimar** [MrTJP/ProjectRed#1129]
I first tried adding the mods to my main mod pack and then made a testing pack with nothing on it but the following:

http://prntscr.com/edrz7t

Crash/output: http://paste.ubuntu.com/24075332/

Not sure what causes it, it just crashes no matter what mods are installed :/

**Comment by Zedrimar** [comment]
nvm turns out curse downloaded the wrong version of core mods

**Comment by bookerthegeek** [comment]
Speaking of which, by the way, the curse download has the 1.7 mods listed as dependanceies, not the 1.10 versions.

**Comment by Zedrimar** [comment]
Yeah, I had to go back to look because of that error :/ if no one has made an issue about the incorrect dependencies then I will open one myself
