### ISSUE TITLE
[1.10.2] ProjectRed calls for wrong dependency versions

### ISSUE THREAD

**Issue by Zedrimar** [MrTJP/ProjectRed#1130]
The title basically says it all... if not already installed, Project Red will call the 1.7 versions of CCC and FMP rather than the 1.10.2 versions. It does however call the right version for CCL. 

Files used (curse launcher): http://prnt.sc/edrz7t

Error output: http://paste.ubuntu.com/24075332/

**Comment by MrTJP** [comment]
This has been fixed long ago, for some reason curse is acting like I didnt fix it. I guess it will 'refresh' the next time I upload a build...

**Comment by covers1624** [comment]
Ill poke zeldo and see what he thinks.

**Comment by Zedrimar** [comment]
I really love using curse, I hate when things glitch XD
