### ISSUE TITLE
[1.10.2] Basalt stone does not drop

### ISSUE THREAD

**Issue by aiun** [MrTJP/ProjectRed#1131]
Basalt stone does not drop when dig with pickaxe.
1.10.2-forge1.10.2-12.18.3.2239
ForgeMultipart-1.10.2-2.0.0.24-universal
MrTJPCore-1.10.2-2.0.0.12-universal
CodeChickenLib-1.10.2-2.5.6.224-universal
ProjectRed-1.10.2-4.8.0.17-Base
ProjectRed-1.10.2-4.8.0.17-world

**Comment by MrTJP** [comment]
Fixed via f1aa20a925bf05ee956d2c7c6fab9c511eed7f4e
