### ISSUE TITLE
[1.10.2]Green sapphire block crash

### ISSUE THREAD

**Issue by aiun** [MrTJP/ProjectRed#1132]
Crash when green sapphire block crafting
[crash-2017-03-01_23.16.13-client.txt](https://github.com/MrTJP/ProjectRed/files/811011/crash-2017-03-01_23.16.13-client.txt)

1.10.2-forge1.10.2-12.18.3.2239
ForgeMultipart-1.10.2-2.0.0.24-universal
MrTJPCore-1.10.2-2.0.0.12-universal
CodeChickenLib-1.10.2-2.5.6.224-universal
ProjectRed-1.10.2-4.8.0.17-Base
ProjectRed-1.10.2-4.8.0.17-world

**Comment by MrTJP** [comment]
Most likely fixed with 531eb411ba3b1bf3b0c3d1a085d883b351936adc
