### ISSUE TITLE
[1.7.10-1.10.2] Integration with WorldGurad 

### ISSUE THREAD

**Issue by skar404** [MrTJP/ProjectRed#1134]
It is possible to integrate fashion with bukkit events that would have sent events to the plugin WorldGurad?

**Comment by covers1624** [comment]
Thats not how server side plugin systems work, SpongeForge is responsible for piping forge events to sponge plugins. If we need to be firing any specific forge event in any place, the WorldGuard devs need to tell us what and when. other than that there is nothing we can do.
