### ISSUE TITLE
[1.10.2] Marble don't chisel

### ISSUE THREAD

**Issue by ZorbaHerbalist** [MrTJP/ProjectRed#1136]
Marble from Project Red can't be chiseled. As far I remember in 1.7.10 - works.

**Comment by covers1624** [comment]
Chisel has may builtin modules for various mods, if they are willing to add one for ProjectRed then cool, otherwise we will add one ourselves.

**Comment by MrTJP** [comment]
Implemented via 0f2f36b78c839f2daab4e7d2aa2b74f45f1ef6c2.

**Comment by acanady** [comment]
MrTJP is on fire

**Comment by acanady** [comment]
Or rather the dev team is on fire. Great work.
