### ISSUE TITLE
Game crush 1.10.2

### ISSUE THREAD

**Issue by KiraLinux** [MrTJP/ProjectRed#1137]
[crash-2017-03-06_17.21.47-client.zip](https://github.com/MrTJP/ProjectRed/files/821398/crash-2017-03-06_17.21.47-client.zip)

Game crashes when I try to click on the tab with lamps

forge ver:
1.10.2-forge1.10.2-12.18.3.2239
 
project red ver mods: 
MrTJPCore-1.10.2-2.0.0.14-universal,
ProjectRed-1.10.2-4.8.1.25-Base,
ProjectRed-1.10.2-4.8.1.25-lighting,
ProjectRed-1.10.2-4.8.1.25-world.

ForgeMultipart ver: 
ForgeMultipart-1.10.2-2.0.0.29-universal

CCL ver:
CodeChickenLib-1.10.2-2.5.6.233-universal

etc...

I checked also with OptiFine and without
same

**Comment by MrTJP** [comment]
Fixed in 657f6065ed139ea0fbb5d1a4234008ab19b91e9d. Accidental dependency on Integration module. For now, install Integration as well and it will fix the error.
