### ISSUE TITLE
[1.10.2] Crashes when loading chunks with a PR creation in them

### ISSUE THREAD

**Issue by tralce** [MrTJP/ProjectRed#1138]
I get this crash when joining my server, if my character was left in the vicinity of my base where I built a simple device with a couple logic gates and some PR wires. If I delete the playerdata file for my character and then rejoin at worldspawn, everything remains fine until I get close to my base again. 

Here's the crash report: http://termbin.com/9qwc

Is this PR's fault, or is this something I should ask CodeChicken about?

Edit: I should point out that the coordinates of the affected block seem to change each time I crash. It's almost always referring to a block that a piece of insulated wire is running through.

**Comment by MrTJP** [comment]
Maybe fixed with 1858e9873ad265bbeb62c3bc696b8c06ea632f2b
