### ISSUE TITLE
[1.10.2] ArrayIndexOutOfBoundsException RenderWire.scala

### ISSUE THREAD

**Issue by everseeking** [MrTJP/ProjectRed#1143]
Snippet
>Description: Tessellating CCL block in world
>java.lang.ArrayIndexOutOfBoundsException: 44 
>at mrtjp.projectred.transmission.WireModelGen$$anonfun$addVerts$1.apply$mcVI$sp(RenderWire.scala:392)

https://github.com/MrTJP/ProjectRed/blob/1.10/src/mrtjp/projectred/transmission/RenderWire.scala#L392

Details
- FTB Beyond v. 1.1.0
- ProjectRed-1.10.2-4.8.1.25-Base.jar
- ProjectRed-1.10.2-4.8.1.25-integration.jar
- ProjectRed-1.10.2-4.8.1.25-integration.jar
- ProjectRed-1.10.2-4.8.1.25-lighting.jar
- ProjectRed-1.10.2-4.8.1.25-mechanical.jar
- ProjectRed-1.10.2-4.8.1.25-mechanical.jar
- ProjectRed-1.10.2-4.8.1.25-world.jar

Full Report
- [Crash Report](http://pastebin.com/tX97rnSB)

**Comment by MrTJP** [comment]
Attempted fix via 1858e9873ad265bbeb62c3bc696b8c06ea632f2b
