### ISSUE TITLE
[1.7.10] Dupe microblocks

### ISSUE THREAD

**Issue by Master26** [MrTJP/ProjectRed#1145]
https://youtu.be/W7D8kYfX39o?t=29s

**Comment by joeyyellow2005** [comment]
@Thats pretty insane. This should be fixed immediately!

**Comment by covers1624** [comment]
Oh.. Well then.. Seems to be a project bench issue..

**Comment by MrTJP** [comment]
Fixed with 7ffe62ef5c62e4a92ed960a65c7d9307fe23a6d0

**Comment by Dream-Master** [comment]
@MrTJP is this fixed in 1.7.10 too?

**Comment by covers1624** [comment]
No just 1.10

**Comment by Dream-Master** [comment]
@covers1624 would be very nice to fix this in 1.7.10 too because this is a major dupe bug. Thanks

**Comment by MrTJP** [comment]
1.7.10 versions are no longer being worked on. Update or use something else to disable the block altogether.

**Comment by Dream-Master** [comment]
@MrTJP sad to hear that because update my pack is impossible because of Gregtech. So will look for another solution.
