### ISSUE TITLE
I can't place any gate in the world!

### ISSUE THREAD

**Issue by MateusMoreiraBR** [MrTJP/ProjectRed#1147]

**Comment by MateusMoreiraBR** [comment]
I tried putting it in solid blocks like sandstone and sandstone, but it did not work.

**Comment by phillips1012** [comment]
Same issue here, on 1.10.2. Wires can be placed, but none of the gates can.

**Comment by DaisukePlays** [comment]
This problem occured with me to but i managed to fix it with updating Project Red integration and forgemultipart

**Comment by covers1624** [comment]
This was fixed ages ago, update your mods people.
