### ISSUE TITLE
1.10.2 - Game Crash with OptiFine

### ISSUE THREAD

**Issue by Nosiphus** [MrTJP/ProjectRed#1150]
Whenever I attempt to view the third tab of my Minecraft 1.10.2 environment, the game crashes. I believe that Project Red may be at fault, as it does have rendering issues with OptiFine present, however I cannot be certain.

https://pastebin.com/gVveuJ3c

I do know that whenever OptiFine is not present, I can view the third page of tabs without issue, and everything loads fine. With OptiFine installed, I did place a wire from Project Red down, and it loaded fine, but framed wires tell another story entirely:

https://pastebin.com/fq2Y7Gz1

**Comment by Konnorg** [comment]
I have also had those errors, even after removing Optifine, although that lessened the crash frequency. 
https://pastebin.com/3bkkEu7a

**Comment by Nosiphus** [comment]
I've evaluated the situation, and it turns out that the culprit is neither OptiFine nor Project Red: it's actually Sphax PureBDcraft. I have no clue why the standard textures work but whenever Sphax is introduced, it crashes.
