### ISSUE TITLE
[1.10.2] Server Crash when using Ore Excavation to get rid of all Red Alloy Wire

### ISSUE THREAD

**Issue by mckouba** [MrTJP/ProjectRed#1153]
When using Ore Excavation to get all Red Alloy Wire, the server crashes.

Crash Report:
[crash-2017-04-03_19.28.15-server.txt](https://github.com/MrTJP/ProjectRed/files/891804/crash-2017-04-03_19.28.15-server.txt)

**Comment by MrTJP** [comment]
This will be a non-issue in 1.11 when FMP tile classes are no longer dynamically constructed. Not sure if its worth going into for 1.10

**Comment by covers1624** [comment]
This has been fixed, FMP tile classes are still dynamically constructed, but they are a little smarter.
