### ISSUE TITLE
[1.10.2] Cannot craft recipes that require microblocks.

### ISSUE THREAD

**Issue by GreyWynaught** [MrTJP/ProjectRed#1154]
**The Problem**
Any recipe that requires the use of Forge Multipart microblocks are unusable. *Problem is assumed to be with Project Red, as other Multipart recipes function properly.* The appropriate crafting recipes are being used, (well the 1.7 recipes at least, I don't believe they have changed). No output is obtained from the recipes of, Any framed wire variant, red wire, insulated wire, low load line, and bundled wire, As well as, the draw plate.

**Versions Affected**
Using latest version of forge: 12.18.3.2221, Multipart: 2.0.0.29, Project Red Base and Integration: 4.8.1.25, and MrTJP Core: 2.0.0.14. All of which are for Minecraft 1.10.2.

See attached images.

**Draw Plate**
![2017-04-04_10 29 14](https://cloud.githubusercontent.com/assets/26860217/24662757/10f921ea-1924-11e7-980f-b35ef64215c4.png)

**Insulated Framed Wire**
![2017-04-04_10 45 34](https://cloud.githubusercontent.com/assets/26860217/24662758/10fa5380-1924-11e7-9d77-210b08b731f8.png)

**Low Load Framed Wire**
![2017-04-04_10 45 38](https://cloud.githubusercontent.com/assets/26860217/24662760/10fc8c36-1924-11e7-992a-d41b19258e29.png)

**Framed Bundled Wire**
![2017-04-04_10 45 43](https://cloud.githubusercontent.com/assets/26860217/24662761/1101bcce-1924-11e7-84e4-7c13f269a352.png)

**Framed Wire**
![2017-04-04_10 45 46](https://cloud.githubusercontent.com/assets/26860217/24662762/11035aca-1924-11e7-9ffd-9f65165bccc5.png)

**Comment by MrTJP** [comment]
Thats because your recipes are wrong. Framed wires require wooden panels, and the drawplate requires iron panels.
