### ISSUE TITLE
Crashes involving Electrotine

### ISSUE THREAD

**Issue by Ra-Zim** [MrTJP/ProjectRed#1158]
There are three crash reports here: https://pastebin.com/z3vcDU8W

Here is what my player had to say:

3 reports all the same deal, adding time to CTRL F search to make it easier

1st Crash: Don't recall what I was doing // 1:23 PM

This applies to the next 2 crashes: Trying to get the Electrotine dust from Project red out of block form and crashed. 
2nd report was shift clicking the dust to craft multiple // 1:55 PM
3rd report was just a left click on the dust  // 2:02 PM

**Comment by MrTJP** [comment]
I tried to reproduce and cannot. Nonetheless, I am not going to bother sifting through that crash report. Next time, please make 3 separate issues with reports on 3 separate pastebin links.
