### ISSUE TITLE
Demultiplexer reqeust

### ISSUE THREAD

**Issue by emanuele6** [MrTJP/ProjectRed#1159]
there should be also a demultiplexer. it would be really useful.

**Comment by emanuele6** [comment]
Logisim: https://sourceforge.net/projects/circuit/
Logisim repo: https://github.com/lawrancej/logisim

IEC:
![schermata da 2017-04-23 16-29-02](https://cloud.githubusercontent.com/assets/20175435/25314329/2dd6e9e6-2842-11e7-9760-6c5b18aa303d.png)

ANSI:
![schermata da 2017-04-23 16-29-15](https://cloud.githubusercontent.com/assets/20175435/25314328/2dd16d86-2842-11e7-9c7f-a173f826f087.png)

**Comment by emanuele6** [comment]
My Super Circuit Maker design: https://gist.github.com/anonymous/159df663d4ff24305fdd3d032a2809bb

Pin Map:
![schermata da 2017-04-23 16-48-34](https://cloud.githubusercontent.com/assets/20175435/25314493/51623822-2845-11e7-8703-c9924b4dee69.png)

Example:
![schermata da 2017-04-23 16-44-40](https://cloud.githubusercontent.com/assets/20175435/25314495/5167f276-2845-11e7-93c3-ac1953560a98.png)

Close-up:
![schermata da 2017-04-23 16-45-06](https://cloud.githubusercontent.com/assets/20175435/25314494/51654030-2845-11e7-9189-c7ec2b3ac52f.png)

**Comment by MrTJP** [comment]
Honestly I'm pretty much done adding gates for now. This can be made yourself in an IC once the fabrication module is done. I'll have a beta release of that very soon.

**Comment by Barhandar** [comment]
Doesn't need a separate gate, just ability to swap IO on existing one.
