### ISSUE TITLE
[1.10.2][BUG] Overflow chip does not work

### ISSUE THREAD

**Issue by FlyveHest** [MrTJP/ProjectRed#1162]
I've been struggling with this on our server, so I tried cloning the latest version from GitHub and compiling it myself, and the problem still persists.

The setup is this:
![2017-04-24_14 51 35](https://cloud.githubusercontent.com/assets/55623/25337963/f6ba9f90-28fd-11e7-8670-7809ac79d4b3.png)

Farthest (right) chest has an Item Extractor, that extracts everything.
Closest (left) chest has an Item Responder that accepts everything.
Center chest has an Item Overflow chip.

If I put some stone in farthest chest, its transported to closest as expected.

But, trying this

1. Fill closest chest
2. Put stack of stone in farthest chest
3. Remove stack from closest chest and let extractor chip extract items from farthest chest.
4. Put stack back into closest chest

Then we get this

![2017-04-24_14 53 43](https://cloud.githubusercontent.com/assets/55623/25337967/f8b33e06-28fd-11e7-95b2-febd438a0479.png)

Stones just floating in the pipes until closest chest has room for them.

It might be me misreading how the overflow chip is supposed to work, but I would expect "loose" items in the pipes to go there, when they no longer have any destination.

This doesn't happen, they just roam until there is room again.

**Comment by MrTJP** [comment]
Cant believe no one reported this before haha. Fixed via cc517e100e60467b62932dad5a55a7ce3f12b00f

**Comment by BloodyRain2k** [comment]
@mrtjp any chance that this fix could get retrofitted into 1.7.10 and most popular after?
