### ISSUE TITLE
[1.10.2] Routing chips disappear after update 25 -> 30

### ISSUE THREAD

**Issue by SirOutlander** [MrTJP/ProjectRed#1166]
After update from ProjectRed-1.10.2-4.8.1.25 to ProjectRed-1.10.2-4.8.1.30 all Routed Interface Pipes are empty. There there should be warning.

**Comment by MrTJP** [comment]
Shouldn't have happened. Unless its because the transportation mod id changed. In which case, you would have to fix it manually unfortunately. Sorry about that :(
