### ISSUE TITLE
[1.10.2][1.7.10]Bad load Solar Panel

### ISSUE THREAD

**Issue by friksasha** [MrTJP/ProjectRed#1169]
Okay, my past isssue was not full information.
I researched my problem and found out what the problem is in the solar panels. After loading world, they begin to consume energy from sources (wires, batterybox). This is especially noticeable at night when they can not generate energy. And more, in 1.10.2 the multimeter does not work.
1.10.2
https://youtu.be/JwZGB5KohT0

1.7.10
https://youtu.be/6LghmIRk_5M

**Comment by friksasha** [comment]
New solar panels.
![2017-05-02_21 12 29](https://cloud.githubusercontent.com/assets/25547088/25633101/b370c4da-2f7e-11e7-8352-793b9f59107d.png)

**Comment by MrTJP** [comment]
Fixed via 7cd056929c914ab9e9c6648686de05e94af99d98
