### ISSUE TITLE
[1.10.2] inverted Lamps not staying inverted

### ISSUE THREAD

**Issue by YOYOK9** [MrTJP/ProjectRed#1172]
When placing inverted lamps some of them turn into normal white lamp blocks instead of being inverted. Doesn't seem to matter what colour of inverted lamp you use. Always defaults back to the white lamp. And it is random as some will stay inverted and others won't.

ProjectRed-1.10.2-4.8.1.30-lighting
We are using Sponge forge if that helps
Forge: 1.10.2-12.18.3.2281-universal
spongeforge: 1.10.2-2281-5.2.0-BETA-2292

**Comment by covers1624** [comment]
Doesn't happen in 1.12, Please resubmit if you encounter the issue again.
