### ISSUE TITLE
Electrotine Block Recipe Missing in JEI - FTB Beyond

### ISSUE THREAD

**Issue by znxster** [MrTJP/ProjectRed#1173]
A very minor issue, there is no recipe for an Electrotine Block visible in JEI. The block is still craftable despite this.

This is in the FTB Beyond pack, ProjectRed version 4.8.1.25

**Comment by MrTJP** [comment]
09d722f860852f0f6a953344c34b4292d6fec910 should fix a few recipes not behaving with JEI.
