### ISSUE TITLE
Interface pipes no longer connect to Storage Drawer Controller

### ISSUE THREAD

**Issue by Kohlerslave** [MrTJP/ProjectRed#1175]
Pretty much says it all.  I updated mods on my server and all the chips inside the junction pipes disappeared.  When I replaced them, I noticed that my request pipes were not propogating with the items from my Storage Drawers warehouse.  When I broke the pipes and tried to reconnect them, the interface pipe no longer connects to the Storage Drawer controller.

**Comment by bookerthegeek** [comment]
This is do to forge having a new slot interface for automation, and storage drawers bo longer sopports the old way.

**Comment by Kohlerslave** [comment]
Ok.  Thank you for the info.  While it's a bummer, there are work arounds.

**Comment by MrTJP** [comment]
I am planning on moving to capabilities soon... It will work then

**Comment by Kohlerslave** [comment]
Awesome to hear!  Looking forward to it.
