### ISSUE TITLE
[1.11.2] forgemultipart crash when minecraft starts

### ISSUE THREAD

**Issue by Ulti91** [MrTJP/ProjectRed#1177]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forge Multipart CBE (forgemultipartcbe)

ForgeMultipart-1.11.2-2.1.0.34-universal.jar

**Comment by covers1624** [comment]
This is not the place for FMP support. Go Here: https://github.com/TheCBProject/ForgeMultipart
Also, FMP is not ready for 1.11 testing hence why it isn't released. For future reference you need to provide a crash report.
