### ISSUE TITLE
Compressed resource blocks cause the game to crash when uncrafted into their respective components

### ISSUE THREAD

**Issue by AlexanderBulanov** [MrTJP/ProjectRed#1179]
I was in the process of Minetweaking my instance when I noticed that block forms of gems, ingots, as well block form of Electrotine weren't craftable. After adding block recipes I looked through JEI and found that each of the blocks were uncraftable into their respective components. However, when I put each of those blocks into any crafting table, 9 respective components of the inputted block show up in the crafting GUI. Upon confirming crafting operation, the instance crashes (and loads without issues).
![2017-05-26_22 57 32](https://cloud.githubusercontent.com/assets/8094020/26518546/74341a78-4267-11e7-9fe2-65ab97492d31.png)
![2017-05-26_22 57 40](https://cloud.githubusercontent.com/assets/8094020/26518547/743543d0-4267-11e7-9e44-2b80dbe4ee99.png)

).

**Comment by covers1624** [comment]
This issue has been fixed recently iirc. Not sure if an update has been pushed yet.

**Comment by MrTJP** [comment]
These issues were fixed when a JEI plugin was added in 7ffe62ef5c62e4a92ed960a65c7d9307fe23a6d0.
