### ISSUE TITLE
No recipe for Framed Red Alloy Wire

### ISSUE THREAD

**Issue by bonnedav** [MrTJP/ProjectRed#1182]
The recipe for Framed Red Alloy Wire seems to be missing. Please put it back in as soon as you can. Thank you.

**Comment by MrTJP** [comment]
Recipe exists. JEI will tell you what it is.

**Comment by bonnedav** [comment]
when i pressed R nothing showed up.

**Comment by MrTJP** [comment]
You're probably on an older version then

**Comment by bonnedav** [comment]
I have version 4.8.2.41 of ProjectRed and version 3.14.7.419 of JEI.

**Comment by bonnedav** [comment]
I still do not know what the recipe is.

**Comment by MrTJP** [comment]
It looks like the JEI plugin never made it into the latest version. I just uploaded a fix. Update PR once it shows up on Curse

**Comment by bonnedav** [comment]
It works. Thank you.
