### ISSUE TITLE
Electrotine Generator problem.

### ISSUE THREAD

**Issue by bonnedav** [MrTJP/ProjectRed#1183]
When I place down an Electrotine Generator the game crashes with this error:
`The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: mrtjp.projectred.expansion.TileElectrotineGenerator.size()I`
[Crash Report](https://pastebin.com/ZwKVrDv9)

**Comment by MrTJP** [comment]
Update MrTJPCore
