### ISSUE TITLE
[1.10.2] Comparator don't detect block state change

### ISSUE THREAD

**Issue by ZorbaHerbalist** [MrTJP/ProjectRed#1186]
After upgrade to ProjectRed-1.10.2-4.8.3.47-integration comparator sometime don't detect block redstone state change (i.e. Red Stringed Comparator), placing redstone on output causes update.

**Comment by MrTJP** [comment]
Can you confirm that this is only happening after that update and was not happening before?

**Comment by ZorbaHerbalist** [comment]
It was happened before. Similar problem:

https://www.reddit.com/r/feedthebeast/comments/6jxqcm/1102_anyone_else_notice_that_project_red/

**Comment by fscan** [comment]
I have the same issue in 1.12.2 measuring a TE energy cell. Block updates (eg breaking a block or wire next to it) update the comparator. Vanilla comparator works.

**Comment by ShaneCourtrille** [comment]
This still happens today... and I think it happens to other things as well.  These kinds of blocks are a major reason for using ProjectRed so I would think this should be a high priority fix?

**Comment by MrTJP** [comment]
Functioning properly in 1.15+. I tested with a vanilla chest. The comparator updates signal strength accordingly when items are added/removed from the chest.

**Comment by VorpalLemur** [comment]
In my testing, the comparator does work on vanilla chests... however it still doesn't update correctly when used on droppers or hoppers as of version 1.16.5-4.11.0-beta.
