### ISSUE TITLE
[1.10.2] Request Pipe not always giving the items you requested

### ISSUE THREAD

**Issue by NeOAnderson2005** [MrTJP/ProjectRed#1188]
Hello , this is a second issue that I have with the pipe system I have whereby sometimes, randomly, I will request a certain item and it will either not return anything at all, or it will return less than that which was requested. I have noticed it is not specific to a certain item, and if I break and replace a pipe along the network , suddenly everything works fine again. As a side note to this, I tested a theory and I wished I had recorded it but I placed items into a chest that was attached to an extractor chip , the system had none of this item in it originally and once the item arrived at its destination the request pipe displayed 3 of the item rather than 1 that I had put in. If I request all 3, it will deliver 1 or none until I request 1. I took it out and tested it again, it did the same thing. So I'm unsure how or what the issue is again, but it doesnt seem to be able to calculate correctly what is in the chests which is possibly why items are either not coming (because they dont exist perhaps?) or reduced amounts come out because it miscalculated originally thus showing more items in there than what actually is in there. If I managae to get a chance to reproduce a good test, I will record and upload. 

PS: The items not coming AT ALL sometimes is related to #1187 and again, breaking and replacing a pipe in the network resolves the issue.

**Comment by MrTJP** [comment]
Fixed a request issue in 7054e5eef55f9c950854f75d47d999839f7aab4e a few minutes ago, I'm pretty sure this is related to that and should be fixed now
