### ISSUE TITLE
[1.10.2] Crash when player joins

### ISSUE THREAD

**Issue by YOYOK9** [MrTJP/ProjectRed#1190]
When a player reloads his base my server crashes. I tried removing sponge and it still crashes. Something about a barrel being ticked. 

Both reports:
https://pastebin.com/D0RNWa2M
https://pastebin.com/HyL5wEAH

**Comment by MrTJP** [comment]
Update MrTJPCore.

**Comment by YOYOK9** [comment]
My server is using MrTJPCore-1.10.2-2.0.0.19-universal

**Comment by MrTJP** [comment]
Then update ProjectRed
