### ISSUE TITLE
RedAlloy Wires look weird on QuiteClearGlass

### ISSUE THREAD

**Issue by emanuele6** [MrTJP/ProjectRed#1195]
![schermata da 2017-06-20 20-34-52](https://user-images.githubusercontent.com/20175435/27349691-667c9eb0-55f8-11e7-9ae0-fd34e561702e.png)
Can you do anything about that?

**Comment by emanuele6** [comment]
![schermata da 2017-06-20 20-45-17](https://user-images.githubusercontent.com/20175435/27350003-64e0b982-55f9-11e7-9a8b-d4b0b1345c64.png)
It looks fine on the other side and it's working ok.

**Comment by MrTJP** [comment]
Wires are not meant to be placed on transparent surfaces. It appears that the block you are using is not correctly reporting its transparency.

**Comment by emanuele6** [comment]
Yeah, I think you're right. I can place wires on all sides but the top. I'm gonna report to the EnderIO developer.
