### ISSUE TITLE
Red Alloy Wire

### ISSUE THREAD

**Issue by fscan** [MrTJP/ProjectRed#1197]
Red alloy wires currently have strange power behavior. In my current world i connected redstone with power 13 to a line of red alloy wires. Directly after the connection the power is 1. After 12 red alloy wires the power drops to 0 (like it would if it had been normal redstone).
AFAIK the wires aren't supposed to loose power?

project red 1.10.2-4.8.4.49
forge 12.18.3.2316

**Comment by MrTJP** [comment]
Power of alloy wires is a value 0-255, redstone dust is 0-15. When propagating from dust to wire, the power isn't scaled up. (14/15 power redstone dust results in 14/255 for wires). This is intentional design.

**Comment by fscan** [comment]
I'm sorry to be annoying here, but what's the rational behind this? It seems the signal is even scaled down on output to redstone dust. Also, putting a lever (or vanilla repeater) directly at the wire seems to do upscaling. I mean i can work around it if i know it, but it "feels" buggy to me.

**Comment by ThePoshTux** [comment]
This is very irritating behaviour, especially when taking output from blocks that cannot directly interact with project red. Is there the possibility of some kind of gate that does correctly scale?
