### ISSUE TITLE
Fabrication Crashes - IC Printer & Gate

### ISSUE THREAD

**Issue by BlockyNoob** [MrTJP/ProjectRed#1201]
When placing the IC printer or the IC gate
Crash reports below:
IC Printer: https://pastebin.com/56Yxn66M  
(world does not load after that. had to create new one.)
Also IC Printer: https://pastebin.com/rKpuC1y6
(also didnt load the world)
IC Gate: https://pastebin.com/g0fbxynU
(loads world without IC gate)

**Comment by MrTJP** [comment]
Update MrTJPCore.
