### ISSUE TITLE
Lightning looking weird with OptiFine Shaders

### ISSUE THREAD

**Issue by pommes** [MrTJP/ProjectRed#1204]
With Shaders every Lightning Light Source looks like the following screenshot:
https://www.dropbox.com/s/zpllmoyzv9wcj9d/javaw%202017-06-23%2015-09-21-03.bmp?dl=0
It looks like the whole texture palette is shown within the texture. 

I tried it with
Minecraft 1.10.2
Forge 12.18.3.2316
OptiFine 1.10.2 HD U D8
Lightning 1.10.2.-4.8.4.47 (and 49)

**Comment by MrTJP** [comment]
Will probably be fixed with the rendering changes in 1.11 or 1.12 but I don't support shaders so if this is only happening while using them then I'm not going to be looking into it.
