### ISSUE TITLE
Weird white parts

### ISSUE THREAD

**Issue by Maineri** [MrTJP/ProjectRed#1205]
Wires etc.. sometimes are white. Block update next to it fixes it. 
[https://ibb.co/cccdoQ](https://ibb.co/cccdoQ)
[https://ibb.co/fy0yoQ](https://ibb.co/fy0yoQ])

And for some reason when I made this thing with rotating light: [https://ibb.co/iUVnhk](https://ibb.co/iUVnhk) , the white part thing happened sometimes to gates in my hotbar.

Reloading chunks (f3+a) makes the ones close to you disappear. It can be this bad: [https://ibb.co/cHGrsk](https://ibb.co/cHGrsk)

Graphics settings: [https://ibb.co/fCLUdQ](https://ibb.co/fCLUdQ)

**Comment by Dushess** [comment]
Subscribing on this thread, seen same behaviour, which way white wool texture at all correlates redstone?

**Comment by covers1624** [comment]
This is fixed in 1.12.
