### ISSUE TITLE
[1.10.2] ComputerCraft Bundled Cables

### ISSUE THREAD

**Issue by Timsuper** [MrTJP/ProjectRed#1206]
It is quite a complicate Situation. You can get ComputerCraft working with CCTweaks on 1.10.2. Even on Server.

Because there is no Compat for ~~1.7~~ 1.8 and above, could you help to integrate the bundled cables back in.

The original Developer of ComputerCraft isn't working on the mod any more, and the guy from CCTweaks thought it should be on your end. Mah non the less, maybe you got some spare time to implement that back / fix it.

**Comment by SquidDev** [comment]
Just as a note, whilst Dan isn't working on the mod, he is merging PRs that others have submitted. Consequently, ComputerCraft is being [developed for 1.10+](https://github.com/dan200/ComputerCraft).

I'm happy to submit a PR adding back bundled cable support, I'm just not sure where you'd want it added.

**Comment by MrTJP** [comment]
As long as ComputerCraft's API is still available I can enable compatibility on my end

**Comment by Timsuper** [comment]
ComputerCraft still has the API to use Bundled Cables.

So there are different "custom" versions of CC since the dev.  stopped, I understand...

**Comment by SquidDev** [comment]
I think the only change which needs to be made in order for this to work is to lowercase the mod id - as of 1.11, it's `computercraft`.
