### ISSUE TITLE
Forge multipart links old

### ISSUE THREAD

**Issue by dsweber2** [MrTJP/ProjectRed#1211]
Hi! I'm a big fan of the mod. Just thought you should know that the links to Forge relocation and the FMP plugin go to the only 1.7 version. For 1.10, is the dependency [this](https://minecraft.curseforge.com/projects/forge-multipart-cbe)? Also, does the FMP plugin have a replacement?

**Comment by MrTJP** [comment]
Those mods are not updated yet to 1.10, hence why they still depend on 1.7 mods.
