### ISSUE TITLE
[1.10.2] Item Barrel, The world destroyer

### ISSUE THREAD

**Issue by sybershot** [MrTJP/ProjectRed#1214]
So, i've got myself a handy-dandy brand new 'ol Item Barrel...And when i placed it in the world my client crashed, after this i've tried to reload my client. It crashed after i loaded the world again. So, now the world is trashed...luckly i've had some recent backups, waiting to be restored.
Here's the detailed log: https://paste.ee/p/v9vR2
I'm using PR 4.8.4.49.

**Comment by MrTJP** [comment]
Update MrTJPCore.
