### ISSUE TITLE
[Request] Comparators inside Integrated Circuits

### ISSUE THREAD

**Issue by OUGHT** [MrTJP/ProjectRed#1218]
Hello!

I have analog ProjectRed scheme: http://imgur.com/a/pFq7l . It involves two Comparators, one Not Gate and one RS Latch. I use it for turning on and off my energy generation - for example, it can be configured to "turn on my boiler when there is less than 3/16 energy left, and turn it off when there is more than 14/16 energy in the storage". 

I tried to compact this scheme using ProjectRed's Integral Circuits, but the resulting scheme becames "hard-coded" - there is no way to insert a Comparator into IC, and I want to be able to configure this on the fly - providing new values to compare against. It would be very handy to be able to use Comparators inside IC Gates - Analog IOs are good only if you do not need to compare two or more of them.

Please, bring analog logic to Integral Circuits!

**Comment by MrTJP** [comment]
There are plans to have a comparator input type to integrated circuits but there won't be an actual comparator tile since the internal logic is not set up to handle analog signals.

**Comment by StragaSevera** [comment]
> There are plans to have a comparator input type
What is the progress on this? Is it still in plans, or is it dropped from them?
