### ISSUE TITLE
Update for 1.12

### ISSUE THREAD

**Issue by Pival81** [MrTJP/ProjectRed#1220]
Is there any plan on updating the mod to 1.12?
Or can I already build it against 1.12?
If so, how? Can it be done without installing a full IDE?

**Comment by MrTJP** [comment]
It is being worked on but is not available yet.

**Comment by VirtualGaming1** [comment]
any update?

**Comment by ogaskell** [comment]
Has this happened yet?

> It is being worked on but is not available yet.

That was over 6 months ago.
