### ISSUE TITLE
[1.7.10] bibliocraft and PR redstone signal 

### ISSUE THREAD

**Issue by Fabboz** [MrTJP/ProjectRed#1222]
the typesetting table from bibliocraft don't accept the redstone signals transmitted from wires or button or anything from project red, only works with vanilla signals.
why?may be bibliocraft?

**Comment by Dushess** [comment]
Probably hardcoded vanilla redstone as signal sourse in Bibliocraft

**Comment by MrTJP** [comment]
Considering they emit raw redstone signals that work with everything else, its Bibliocraft.
