### ISSUE TITLE
Huge rubber trees

### ISSUE THREAD

**Issue by Pival81** [MrTJP/ProjectRed#1223]
I remember that in redpower 2 there were some huge rubber trees, which were very useful if you were out of normal rubber trees from ic2.
Is there any plan to reimplement this? Searching on the forum thread i found some link to your TODO list which seems to have included this, but the link is down...
I am talking about [this](http://technicpack.wikia.com/wiki/Rubber_Tree_(RedPower)).

**Comment by MrTJP** [comment]
Currently no plans to bring back rubber trees as rubber isn’t needed in PR. Maybe if that’s ever the case I’ll consider some kind of rubber source such as those trees.
