### ISSUE TITLE
Config for Fuel Efficiency

### ISSUE THREAD

**Issue by Ajsuenb** [MrTJP/ProjectRed#1224]
Hi, it's not so much an issue, more of an ask for help. I really don't want the Fuel Efficiency enchantment and I have looked hard for the configuration to no result. How can I remove this?

Thank you.

**Comment by MrTJP** [comment]
Hmmm. Well, if you really need to disable it, I guess I'll add a config option.

**Comment by Chefbarbie** [comment]
> Hmmm. Well, if you really need to disable it, I guess I'll add a config option.

July 17, 2018. Still waiting to disable this enchant. Making it ONLY stick to your own jetpack would be better.

**Comment by MrTJP** [comment]
I was not aware that it can stick to other items besides my jetpack...

**Comment by Chefbarbie** [comment]
Oh yeah. I have it on a fishing pole, a pair of pants, a bow. 

Kinda funny, but aggravating too.

**Comment by Stephenator0316** [comment]
2019... Still waiting... :( 

I really don't need it showing up in every other enchant option on my diamond pick please :(

**Comment by TheDeviantCrafter** [comment]
As a temporary workaround, you can use Enchantment Tweaks to disable the enchantment.

**Comment by frenchiveruti** [comment]
Why is this still not fixed?  
At least add an enchantment description for forge haha.

**Comment by frenchiveruti** [comment]
At least move it away from the CORE and ship it separatedly.  That would solve a big part of it.

**Comment by frenchiveruti** [comment]
> 
> 
> As a temporary workaround, you can use Enchantment Tweaks to disable the enchantment.

How?

**Comment by MrTJP** [comment]
This is a priority ticket for this Saturday's release.

**Comment by TheDeviantCrafter** [comment]
On a related note, it should probably be less common. If it's changed so it can only be applied to the Jetpack, it would still appear a little too often when enchanting books.

On my last world I got six or seven fuel efficiency books before getting fortune, looting or silk touch.

**Comment by MrTJP** [comment]
True. I was in the process of evaluating rarity if the enchantment vs how effective it was at saving fuel. It was made to be fairly common because it only slightly helped consumption.

If you did use in on actual jet packs though I’m open for input on this.

**Comment by TheDeviantCrafter** [comment]
I don't like getting enchantments I don't have a use for. The fuel efficiency enchantment is one I'll use exactly once per world unless I die. I'd much rather it be rare, but very effective.

Another option would be to use CoFH Core's holding enchantment if it's detected. Instead of using less fuel, it can store more. That would have the same effect unless you're struggling with power generation.

**Comment by MrTJP** [comment]
Interesting. Will look into increasing storage instead. Also will increase rarity along with effectiveness.

**Comment by TheDeviantCrafter** [comment]
As a bonus, it would be more obvious to the player how much of an improvement it is.

The nice thing about using CoFH Core's enchantment is that you don't need to make a duplicate enchantment.

Personally I would remove fuel efficiency if CoFH Core is installed, and then use that one. Fuel efficiency would only exist if CoFH Core isn't detected.

**Comment by frenchiveruti** [comment]
> How can I remove this?

Has this been implemented?  
Like a config option for the enchantments of the mod.

**Comment by MrTJP** [comment]
The enchantment now only goes on the correct items. No longer any need to disable it.

**Comment by frenchiveruti** [comment]
I see.  
I think still, should be a config thing for packs that for example have other jetpacks but it's good to know that now is more rare and works correctly.  
Thanks for your work.
