### ISSUE TITLE
[1.7.10] Server crash that is caused by the Integration module of ProjectRed

### ISSUE THREAD

**Issue by dat3ngy** [MrTJP/ProjectRed#1225]
First off, I would like to start off by saying that I don't know how to reproduce this issue. At first I thought it might've been because I right clicked on a weird block with the chips while trying to configure some extractor and responder chips but the crash log mentions the integration module and the chips aren't in that one. Again I apologize for not knowing the cause. This happened on a Forge 1.7.10-10.13.4.1614 server with about 87 other mods installed. Here is the crash log: https://pastebin.com/ZPNed6NZ if more information is needed, I'll be happy to comply, thanks.

UPDATE: I was able to reproduce the crash again with the same crash report. It appears that placing counters, timers, ProjectRed repeaters, etc next to other modded blocks, in this case Mekanism Teleporter is causing the crash. I cannot 100% confirm this as the cause but I'll do more testing.

**Comment by MrTJP** [comment]
That portion of the code has been worked on since 1.7 so its probably fixed by now. Either way, not looking into bugs from that version anymore. Let me know if its still an issue in 1.10 or 1.11.
