### ISSUE TITLE
Graphic bug 

### ISSUE THREAD

**Issue by Mierafet334** [MrTJP/ProjectRed#1226]
I have a graphics issues when playing minecraft 1.10.2 
I have tried reloading chunks but it doesn't change anything.

![2017-09-02_18 01 37](https://user-images.githubusercontent.com/31570905/29997002-62d7c992-9009-11e7-8a0c-6bc76f41a44d.png)
![2017-09-02_18 01 43](https://user-images.githubusercontent.com/31570905/29997003-62ef1a70-9009-11e7-8f65-63439d67f6ce.png)
![2017-09-02_18 01 52](https://user-images.githubusercontent.com/31570905/29997004-62f38b0a-9009-11e7-8949-a2848a1463a9.png)
![2017-09-02_18 02 28](https://user-images.githubusercontent.com/31570905/29997005-62f7deee-9009-11e7-9f89-4a5d62406dc7.png)

Sorry for my English, I'm from Poland.

**Comment by covers1624** [comment]
The first fmp bug has been fixed, update your mods then retest.
