### ISSUE TITLE
Placing IC Gate = Instant crash [1.10.2]

### ISSUE THREAD

**Issue by Neekow** [MrTJP/ProjectRed#1228]
Forge version: 1.10.2-12.18.3.2185
ProjectRed version: 1.10.2-4.8.4.49

what's happening?
Had a crash by placing an IC gate, removed all the other mod and only keept ProjectRed mod and its dependencies then creating a whole new world, still crashing on placing the IC gate.

link to the crash report: [https://pastebin.com/hyP8qYjz](https://pastebin.com/hyP8qYjz)

**Comment by ensirius** [comment]
@Neekow your link is broken when you click

**Comment by Neekow** [comment]
Fixed (1st time with this code ...)

**Comment by MrTJP** [comment]
As of a3aa13ef06fc43ebadae445b2db7b85b91a652a1, invalid gates from creative inventory no longer crash the game. Instead, they are placeable but have no IO on any sides.
