### ISSUE TITLE
[1.7.10] Block override using ic2 wire

### ISSUE THREAD

**Issue by ensirius** [MrTJP/ProjectRed#1229]
When you click microblock with ic2 wire it's have weird behavihaor and breaking the block.

https://image.prntscr.com/image/cmo81wD0SaS05OOTDcI10Q.jpeg
https://image.prntscr.com/image/l8TS9V2XTLq6g0x-CMBWuA.jpeg

**Comment by MrTJP** [comment]
This is probably an issue with IC2, though I'm not really gonna track down a bug from 1.7 anymore. Most likely not an issue in the current version.
