### ISSUE TITLE
Inverted lamps flicker?

### ISSUE THREAD

**Issue by totte1015** [MrTJP/ProjectRed#1233]
I dont know why, but the lightning that appears from the colored lamp blocks, is "waving" or flickering a little, why is this?

**Comment by Dushess** [comment]
Like that? https://www.youtube.com/watch?v=-3eB9i0BZNM

**Comment by covers1624** [comment]
Whats linked in that video is a product of how MC does rendering and nothing we can fix at all. Basically in newer versions, 1.8+ there are multiple threads handling each 16*16*16 sub chunk individually, so some threads finish before others causing that weird lighting. If that is the "waving" you are talking about @totte1015 then ill go ahead and close this issue.
