### ISSUE TITLE
[1.7.10] Frames/Blocks get destroyed by an unreplacable air block left behind by chests

### ISSUE THREAD

**Issue by TheLastRar** [MrTJP/ProjectRed#1234]
When a chest on a frame is connected to an TE Itemduct or an AE2 Import bus (and possible other item transport blocks) and the frame moves independently of Itemduct (or whatever), an invisible, non replaceable block is left in the chests original location, 

Any block that tries to replace this bugged air block (i.e. placing, or moving another frame to it) gets destroyed.

The creation of this bugged block appears to occur when the Itemduct (or whatever) encounters an air block where there was once a non-air block, I have seen this occur with a TE Fluxduct that directly past a moving frame, but have not tested this case specificity, (I've only tested the case mention in the first paragraph).

These bugged blocks become normal air blocks on server reload, but _appear_ to persist across chunk reloads.

This is on a recently created custom mod-pack, using ForgeRelocation-0.0.1.4-universal for 1.7.10

**Comment by TheLastRar** [comment]
I've managed to reproduce this issue with slab stone slabs on frames moving past TE fluxducts or an AE2 Import bus

**Comment by MrTJP** [comment]
So ForgeRelocation hasn't been a thing since 1.7, and even back then it was in beta. Its not being worked on at this point.
