### ISSUE TITLE
New Year. New version :)

### ISSUE THREAD

**Issue by iKEVAREZ** [MrTJP/ProjectRed#1242]
Hi! Can we get new branch of ProjectRed for minecraft 1.12?

**Comment by covers1624** [comment]
The update will be done when its done, waiting on @MrTJP's input on a few things before it is pushed.

**Comment by Dushess** [comment]
1.11.2 first, because it already WIP.

**Comment by covers1624** [comment]
1.11 shares a few bugs with my local 1.12 branch at the moment, waiting on tj to check it out then ill manually merge it to my 1.12 branch. Don't worry, things are under control.

**Comment by Dushess** [comment]
So, 1.11.2 will be released?

**Comment by SirWindfield** [comment]
@Dushess Yes. Porting mods takes a lot of time depending on how complex the stuff is. And I am pretty sure that everyone that works on minecraft mods does not commit 100% of their time into making those mods and maintaning them :D
