### ISSUE TITLE
1.12dev multipart cbe?

### ISSUE THREAD

**Issue by Poccket** [MrTJP/ProjectRed#1246]
I can't figure out how to run the 1.12dev version, as the [Curse](https://minecraft.curseforge.com/projects/forge-multipart-cbe) page is 1.11.2 and the [GitHub](https://github.com/Chicken-Bones/ForgeMultipart) is even more outdated, where can I find the forge multipart cbe for 1.12?

**Comment by covers1624** [comment]
As FMP isn't released for 1.12 you will need to grad a dev build from http://chickenbones.net/Pages/links.html under the 1.12 mc version, will run fine on 1.12.2
