### ISSUE TITLE
Weird Graphics Issues w/ Lights

### ISSUE THREAD

**Issue by iancbogue** [MrTJP/ProjectRed#1248]
I seem to be having two issues with all lights in Project Red. The first of these (Picture 1) is one that has been a problem for a while. In the first-person view when looking at the lamp in your hand, there is a "texture map" if that makes sense. The second has to do with when lights are placed in the world. They have a red circle on the outside layer of the block texture. This happens without any resource packs enabled. I use OptiFine, FWIW.

![2018-02-20_10 45 23](https://user-images.githubusercontent.com/18062067/36442860-f686535e-162b-11e8-8e9d-ab0da1a9cc64.png)
![2018-02-19_15 05 48](https://user-images.githubusercontent.com/18062067/36442871-f96eb868-162b-11e8-951b-2e5a274cf6a7.png)

**Comment by simon816** [comment]
First thing to try is removing optifine. It often causes graphical weirdness.

**Comment by iancbogue** [comment]
OK.

**Comment by iancbogue** [comment]
Removing OptiFine solved the issue, but my performance takes a heavy hit.
