### ISSUE TITLE
Project red redstone tubes

### ISSUE THREAD

**Issue by Darktotaled** [MrTJP/ProjectRed#1249]
Im using last version for 1.7.10
also latest forge
im trying to use pressure tubes with strip of redstone blocks, but they do not connect with timers, for example. The only things i tried and i know it does connect are redstone torches and levers.
Is there any info on what they connect to and/or why it doesnt connect to a timer?

Btw, its a project red timer

**Comment by Darktotaled** [comment]
just adding a screenshot so its easier to understand what i said.
http://prntscr.com/iir34u
i added block of redstone strips to pressure tubes but i can make they work with a projectred timer. it just doesnt connect.
as you can see in the screenshot, framed alloy wire connects to it but doesnt connect to timers, redstone or red alloy wire. redstone and alloy wire doesnt connect to the pressure tube also.

**Comment by covers1624** [comment]
You need to place an alloy wire underneath the framed alloy wire.

**Comment by Darktotaled** [comment]
i see. gonna try that out. you can close this issue =] thank you
