### ISSUE TITLE
Error: Caught exception from ProjectRed Transmission (projectred-transmission)

### ISSUE THREAD

**Issue by iancbogue** [MrTJP/ProjectRed#1253]
What is causing the issue? I see in the crash report at line 158 there is a UCE for Integration, Transmission, and Illumination.
[crash-2018-03-17_15.09.39-client.txt](https://github.com/MrTJP/ProjectRed/files/1822148/crash-2018-03-17_15.09.39-client.txt)

**Comment by Dushess** [comment]
https://github.com/MrTJP/ProjectRed/issues/1251

**Comment by Dushess** [comment]
Someone was too fast with decisions. You're from minecraftforum?

**Comment by iancbogue** [comment]
Oh i guess. Do you mean this post?
![chrome_2018-03-17_15-23-45](https://user-images.githubusercontent.com/18062067/37560528-3f1b02ca-29f7-11e8-9366-5b32f9ce6008.png)

**Comment by Dushess** [comment]
Latest comment is for preventing excessive question.
