### ISSUE TITLE
Filtered Importer crash when using the wrong sides

### ISSUE THREAD

**Issue by PulzHF** [MrTJP/ProjectRed#1256]
I initially reported this to the BuildCraft team, but then discovered that it is a ProjectRed issue.

This is for ProjectRed 1.7.10-4.7.0pre12.95, the issue is fully described in the issue thread below, though a quick tl;dr:
Piping items into the wrong sides (the non-input/output) of a Filtered Importer will cause a crash.

https://github.com/BuildCraft/BuildCraft/issues/4131

**Comment by covers1624** [comment]
This is fixed in 1.10+, it will not be backported.
