### ISSUE TITLE
[1.10.2] IC gate crashing game when placing

### ISSUE THREAD

**Issue by Golgroth** [MrTJP/ProjectRed#1258]
The error:

>  TileEntity type TileMultipart_cmp$$0 has throw an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException
> 	at mrtjp.projectred.fabrication.ICSimEngineContainer.saveSimState(SimInterface.scala:150)
> 	at mrtjp.projectred.fabrication.ICGateLogic.save(fmpgatepart.scala:101)
> 	at mrtjp.projectred.integration.TComplexGatePart$class.save(gatepart.scala:344)
> 	at mrtjp.projectred.fabrication.ICGatePart.save(fmpgatepart.scala:36)
> 	at codechicken.multipart.TileMultipart$$anonfun$writeToNBT$1.apply(TileMultipart.scala:154)
> 	at codechicken.multipart.TileMultipart$$anonfun$writeToNBT$1.apply(TileMultipart.scala:151)
> 	at scala.collection.immutable.List.foreach(List.scala:383)
> 	at codechicken.multipart.TileMultipart.func_189515_b(TileMultipart.scala:151)
> 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384)
> 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227)
> 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013)
> 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:325)
> 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:456)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by MrTJP** [comment]
Should be fixed with the update to how ICs work in 1.11+
