### ISSUE TITLE
[1.12.2] TP fail

### ISSUE THREAD

**Issue by TheSnowyChickens** [MrTJP/ProjectRed#1259]
Hello,
I found a bug, I produced a video for an more easier preview.. :)
MC 1.12.2

https://youtu.be/tSkBJL322dU

Versions from your mod at the end of the Video.

Thx

**Comment by covers1624** [comment]
This is the issue tracker for ProjectRed not Aroma's Mining Dimension.. Please open an issue over at their issue tracker.

**Comment by TheSnowyChickens** [comment]
oh lol, Google show me this Github as one from Aroma Core, sry then.
