### ISSUE TITLE
Why is Corsa not 1.12.2?

### ISSUE THREAD

**Issue by MrLador** [MrTJP/ProjectRed#1260]
I tested the version:[http://chickenbones.net/](http://chickenbones.net/maven/mrtjp/).
Use version:
CodeChickenLib-1.12.2-3.1.5.334 [http://chickenbones.net/](http://chickenbones.net/maven/codechicken/CodeChickenLib/1.12.2-3.1.5.334/)
ForgeMultipart-1.12-2.3.0.47 [http://chickenbones.net/](http://chickenbones.net/maven/codechicken/ForgeMultipart/1.12-2.3.0.47/)
ProjectRed-1.12.2-4.8.6.55-Base [http://chickenbones.net/](http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.8.6.55/)
ProjectRed-1.12.2-4.8.6.55-integration [http://chickenbones.net/](http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.8.6.55/)
ProjectRed-1.12.2-4.8.6.55-lighting [http://chickenbones.net/](http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.8.6.55/)
MrTJPCore-1.12.2-2.1.1.23-universal [http://chickenbones.net/](http://chickenbones.net/maven/mrtjp/MrTJPCore/1.12.2-2.1.1.23/)
Everything works fine, but I build on Corsa and can't use these versions in modpack. Please add everything you need on the Corsa at least as a beta. Or some other way to allow them to be used in mod assemblies.
I'm afraid that the mod just throw for a very long time, and spread the Assembly to the new version you want. There are no analogues yet or they develop for a long time.

**Comment by covers1624** [comment]
It appears what you are trying to say was lost in what i assume is Google Translate. The mod is not on curse because its not ready yet. When its released its ready.
