### ISSUE TITLE
No recipes for anything but the "base" part of Project red [1.12]

### ISSUE THREAD

**Issue by warplord** [MrTJP/ProjectRed#1262]
Pretty self-explanatory, no crashes or anything but I have no recipes for anything but the basic materials and tools. Any idea what might be causing this? My modpack or is it a general problem ?

**Comment by MrTJP** [comment]
General problem. Expect a fix ASAP.

**Comment by Sandrituky** [comment]
I was going to report the same. Please fix it :(

**Comment by calloatti** [comment]
Same problem here. Installed base and Lightning for the cage lamp, items show up on JEI but there are no recipes for them except the basic ones.

**Comment by MrTJP** [comment]
Yes yes. 1.12 had some major changes to the recipes. I guess i did it wrong lol. Fix coming sometime today. Sorry about that :P

**Comment by warplord** [comment]
Hey guys, I know this is a bit offtopic - but can MrJTP or covers please take a look at the other issue I posted for 1.12 - it is kind of a big problem and I would like to know what is causing it and if it can be avoided or fixed in the future? Thanks!

**Comment by covers1624** [comment]
All have been fixed, but i haven't put labels on them yet. New builds out tomorrow.

**Comment by Sandrituky** [comment]
I can't wait! I need lights on my home D: D: I will save materials until the new release!!
