### ISSUE TITLE
Tick loop crash [1.12]

### ISSUE THREAD

**Issue by warplord** [MrTJP/ProjectRed#1263]
That happened after I try to load any of my worlds now. I placed a state cell in one of them before closing MC. Now that is crashing when I try to load my worlds:

https://pastebin.com/EP54xwEb

**Comment by warplord** [comment]
Something is not right - I even deleted my world where the state cell was placed but I still cannot load my other worlds because of the same error. Is that something from the mod or something else that is causing this?

**Comment by covers1624** [comment]
This was actually an FMP issue, that i have fixed, version is bumped ready for the next release.

**Comment by warplord** [comment]
Awesome, thanks!
