### ISSUE TITLE
bundled cables [1.12.2]

### ISSUE THREAD

**Issue by Cobus777** [MrTJP/ProjectRed#1264]
hi, bundled cables not connecting to computercraft.

please assist.

regards

**Comment by MrTJP** [comment]
Compatibility between computer craft and bundled cables will be explored again in the future. For now they will not connect.

**Comment by Cobus777** [comment]
Please Sir,

I rely on this mod to connect to my Computercraft system managing various parts in my reactor building.
I wrote a whole managing program with bundled cables back in 1.7.10, since then i upgraded to 1.12.2 and was waiting so long for this mod. Can you maybe give a time frame.. No pressure I now there is a lot of work going into the code. 

thanks in advance for a great mod.
