### ISSUE TITLE
[1.12.2] OreDictionary names for marble and basalt

### ISSUE THREAD

**Issue by OneEyeMaker** [MrTJP/ProjectRed#1265]
Hello.
Firstly, great thanks for you work! I'm very excited about release of ProjectRed for MC 1.12!
Secondly, I've suggestion to improve compatibility with other mods.
There are mods which already have marble and/or basalt (such as Chisel, Quark, Astral Sorcery). All such mods use ```stoneMarble``` and ```stoneBasalt``` OreDictionary names for these materials.
I suggest to add these names for marble and basalt blocks to make ones interchangeable.

**Comment by covers1624** [comment]
I sware they already had OreDict names..

**Comment by OneEyeMaker** [comment]
@covers1624 
I'm using ProjectRed 4.8.6.62. In this version marble has OD name ```blockMarble```, basalt doesn't have any ones.
I suggest to use ```stoneMarble``` and ```stoneBasalt``` names (instead or in addition) because:
a) most mods use such names to *unify* these materials;
b) such OreDictionary names correspond ones for vanilla rocks (```stoneAndesite```, ```stoneDiorite``` and ```stoneGranite```).

**Comment by warplord** [comment]
I agree. Being able to chisel marble and basalt back and forth would be a nice addition.

**Comment by covers1624** [comment]
next question, BasaltCobblestone or just Basalt

**Comment by warplord** [comment]
I think basalt - the smooth one that generates should be ore dict-ed.
