### ISSUE TITLE
[1.12.2] Move OreDictionary entries registration and recipe addition to earlier game stage

### ISSUE THREAD

**Issue by OneEyeMaker** [MrTJP/ProjectRed#1267]
Hello.
I've simple suggestion: move OreDictionary entries registration and recipe addition to earlier game stage in Exploration module ([this code](https://github.com/MrTJP/ProjectRed/blob/master/src/mrtjp/projectred/exploration/proxies.scala#L322-L333)).
This change allows to other mods to add its own recipes and integrations. It also allows to modify these recipes via CraftTweaker.

With current version of ProjectRed (4.8.6.62-64) most other mods can't recognize mod's blocks, because ones are registered too late.

**Comment by MrTJP** [comment]
Addressed with f3cbfa581fa577b84b03c29f35cbad950d123530

**Comment by covers1624** [comment]
It should actually be moved to preInit, directly after registration of blocks, if my memory is correct on ten order of registry events.
