### ISSUE TITLE
Project Red - Mechanical Causing Crash

### ISSUE THREAD

**Issue by crazyamri** [MrTJP/ProjectRed#1271]
Hello.

I just can't get the Project Red - Mechanical mod to work. It seems that's the cause for crash.

I'll put the crash log together in here.

Thank you.

https://pastebin.com/SdDZuDvM

**Comment by covers1624** [comment]
You'll have to install ProjectRed-Transmission for the moment, i'm unsure if there is meant to be a hard dependency between the 2 or not at this stage.

**Comment by crazyamri** [comment]
Okay, i'll try it.

Thank you for fast response.
