### ISSUE TITLE
[1.12.2] Wires fragmented after re-entering world/server restart

### ISSUE THREAD

**Issue by The0programmer** [MrTJP/ProjectRed#1272]
When I re-enter a singelplayer world or restart my server this happens to all my wires.
![2018-05-09_17 16 22](https://user-images.githubusercontent.com/39129928/39823296-13d4d5de-53ad-11e8-8846-f8788182e493.png)

They go back to normal after block update.

**Comment by Dushess** [comment]
Not in theme, this bundled cables was other before (in 1.7.10, as i seen, the corners has been clearly visible as wires continue, without colors overlap)

**Comment by MrTJP** [comment]
This is a known issue with FMP. It is being looked into and is the highest priority issue to be fixed.

**Comment by warplord** [comment]
Does it cause cables to be disconnected or is it just a visual bug?

**Comment by Dushess** [comment]
A little delay on worldload? Also this happened with chunk reload? Or only world.

**Comment by covers1624** [comment]
Its not that simple, i'm looking in to the issue, its extremely complex, and its nothing in ProjectRed, its purely an FMP issue.
