### ISSUE TITLE
gem ore gen rates

### ISSUE THREAD

**Issue by Spenny519** [MrTJP/ProjectRed#1274]
I don't know if it is just me but the ore gen for all the gems seems low. Is there a way to increase it in the config or not?

**Comment by MrTJP** [comment]
Nope. There is a way to lower it though. Gen rates are as intended. They are suppose to be about as rare as diamond.

**Comment by Spenny519** [comment]
They just seem a little too rare. Would it be possible to add an option in the config so we can change the rates if we want to?
