### ISSUE TITLE
v 4.8.6.74 requires unavailable version of FMP-CBE

### ISSUE THREAD

**Issue by dmauldin** [MrTJP/ProjectRed#1275]
ProjectRed-1.12.2-4.8.6.74-Base and friends requires Forge MultiPart CBE vs >= 2.4.2, which is not available on curse, so updating ProjectRed on curse causes packs to fail.

Just a friendly reminder that you may want to verify dependencies are available prior to uploading.  :P

**Comment by MrTJP** [comment]
FMP will be available shortly.
