### ISSUE TITLE
Randomly appearing and disappearing components.

### ISSUE THREAD

**Issue by warplord** [MrTJP/ProjectRed#1277]
Ok, the tick loop crash is gone but I am having another problem. 

I set up a few redstone wires, a few gates, a state cell, that kind of stuff and exited the game. When I came back the first time there were extra redsotne wires (?!) and when I fixed my machine and exited and came back again the state cell and a few wires were gone. So ... that is strange. 
No crash report or anything to provide this time - just a description of what happened. Hope that helps you figure out why this is happening.

**Comment by MrTJP** [comment]
What version of PR and FMP are you using?

**Comment by warplord** [comment]
Always the latest, the ones uploaded last night. I was waiting for the new version without the tick loop crash in order to enter my world

**Comment by covers1624** [comment]
Gonna need screenshots of what you are seeing.

**Comment by calloatti** [comment]
The same thing is happening to me but with Fallout Lamps, and that is the only item from the mod that I am using right now.

I place Fallout Lamps, and when I exit the game and then load it again, most lamps are gone, and others are placed in other places.

Sometimes the light effect of the lamps seems to remain.

Before reloading game:

![2018-05-12_20 48 27](https://user-images.githubusercontent.com/12817862/39967432-8787ff60-5691-11e8-8af1-5a6dd6b9f80b.png)

After reloading game:

![2018-05-13_09 36 53](https://user-images.githubusercontent.com/12817862/39967433-921776b8-5691-11e8-9314-cbfee759f7f0.png)

This is a long wall that has Fallout Lamps every 3 blocks. A lot of the lamps vanish after reloading the game:

![2018-05-13_09 37 47](https://user-images.githubusercontent.com/12817862/39967444-b302f186-5691-11e8-8a03-ec3b3e649027.png)

![2018-05-13_09 38 06](https://user-images.githubusercontent.com/12817862/39967446-b7345f2e-5691-11e8-8bf9-c60e4bbbdb49.png)

![2018-05-13_09 38 25](https://user-images.githubusercontent.com/12817862/39967452-bb9f9650-5691-11e8-8447-3f0ffd893272.png)

It seems that some chunks keep their lamps, others don't.

MC 1.12.2
ProjectRed-1.12.2-4.8.6.74-Base
ProjectRed-1.12.2-4.8.6.74-lighting
Forge 2655

**Comment by covers1624** [comment]
What happens if you press F3 + A once you have discovered these missing lamps. Do they reappear at all ever? do the blocks still exist in world? can redstone still trigger them? does redstone triggering them make them appear?

**Comment by calloatti** [comment]
When I press F3+A nothing happens.

The blocks do not seem to be there since I can place another block in the same place.

I only used inverted fallout lamps and have not tried using redstone on them, but since the blocks seems to have vanished I doubt that will work.

I used inverted fallout lamps I obtained switching to creative mode since the recipe was not there in the previous jar version.

I will create a test world when I have more time and do some tests.

As you can see from the pics, some lamps are still there after reloading. Other lamps just vanish. And not in the pictures, other lamps appear in other random places.

**Comment by calloatti** [comment]
Did a quick test in a new instance with these mods:

```
"ForgeMultipart-1.12.2-2.4.2.58-universal.jar"
"jei_1.12.2-4.9.1.179.jar"
"MrTJPCore-1.12.2-2.1.1.27-universal.jar"
"ProjectRed-1.12.2-4.8.6.74-Base.jar"
"ProjectRed-1.12.2-4.8.6.74-lighting.jar"
"ChickenASM-1.12-1.0.2.7.jar"
"CodeChickenLib-1.12.2-3.1.8.341-universal.jar"
```

And cannot reproduce the problem

This is my full mod list in the world with the problem:

```
angelringforbauble-12.21.0.0.jar
Architect-MC1.12-1.2.0.6.jar
Aroma1997Core-1.12.2-2.0.0.0.b150.jar
AromaBackup-1.12.2-2.1.1.3.b98.jar
AutomatedRedstone-1.12.2-6.1.3.jar
AutoRegLib-1.3-17.jar
autowalk-1.12.2-1.0.jar
base-1.12.2-3.7.1.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
bedpatch-2.2-1.12.2.jar
BetterBoilers-1.2-dev.55.jar
BetterFps-1.4.8.jar
BetterPlacement-1.0.0-1.jar
BetterThanMending-1.1.1.jar
BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar
blockcraftery-0.1.3.jar
bonsaitrees-1.0.4-b71.jar
Bookshelf-1.12.2-2.3.544.jar
BottledMilk-1.12-1.1.0.jar
BowInfinityFix-1.11.x-1.12.x-rv5.jar
CapabilityProxy-1.12.2-2.1.1.jar
CD4017BE_lib-1.12.2-6.2.3.jar
Chameleon-1.12-4.1.3.jar
Charset-Lib-0.5.0.246.jar
ChestTransporter-1.12.2-2.8.8.jar
ChickenASM-1.12-1.0.2.7.jar
ChopDown Updated (1.12.2+)-1.0.9.jar
Chunk Pregenerator V1.12-1.8.jar
clarity-1.1.jar
ClientTweaks_1.12.2-3.1.6.jar
Clumps-3.0.0.jar
CodeChickenLib-1.12.2-3.1.8.341-universal.jar
ColossalChests-1.12.2-1.6.11.jar
colytra-1.12.2-1.0.4.3.jar
Controlling-3.0.6.jar
CraftTweaker2-1.12-4.1.8.jar
CTM-MC1.12-0.2.3.12.jar
CyclopsCore-1.12.2-0.11.5.jar
DankNull-1.12-1.4.33.jar
DebugServerInfo-1.12.2-1.0.5.jar
DeepSeaExpansion-1.12.2-Preview-A6.jar
dooglamooworlds-1.12-1.1.2.jar
easierchests-1.12-forge14.21.1.2387-1.1.jar
EDX-Multipart-1.1.1.jar
ElevatorMod-1.12.2-1.3.6.jar
elulib-0.1.12.jar
Elytra Crafting Mod 2.0.1.jar
EnchantmentDescriptions-1.12.2-1.1.8.jar
Ender Ore-1.12.2-1.0.jar
EnderCore-1.12.2-0.5.22.jar
EnderIO-1.12.2-5.0.24.jar
EnderZoo-1.12.1-1.4.0.49.jar
engineersdoors-0.7.2.jar
Exchangers-1.12.2-2.7.2.jar
extrautils2-1.12-1.7.6.jar
FactoryTech-1.12.2-1.4.jar
FastLeafDecay-v14.jar
FastWorkbench-1.12.2-1.3.2.jar
FinderCompass-1.12.1.jar
FluidFunnel-1.12.2-1.3.0.jar
foamfix-0.9.9.1-1.12.2-anarchy.jar
Forgelin-1.6.0.jar
ForgeMultipart-1.12.2-2.4.2.58-universal.jar
FullscreenWindowed-1.12-1.6.0.jar
GiacomosFoundry-1.12.2-1.3.13.jar
Guide-API-1.12-2.1.5-60.jar
Harvest-1.12-1.2.6-18.jar
HorseTweaks_1.12.2-1.0.3.jar
iChunUtil-1.12.2-7.1.4.jar
ImmersiveEngineering-0.12-82-385-core.jar
ImmersiveEngineering-0.12-82-385.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.8.jar
industrialforegoing-1.12.2-1.9.0-163.jar
IndustrialWires-1.6-25.jar
infinimend-1.12-1.0.2.jar
instantunify-1.12.2-1.1.1.jar
invcoalgen-1.0.2.jar
InventoryTweaks-1.64-dev.jar
IvToolkit-1.3.3-1.12.jar
jeiintegration_1.12.2-1.5.1.36.jar
jei_1.12.2-4.9.1.179.jar
justamagnet-1.12.2-1.1.0.jar
JustEnoughButtons
justenoughbuttons-1.12.2-1.2.2-5.jar
JustEnoughResources-1.12.2-0.8.7.41.jar
kjlib-1.0.4.jar
KleeSlabs_1.12.2-5.4.9.jar
LagGoggles-FORGE-1.12.2-4.1.jar
list.txt
LLOverlayReloaded-1.1.4-mc1.12.jar
Magneticraft_1.12-2.3.1-dev.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
mcjtylib-1.12-2.6.7.jar
MCMultiPart-2.5.1.jar
modelloader-1.0.5.jar
ModernLights-1.0.3_1.12.jar
modular-routers-1.12.2-3.1.4.jar
Morph-o-Tool-1.2-16.jar
MrTJPCore-1.12.2-2.1.1.27-universal.jar
mtqfix-1.12.2-1.1.0.jar.disabled
NaturesCompass-1.12.2-1.5.1.jar
NBTEdit-0.7.jar
NetherPortalFix_1.12.1-5.3.13.jar
NHCore-1.12-4.0.3.jar
nmclc-1.12-MC1.12.2-1.2.0-b56-universal.jar
notenoughwands-1.12-1.6.1.jar
OpenGlider-1.12.1-1.1.0.jar
OreExcavation-1.4.118.jar
p455w0rdslib-1.12-2.0.29.jar
PersistentBits-1.12-1.0.6a.jar
platforms-1.12.0-1.4.5.jar
prefab-1.3.0.20.jar
pressure-1.3.1.9-mc1.12.2.jar
ProjectRed-1.12.2-4.8.6.74-Base.jar
ProjectRed-1.12.2-4.8.6.74-lighting.jar
Quark-r1.4-123.jar
quickget-1.0.jar
randompatches-1.12.2-1.1.0.0.jar
RandomThings-MC1.12.2-4.1.6.jar
RebornCore-1.12.2-3.8.1.271-universal.jar
RebornStorage-1.12.2-3.0.6.43.jar
reconstructor-2.11a.jar
recycler-1.5.0-1.12.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refinedstorage-1.5.33.jar
refinedstorageaddons-0.3.jar
rflux-1.12-0.2.0.jar
rftools-1.12-7.33.jar
rftoolspower-1.12-1.0.0.jar
ropebridge-1.12-2.0.7.jar
sampler-1.73.jar
Scannable-MC1.12-1.6.3.17.jar
SereneSeasons-1.12.2-1.1.5-universal.jar
shetiphiancore-1.12.0-3.5.6.jar
ShoulderSurfing-1.12.2-1.12.jar
SimpleLogic-0.5.0.239.jar
SimplyEnchanting-1.12-1.0.3.jar
SmoothWater-0.1.4.jar
SophisticatedWolves-1.12.2-3.13.2.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.3.6.jar
Tesla-1.12.2-1.0.63.jar
tesla-core-lib-1.12.2-1.0.14.jar
theoneprobe-1.12-1.4.22.jar
Torched-1.12.2-7.0.0.jar
totemexpansion-1.2.1-1.12.2.jar
UnicodeFontExtension-1.12.2-2.7.jar
unridekeybind-1.0-core.jar
unridekeybind-1.0.jar
VanillaTeleporter-1.12-1.6.3-beta4.jar
ViesCraft-1.12.2-5.6.1.jar
WaterStrainer-1.12-3.2.0.jar
WHAT-0.2.jar
WirelessCharger-1.3.0.jar
woot-1.12.2-1.2.1.jar
XaerosWorldMap_1.2.4_Forge_1.12.jar
Xaeros_Minimap_1.15_Forge_1.12.jar
xnet-1.12-1.6.9.jar
xray-1.12.2-1.4.2.jar
zettaindustries-1.3-1.12.2-155.jar
[1.12]UncraftingTable-1.8-beta6.jar

```

**Comment by Dushess** [comment]
Something tells me about better placement, but not sure, check it.

**Comment by Njet75** [comment]
@calloatti I have this problem also.Exit and reloading World fixes it sometimes.
Also happens to CBE wireless mod Components.

**Comment by matix931** [comment]
Same problem here

forge-1.12.2-14.23.3.2698

ChickenASM-1.12-1.0.2.7.jar
ironchest-1.12.2-7.0.40.824.jar
Thaumcraft-1.12.2-6.1.BETA13.jar
twilightforest-1.12.2-3.7.424-universal.jar
ThermalFoundation-1.12.2-2.4.1.15-universal.jar
EnderCore-1.12.2-0.5.22.jar
Backpacks-Mod-1.12.2.jar
ThermalCultivation-1.12.2-0.2.0.6-universal.jar
CoFHCore-1.12.2-4.4.1.12-universal.jar
iChun-Util-Mod-1.12.2.jar
RedstoneArsenal-1.12.2-2.4.2.9-universal.jar
ForgeMultipart-1.12.2-2.4.2.58-universal.jar
Forgelin-1.6.0.jar
tesla-core-lib-1.12.2-1.0.14.jar
ProjectRed-1.12.2-4.8.6.74-lighting.jar
CodeChickenLib-1.12.2-3.1.8.341-universal.jar
ProjectRed-1.12.2-4.8.6.74-Base.jar
Baubles-1.12-1.5.2.jar
NetherPortalFix_1.12.1-5.3.13.jar
extrautils2-1.12-1.7.6.jar
EnderStorage-1.12.2-2.4.2.126-universal.jar
EnderIO-1.12.2-5.0.24.jar
WR-CBE-1.12.2-2.3.0.27-universal.jar
buildcraft-7.99.17.jar
ProjectRed-1.12.2-4.8.6.74-integration.jar
Advanced Solar Panels-4.2.0.jar
Chisel-MC1.12.2-0.2.0.31.jar
ThermalInnovation-1.12.2-0.2.1.6-universal.jar
Portal-Gun-Mod-1.12.2.jar
ProjectRed-1.12.2-4.8.6.74-mechanical.jar
appliedenergistics2-rv5-stable-11.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar
ThermalExpansion-1.12.2-5.4.2.27-universal.jar
industrialforegoing-1.12.2-1.9.0-163.jar
ProjectRed-1.12.2-4.8.6.74-fabrication.jar
industrialcraft-2-2.8.76-ex112.jar
ProjectRed-1.12.2-4.8.6.74-world.jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
Tesla-1.12.2-1.0.63.jar
ThermalDynamics-1.12.2-2.4.1.10-universal.jar
ExtremeReactors-1.12.2-0.4.5.48.jar
CTM-MC1.12-0.2.3.12.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
zerocore-1.12-0.1.2.1.jar
Hwyla-1.8.24-B39_1.12.jar
jei_1.12.2-4.9.1.168.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
MrTJPCore-1.12.2-2.1.1.27-universal.jar

**Comment by Kalmeira** [comment]
To add to this, pipes in chunks that remain chunk loaded (with chicken chunks, in my case) do not get deleted. However, once you cross into a non chunk loaded chunk they will get deleted.

**Comment by lonyelon** [comment]
Same issue on server 1.12.2

**Comment by Frosthaven** [comment]
This problem just cropped up for some of my users, so just adding my voice to the bucket. Definitely related to unloaded/loaded chunks

**Comment by lonyelon** [comment]
I have been testing this and it seems like it also affects Forge Multipart, if i find something more i'll post it

**Comment by jcettison** [comment]
Also having this problem; have some insulated wires and wires that keep disappearing. Think a chunk loader would fix this in the meantime?

**Comment by NewMilenium** [comment]
I tested a bit the problem, because it happens to me as well. Pipes "randomly" disappear and reappear (using 1.12.2, local server, local client, i chose the mods i installed, no "pack"). When i leave the server and join it again, other pipes "randomly" disappear and other reappear, but i think it is because the chunks are unloaded and loaded again. It seems to be server-side : the items are still saved somewhere, and re-accessed and loaded after unloading and reloading the chunk, and if i try to go where a pipe is supposed to be but not loaded, i can go through, the server permits me. It happens per chunk; all pipes of a chunk are either loaded or not.

**Comment by NewMilenium** [comment]
Another observation : it seems (so far not denied by all tests done) that the pipes are loaded when the player is in the same chunk when it is loaded, and that the chunk where pipes are not loaded are in some other chunks : notably, all adjacent chunks do not load their pipes. (tested as well by disconnecting while at an adjacent chunk and connecting again to reload everything)

**Comment by kubaxius** [comment]
I have this problem too, but in my world it looks like only items placed on certain chunks aren't loading. 
This includes both Project Red and Forge Microblocks.
![2018-06-26_23 13 35](https://user-images.githubusercontent.com/28007805/41939599-9efa6d36-7996-11e8-8d0b-f89e52178f36.png)

**Comment by covers1624** [comment]
Cleaning this in to a single issue: TheCBProject/ForgeMultipart#29
