### ISSUE TITLE
[1.12.2] Pipes don't connect to modded inventories

### ISSUE THREAD

**Issue by Sixdd6** [MrTJP/ProjectRed#1278]
Trying to set up a simple pipe network and none of the pipes will connect to modded inventories. I've tested with inventories from Metal Chests, Charset Barrels and Impractical Storage.

Minecraft 1.12.2
Forge 2655
MrTJPCore-1.12.2-2.1.1.27
Project Red 4.8.6.74

**Comment by Sixdd6** [comment]
coming right up :)
https://goo.gl/khE5Kq

**Comment by MrTJP** [comment]
Fixed via e46dab213a060bcdb09c4583b84c2b74a43898ee
