### ISSUE TITLE
[1.12.2] pneumatic pipe crash when moved by a piston.

### ISSUE THREAD

**Issue by Cenotaffio** [MrTJP/ProjectRed#1280]
if i try to move with a piston a pneumatic tube 2 things happens.
1) the pipe became "invisible".
2) if an inventory is put near the "invisible" pipe, the game crashes.

**Comment by covers1624** [comment]
In vanilla, TileEntities cannot be moved by pistons, you have some other mod installed that allows moving tileentities with pistons. Probably quark? The issue lies with how that mod handles moving tileentities, regardless i don't have mind reading abilities, ima need that crash report.

**Comment by Cenotaffio** [comment]
Yes, i have quark installed.
There is the report.
[Crash.txt](https://github.com/MrTJP/ProjectRed/files/1997465/Crash.txt)

**Comment by covers1624** [comment]
That appears to be a launch log, that contains nothing about project red crashing.

**Comment by Cenotaffio** [comment]
in the folder there is no crash report, probably because the game freezes, and not closing does not create the report.

**Comment by MrTJP** [comment]
Same behavior as when frames try to move FMP tiles without special handling. Dont move FMP tiles with Quark.
