### ISSUE TITLE
[Lightning] Light Ghosting

### ISSUE THREAD

**Issue by FrostQ** [MrTJP/ProjectRed#1282]
MC version : 1.12.2

![2018-05-12_13 43 12](https://user-images.githubusercontent.com/36822613/39956960-0c691644-55eb-11e8-9fb4-a69fc890ce0e.png)

1. Place any lightning source from this mod (inverted better)
2. Break it
3. Reload world

Not work on lamp

**Comment by Erro88** [comment]
Noticed the same bug playing on a server.  After placing an inverted light fixture and breaking it, the light will go away temporarily.  When I reload the world, there is light ghosting in the same areas where I had put the light fixture.

By replacing a new light fixture where I had the old one and breaking it again, the light again goes away, but only temporarily.  The ghost light source returns on world load.

**Comment by MrTJP** [comment]
This looks to be an FMP bug. Happens when a light-emitting part is removed from world. Investigating...

**Comment by MrTJP** [comment]
Fixed via CBMultipart commit: 5e49e3df3a9a19cb6f4ef54b64bd9257662e3771
