### ISSUE TITLE
[1.12.2] Game crashed when loading a world

### ISSUE THREAD

**Issue by Voldemort127** [MrTJP/ProjectRed#1286]
I was playing around with the mod in a superflat world, and on the second time I loaded that map, the game crashed.

Here you can find the crash report: https://pastebin.com/mNwLdCtY

**Comment by MrTJP** [comment]
Please update your mods before opening issues on Github.

**Comment by Voldemort127** [comment]
I'm sorry, I thought I had the newest version. My mistake.
