### ISSUE TITLE
[1.12.2] Block placer uses entire stack

### ISSUE THREAD

**Issue by hkLolgast** [MrTJP/ProjectRed#1287]
When putting more than one of an item in a single slot in a block placer and then giving it a redstone pulse, the block placer will place the block, but the entire stack will be gone. I.e. put 30 dirt in it, give a redstone pulse, 1 dirt will be placed, 29 will be gone. Putting items in separate slots works as intended. Using the latest versions (1.12.2-4.8.6.74) of the base, mechanical, integration and fabrication mods.

**Comment by MrTJP** [comment]
Fixed via 4d34254a92b482311650dc06aa07ab62b7807d98
