### ISSUE TITLE
Crash with stock keeper chip in routed interface pipe 1.12.2-4.8.6.74

### ISSUE THREAD

**Issue by Kalmeira** [MrTJP/ProjectRed#1288]
I placed a stock keeper chip set inside a routed interface pipe which was connected to one transport pipe and another routed interface pipe with no chip set. The game crashed and continues to crash as soon as I enter the world.
I don't know how to put in a spoiler, if I even can with github. Sorry.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 5/15/18 8:41 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mrtjp.core.inventory.CapWrapper$$anonfun$getItemCount$1.apply$mcVI$sp(invwrapper.scala:269)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.core.inventory.CapWrapper.getItemCount(invwrapper.scala:267)
	at mrtjp.projectred.transportation.ChipStockKeeper$$anonfun$update$1$$anonfun$apply$mcVI$sp$1.apply$mcV$sp(ChipStockKeeper.scala:54)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at mrtjp.projectred.transportation.ChipStockKeeper$$anonfun$update$1.apply$mcVI$sp(ChipStockKeeper.scala:45)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.projectred.transportation.ChipStockKeeper.update(ChipStockKeeper.scala:44)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart$$anonfun$updateServer$1.apply(RoutedInterfacePipePart.scala:66)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart$$anonfun$updateServer$1.apply(RoutedInterfacePipePart.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart.updateServer(RoutedInterfacePipePart.scala:66)
	at mrtjp.projectred.transportation.TNetworkPipe$class.update(netpipetraits.scala:267)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart.func_73660_a(RoutedInterfacePipePart.scala:13)
	at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58)
	at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95)
	at TileMultipart_cmp$$1.func_73660_a(Unknown Source)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mrtjp.core.inventory.CapWrapper$$anonfun$getItemCount$1.apply$mcVI$sp(invwrapper.scala:269)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.core.inventory.CapWrapper.getItemCount(invwrapper.scala:267)
	at mrtjp.projectred.transportation.ChipStockKeeper$$anonfun$update$1$$anonfun$apply$mcVI$sp$1.apply$mcV$sp(ChipStockKeeper.scala:54)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at mrtjp.projectred.transportation.ChipStockKeeper$$anonfun$update$1.apply$mcVI$sp(ChipStockKeeper.scala:45)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.projectred.transportation.ChipStockKeeper.update(ChipStockKeeper.scala:44)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart$$anonfun$updateServer$1.apply(RoutedInterfacePipePart.scala:66)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart$$anonfun$updateServer$1.apply(RoutedInterfacePipePart.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart.updateServer(RoutedInterfacePipePart.scala:66)
	at mrtjp.projectred.transportation.TNetworkPipe$class.update(netpipetraits.scala:267)
	at mrtjp.projectred.transportation.RoutedInterfacePipePart.func_73660_a(RoutedInterfacePipePart.scala:13)
	at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58)
	at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95)
	at TileMultipart_cmp$$1.func_73660_a(Unknown Source)

-- Block entity being ticked --
Details:
	Name: ccmp:saved_multipart // TileMultipart_cmp$$1
	Block type: ID #978 (tile.null // codechicken.multipart.BlockMultipart)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-948,63,1417), Chunk: (at 12,3,9 in -60,88; contains blocks -960,0,1408 to -945,255,1423), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Actual block type: ID #978 (tile.null // codechicken.multipart.BlockMultipart)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: My World
	All players: 1 total; [EntityPlayerMP['kalmeira'/232, l='My World', x=-940.84, y=64.00, z=1424.87]]
	Chunk stats: ServerChunkCache: 1258 Drop: 0
	Level seed: 6953755706356148409
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2585290 game time, 4281423 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83217 (now: false), thunder time: 95396 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 826379856 bytes (788 MB) / 4290248704 bytes (4091 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.3.2678.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.3.2678             | forge-1.12.2-14.23.3.2678.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | aether_legacy             | 1.12.2-v3.0              | aether_legacy-1.12.2-v3.0.jar                   | None                                     |
	| UCHIJAAAA | architecturecraft         | @VERSION@                | architecturecraft-1.12-2.68.jar                 | None                                     |
	| UCHIJAAAA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | betterbuilderswands       | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | bibliocraft               | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJAAAA | ic2                       | 2.8.76-ex112             | industrialcraft-2-2.8.76-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | jei                       | 4.9.1.179                | jei_1.12.2-4.9.1.179.jar                        | None                                     |
	| UCHIJAAAA | forestry                  | 5.8.0.290                | forestry_1.12.2-5.8.0.290.jar                   | None                                     |
	| UCHIJAAAA | binniecore                | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | binniedesign              | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | genetics                  | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | botany                    | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | extrabees                 | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | extratrees                | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                | None                                     |
	| UCHIJAAAA | guideapi                  | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                     | None                                     |
	| UCHIJAAAA | bloodmagic                | 1.12.2-2.2.12-97         | BloodMagic-1.12.2-2.2.12-97.jar                 | None                                     |
	| UCHIJAAAA | buildcraftlib             | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftcore            | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftbuilders        | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftenergy          | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftfactory         | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftrobotics        | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcrafttransport       | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | buildcraftsilicon         | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCHIJAAAA | carryon                   | 1.9                      | CarryOn MC1.12.2 v1.9.jar                       | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.1.8.341                | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks             | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ctm                       | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCHIJAAAA | chisel                    | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCHIJAAAA | chiselsandbits            | 14.16                    | chiselsandbits-14.16.jar                        | None                                     |
	| UCHIJAAAA | compactsolars             | 1.12.2-5.0.17.340        | CompactSolars-1.12.2-5.0.17.340-universal.jar   | None                                     |
	| UCHIJAAAA | crafttweaker              | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJAAAA | cookingforblockheads      | 6.3.26                   | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCHIJAAAA | ctgui                     | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJAAAA | crafttweakerjei           | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJAAAA | ptrmodellib               | 1.0.2                    | PTRLib-1.0.2.jar                                | None                                     |
	| UCHIJAAAA | props                     | 2.6.0                    | Decocraft-2.6.0_1.12.2.jar                      | None                                     |
	| UCHIJAAAA | flatcoloredblocks         | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
	| UCHIJAAAA | forgemultipartcbe         | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe             | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe     | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | None                                     |
	| UCHIJAAAA | funkylocomotion           | 1.0                      | funky-locomotion-1.12.2-1.1.1.jar               | None                                     |
	| UCHIJAAAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jeibees                   | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | magicbees                 | 1.0                      | MagicBees-1.12.2-3.1.9.jar                      | None                                     |
	| UCHIJAAAA | malisiscore               | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHIJAAAA | malisisdoors              | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHIJAAAA | mcjtylib_ng               | 2.6.7                    | mcjtylib-1.12-2.6.7.jar                         | None                                     |
	| UCHIJAAAA | mtrm                      | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar      | None                                     |
	| UCHIJAAAA | mrtjpcore                 | 2.1.1.27                 | MrTJPCore-1.12.2-2.1.1.27-universal.jar         | None                                     |
	| UCHIJAAAA | nei                       | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft              | 1.12.2u                  | Pam's HarvestCraft 1.12.2u.jar                  | None                                     |
	| UCHIJAAAA | personalcars              | 1.4                      | PersonalCars-1.4.jar                            | None                                     |
	| UCHIJAAAA | projecte                  | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                       | None                                     |
	| UCHIJAAAA | projectred-core           | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-Base.jar             | None                                     |
	| UCHIJAAAA | projectred-integration    | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-transmission   | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-fabrication    | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-fabrication.jar      | None                                     |
	| UCHIJAAAA | projectred-illumination   | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-lighting.jar         | None                                     |
	| UCHIJAAAA | projectred-expansion      | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-transportation | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-exploration    | 4.8.6.74                 | ProjectRed-1.12.2-4.8.6.74-world.jar            | None                                     |
	| UCHIJAAAA | quickleafdecay            | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJAAAA | reborncore                | 3.8.1.271                | RebornCore-1.12.2-3.8.1.271-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rftools                   | 7.33                     | rftools-1.12-7.33.jar                           | None                                     |
	| UCHIJAAAA | rftoolsdim                | 5.53                     | rftoolsdim-1.12-5.53.jar                        | None                                     |
	| UCHIJAAAA | stevescarts               | 2.4.18.92                | StevesCarts-1.12.2-2.4.18.92.jar                | None                                     |
	| UCHIJAAAA | thaumcraft                | 6.1.BETA13               | Thaumcraft-1.12.2-6.1.BETA13.jar                | None                                     |
	| UCHIJAAAA | twilightforest            | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCHIJAAAA | xtones                    | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                        | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.1.271
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['kalmeira'/232, l='My World', x=-940.84, y=64.00, z=1424.87]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MrTJP** [comment]
What was the interface pipe connected to?

**Comment by Kalmeira** [comment]
The one with the chip was connected to a peat bog from forestry (the new retro style farm machine).  the one without a chip was connected to a carpenter.

**Comment by MrTJP** [comment]
Fixed in latest commit to MrTJPCore.
