### ISSUE TITLE
Item crafting chip causes request GUI crash

### ISSUE THREAD

**Issue by SFort** [MrTJP/ProjectRed#1289]
Tried to use the Item crafting chip from project red transport.
Crashed when opening the routed request pipe GUI
[Crash log](https://paste.dimdev.org/kayinitiva.txt)
[Video of setup](https://youtu.be/Q-0sVlGuctQ)

**Comment by MrTJP** [comment]
Fixed via 78fd61d060257baf614b7062588646b897049c36
