### ISSUE TITLE
1.12.2 extractor chip issue

### ISSUE THREAD

**Issue by SFort** [MrTJP/ProjectRed#1291]
If a Item Responder chip is set to match ore dictionary.
extractor chip pipes that have items that they can pull will glitch.
(They don't glitch until you put a item inside the input chest)

Forge: 1.12.2-14.23.3.2676
PR version: 4.8.6.74
[Video](https://youtu.be/-hMqmdbYx-A)

**Comment by MrTJP** [comment]
Fixed in newest commit to MrTJPCore
