### ISSUE TITLE
Looking to add xmod support for ProjectRed [1.7.10]

### ISSUE THREAD

**Issue by draknyte1** [MrTJP/ProjectRed#1295]
Just wondering what the best way to extend the power network would be, as implementing the Tx named interfaces doesn't work overly well in Java.

Without implementing support on my side in Scala, any suggestions?
I'll eventually migrate this to future versions of MC, so I guess it's still a valid Q for 1.12~

Apologies if this is in the wrong spot, but I tried to catch you on IRC for a few days without any luck.

**Comment by MrTJP** [comment]
So the api for power stuff isn’t ready to be implemented yet externally. But there will be a clean way to do it very soon. It’s one of the next few things on the list.

**Comment by draknyte1** [comment]
I guess for older versions it's not really available for external implementation easily at all?

**Comment by MrTJP** [comment]
No. Older versions are not supported at all. It’s time to update.

**Comment by draknyte1** [comment]
> It’s time to update.

Up until the other projects mine rely on update, then that's not happening.
Time to just go back to making compat myself.

Thanks for your time, 
I'll return to this in the future to ask again when I am able to move to newer Forge versions.
