### ISSUE TITLE
[1.12.2] Loading Crash With Thermal Expansion

### ISSUE THREAD

**Issue by EmosewaPixel** [MrTJP/ProjectRed#1296]
So it seems when loading a pack of mine, a crash occurs. I just don't understand why that'd be there are no issues with another pack I have. It seems to be related to the adding a recipe to the TE compactor.
https://pastebin.com/StnFNTzj

**Comment by EmosewaPixel** [comment]
Wait... this is base metals... that was a derp.

**Comment by Morpheus1101** [comment]
You have to turn thermal intergration off as it is apart of Thermal by default now :D
