### ISSUE TITLE
Missing Mods: MrTJPCoreMod : any Forge : any

### ISSUE THREAD

**Issue by astetyn** [MrTJP/ProjectRed#1300]
I have both of them installed in mods. Forge + _MrTJPCore-1.11.2-2.1.0.25-universal_. But forge still cant recognize them :(  . Using _forge-1.11.2-13.20.1.2386-universal_.    Minecraft version 1.11.2

**Comment by astetyn** [comment]
[crash-2018-05-25_21.37.47-server.txt](https://github.com/MrTJP/ProjectRed/files/2040941/crash-2018-05-25_21.37.47-server.txt)

But the mods which are missing were there.

**Comment by OmarWazzan** [comment]
I'm having the same issue as this.

**Comment by astetyn** [comment]
Has someone got the solution for this?

**Comment by Seryyd** [comment]
I`m also having exact same issue.

**Comment by covers1624** [comment]
I don't have a 1.11 env setup anymore, but im going to attempt a fix for this, hold your horses :P

**Comment by OmarWazzan** [comment]
@covers1624 How would I go about downloading the dev version?
