### ISSUE TITLE
Server crash with latest 1.12.2.4.9.0.86 modules.

### ISSUE THREAD

**Issue by Kriiks** [MrTJP/ProjectRed#1307]
Hello!
Updated my server to latest Project Red modules (1.12.2.4.9.0.86) and getting server crash now.
[crash-2018-05-31_08.08.12-server.txt](https://github.com/MrTJP/ProjectRed/files/2056989/crash-2018-05-31_08.08.12-server.txt)

**Comment by MrTJP** [comment]
Duplicate of #1299
