### ISSUE TITLE
Pipes connect but do not interact with alchemical chests

### ISSUE THREAD

**Issue by Kalmeira** [MrTJP/ProjectRed#1309]
While pipes from Project Red now connect to alchemical chests from Project E, they do not actually interact with them. For example, Dynamic Item Responder chips will not allow items to rout into an alchemical chest, nor will broadcasting chips allow you to pull from them.

**Comment by Sixdd6** [comment]
This is confirmed with both Charset Barrels and chests from Metal Chests. The pipes do indeed connect to the modded inventories but refuse to interact with those inventories.

**Comment by MrTJP** [comment]
Omg fixing next. I swear I’ve fixed this like 3 times already 😅

**Comment by MrFastZombie** [comment]
I am having a similar issue with the storage drawers controller, and YABBA barrels.

**Comment by MrTJP** [comment]
Fixed via e42d601ac8e943fe47be488c6e291ef5f515e675
