### ISSUE TITLE
bundled cables + computercraft not working [1.12.2]

### ISSUE THREAD

**Issue by binary1230** [MrTJP/ProjectRed#1310]
I saw #1264 was closed and marked as fixed, but I gave latest downloads a shot and Bundled Cables + ComputerCraft doesn't seem to be working for me with the most recent versions available on Curse. I wanted to ask if bundled cables should be expected to work with CC currently, or if we'd expect them to need some more work.

I see a commit here that is looking related to fixing bundled cables:
https://github.com/MrTJP/ProjectRed/commit/4d34254a92b482311650dc06aa07ab62b7807d98

CC'ing https://github.com/SquidDev since mentioned in https://github.com/MrTJP/ProjectRed/issues/1206

I'm new to minecraft modding but might be able to dig into this, any pointers for doing a build and debugging it to see where things might require fixing?  I am motivated by a [slightly insane pet project](https://www.youtube.com/watch?v=JW55HgpsaYI) I am currently in the middle of converting from MC1.7 to MC1.12, and this is the last big thing that's not working.

Also, is there a canonical or recommended fork of Computercraft currently?

---

my versions of relevant stuff:

```
minecraft: 1.12.2
Win10

ComputerCraft1.80pr1.jar    <--- seems to be the only CC with MC12 release, is this the one you guys are working with?

ForgeMultipart-1.12.2-2.4.2.58-universal.jar
MrTJPCore-1.12.2-2.1.2.34-universal.jar
ProjectRed-1.12.2-4.9.0.86-Base.jar
ProjectRed-1.12.2-4.9.0.86-compat.jar
ProjectRed-1.12.2-4.9.0.86-fabrication.jar
ProjectRed-1.12.2-4.9.0.86-integration.jar
ProjectRed-1.12.2-4.9.0.86-lighting.jar
ProjectRed-1.12.2-4.9.0.86-world.jar
```

Thanks all, both these mods are amazing.

**Comment by MrTJP** [comment]
Hmmm. I was using Computeacube, though the underlying api should be the same.

**Comment by binary1230** [comment]
will give that a shot real quick see if it makes a difference, thanks!

**Comment by binary1230** [comment]
ok, with Computeacube mod I did a simpler repro and that seems to be working now, though my other test isn't (which makes me think it's actually now a problem with my lua code), I think it's probably an issue on my end.  will diagnose it some more and also figure out if it's a Computeacube-specific thing or if it works with any ComputerCraft mod.   thanks

**Comment by MrTJP** [comment]
If the cables are visibly connecting, that means the compatibility code is working. The rest is up to your Lua code. I will close this now.

**Comment by binary1230** [comment]
alright, after fiddling for a while I traced it down to my fault with the attachment points to the computercraft computer.

This configuration works:
![image](https://user-images.githubusercontent.com/5413064/40827601-082c849c-654c-11e8-8e68-82ca2eea92d3.png)

This config doesn't work (if you crouch with SHIFT and right click the side of the computer with a multi-cable)
![image](https://user-images.githubusercontent.com/5413064/40827668-4438043e-654c-11e8-8171-f7f57b64dd64.png)

This crouch+right click behavior is how computercraft attaches modems to the side of the interface.

So, moral of the story is: don't do that with the bundled cable?  Is that by design or a bug?

**Comment by binary1230** [comment]
for clarity sake here's the piece highlighted:
![image](https://user-images.githubusercontent.com/5413064/40827796-aeea7578-654c-11e8-8da3-89e22b9fc3cd.png)

**Comment by MrTJP** [comment]
Well, if you put a cable on the side like in the third picture, it’s not even connected to the computer. Try it with a lamp and insulated wire. Same behavior ;)

**Comment by binary1230** [comment]
yea, funny thing I think I had it hooked up the right way originally, then when I couldn't get it to work due to the older version, must've changed it to be this way by mistake, then when upgrading to the new version, I started with it like this.   sometimes just how it goes :)    Anyway thanks again

-Dom
