### ISSUE TITLE
[1.12.2] Strange button lighting on multiple bus input panels.

### ISSUE THREAD

**Issue by MaudDibb** [MrTJP/ProjectRed#1319]
when using multiple bus input panels, it seems *only* the first panel placed gets button lighting when any buttons (not just on the first panel) are toggled.  The other panels don't get any lights at all, although they add more light to the first panels buttons, making them brighter than usual.

see attached image:
![2018-06-12_22 24 09](https://user-images.githubusercontent.com/7418069/41328900-16cbdd84-6e90-11e8-973d-557d77d210cd.png)

running 1.12.2, latest pr mod files, forge 14.23.3.2670, computer craft 1.80pr1, world edit 6.1.8, world edit cui 2.1.2, WirelessRedstone-CBE 2.3.0.27, NEI, JEI, CodeChickenLib 3.1.9.344 (all installed in custom profile via Twitch client)

**Comment by MaudDibb** [comment]
updated to forge 14.23.4.2707, still same glitch

**Comment by MrTJP** [comment]
Fixed via 38b894f1d04e420c324b046fc53cf1ba6f3a63a5
