### ISSUE TITLE
Batching chunks crash

### ISSUE THREAD

**Issue by kaosjr** [MrTJP/ProjectRed#1321]
I've had a really strange issue recently while trying to get the modpack I author, Potentiality, to work properly on my laptop.
For some reason, whenever I join a server, it seems to work properly for about half a minute. After that, the screen goes black, and I get a crash report for 'batching chunks'. 
Here's a link to Pastebin: [](https://pastebin.com/gHq3SZri)
It might have something to do with the integrated graphics, but that hasn't had issues with any 1.12 packs before for me. This crash doesn't occur on my PC with a GTX 960 and a i5 6600K, with the exact same pack.

**Comment by kaosjr** [comment]
I've also tried disabling FoamFix, with no luck.

**Comment by MrTJP** [comment]
Update to the latest build. Should fix this.
