### ISSUE TITLE
(1.12.2) item duplication bug

### ISSUE THREAD

**Issue by larskr96** [MrTJP/ProjectRed#1322]
The setup and whats happening:
![2018-06-17_16 22 11](https://user-images.githubusercontent.com/10383027/41508852-7f201544-724b-11e8-9dde-e8ae547d76c7.png)

Mods im using
Jei
And all of the Project Red mods

**Comment by acanady** [comment]
yeah i'm getting this same thing too

**Comment by MrTJP** [comment]
Fixed in MrTJP/MrTJPCore@18c033f361f15e07c8470e94e75513d9a0456390
