### ISSUE TITLE
[Request] Buffer/Inverter cells for IC Workbench?

### ISSUE THREAD

**Issue by MaudDibb** [MrTJP/ProjectRed#1324]
Right now, only null cells are available when working on ic blueprints (1.7.10 versions did have all 3). It would be really handy to have the buffer/invert cells for building ic circuits like 4-16 decoders, 7/16 seg display drivers, binary to decimal converters (think double-dabble). Those are not possible to do in an ic with only null cells, and would require massive real estate on a blueprint if done the 'hard' way with not/buffer gates, never mind the wiring mess. It would be amazing to see and/data cells as well...those are really handy for latching data while keeping things compact.

**Comment by covers1624** [comment]
This is something that is planned, due to the complexity of how integration 'compiles' the logic down, i'm not sure if the backend currently supports this, @MrTJP was working on it, and got null cells working. He will have to fill in more.

**Comment by elijahlorden** [comment]
+1 This would allow you to design any kind of decoder in an IC.  Imagine being able to fit a 4:16 demultiplexer in a single block.  The massive 256-address Memory Address Decoder I recently finished would fit in just a few blocks!

**Comment by MrTJP** [comment]
This is being discussed here: #1616
