### ISSUE TITLE
Project Red Transportation Pipes/Chips not Recognizing Mass Storage Units

### ISSUE THREAD

**Issue by leojaxx** [MrTJP/ProjectRed#1325]
Trying out some things in a test world and found that the Routed Interface pipes and the Broadcaster & Responder chips don't work with mass storage units. Tried with Storage Drawers ( single drawer and controller ) Yabba barrels, Industrial Foregoing Black Hole Units and the Thermal caches. They don't even work with the Immersive Engineering Crates.

By not working I mean the request pipe doesn't show what's in the inventories and when putting items into the system the storage units they get skipped, even if the priorities higher. I also checked with a vanilla chest and a crystal chest from the Iron Chest mod to make sure I had the chips configured correctly.

The pack is Revelations 2
Project Red version is 4.9.0.86
MrTJP Core Version is 2.1.2.34

Please let me know if you need to know anything else.

Thanks

**Comment by larskr96** [comment]
Its an old bug
![2018-06-18_09 57 45](https://user-images.githubusercontent.com/10383027/41524539-2e111110-72de-11e8-9d69-69777b26288d.png)

Im using the newest versjon of Project Red

**Comment by MrTJP** [comment]
Update.
