### ISSUE TITLE
Block Breakers get moved by frames on their front face

### ISSUE THREAD

**Issue by Lach01298** [MrTJP/ProjectRed#1326]
Title says everything. Tested in version 1.12.2-4.9.1.92

**Comment by covers1624** [comment]
I'm not exactly sure if this is a bug or not..

**Comment by Lach01298** [comment]
So how do you make frame machines with extendable arms ie quarrys? Also the block placer doesn't stick to frames on the front so i would only imagine the block breaker to do the same. this was how it was with red power.

**Comment by covers1624** [comment]
OH, it is movable ONLY by the front face?

**Comment by Lach01298** [comment]
no the breaker is movable on all faces. the placer is movable on all faces but the front.

**Comment by Lach01298** [comment]
i'm say the breaker should be the same as the placer

**Comment by MrTJP** [comment]
I believe this is a bug. If I remember, RP block breakers were not stickable on the front face. Will be fixed.

**Comment by MrTJP** [comment]
Fixed via ca7860967509597ec6e9a5e90ce1d73c9a096189
