### ISSUE TITLE
Lag issue with frames on server

### ISSUE THREAD

**Issue by karelmikie3** [MrTJP/ProjectRed#1328]
First of all, I haven't had the time to test this in a clean environment nor in a client world but from what is seems like that some tileentities and especially project red's own battery boxes stay as tileentity behind and keep ticking when moved by frames.
https://puu.sh/AHvxl.png
in this image I used LagGoggles to profile the lag in the mining dimension which I had thought to be caused by a frame quarry I made with buildcraft Mining wells. I thought moving the mining wells caused the lag issue but when I checked I saw an array of ticking air blocks exactly where the battery boxes had been. Furthermore restarting the server fixes the error, probably because it invalidates the invalid tileentities that aren't supposed to be on air blocks.

[latest.log](https://paste.ee/p/issNs)

minecraft: 1.12.2
project red: 4.9.1.92
forge: 14.23.4.2705

**Comment by MrTJP** [comment]
Dear god lol. Looking into this now

**Comment by MrTJP** [comment]
Hopefully fixed via ca7860967509597ec6e9a5e90ce1d73c9a096189
