### ISSUE TITLE
Crash when opening quark config

### ISSUE THREAD

**Issue by build2stone** [MrTJP/ProjectRed#1331]
This happens when the Project Red - Mechanical module is included.
https://pastebin.com/wKzaD30F

Mods used:
-forge-14.23.4.2709
-AutoRegLib-1.3-18
-CodeChickenLib-1.12.2-3.1.9.344
-ForgeMultipart-1.12.2-2.4.2.60
-ProjectRed-1.12.2-4.9.1.92-Base
-ProjectRed-1.12.2-4.9.1.92-mechanical
-Quark-r1.4-125

**Comment by MrTJP** [comment]
Fixed via dd27e1e3f194d3bef80e33b3f9372ce66891e715

**Comment by SilverDarkBlade** [comment]
still having this issue with current version
