### ISSUE TITLE
[1.11.2] Project Red "missing mods"

### ISSUE THREAD

**Issue by OmarWazzan** [MrTJP/ProjectRed#1332]
![63581d 1](https://user-images.githubusercontent.com/19527321/41807112-3d319e42-76d2-11e8-9ad2-3cd47cf4fbb0.png)

Log file: https://pastebin.com/KWu3Lc3C

both forge and MrTJPCore are installed.

**Comment by MrTJP** [comment]
Duplicate of #1300
