### ISSUE TITLE
Lamps look weird

### ISSUE THREAD

**Issue by ThatEpicBanana** [MrTJP/ProjectRed#1333]
Lamps seem to have all the textures on them while the lamps are on

Using Faithful+1.12.2-rv4 Faithful x32
![minecraft 1 12 2 6_26_2018 3_21_12 pm](https://user-images.githubusercontent.com/40611336/41934794-9c089436-7955-11e8-8390-3f4d7bd7741a.png)
![minecraft 1 12 2 6_26_2018 3_21_24 pm](https://user-images.githubusercontent.com/40611336/41934795-9c19698c-7955-11e8-88c4-8e5829d1110d.png)

**Comment by acanady** [comment]
Yeah I got the same issue. Remove optifine, that'll fix out. Sadly you wont have your awesome Shaders but hey. I'm guessing there's a rendering issue for the little glow texture that the lamps have on the outside when optifine is installed. I remember having the same issue on past version of MC. Also, what version of optifine do you have? It may be that it doesn't happen on a specific version.

**Comment by covers1624** [comment]
Yeah this sounds like an optifine issue, you'll have to seak support from them on this one.

**Comment by ThatEpicBanana** [comment]
I have HD_U_D1 for optifine(I think)
And that seems to work.

**Comment by acanady** [comment]
by seems to work did you mean that it doesn't cause issue?

**Comment by acanady** [comment]
Oh and it can also be the shaders. When i have the shaders turned on, TME shaders, it causes problems.

**Comment by ThatEpicBanana** [comment]
I meant that it was optifine.

**Comment by acanady** [comment]
So I'm using the exact same version and I dont get the broken textures of no shaders are applied

**Comment by acanady** [comment]
It was a problem in past versions and was solved, looks like its cropped back up lol.

**Comment by ThatEpicBanana** [comment]
Yeah, it seems to be the shaders for me too.
The shader I use is BloomnX 2 - Medium
