### ISSUE TITLE
[1.12.2] client disconnecting when using a frame motor

### ISSUE THREAD

**Issue by SpeedrunnerG55** [MrTJP/ProjectRed#1335]
ProjectRed version: ProjectRed-1.12.2-4.9.0.86-Base
MrTJPCore version: MrTJPCore-1.12.2-2.1.2.34-universal

Steps to reproduce:

place down a frame motor
power it
activate it to move a block or fame
Client will disconnect immediately and the server will show the following in the console. Server doesn't crash though, client can reconnect immediately. the blocks move after reconnecting

`[14:48:57] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: SpeedrunnerG55 lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoEx
ception: syscall:read(..) failed: Connection reset by peer
`
and the disconnect message is 

`project red internal exception io.netty.handler.coder.decoderexception: the received string is longer then the maximum allowed (21 > 20)`

**Comment by MrTJP** [comment]
You want to update *before* asking for help.
