### ISSUE TITLE
Alloy Wires disappear when restarting server

### ISSUE THREAD

**Issue by MatthewThePiano** [MrTJP/ProjectRed#1336]
Every time I restart my server, a seemingly random amount of my placed alloy wires disappear.
I haven't the slightest idea what could be causing this issue...
If any of you can help, I can provide whatever logs or info you may need.

Plz help :D

My mods:
![currentmods](https://user-images.githubusercontent.com/40648908/42008815-65dac41e-7a55-11e8-9142-ce3650e709de.PNG)

**Comment by covers1624** [comment]
Cleaning this in to a single issue: https://github.com/TheCBProject/ForgeMultipart/issues/29
