### ISSUE TITLE
Issue with timers in IC gates

### ISSUE THREAD

**Issue by brandon3055** [MrTJP/ProjectRed#1338]
Im not sure exactly what causes this but when triggering a frame motor with a timer regular the minimum interval you can use is 0.8 seconds. As i'm sure you know this results in a smooth continuous movement. 
If you attempt to do the same thing with a timer in an ic gate the motor misses every second pulse. Its as if the gate timer is running faster or is somehow out of sync in some way.

**Comment by MrTJP** [comment]
This is outdated now, due to a pending rewrite: #1616
