### ISSUE TITLE
IC Printer UI not updating required items based on contents of adjacent inventories. 

### ISSUE THREAD

**Issue by brandon3055** [MrTJP/ProjectRed#1340]
As i'm sure you know the IC printer is capable of pulling ingredients from an adjacent inventory. This works correctly however the printer UI does not reflect what is available in those inventories. i.e items that are available in an adjacent inventory show as missing in the printer UI.

**Comment by MrTJP** [comment]
Fixed via 5526a01ab0791d19a9920b2e831762680a2fe253.
