### ISSUE TITLE
Totally inadequate documentation on the proper use of the IC workbench and IC chip printer. ESPECIALLY CHANGES LIKE A NEW BUNDLED CABLE IO

### ISSUE THREAD

**Issue by deadscion** [MrTJP/ProjectRed#1343]
Bundled IO set for output, with bundled cable connected is ok. Insulated wires connected to bundled cable also show ok, but with a "not connected to output error". If I ignore this error alert and print the IC chip anyway, the result is useless bundled cable connectors.

**Comment by deadscion** [comment]
Suggest further documentaion, especially when changes like a bundled cable IO  addition is concerned. Why should I have to learn how to use you mod the hard way??? HUH??? WHY???
Anyway for other readers, when you use a bundled IO on the edge of a blueprint, you are making that entire side of the chip a bundle port. A bundle port has 16 channels for 16 wires in the bundled cable.
You, as the editor of this chip, must send every wire needing this bundle cable  to a seperate bundle IO.  
Set each bundled IO  to input or output and channel color to the color of the wire you want to use outside the chip.
When you connect a bundled cable to the chip the same color of wire in that bundle must be used. to operate your chip.

**Comment by covers1624** [comment]
You are basically raging at a 1 man dev team for not providing documentation when life is a thing. Myself and TJ have this planned, but need to find time to get arround to it. Do NOT create another issue on this if you are just going to be a cunt. Consider this a first warning, next will be a ban.
