### ISSUE TITLE
[Suggestion] Add Comparators to ICs

### ISSUE THREAD

**Issue by elijahlorden** [MrTJP/ProjectRed#1344]
I have been trying to find a compact way of extending the length of bundled cables, but have been unable to do so.  The only way I have found of bi-directional signaling is through the use of comparators.  Comparators are not available on ICs, which means it is not possible to use this method in a compact manner.  Unless there is some technical reason for comparators not being present in ICs, they would be a nice addition.

**Comment by elijahlorden** [comment]
If the reason for them not being included is that signal strength is not simulated, an efficient way to simulate signal strength could be to save the distance between connections and subtract it from 255 when handling an incoming signal.

**Comment by Dushess** [comment]
It was already asked, and not possible to make.

**Comment by MrTJP** [comment]
Signals within ICs are not analog so a comparator would be pointless to have in there.

**Comment by xMGZx** [comment]
Why exactly do you offer analog input then into ICs if it can't use it?
