### ISSUE TITLE
Can't process Project Red metallic ores with Mekanism

### ISSUE THREAD

**Issue by TheRedMelon** [MrTJP/ProjectRed#1346]
Mekanism's machines wont accept them

**Comment by covers1624** [comment]
ProjectRed should register its ores to the OreDictionary, if Mek isn't handling that properly then its not on our end. I believe @thiakil is a Mek dev, perhaps they are able to shead some light on this.

**Comment by thiakil** [comment]
If they're registered when the items are registered (or at the latest before Mek's init iirc) and they're in our "minor compatibility" list it should work indeed.

Minor compat is `"Nickel", "Aluminum", "Uranium", "Draconium", "Platinum", "Iridium"`  (https://github.com/aidancbrady/Mekanism/blob/3e469fb40a2a086527cf14dbe9ba709f708a9bca/src/main/java/mekanism/common/integration/OreDictManager.java#L34)

Plus common metals like iron, gold, copper, tin, silver, lead (https://github.com/aidancbrady/Mekanism/blob/3e469fb40a2a086527cf14dbe9ba709f708a9bca/src/main/java/mekanism/common/Resource.java#L7)

**Comment by MrTJP** [comment]
ProjectRed now registers all OreDictionary values along with the item during PreInit (4d65f167988d65c2b5dd6b0c3e2b2467b842eddb). It should fix this issue if Mek was checking this during the Init phase.

**Comment by thiakil** [comment]
Uhhh, why are you not using the registry events?

**Comment by MrTJP** [comment]
Wasn’t aware there were events for registering to the OreDict?

**Comment by thiakil** [comment]
no, your items. `ForgeRegistries.ITEMS.register` is wrong.
