### ISSUE TITLE
[request] Compatiblity with BuildCraft Builder block to copy/paste ProjectRed logic and wires

### ISSUE THREAD

**Issue by deadscion** [MrTJP/ProjectRed#1350]
Or compatibility with some  other copy and paste mod to reduce time and errors on large logic projects like large light displays, player piano, or other challenges attempted without ComputerCraft help.

**Comment by covers1624** [comment]
This should technically be possible but depends on how BuildCraft is handling their pasting. Regardless this is technecally an FMP issue, but ill leave this open here for now.

**Comment by MrTJP** [comment]
Gonna close this out, since it is an FMP issue.
