### ISSUE TITLE
[1.12.2] Crash on world load

### ISSUE THREAD

**Issue by drewbit** [MrTJP/ProjectRed#1351]
One of my players was getting this consistently, removing Better Foliage fixed the issue. Figured it should be reported here too.

Project Red Versions: ProjectRed-1.12.2-4.9.0.86 (Every module same version)
Forge Version: 14.23.4.2707

Crashlog: https://paste.ee/p/whcml

**Comment by MrTJP** [comment]
If you went through the trouble to figure out that removing Better Foliage mitigates the issue, you could’ve also tried updating ProjectRed. That will actually fix it.
