### ISSUE TITLE
1.10.2 -  game crash with full backpack

### ISSUE THREAD

**Issue by Golummechanic** [MrTJP/ProjectRed#1352]
greetings MrTJP,

while playing my new modpack I got a bit shortpocketed so I crafted a backpack from Project red to stuff my inventory in. however, everytime I tried to open the bag it flatout crashed on me.
I tested it twice yeterday and once today for good mesure.

Now I have browsed around the web and found the crash logs with a identical problem here on this github.
What suprised me was that the problem was lebelt as fixed, I have checked if I had the last version of 1.10.2 and if you had another place of distribution outside forge curse.
But it seems Im fully uptodate.

As a way to help myself I tried to look up the file menioned in here :[https://github.com/MrTJP/ProjectRed/blob/master/src/mrtjp/projectred/exploration/items.scala](url)
Which I was not able to.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Other data what might be handy:**

**_Minecraft:_** 1.10.2
**_Forge:_** 1.10.2-12.18.3.2488

**_Project red Mods used:_**
MrTJPCore-1.10.2-2.0.1.20-universal
ForgeMultipart-1.10.2-2.0.0.38-universal
ProjectRed-1.10.2-4.8.4.49-Base
ProjectRed-1.10.2-4.8.4.49-fabrication
ProjectRed-1.10.2-4.8.4.49-integration
ProjectRed-1.10.2-4.8.4.49-lighting
ProjectRed-1.10.2-4.8.4.49-world

**_Other mods used:_**
JustEnoughCalculation-1.10.2-2.6.5
InventoryTweaks-1.62-dev-66
ProjectE-1.10.2-PE1.3.1
Railcraft_1.10.2-10.3.1
RailCraft+Cosmetic+Additions-3.0.5
iChunUtil-1.10.2-6.5.0
PortalGun-1.10.2-6.0.1-fix-1
davincisvessels-1.10.2-0006-full
movingworld-1.10.2-0007-full
IronBackpacks-1.10.2-2.2.33
ironchest-1.10.2-7.0.15.804
GalacticraftCore-1.10.2-4.0.1.181
Galacticraft-Planets-1.10.2-4.0.1.181
MicdoodleCore-1.10.2-4.0.1.181
ModularPowersuits-1.10.2-1.2.129
nuclearphysics-1.10.2-0.1.37
MCMultiPart-1.4.0-universal
Mekanism-1.10.2-9.2.4.103
MekanismGenerators-1.10.2-9.2.4.103
CodeChickenCore-1.10.2-2.4.1.102-universal
jei_1.10.2-3.14.8.422
CodeChickenLib-1.10.2-2.5.9.320-universal
journeymap-1.10.2-5.5.2
NotEnoughItems-1.10.2-2.1.3.220-universal

And the 3 crash reports on the matter:
[crash-2018-07-09_22.00.53-client.txt](https://github.com/MrTJP/ProjectRed/files/2181528/crash-2018-07-09_22.00.53-client.txt)
[crash-2018-07-09_22.03.51-client.txt](https://github.com/MrTJP/ProjectRed/files/2181529/crash-2018-07-09_22.03.51-client.txt)
[crash-2018-07-10_19.20.23-client.txt](https://github.com/MrTJP/ProjectRed/files/2181530/crash-2018-07-10_19.20.23-client.txt)

**Comment by MrTJP** [comment]
Update.

**Comment by Golummechanic** [comment]
@MrTJP Update what?
MrTJPCore?
ForgeMultipart?
ProjectRed base?
