### ISSUE TITLE
two random crashes related to your mod.

### ISSUE THREAD

**Issue by Trinsdar** [MrTJP/ProjectRed#1356]
I don't know why but twice when I placed down items from your mod it crashed me.
https://paste.dimdev.org/guyimeqeho.mccrash
https://paste.dimdev.org/obeqeyogot.mccrash

minecraft version is 1.12
forge is 14.23.4.2729
code chicken lib 3.2.0.345
forge multipart 2.4.2.60
project red 4.9.1.92 base/compat/fabrication/integration/lighting/mechanical/world

**Comment by Trinsdar** [comment]
make it three now

**Comment by MrTJP** [comment]
You have 254 active mods (!). Unless you narrow that down, there is no way for me to look into this.
