### ISSUE TITLE
Dimensional doors schematics incompatible with multiparts

### ISSUE THREAD

**Issue by Trinsdar** [MrTJP/ProjectRed#1359]
i can create the schematics, but if i try to load them it throws an error and fails to load any forge multipart and project red multiparts.
Full log: https://gist.github.com/Trinsdar/c00dcfe1c3bc871276141e1301287033

minecraft version 1.12.2
forge 14.23.4.2729
code chicken lib 3.2.0.345
forge multipart 2.4.2.60
project red 4.9.1.92 base/compat/fabrication/integration/lighting/mechanical/world
DimensionalDoors-3.0.9-287
I also made an issue on their github: https://github.com/DimensionalDevelopment/DimDoors/issues/83
They told me in discord that it was a problem on your end as the mod schematica also has problems loading schematics with project red multiparts.

**Comment by covers1624** [comment]
/technecally/ the same as https://github.com/TheCBProject/ForgeMultipart/issues/35 and should be fixed by my changes for that. if DimDoors has an API for tile construction that would be nice.
