### ISSUE TITLE
[Request] I/O Workbench blueprints saved to real life files for sharing.  Knowledge is power.

### ISSUE THREAD

**Issue by deadscion** [MrTJP/ProjectRed#1362]
Many classic logic diagrams, in real life, do not work in MineCraft for many reasons. Sharing knowledge on what does work is a huge help.

**Comment by SupinePandora43** [comment]
if you want add Workbench blueprint exporting to file, i want it too.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
