### ISSUE TITLE
[1.12.2] project red blocks (namely pipes) disappear when the chunk they are in is not loaded

### ISSUE THREAD

**Issue by watermeadow** [MrTJP/ProjectRed#1367]
this has been happening for a loooong time. i run a server and we have a very tidy modpack with about 50 mods, including the entirety of projectred. upon leaving an area containing pr blocks such as item transport pipes, and returning (thus reloading the chunk after it had been unloaded), all pr blocks have disappeared. they aren't invisible. they're gone. occasionally they seem to pop back up, such as after a server restart. a number of folks have been having this issue [here](https://minecraft.curseforge.com/projects/project-red-base?gameCategorySlug=mc-mods&projectID=228702)

**Comment by covers1624** [comment]
Duplicate, Master issue over here: https://github.com/TheCBProject/ForgeMultipart/issues/29
