### ISSUE TITLE
Incompatible with WorldEdit

### ISSUE THREAD

**Issue by dooferorg** [MrTJP/ProjectRed#1369]
Running Minecraft 1.12, if greater than 6 Project Red illumination entities are within an area and you copy and then paste it with World Edit, the client disconnects out with the message 'Client multipart @BlockPos (coordinates) not found'

No messages on the server.

**Comment by covers1624** [comment]
FMP issue, https://github.com/TheCBProject/ForgeMultipart/issues/35
