### ISSUE TITLE
How much do ProjectRed wires increase packet size?

### ISSUE THREAD

**Issue by seancrain** [MrTJP/ProjectRed#1370]
I'm having a connection issue that started only a few hours ago, and the only things I can think of that are causing packet sizes to increase over the limit are BiblioCraft creative bookcases and ProjectRed wiring. Do wires contribute enough to cause packet overflow or is something else likely to blame?

**Comment by covers1624** [comment]
Something else would be to blame, PR used FMP's packet system and things are extremely efficient, each chunk's updates for multiparts are batched into the one packet at the end of the tick, it'd likely be something else causing the issues.
