### ISSUE TITLE
1.7.10 | Bucket dissapears when crafting ICBM-Classic concrete in Project Bench

### ISSUE THREAD

**Issue by StrBrkrs-NullException** [MrTJP/ProjectRed#1371]
Whenever I craft ICBM Concrete in the Project Bench, the water bucket used is not returned/is consumed. This is not an intended outcome, since the bucket is returned when using the vanilla crafting table.

**Comment by covers1624** [comment]
1.7.10 is unsupported, If the issue persists in 1.12 we can address that in a separate issue.
