### ISSUE TITLE
Stuff disappears from world on large Logic gate projects

### ISSUE THREAD

**Issue by deadscion** [MrTJP/ProjectRed#1373]
I was building a player piano without the aid of ComputerCraft, out of logic and wires. When it came to increasing ram, I reached a limit and can go no further. Anything extra I place beyond what I currently have in the world will disappear. No errors show.

**Comment by Dushess** [comment]
Seems to be exceeding chunk storage limin, but not sure.

**Comment by deadscion** [comment]
You were right Dushess. I had no idea there any such thing as chunk storage limit. I will have to reconfigure my ram storage areas to respect that but thank you very much.
