### ISSUE TITLE
[Request] Labeling Inputs/Sections of an IC Blueprint

### ISSUE THREAD

**Issue by kitlith** [MrTJP/ProjectRed#1375]
For inputs, especially bundled cable inputs, it would be nice to be able label their purpose in the blueprint. Additionally, for complicated ICs with multiple components, it would be nice to be able to label the purpose of various sections of the IC.

For instance, in the 4x8 bit dual read memory IC I created recently, I would be able to label my data inputs, address inputs, chip select inputs (for external address decoding), and data outputs, as well as each memory cell and the internal (2 bit) address decoding logic.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
