### ISSUE TITLE
Project Red's Comparator does not match Vanilla behavior when signal strength output would be greater than 15

### ISSUE THREAD

**Issue by kitlith** [MrTJP/ProjectRed#1376]
![comparator_mismatch](https://user-images.githubusercontent.com/7027737/43699512-e37d7c50-9903-11e8-9d69-0baf24e2c56d.png)

If someone manages to obtain a stack of non-stackable items (#1377), then a comparator can calculate a signal strength of greater than 15 (for vanilla Redstone). In this case, the vanilla comparator saturates -- it stays at 15 ss (what actually happens is that Redstone dust itself caps the ss, it'll transfer to other comparators), while the project red comparator wraps around.

![hopper_ui_comparator_mismatch](https://user-images.githubusercontent.com/7027737/43699712-ba3eb754-9904-11e8-93f0-971ae43b0d2a.png)

(If you're wondering what's up with the numbers on the redstone dust, that's from a resource pack)

**Comment by MrTJP** [comment]
I've adjusted the comparator as much as possible to act more like the vanilla comparator in 64ab50eeeb2cff2f5b76d68a6051967e4dfd6fb9. It doesn't fix this specific case though, but since this is only relevant when you have invalid items, I'm not too concerned.

**Comment by MrTJP** [comment]
It is. But this is outside of normal conditions and it’s undefined behavior when the signal is more than 15. And this is caused by the core foundation of how PR logic gates calculate power. Not worth changing over this.

**Comment by kitlith** [comment]
Yeah, I get that.
