### ISSUE TITLE
Copying Blueprint ICs allows you to create a stack of 'non-stackable' items

### ISSUE THREAD

**Issue by kitlith** [MrTJP/ProjectRed#1377]
So, first off, this isn't a very important issue unless you're working with comparators, I'm just documenting what's up here.

When you copy an IC blueprint, it puts all of the final blueprints into the crafting bench output slot. This allows you to create a stack of an item classified as non-stackable items.

![crafting-bench-stacking](https://user-images.githubusercontent.com/7027737/43699302-144bd86e-9903-11e8-8552-22b03f4dd2d7.png)

This doesn't do too much until you take a comparator output on a container and go "the container isn't actually full, but my comparator says it is." Unless you're using the comparator bundled with project red, in which case you run into #1376.

**Comment by MrTJP** [comment]
I have addressed this in 504581acfdfaa4e01f7b677e4aea407ce57a4021. You can now only copy to a single blueprint at a time, and the original will just stay in the crafting grid instead of being stacked with the output.
