### ISSUE TITLE
Feedback loop between Red Alloy Wire and Redstone Dust can cause it to become 'stuck' on

### ISSUE THREAD

**Issue by kitlith** [MrTJP/ProjectRed#1378]
![feedback-loop](https://user-images.githubusercontent.com/7027737/43745913-1d3e4c48-9996-11e8-875e-7766d89e87ab.png)

Not super important, but something that people should at least be aware of.

**Comment by MrTJP** [comment]
Fixed with fee6bfbefd8f36ef0a036a34631ae8ed2e9a3cd2
