### ISSUE TITLE
Routed pipes network is not working

### ISSUE THREAD

**Issue by CryingFox** [MrTJP/ProjectRed#1380]
![2018-08-08_16 13 52](https://user-images.githubusercontent.com/42212165/43843008-db2d2440-9b26-11e8-8960-dd54f01dc9c8.png)

i Built a basic storage network : a chest with an extractor chip and a chest with a responder chip and a broadcaster chip. The system is not working : I can't see items in the request pipe and the items in the chest with the extractor chip don't leave the chest. I tried the same network on a different world and it not worked too.

**Comment by covers1624** [comment]
Please provide version numbers, its basically impossible to say without them.

**Comment by Psy-Virus** [comment]
Just guessing: Did you check the white/black listing?
It sounds like you white listed nothing.

**Comment by MrTJP** [comment]
This is just an incorrectly configured system. The requester only needs the broadcast chip to work. The broadcast chip needs to be configured to allow all items.

The extractor is a passive system. Configure something with a responder chip. Make sure they both allow the items you want.
