### ISSUE TITLE
Inductive Furnace won't smelt Tin/Copper/Silver Ore - ProjectRed 1.12.2

### ISSUE THREAD

**Issue by SgtHugoStiglitz** [MrTJP/ProjectRed#1381]
Inductive Furnace won't smelt Tin/Copper/Silver Ore.

Gold/Iron Or Cobble to Stone is working fine. 

Stone Furnace is able to smelt Tin/Copper/Silver.

Installed Mods:

ChickenChunks-1.12.2-2.4.1.73-universal
CodeChickenLib-1.12.2-3.2.1.350-universal
ForgeMultipart-1.12.2-2.5.0.70-universal
jei_1.12.2-4.11.0.202
MrTJPCore-1.12.2-2.1.3.35-universal
ProjectRed-1.12.2-4.9.1.92-Base
ProjectRed-1.12.2-4.9.1.92-fabrication
ProjectRed-1.12.2-4.9.1.92-integration
ProjectRed-1.12.2-4.9.1.92-lighting
ProjectRed-1.12.2-4.9.1.92-mechanical
ProjectRed-1.12.2-4.9.1.92-world

**Comment by MrTJP** [comment]
Fixed via 1bd81b0c4996f7e1348c3c0400be8a66a6329ddf.
