### ISSUE TITLE
Open Computer Support of Bundled Cables

### ISSUE THREAD

**Issue by darkman1984** [MrTJP/ProjectRed#1383]
Hi there!
Not an issue but is it possible that you implement that the bundled cables works on the Redstone I/O or directly on the Computer of Open Computers? Currently if you place one next to the Redstone I/O it doesn't connect to the block. Or is there a trick to do that?

Greetings
DaRkMaN1984

**Comment by darkman1984** [comment]
For one second tested: Bundled cables with ComputerCraft works and connect but not with OpenComputers and no... OpenComputers has it's own API and don't depends on ComputerCraft.
BUT... i found an issue in the OpenComputers Github where the same problematic is part of the issue and if i remind it correcly the official OpenComputers Version can't connect to the bundled cables and the inofficial Version can connect? But don't nail me down.

I think it would be better and easier if you use their API to connect the Cables.

**Comment by MrTJP** [comment]
Seems like OpenComputers is not yet on 1.15+. If it does get ported, I will support it.
