### ISSUE TITLE
CTD, Error with Quark installed.

### ISSUE THREAD

**Issue by I2pRandom** [MrTJP/ProjectRed#1386]
Crashed straight to Desktop when attempting to access the Quark menu.
As far as i'm understanding when reading this error, the error starts from ProjectRed.
Also posted on the Quark git in-case this problem actually has something to do with Quark it's self

[crash-2018-08-18_21.05.07-client.txt](https://github.com/MrTJP/ProjectRed/files/2300043/crash-2018-08-18_21.05.07-client.txt)

**Comment by meradz** [comment]
Duplicate of #1331
