### ISSUE TITLE
Porting from RedPower FORTH Computers

### ISSUE THREAD

**Issue by 0xF6** [MrTJP/ProjectRed#1387]
[Central Processor Unit](https://mcmod.wiki/Central_Processing_Unit_(RedPower_2)) and etc

**Comment by simon816** [comment]
Coincidentally, I just published a 65el02 CPU implementation - https://github.com/simon816/J65el02

**Comment by 0xF6** [comment]
@simon816, nice!

**Comment by MrTJP** [comment]
I was at one point super interested in adding the computers to ProjectRed but I don’t think i can justify taking that on with my time constraints.

**Comment by 0xF6** [comment]
I think it will be enough to port the code eloraam, and connect the integration of your mod.

**Comment by 0xF6** [comment]
As far as I remember, eloraam had an implementation of 65el02 CPU and an image of FORTH machine.
All the rest is just the implementation of blocks and classical logic

**Comment by MrTJP** [comment]
No. You don’t ‘port’ a closed source mod. It would be my custom implementation. In fact, I had already designed my variation of the micro controller and was working on the OS before i decided to dedicate my time elsewhere.

**Comment by 0xF6** [comment]
It's a pity then, I've been dreaming for several years about this computer, 1.4.6 is now very lagging compared to the new versions.
If you can not take its operating system, then it's very sad.

**Comment by 0xF6** [comment]
Maybe there's a chance to ask her permission?

**Comment by 0xF6** [comment]
I found [RedPower CPU Instruction Table](http://www.eloraam.com/nonwp/redcpu.php)
