### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by wormzjl** [MrTJP/ProjectRed#1391]
https://pastebin.com/PKQfPDpq
Might be related to quark?

**Comment by MrTJP** [comment]
Fixed a while back. Will be in the next release.

**Comment by dualinfinities** [comment]
is this next release close to being done? last release was june, and there's several issues posted about this bug. it's affecting compatibility with a number of mods, at least one of which gains substantial amounts of content with each of the updates the current (several months outdated) release is incompatible with. 

barring a pending update, is there any version, whether previous or commit, which is known not to have this issue (and relatively stable)? I'd rather not be taking potshots in the dark to solve this.
