### ISSUE TITLE
[Feature Request] Multi colored framed bundled cable

### ISSUE THREAD

**Issue by DeaSTL** [MrTJP/ProjectRed#1392]
![javaw_2018-09-04_14-28-42](https://user-images.githubusercontent.com/19532324/45050307-f2aa8800-b04e-11e8-9237-bb152226904d.png)

I ran into a problem with cleanliness on this CPU a friend and I are building.

![image](https://user-images.githubusercontent.com/19532324/45050405-3a311400-b04f-11e8-8bc9-267e599ee670.png)

**Comment by LordMZTE** [comment]
you could use covers to separate them (that's kind of a bad solution but its better than nothing)

**Comment by MrTJP** [comment]
Coloured bundled cables were just added in commit c48805bafc7eb094cadf11154971155459611d6c
