### ISSUE TITLE
Redstone wire does not connect to the bottom of modded blocks

### ISSUE THREAD

**Issue by malte0811** [MrTJP/ProjectRed#1393]
Original issue: BluSunrize/ImmersiveEngineering#3181
This seems to be caused by some code in FMP that assumes vanilla's `canConnectRedstone` can't handle the bottom side properly. The current `canConnectRedstone` is added by a Forge patch, MCPBot indicates that a vanilla method of that (MCP) name existed in 1.5 (mh canConnectRedstone), which would fit with the code having been added 5 years ago.
@covers1624 asked me to open an issue here, otherwise I'd probably have opened this in the FMP repo.

**Comment by MrTJP** [comment]
I thought I fixed this a long time ago, but maybe I never opened a PR, or the change was lost at some point.

Will be fixed by: https://github.com/TheCBProject/CBMultipart/pull/149
