### ISSUE TITLE
Search bar typing priority

### ISSUE THREAD

**Issue by Psy-Virus** [MrTJP/ProjectRed#1399]
When you have other mods installed and you search in the request search bar, the activation keys for the mods get triggered.

**Comment by MrTJP** [comment]
That is out of my control. The GUI classes have no way to consume these events. Other mods should be consuming these events so it never makes it to the GUI in the first place.

**Comment by Psy-Virus** [comment]
I'm sorry but if I type something into NEI for example the mod activation keys don't get triggered.
Shouldn't it be possible to do that for PR too?
