### ISSUE TITLE
Crash when rendering entities with no world loaded

### ISSUE THREAD

**Issue by soylens** [MrTJP/ProjectRed#1407]
> https://paste.dimdev.org/jepuqokopi.mccrash
See also https://github.com/Vazkii/Quark/issues/1021
I'm posting this issue here also, because the last function of the callstack is part of ProjectRed

**Comment by MrTJP** [comment]
This has been fixed since 2001af649bc0c844593c405822a3249d21e00c74. Will be included in the next release.
