### ISSUE TITLE
Crash with Relocation on Client 

### ISSUE THREAD

**Issue by Diamondman121314** [MrTJP/ProjectRed#1408]
I haven't tested this in awhile so I forgot it was an issue I was having, but tried it today, and still the same case. 

ProjectRed Version: I tested it with 4.9.2.101 and also compiled it myself, still getting the same issue.
https://pastebin.com/wg8nHh15

There's also a line at the top of that Pastebin which may or may not be important with this.

**Comment by MrTJP** [comment]
The access transformer is not being applied. Any reason for this @covers1624? Its included in the build script and seems to work for everyone else.

**Comment by covers1624** [comment]
Not sure.. Buildscript looks fine to me, should just work.

**Comment by MrTJP** [comment]
Try it with just ProjectRed installed and see if you get the same results. It might be an optifine conflict.

**Comment by Diamondman121314** [comment]
I tried ProjectRed with no other mods. Only mods being CCL, FMP, MrTJPCore and PR.
https://paste.ee/p/JNdES

**Comment by covers1624** [comment]
Oh you are using the -all jar from maven. Dont do that. You need to use the module jars.

**Comment by Diamondman121314** [comment]
Oh. I didn't know that I shouldn't be. I mean, what would the difference be anyway apart from -all jar containing Relocation, which in this case though, is the reason it's unfortunately crashing.

**Comment by MrTJP** [comment]
It doesn’t have everything needed to work. Don’t use it.

**Comment by Diamondman121314** [comment]
Alright, that's fine.
