### ISSUE TITLE
Counter's hands glitch after configure one of them

### ISSUE THREAD

**Issue by FrostQ** [MrTJP/ProjectRed#1411]
- Before configure one of them
![2018-10-12_18 43 37](https://user-images.githubusercontent.com/36822613/46882431-f6e87300-ce4e-11e8-8635-f56eb9551d18.png)
- After configure one of them (look left)
![2018-10-12_18 43 40](https://user-images.githubusercontent.com/36822613/46882514-4464e000-ce4f-11e8-9d3a-72c536b4ea36.png)

**Comment by MrTJP** [comment]
You might have found the oldest bug in the mod. Fixed via eeb28a66b73a6d65f1db7c270059469174203820.

**Comment by covers1624** [comment]
omfg i searched for hours for this a while ago..
