### ISSUE TITLE
Placing lamps with RFTools Builder sends server into crash loop

### ISSUE THREAD

**Issue by ArcanoxDragon** [MrTJP/ProjectRed#1412]
One of the players on my server mistakenly tried to place a Project Red lamp with an RFTools builder. This sent the server into a crash loop with the following crash report:

https://gist.github.com/briman0094/1fc951b2e216031be0ec11c8a62431d6

The builder placed the block without filling its metadata properly (it clearly placed the block by itself instead of simulating a player using an ItemBlock or some other similar situation). Preferably this should not crash the server but simply remove the block in question from the world and print a warning or error to the server log.

I should be able to remove the block in question, but I can't be sure the builder won't try and place another when I restart the server.

**Comment by MrTJP** [comment]
If RFTools uses the proper default state of the block then this shouldn't happen

**Comment by Toolito** [comment]
Same issue here
