### ISSUE TITLE
License - Modifications of 4.7.0 (MC 1.7.10) for GT New Horizons

### ISSUE THREAD

**Issue by nbauernfeind** [MrTJP/ProjectRed#1414]
GT New Horizons is a huge modpack that runs on minecraft 1.7.10. This latest version of project red for 1.7.10 is 4.7.0pre12.95 and no longer supported.

I have made several changes that improves the compatibility (and QoL) of ProjectRed in this pack. Including:
- item equality for Forestry items based on genetic data (i.e. this enables project red pipes to be used to automate apiaries)
- support to use greg tech screwdrivers

You can see these changes [here](https://github.com/nbauernfeind/ProjectRed).

We would like to keep an unofficial [GTNH fork](https://github.com/GTNewHorizons/ProjectRed), but I understand that this is against the text of the chosen license. Is there anything we can do to work through the licensing?

**Comment by Dream-Master** [comment]
If there are any issues or bugs we will say people to report this on us side.

**Comment by Dream-Master** [comment]
https://www.technicpack.net/modpack/mcnewhorizons.677387
https://minecraft.curseforge.com/projects/gt-new-horizons

**Comment by covers1624** [comment]
Permission for redistribution of modified versions of PR is entirely up to TJ, but, If you can round up a large list of 1.7 bugs + these features, id be willing to do one final update for 1.7.

**Comment by nbauernfeind** [comment]
I couldn't be more interested in crawling through 1.7 bugs. Is the easiest way to find them to search for 'unsupported' in the issue list? Are there new features that might be worth back-porting as well?

One slightly small issue with including the changes I want to make in 1.7 is that, as I've already implemented, they force the mod to explicitly depend on Forestry and Gregtech. I could introduce hooks and toss them into the compat jar (or create a new jar or two) to keep the dependency removed from the meat of the project but it will be additional work to keep them optional.

**Comment by MrTJP** [comment]
If you would like to maintain a 1.7 version I would be willing to pull your contributions into an official branch. But know that there are huge features added after 1.7 and I would not be able to take the time to backport them.

**Comment by Dream-Master** [comment]
Sounds good  for me @MrTJP . Will talk with @nbauernfeind .

**Comment by nbauernfeind** [comment]
@MrTJP I totally understand and I wouldn't ask for any of your time except to release. If we do this, I would be willing to attempt backporting if you have requests and time to give high-level overview.

How attached are you to keeping the 1.7 branch as clean/pure as it originally was? For example, the changes I tossed together blindly cause PR to depend on Forestry and GregTech. I could restructure these changes by adding hooks and then having a single jar (say ProjectRed-GTNewHorizons) that adds the compatibility for features that are less generic.

Will you require (or desire) that improvements be applied to the newest version(s) of PR as well?

At the moment I am exploring the idea of creating an automated piping/transport system that integrates really well with GT. It's possible that doing so might yield the best results.

**Comment by MrTJP** [comment]
I am no longer going to spend time on outdated versions. If you would like to include your own changes in personal packs, you may do so as long as it doesn't violate the original license and you make it clear that you are using an unsupported/unofficial release of PR. (Basically, don't let anyone come here and open an issue for something not working in your unofficial backport).

Enjoy :)

**Comment by EndangeredNayla** [comment]
Is the MIT Relicense Retroactive?
And if so mind changing the license on all branches.

Thank you very much
