### ISSUE TITLE
(Suggestion) Extended Colorset for Bundled/Insulated Wires

### ISSUE THREAD

**Issue by ZeekPlayz** [MrTJP/ProjectRed#1415]
This sounds dumb, but in the future would it be possible to have a color-picker like option so there can be more than 16 colors? This would extend the usage of many systems and would also remove limitations when it comes to memory-based programs.

**Comment by MrTJP** [comment]
Currently there are no plans for increasing from 16 colors. That would require a complete rewrite. 16 channels is more than enough for pretty much anything with smart design.
