### ISSUE TITLE
Inverted Lamps

### ISSUE THREAD

**Issue by jthantranon** [MrTJP/ProjectRed#1422]
#1333 

Hey guys. This mod is in my top 5 list of must haves for any pack I run. And the Inverted White Lamp is probably my favorite block in all of modded minecraft (and I suspect I'm not the only one). I'll ditch any shader 100x over before I ever ditch Project Red Illumination... AND / BUT... please keep reading:

I know there's a long history here about not supporting Optifine / Shaders etc. .... but I did extensive testing.... 

Would it at all be helpful to know that the bug shown in #1333 does NOT happen with ONLY optifine installed (but NO shaders turned on)... and here's the new info: the bug appears with ANY shader loaded. I went down the list of top 10 shaders, turn on and off each one down the list and it happens with EVERY SINGLE shader. 

I'm a developer too and I would be more than happy to help fix this if someone can point me in the right direction of what it might be. But it seems to be me like the issue may be on the ProjectRed end since it happens with every single one of the top 10 shaders (all from different authors).
![lamp glitch](https://user-images.githubusercontent.com/3235678/48218668-64a59300-e358-11e8-9ae7-89ad5cadb466.PNG)

**Comment by covers1624** [comment]
Remove optifine.

**Comment by DarkShyMW** [comment]
@covers1624 but how install shaders? i use 1.12.2 and have this troubles.

**Comment by leodesa** [comment]
Hello, I'm having the same problem on a server and Sky Factory 4 modified with Project Red and whenever I activate the shaders it bothers me. Do you already know any solution?

**Comment by juleklO** [comment]
Issue still exists on 1.12.2
_OptiFine_1.12.2_HD_U_G5_
_ProjectRed-1.12.2-4.9.4.120-lighting_
_Sildurs Vibrant Shaders_

**Comment by juleklO** [comment]
> Issue still exists on 1.12.2 _OptiFine_1.12.2_HD_U_G5_ _ProjectRed-1.12.2-4.9.4.120-lighting_ _Sildurs Vibrant Shaders_

Under /config/ProjectRed.cfg/renderSettings/lightHaloRenderCount setting the value to 0 will remove the issue, but will also remove the 'halo' effect of the lamps.

I think this is a good compromise for the time being.
