### ISSUE TITLE
(Suggestion) "Layered" IC Chip

### ISSUE THREAD

**Issue by ZeekPlayz** [MrTJP/ProjectRed#1428]
My suggestion is to allow multiple  "layers" of an IC chip.

Inside the IC chip would be an option to go down or up a layer. And there would also be a new component called a "Layered Wire" block, which is a wire that connects to any wires in the above/below layer.

This would mean you could definitely fit more components in the IC gate.

**Comment by MrTJP** [comment]
This is planned for next major update to the IC system.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
