### ISSUE TITLE
Cubic Chunks compatibility, small but serious bugs fixes

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [MrTJP/ProjectRed#1430]
Hello. Great mod you got there. Im a long term user of your mod. Recently i tested it with cubic chunks and at negative block y coordinates, lamps, pipes and several other items are becoming invisible and untargetable after placing (also lamps in addition dont emit light, not only theyre not invisible and untargetable).
Forge 2768
![2018-11-23_21 37 16](https://user-images.githubusercontent.com/34427698/48959786-0982bb80-ef68-11e8-903c-3a1fbc7f5662.png)

**Comment by Adam-R-Kaminski** [comment]
https://github.com/OpenCubicChunks/CubicChunks

**Comment by Adam-R-Kaminski** [comment]
I will report further issues when i find them.

**Comment by Redd56** [comment]
cough microblocks cough

**Comment by MrTJP** [comment]
Closing this because Cubic Chunks doesn't seem to be ported to 1.15+
