### ISSUE TITLE
Suggestion:Control panel

### ISSUE THREAD

**Issue by Twetch** [MrTJP/ProjectRed#1433]
Hi,i want ask if is possible to implement something like this to your mod.  http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/doc/ControlPanel.html

**Comment by Dushess** [comment]
He told something about updating... But it was in 1.10.2 version time and he just don't have time probably...

**Comment by Twetch** [comment]
Yes, he is long time gone, so thats why im asking here, cuz this addon is really good and gr8 with ic chip combination :) and deserve remake.

**Comment by Rayzeq** [comment]
It seems unnecessary with the arrival of Fabrication v2, which will make it possible to do this with the Surface-mount components on the IC Gates

**Comment by MrTJP** [comment]
Correct. Something like this will be covered in Fabrication V2.
