### ISSUE TITLE
ProjectRed blocks CubicChunks issue.

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [MrTJP/ProjectRed#1435]
Hey there!
Love your mod guys!
But it has some serious issues with CubicChunks.
forge 2772  PR 4.9.1.92
when placing a block facade at -5700meters and placing a redstone torch on it and deactivating it with another redstone torch, the server gets completely crashed
another issue, when placing vertical half slabs and activating a pressure plate next to them, client is getting errored and kicked out of the server, after rejoining the server, the facades are visually no longer there but you cant place any block in their place, after relogging to the server again, you CAN place a block there, but the client gets frozen (first log is the half slabs error second one is the complete server crash with the redstone contraption)
[project red half slabs error client.log](https://github.com/MrTJP/ProjectRed/files/2650664/project.red.half.slabs.error.client.log)
[redstone contraption crash  _ server.txt](https://github.com/MrTJP/ProjectRed/files/2650665/redstone.contraption.crash._.server.txt)

**Comment by Redd56** [comment]
i think its multiblocks in general :p doing multiple torches in a single block then trying to break them causes huge wonk

**Comment by MrTJP** [comment]
Closing this because Cubic Chunks is not available in 1.15+ as far as I know
