### ISSUE TITLE
Crash with Betweenlands mod. 

### ISSUE THREAD

**Issue by warplord** [MrTJP/ProjectRed#1442]
https://pastebin.com/DQxuX4Dm

Crash on startup. Any ideas what to do?

**Comment by Denoknight** [comment]
Same problem. I'm gonna test with Betweenlands versions.

**Comment by GoryMoon** [comment]
Duplicated of #1429 
`downgrading ProjectRed to 4.9.0.086 works with that version, if you prefer an outdated PR to an outdated TBL` or not using the `Project Red - Mechanical` part works.
This has been fixed since mid July 2018 but not released yet.

**Comment by warplord** [comment]
Can we get a release with maybe other fixes if there are any, please?

**Comment by DemonfangArun** [comment]
"Me Too": https://paste.dimdev.org/qadovopame.mccrash
Why has there not been an update to fix this yet? It also appears there have been no updates since last june, is this mod dead?

**Comment by collwee** [comment]
https://github.com/MrTJP/ProjectRed/issues/1461

**Comment by MrTJP** [comment]
Can someone confirm if this issue is solved with release v4.9.3 from last week?

**Comment by MrTJP** [comment]
Duplicate of #1437

This issue will be tracked there.

**Comment by MrTJP** [comment]
Duplicate of #1429
