### ISSUE TITLE
[Suggestion] delay in item description

### ISSUE THREAD

**Issue by LordMZTE** [MrTJP/ProjectRed#1446]
it would be very useful to have a text that gets display when a logic component is hovered over with the cursor in an inventory that displays the delay of the component in ticks that would make timing much easier

**Comment by MrTJP** [comment]
Going to close this out. This shouldn't be necessary information. All gates have a minimum forward delay of 2 ticks. The only exceptions are gates that are designed to extend this delay, such as repeaters. And those gates are almost always configurable to different delays, so having only the default delay show up in a tooltip is not useful either.
