### ISSUE TITLE
IC Chips get scrambled on game load

### ISSUE THREAD

**Issue by MatCat** [MrTJP/ProjectRed#1448]
Any IC I fabricate gets scrambled upon world reload, and requires all of them to be broken and replaced back down to work.  (Note I have only tested in creative where inventory is unlimited and I am placing back down a new IC, haven't tried to see if in survival a broken IC will place back down and work or still be scrambled).  I am on newest version of forge on MC 1.12.2, no other mods installed except for the required prerequisites and Integration, Fabrication, and Lights, compat, and worldedit.

**Comment by FelixFleckenstein** [comment]
The output shows a 1 after loading, although it should be 0. When I turn the input on and off, the output will work properly again.
But for the quite large number of ICs in my project, that's not a solution.

**Comment by EnderShadow** [comment]
This issue has been preset for a long time. I initially reported exactly one year ago for the 1.10.2 version #1245

**Comment by MatCat** [comment]
> This issue has been preset for a long time. I initially reported it exactly one year ago for the 1.10.2 version #1245

Ah, I looked too to try and find the issue before posting it but apparently I failed :)

**Comment by antoniopellegrini** [comment]
Same thing here, every time i log on singleplayer every IC get scrubled and i need brake and replace all of them

**Comment by ccfb3ee765a58cae** [comment]
This is incredibly disappointing. Really puts a halt on everything I wanted to do, with no clear workaround.

**Comment by ccfb3ee765a58cae** [comment]
1b4e790fbf14322fbc825db521da34a1a4cf8baf claims to fix this. Any idea if this just hasn't been pushed to curseforge yet? Building from source might be a solution.
