### ISSUE TITLE
Block placer shouldn't move by frame from the face (place) side.

### ISSUE THREAD

**Issue by slayerain** [MrTJP/ProjectRed#1453]
Hello. I've seen same issue that been made 2 years ago and wasn't solved eventually.
I wanna try to make u reconsider current feature that makes block placer drug by frame.

I building a very tall elevator. I can't use a stick on the bottom since it will hit into a bedrock and length from bedrock to sea lvl where building starts is not enough.
On upload picture 
![2019-01-26_22 04 50](https://user-images.githubusercontent.com/11138221/51792401-fcc55280-21b8-11e9-8642-e8e6d4c59c12.jpg)
u can see the system that how it suppose to work. When it goes up it place new frame by block placer and make it go elevator very very hight. When it goes down, block breaker breaks a frame and put it back into block placer. This method was successfully used in redpower by many players and this is the only way to make a tall elevator by using project red. Now the black placer drugs up by frame and this is pretty much "game over". I tried lot of things but cannot do any other tricks to make a tall elevator with frame motor.
I'd like to notice that there is no use of moving block placer face to frame by frame motor. Other side still can be attachable to frame, but face side shouldn't be. 
Would be very appreciated to have a patch or new version that will include current fix. Thank you for your hard work!

**Comment by MrTJP** [comment]
Tested on v4.9.3 and this is working as you described. Block placers and block breakers cannot be moved by the face.
