### ISSUE TITLE
Weird frame issue

### ISSUE THREAD

**Issue by XsFrozdY** [MrTJP/ProjectRed#1454]
[This](https://www.youtube.com/watch?v=9FFUUVbpBCs) youtube video will explain things better than I ever could with words.

**Comment by Fishandchips321** [comment]
Having the same issue while playing All The Mods 3 Remixed (single player creative mode) with version 4.9.0.86 of ProjectRed and version 2.1.3.35 of MrTJPCore. Seems to be something left behind by a frame when it's moved with a frame motor. It removes any blocks that are placed there or moved into it with frame motors or with pistons. Seems to only happen where a frame block is touching a frame motor. A reload of the world fixes the problem but any blocks placed/moved into the space is permanently removed. Also tested with ProjectRed version 4.9.2.110 and MrTJPCore version 2.1.4.38 from #1461 with the same results.

**Comment by Dunkhan** [comment]
I have had this issue twice. In my current save the issue reproduces each time, i.e. if you load up the save and press the down lever for the frame motor it immediately deletes the bottom frame, and leaves behind whatever deletes all blocks in that square.

Would it be useful for me to upload that save here?

Also does anyone know a workaround other than reloading? It would be nice to be able to use my frame setup again.

**Comment by Chameebling** [comment]
It seems like the frame deletion bug is caused by this feature:
_"To moves a second block (which eg. was moved by an other Frame Motor on this) the first redstone signal must be terminated and an new signal must receive the Frame Motor."_

Source: https://ftb.gamepedia.com/Frame_Motor_(Project_Red)
