### ISSUE TITLE
Add comparator and constant out (redstone block) to IC workbench

### ISSUE THREAD

**Issue by anar4732** [MrTJP/ProjectRed#1455]

**Comment by MrTJP** [comment]
Internal logic of ICs is not analog, so comparators are not a thing. Also, you can use the redstone torch in the *debug* menu as constant out.

**Comment by 4rz0** [comment]
> Internal logic of ICs is not analog, so comparators are not a thing. Also, you can use the redstone torch in the _debug_ menu as constant out.
Is  this specific for a version of the mod? Because I only have button and switch in there.
