### ISSUE TITLE
lags after downloading project red

### ISSUE THREAD

**Issue by BlackHoleTON618** [MrTJP/ProjectRed#1459]
i used to get 190 FPS with my old modpack but now i get only 20fps and blocks arent breaking like before i have to break twice and my fps was still 30 20 even render distance is 2 chunks but before even i used 64 chunks i got 60 fps what the hell happened
minecraft 1.12.2
forge 14.2.2768
project red 1.4.38

**Comment by MrTJP** [comment]
I need more details. Also that is an invalid version of PojectRed.

**Comment by MrTJP** [comment]
Closing because I don't have enough details to reproduce.
