### ISSUE TITLE
World Gen generates disabled ores

### ISSUE THREAD

**Issue by ArakoKatoc** [MrTJP/ProjectRed#1460]
There's a similar problem referenced elsewhere, but it involves someone using an old version's config file. In my case I altered the config file that was included when I first launched my server. Using ProjectRed-1.12.2-4.9.1.92, I've tried to disable Silver and tin (as I'm using Thermal Foundation for these), but my clients are reporting the existence of ProjectRed Silver and Tin. My config...

"world gen" {
    B:"Copper Ore"=false
    I:"Copper Ore resistance"=0
    B:"Copper Ore retrogen"=false
    B:"Electrotine Ore"=true
    I:"Electrotine Ore resistance"=0
    B:"Electrotine Ore retrogen"=false
    B:"Marble Caves"=true
    I:"Marble Caves resistance"=0
    B:"Marble Caves retrogen"=false
    B:"Peridot Ore"=true
    I:"Peridot Ore resistance"=0
    B:"Peridot Ore retrogen"=false
    B:"Ruby Ore"=true
    I:"Ruby Ore resistance"=0
    B:"Ruby Ore retrogen"=false
    B:"Sapphire Ore"=true
    I:"Sapphire Ore resistance"=0
    B:"Sapphire Ore retrogen"=false
    B:"Silver Ore"=false
    I:"Silver Ore resistance"=0
    B:"Silver Ore retrogen"=false
    B:"Tin Ore"=false
    I:"Tin Ore resistance"=0
    B:"Tin Ore retrogen"=false
    I:"Volcano resistance"=0
    B:"Volcano retrogen"=false
    B:Volcanos=true
}

Can someone help? It's probably me screwing something up.

**Comment by MrTJP** [comment]
I am unable to reproduce. Maybe your config file is screwed up because of a past update to ProjectRed. I recommend deleting it completely to generate a fresh one, and then apply your settings in that.
