### ISSUE TITLE
for peaple wanting the latest projectred compiled

### ISSUE THREAD

**Issue by collwee** [MrTJP/ProjectRed#1461]
https://drive.google.com/file/d/1Ko-en-IPvCo_Iri2gJd9ncDkEdudeRnp/view?usp=sharing

this is the latest version of this github compiled
 i use it for my personal mod pack it also work with latest betweenlands

**Comment by GoryMoon** [comment]
It's also available here on the official maven repo (jars are signed by the build server):
http://chickenbones.net/maven/mrtjp/MrTJPCore/1.12.2-2.1.4.38/
http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.9.2.110/

**Comment by MrTJP** [comment]
v4.9.3 sprint ends Saturday and will have a corresponding release.

**Comment by barcharcraz** [comment]
I'm still getting this crash with 1.12.2-4.9.2.110 and later?
