### ISSUE TITLE
Wall recipes do not use the ore dictionary

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MrTJP/ProjectRed#1462]
All of the wall recipes appear to only use Project Red blocks. This is most noticeable when trying to craft marble or metal blocks, since many mods add their own versions.

**Comment by MrTJP** [comment]
Wall recipes now compatible with ore dictionary. Basalt Cobblestone, Basalt Brick, and Marble Brick walls were left out since they are not dictionary entries as far as I know.
