### ISSUE TITLE
Missing item files

### ISSUE THREAD

**Issue by JamesYeoman** [MrTJP/ProjectRed#1463]
Looking through the logs on my personal server, I can see a couple `FileNotFoundException`s regarding `ic_machine`. Here is a list of the classpath strings

- `projectred-fabrication:models/item/ic_machine.json`
- `projectred-fabrication:blockstates/ic_machine.json`

**Comment by MrTJP** [comment]
This is because we don't use the standard minecraft JSON-based models for our blocks. Instead, we load them up as we did in previous versions of MC. This doesn't effect anything so its not really a big deal.

Maybe @covers1624 knows how to suppress these model warnings?

**Comment by MrTJP** [comment]
No longer relevant for 1.15+
