### ISSUE TITLE
Pulse Formers in IC gates with Repeaters act strange

### ISSUE THREAD

**Issue by DevonFrosch** [MrTJP/ProjectRed#1464]
Hello,

I stumbled over a bug with pulse formers in IC gates and Project Red repeaters where the order of placement determines if the IC will work or not.

![Button, Repeater, Cable split up: (Pulse former, RS latch to bottom), (IC, RS latch to left)](https://devonfrosch.eu/dateien/PR_Initial.png)
![Blueprint (Input, pulse former, output)](https://devonfrosch.eu/dateien/PR_Blueprint.png)

So in theory, both branches are equal cirquits. If you place the repeater last and press the button next to it, everything works as expected:

![Both RS latches active](https://devonfrosch.eu/dateien/PR_Repeater_last.png)

But if you remove the IC and place it again (and reset the RS Latches), pressing the button will only activate the bottom branch with the normal pulse former - the IC doesn't emit a signal.

![Only bottom RS latch active](https://devonfrosch.eu/dateien/PR_IC_last.png)

Small world for testing, only with Project Red: (https://devonfrosch.eu/dateien/PR_NewWorld.zip)

Tested with following mods:
- Forge 1.12.2-14.23.5.2768
- ProjectRed-1.12.2-4.9.1.92-*
- MrTJPCore-1.12.2-2.1.3.35-universal
- ForgeMultipart-1.12.2-2.6.1.81-universal
- CodeChickenLib-1.12.2-3.2.2.353-universal

**Comment by MrTJP** [comment]
Are you accounting for the fact that there is an implicit, 2-tick delay between the endpoint/output inside the IC and the actual redstone output to the world?

**Comment by DevonFrosch** [comment]
Ah ok, this is interesting: If I put a repeater after the pulse former in the IC, it actually seems to work with the setup in the description above, no matter in which order I place the components.

![2019-07-14_14 55 54](https://user-images.githubusercontent.com/2807104/61183908-91c4e680-a647-11e9-93a2-8d198e8f9f41.png)

I'll see if I can fix my other cirquits like this, but for the moment, this could help.

Thanks :-)

**Comment by MrTJP** [comment]
This happens because the pulse former turns on and off before the external gate has time to react. It notices an output change, so it schedules an update 2 ticks in the future. 2 ticks later, when it goes to update, the pulse former inside has already turned off, and thus, there is nothing to update. Not a bug, its something you have to think about when designing your ICs. Currently don't have plans to change this, at least not until the next major overhaul to the IC system.
