### ISSUE TITLE
Update to the latest version on Curse

### ISSUE THREAD

**Issue by blindcat97** [MrTJP/ProjectRed#1468]
Twitch modpacks cannot include projects that aren't on Curse, and that includes unreleased versions of projects that _are_ on Curse. The latest version available on Curse is 4.9.1.92 while the latest version is 4.9.2.1 available on the Maven repo as well as precompiled by another GitHub user in #1461 . For everyone wanting to use Mechanical and the Betweenlands, without asking their users to download individual jars separately (which many server owners will not do), this is a problem.

**Comment by MrTJP** [comment]
v4.9.3 sprint ends this weekend. Will have a release on curse.
