### ISSUE TITLE
There are some problems with the IC workbench

### ISSUE THREAD

**Issue by RZDun** [MrTJP/ProjectRed#1471]
When I put the IC workbench on the ground, Minecraft will crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 3/28/19 3:24 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mrtjp.projectred.fabrication.ICSimEngineContainer.saveSimState(SimInterface.scala:158)
	at mrtjp.projectred.fabrication.ICTileMapEditor.save(ictileeditor.scala:191)
	at mrtjp.projectred.fabrication.TileICWorkbench.save(tileicworkbench.scala:141)
	at mrtjp.core.block.MTBlockTile.func_189515_b(tileblock.scala:470)
	at net.minecraft.client.Minecraft.func_184119_a(Minecraft.java:2611)
	at jobicade.betterhud.element.BlockViewer.getDisplayStack(BlockViewer.java:180)
	at jobicade.betterhud.element.BlockViewer.shouldRender(BlockViewer.java:100)
	at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:265)
	at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:284)
	at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:150)
	at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_753_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mrtjp.projectred.fabrication.ICSimEngineContainer.saveSimState(SimInterface.scala:158)
	at mrtjp.projectred.fabrication.ICTileMapEditor.save(ictileeditor.scala:191)
	at mrtjp.projectred.fabrication.TileICWorkbench.save(tileicworkbench.scala:141)
	at mrtjp.core.block.MTBlockTile.func_189515_b(tileblock.scala:470)
	at net.minecraft.client.Minecraft.func_184119_a(Minecraft.java:2611)
	at jobicade.betterhud.element.BlockViewer.getDisplayStack(BlockViewer.java:180)
	at jobicade.betterhud.element.BlockViewer.shouldRender(BlockViewer.java:100)
	at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:265)
	at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:284)
	at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:150)
	at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_753_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:119)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RZDun'/47, l='MpServer', x=-1691.96, y=4.00, z=1731.83]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1700,4,1730), Chunk: (at 12,0,2 in -107,108; contains blocks -1712,0,1728 to -1697,255,1743), Region: (-4,3; contains chunks -128,96 to -97,127, blocks -2048,0,1536 to -1537,255,2047)
	Level time: 201939 game time, 363046 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['RZDun'/47, l='MpServer', x=-1691.96, y=4.00, z=1731.83]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3240041856 bytes (3089 MB) / 4093640704 bytes (3904 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 Optifine OptiFine_1.12.2_HD_U_E4_pre1 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version               | Source                                            | Signature                                |
	|:------ |:--------------------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                               | 9.42                  | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                               | 8.0.99.99             | forge-1.12.2-14.23.5.2823.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2823          | forge-1.12.2-14.23.5.2823.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jecharacters                      | 1.12.0-3.3.0          | JustEnoughCharacters-1.12.0-3.3.0.jar             | None                                     |
	| LCHIJA | foamfixcore                       | 7.7.4                 | minecraft.jar                                     | None                                     |
	| LCHIJA | jei                               | 4.15.0.269            | jei_1.12.2-4.15.0.269.jar                         | None                                     |
	| LCHIJA | appleskin                         | 1.0.9                 | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LCHIJA | baubles                           | 1.5.2                 | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | betterbuilderswands               | 0.13.1                | BetterBuildersWands-1.12.2-0.13.1.269+13450ff.jar | None                                     |
	| LCHIJA | betterhud                         | 1.4-beta.4            | betterhud-1.12.2-1.4-beta.4.jar                   | None                                     |
	| LCHIJA | botania                           | r1.10-360             | Botania+r1.10-360.jar                             | None                                     |
	| LCHIJA | carryon                           | 1.12.1                | CarryOn+MC1.12.2+v1.12.1.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | chameleon                         | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353             | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks                     | 2.4.1.73              | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chunkanimator                     | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                      | None                                     |
	| LCHIJA | redstoneflux                      | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.2                 | CoFHCore-1.12.2-4.6.2.25-universal.jar            | None                                     |
	| LCHIJA | cofhworld                         | 1.3.0                 | CoFHWorld-1.12.2-1.3.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | customoregen                      | 1.12                  | CustomOreGen-1.12-1.8.1.jar                       | None                                     |
	| LCHIJA | customskinloader                  | 14.10a                | CustomSkinLoader_Forge-14.10a.jar                 | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LCHIJA | cxlibrary                         | 1.6.1                 | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.45         | EnderCore-1.12.2-0.5.45.jar                       | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.2                 | ThermalFoundation-1.12.2-2.6.2.26-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.3                 | ThermalExpansion-1.12.2-5.5.3.41-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiobase                       | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | refinedstorage                    | 1.6.14                | refinedstorage-1.6.14.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | ftblib                            | 5.4.1.89              | FTBLib-5.4.1.89.jar                               | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.40                | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderstorage                      | 2.4.5.135             | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extrabotany                       | 52                    | ExtraBotany-r1.1-52.jar                           | None                                     |
	| LCHIJA | fastleafdecay                     | v14                   | FastLeafDecay-v14.jar                             | None                                     |
	| LCHIJA | mcmultipart                       | 2.5.3                 | MCMultiPart-2.5.3.jar                             | None                                     |
	| LCHIJA | sonarcore                         | 5.0.19                | sonarcore-1.12.2-5.0.19-20.jar                    | None                                     |
	| LCHIJA | fluxnetworks                      | 3.0.19                | fluxnetworks-1.12.2-3.0.19-21.jar                 | None                                     |
	| LCHIJA | foamfix                           | 0.10.3-1.12.2         | foamfix-0.10.3-1.12.2.jar                         | None                                     |
	| LCHIJA | forgemultipartcbe                 | 2.6.1.81              | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe                     | 2.6.1.81              | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | minecraftmultipartcbe             | 2.6.1.81              | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | hammercore                        | 2.0.4.2               | HammerCore-1.12.2-2.0.4.2.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | i18nmod                           | 1.12.2-1.0.8          | i18nupdatemod-1.12.2-1.0.8.jar                    | None                                     |
	| LCHIJA | industrialexpansion               | 1.2.6                 | IndustrialExpansion-1.2.6.jar                     | None                                     |
	| LCHIJA | inventorytweaks                   | 1.64+dev.146.2180b27  | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap                        | 1.12.2-5.5.4          | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LCHIJA | keepinginventory                  | 2.4                   | KeepingInventory-1.12.2-2.4.jar                   | None                                     |
	| LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCHIJA | malisisdoors                      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.1.1                 | mcjtylib-1.12-3.1.1.jar                           | None                                     |
	| LCHIJA | mrtjpcore                         | 2.1.3.35              | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
	| LCHIJA | multipagechest                    | 1.9.1                 | MultiPageChest-1.12-1.9.1.jar                     | None                                     |
	| LCHIJA | neat                              | 1.4-17                | Neat+1.4-17.jar                                   | None                                     |
	| LCHIJA | nei                               | 2.4.2                 | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | projectred-core                   | 4.9.1.92              | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
	| LCHIJA | projectred-integration            | 4.9.1.92              | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | projectred-transmission           | 4.9.1.92              | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | projectred-fabrication            | 4.9.1.92              | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
	| LCHIJA | reborncore                        | 3.13.6.424            | RebornCore-1.12.2-3.13.6.424-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | quantumstorage                    | 4.6.8                 | QuantumStorage-1.12-4.6.8.jar                     | None                                     |
	| LCHIJA | reap                              | 1.5.2                 | reap-1.5.2.jar                                    | None                                     |
	| LCHIJA | rebornstorage                     | 1.0.0                 | RebornStorage-1.12.2-3.3.2.79.jar                 | None                                     |
	| LCHIJA | redstonearsenal                   | 2.6.2                 | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | redstonerepository                | 1.3.2                 | RedstoneRepository-1.12.2-1.3.2-dev-universal.jar | None                                     |
	| LCHIJA | rftools                           | 7.61                  | rftools-1.12-7.61.jar                             | None                                     |
	| LCHIJA | scenter                           | 1.12-3.11.0           | scenter-1.12.2-3.12.0.jar                         | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.4                 | ThermalDynamics-1.12.2-2.5.4.18-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | simplyjetpacks                    | 2.2.10.63             | SimplyJetpacks2-1.12.2-2.2.10.63.jar              | None                                     |
	| LCHIJA | solarflux                         | 4.32r                 | SolarFluxReborn_1.12.2-4.32r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | storagedrawers                    | 1.12-5.3.5            | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| LCHIJA | veinminer                         | 0.38.2                | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCHIJA | veinminermodsupport               | 0.38.2                | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |

	Loaded coremods (and transformers): 
CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  customskinloader.forge.loader.LaunchWrapper
JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)
  me.towdium.jecharacters.core.JechClassTransformer
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.35' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1196 names; 944 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods: None.

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.6.424
		Runtime Debofucsation 1
		RenderEngine: 1
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: HMCL 3.2.112
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Minecraft-Mod-Language-Modpack.zip, Default CHANGING SEASONS V2.0.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre1
	OptiFine Build: 20181218-105534
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13 v7_Low.zip
	OpenGlVersion: 4.6.0 NVIDIA 419.35
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrTJP** [comment]
Cannot reproduce. Reopen with additional details if this still occurs on latest build.
