### ISSUE TITLE
auto crafting bench eats buckets

### ISSUE THREAD

**Issue by SpyceTewan** [MrTJP/ProjectRed#1478]
The auto crafting bench eats unconsumed items like buckets

**Comment by SpyceTewan** [comment]
same happens with project bench

**Comment by MrTJP** [comment]
Could not reproduce with either plan-loaded recipe or manual crafting.
* Manually loaded cake recipe. Craft consumed all ingredients and left 3 empty buckets on top row.
* Inserted recipe plan of cake. Placed enough ingredients for 2 cakes (6 milk buckets). After shift-click craft, yielded 2 cakes and a stack of 6 empty buckets in storage.

Please re-open with more details if you have another way to reproduce.
