### ISSUE TITLE
[1.12.2] Tin not compatible with Tinker's Construct.

### ISSUE THREAD

**Issue by AyeMonThen** [MrTJP/ProjectRed#1479]
The copper and silver added to the game by Project Red are fully compatible with Tinker's Construct and Construct's Armory, while tin is not.

**Comment by TheDeviantCrafter** [comment]
You can't use any mod's tin to make tool parts out of. Tinkers' only adds parts for certain materials.

**Comment by MrTJP** [comment]
Our tin is being registered as any other metal. If you cannot use out tin somewhere then you cannot use any tin at all.
