### ISSUE TITLE
Too many volcanoes spawning

### ISSUE THREAD

**Issue by MineTech123** [MrTJP/ProjectRed#1480]
Uhhhhhhh... What Just Happen?

This happened

https://imgur.com/a/Hj7biv5

Volcanoes are just spawning  Left Right and Center I walked east for a few minutes and this happened

https://imgur.com/a/F9oYMIH

[21:38:03] [Server thread/WARN] [FML]: MrTJPCore loaded a new chunk [208, -20] in dimension 0 (overworld) while populating chunk [207, -23], causing cascading worldgen lag.
[21:38:03] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

This is appearing in the game output like a hundred times

**Comment by MrTJP** [comment]
Volcanoes spawn if there are lava deposits underground. Could any of the settings you are using be effecting the amount of lava found at low Y levels?

**Comment by MaxNeedsSnacks** [comment]
We're experiencing a similar kind of thing with Underground Biomes and YUNG's Better Caves. These two mods significantly alter the underground composition, so that might be part of the reason why so many volcanoes are spawning in our world, but adjusting the resistance value should still technically reduce the amount of them spawning, shouldn't it?

**Comment by MineTech123** [comment]
I noticed that Biome Bundle was causing that because I removed it and it stopped happening but now (a few months after this post was created ) it seems to be fixed


I’m closing this

**Comment by MaxNeedsSnacks** [comment]
Hm, that's odd. It still seems to be happening for me with the mods mentioned above, and it seems to be the same odd interaction you explained, as well. I have a slight feeling the problem lies with how Project Red generates volcanoes, as increasing the rarity did not seem to aid my case either
