### ISSUE TITLE
No new version of MrTJPcore

### ISSUE THREAD

**Issue by TheSexyYeti** [MrTJP/ProjectRed#1490]
The newest version of MrTJPcore hasn't been uploaded to twitch/curseforge. So I can't have your mod in my mod pack until it is.

**Comment by MrTJP** [comment]
Can you confirm that it doesn’t work with the existing version of MrTJPCore? I don’t think anything on that side was changed.

**Comment by TheSexyYeti** [comment]
Yeah. Every time I try to start up my game I keep getting a message saying "you are missing requirements for project red - base. It requires MrTJPcore 2.1.4 and you have MrTJPcore 2.1.3.".

**Comment by MrTJP** [comment]
Ok. I must’ve bumped the version number by accident. Will have it sorted out in 30 mins.

**Comment by MrTJP** [comment]
Sorry for long delay, there is a problem in our build system that i'm still figuring out. I have uploaded it manually to Curse for now.
