### ISSUE TITLE
[1.7.10] Project won't compile from branch 

### ISSUE THREAD

**Issue by musicmanpwns** [MrTJP/ProjectRed#1491]
I'm trying to fix the dupe bug of not handling packets correctly, but I need to compile the file. I'm using branch 7616a956d0ac48e1ec8db96f992e7cbf010ec442 and am getting this error: https://pastebin.com/VyJYHATK I believe this is occurring because I can't resolve this dependency media.forgecdn.net/files/2245/632/CoFHCore-[1.7.10]3.0.3B2-294-dev.jar despite the fact that I am able to download this file just fine. If someone has a fixed jar for 1.7.10 infinity I can have, that'd be greatly appreciated. Suggestions on where I Can place this dependency are also appreciated as I can download it, but not resolve it

**Comment by MrTJP** [comment]
Yup, looks like some kind of error related to a CoFH file. Going to close this since it's not a relevant issue and I won't be dedicating any time to look into this.
