### ISSUE TITLE
filtered importer vs original filter (redpower 2)

### ISSUE THREAD

**Issue by lildevuwu** [MrTJP/ProjectRed#1492]
I know, there is (https://github.com/MrTJP/ProjectRed/issues/1020) already post about it. But it's still not "fixed"? I don't know. 

It would be cool, if it could just take selected amount of items/blocks, from chest. Rather than full stack.

I don't know if it's "feature" or "bug", but it's still kinda annoying.

**Comment by MrTJP** [comment]
Duplicate of #1020
