### ISSUE TITLE
Exception ticking world entities

### ISSUE THREAD

**Issue by Aridean** [MrTJP/ProjectRed#1493]
Haven't seen anything regarding this. Maybe just me?
Using FTB Ultimate Reloaded pack, made an automated frame motor door.
Door opens fine, but crashes just before it finishes closing throwing this error.

[https://pastebin.com/8yK8dsRr](https://pastebin.com/8yK8dsRr)

I've tried the latest Curse version and still get the same errors

Also I'm aware of Optifine being installed in that crash log.  I removed Optifine, and still got the exact same crash, so I'm sure it isn't that.

Any insight would be welcome.  Thanks

**Comment by MrTJP** [comment]
Can you post a picture of your door setup? Also please use the Bug Report issue template next time.

**Comment by MrTJP** [comment]
Never mind, was able to reproduce. Working on it...

**Comment by Aridean** [comment]
will still leave here just in case

![2019-07-13_15 01 52](https://user-images.githubusercontent.com/6120228/61175718-311fa600-a582-11e9-9c8f-1b9d54307a8a.png)
![2019-07-13_15 03 34](https://user-images.githubusercontent.com/6120228/61175719-311fa600-a582-11e9-80cc-c48ea6b6f41f.png)

Left side.  Red cable is Close Green is Open.
![2019-07-13_15 11 20](https://user-images.githubusercontent.com/6120228/61175720-311fa600-a582-11e9-84d4-ce2ccdf8ccc8.png)

Right Side.  Basically the same but reversed top and bottom.
![2019-07-13_15 11 35](https://user-images.githubusercontent.com/6120228/61175721-311fa600-a582-11e9-91ee-894dee84b55f.png)

Logic to control them.  It's crude but funtions.
![2019-07-13_15 12 26](https://user-images.githubusercontent.com/6120228/61175722-31b83c80-a582-11e9-93eb-d3f500767f16.png)

Also I recorded a quick video of exactly how and when the crash occurs
[https://youtu.be/zuU77CQYMMU](https://youtu.be/zuU77CQYMMU)

**Comment by MrTJP** [comment]
Thank you. I have verified the fix against a similar door setup.
