### ISSUE TITLE
Tons of error messages in log with no other mods installed.

### ISSUE THREAD

**Issue by HaddockA** [MrTJP/ProjectRed#1494]
This mod is creating tons of errors in my log when I use either modpack FTB Revelation 3.01, MultiMC or even a plain Minecraft install.

In all 3 cases no other mods were installed.

https://pastebin.com/LuWwHYC4

All the latest versions were used:

  CodeChickenLib-1.12.2-3.2.2.353-universal
   ForgeMultipart-1.12.2-2.6.1.81-universal
   MrTJPCore-1.12.2-2.1.4.43-universal
   ProjectRed-1.12.2-4.9.3.116-Base
   ProjectRed-1.12.2-4.9.3.116-fabrication
   ProjectRed-1.12.2-4.9.3.116-integration
   ProjectRed-1.12.2-4.9.3.116-lighting
   ProjectRed-1.12.2-4.9.3.116-mechanical
   ProjectRed-1.12.2-4.9.3.116-world

Minecraft v1.12.2
Java: v1.8.0.211
OS: Windows 7
Forge: v14.23.5.2838
LWJGL 2: v2.94-nightly-20150209

What is causing this? To me it seems that ForgeMultipart is causing the issues, since I also get warnings once I enable Translocators 1.8+ and Wireless CBE, which both require ForgeMultipart.

**Comment by HaddockA** [comment]
I seem to have similar issues with any mod that uses Forge MultiPart CBE (ForgeMultipart-1.12.2-2.6.1.81-universal and tested with all other mods disabled).

**Comment by HaddockA** [comment]
I noticed that an older thread than mine is getting attention, while mine (which affects all ProjectRed mods) isn't. Why?

**Comment by HaddockA** [comment]
So you guys have no clue what's causing this and instead of simple admitting this in public, you decided to act as of you never saw this thread, since it might hurt your fragile ego to tell the truth?

I run a free educational web site for 16 years and I try to answer questions of my visitors withing 24 hours, because unlike you guys I take pride in what I'm doing.

Bye.

**Comment by HaddockA** [comment]
MrTJP, thanks for ignoring my comments and trying to silence me with that "MrTJP added this to Needs triage in Task Triage", and have the issue end up on a big pile of issues that nobody will probably ever look at it again. 

I wasted 10 hours of my time to experiment with the different versions of the mods, Java and Forge in an attempt to solve the issue or to provide enough information that can help you guys, yet you can't be bothered to even spend 1 minute of your time to respond in a human way, instead you turned this into "low priority" and and removed the "bug" label without saying anything. Is it really unfair of me to call that disrespectful?

If you're thinking about giving me the predictable modders response "It's free, don't complain" argument, then I have a wake-up call for you:

"FREE" doesn't give you the right to frustrate people. Just because you offer to cut my grass for free, doesn't mean that you can mow it in the middle of the night, leave my lawn mover at the end of the street or work so sloppy that you ruin my flower bed. 

I run a popular 17 year old educational web site and unlike you I respond to people within 24 hours in great detail, I never got paid for that...ever.  It's a civil thing to do, because I don't think I should ignore people who have been struggling for quite a while and who have become frustrated. 

Clearly you don't seem to care. I never asked for a quick fix, instead I was only asking what is causing this. Is it really that much effort for you to write a few words when you get on average about 1 new thread a week, while even the US President seems to have more time for his Twitter account?

Go ahead, feel free to frustrate more people with your lack of communication skills, instead I'll stick to modders who don't run away from communicating with its users.

Bye.

**Comment by MrTJP** [comment]
😂
