### ISSUE TITLE
Disabling IO directions conflicts in config

### ISSUE THREAD

**Issue by Koteyk0o** [MrTJP/ProjectRed#1496]
Hi, can you make disabling conflicts in the config? At 1.7.10, I could make the outputs and inputs on the same side, but at 1.12.2 it does not work
![Annotation 2019-07-14 231012](https://user-images.githubusercontent.com/25249029/61188772-c313d580-a68c-11e9-8ed4-5951b0325be7.jpg)

**Comment by MrTJP** [comment]
This was purposefully removed. Even back in 1.7.10 it was really hacky and caused issues like self-powering loops. I have no plans to re-enable it currently.
