### ISSUE TITLE
Ticking block entity: Block placer + Block breaker

### ISSUE THREAD

**Issue by ayangd** [MrTJP/ProjectRed#1497]
## Describe the bug
Minecraft crashes after flicking a lever that powers both block placer and breaker, both placed back to back (faced the opposite way).

## To Reproduce
1. Place block placer and block breaker, as described in the [picture](#screenshots-videos).
2. Place a block in front of the block placer.
3. Place a lever, that switches both blocks on and off.
4. Flick the lever. This will **crash** the game.

## Expected behavior
The block in front of the block placer will disappear, the game freezes, then crashes.

## Crash Log
See [Crash log](https://pastebin.com/XDn9Yqta).

## Versions
* CCL Version: 1.12-1.0.2.7
* FMP Version: 1.12.2-2.6.1.81
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.1.92
>Actually I'm not sure if this is fixed in the newest version. But, since I found no issue about this, I will just post this.

## Screenshots/Videos
![Picture](https://i.imgur.com/LkmnVjr.png)

**Comment by MrTJP** [comment]
This works fine for me. I can break a block in front of the Block Breaker and then activate the Placer to place it. I guess it was fixed in one of the newer versions. If you find this is happening with v9.4.3 or newer, please re-open the issue.
