### ISSUE TITLE
[Suggestion] IC Workbench GUI Edit Tools

### ISSUE THREAD

**Issue by ayangd** [MrTJP/ProjectRed#1498]
# [Suggestion] IC Workbench GUI Edit Tools
A series of tools that are **very useful** once available in the GUI.

## Tools
- Select & Move (or even Nudge) tool
  This is essential for easy compact IC design and aligning.
- Copy/Cut/Paste tool
  This is very useful to make repetition of some parts, and changing them a bit.  
  (Not the same as nesting IC, they are not changeable.)
- Copy/Paste Configuration
  Shift+RClick to copy, Shift+LClick to paste. (Suggested, as same as Factorio's key shortcut.)
  When shift is pressed, a copied dot will show up (like being selected the other way/different select color). (Search `Factorio copy paste settings` for reference.)
  If the part is not same, it won't be copied.
- Import/Export Blueprint
  This is very useful for sharing blueprints. It can be strings. (Similar to Factorio too)
- Map Resize tool
  This will eliminate frustration of out-of-space and rebuilding the blueprint from scratch up again.

## Navigation
- Middle-click to drag blueprint around.

**Comment by MrTJP** [comment]
Everything you mentioned is planned. Just haven't had the time to work on the UI since my main focus currently is to get the IC bugs sorted out.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
