### ISSUE TITLE
"Banned from the wiki account creation"

### ISSUE THREAD

**Issue by thegearzz** [MrTJP/ProjectRed#1499]
I went onto the wiki to create an account, however my ip was banned for:
_The reason given by Mastergalen is Autoblocked because your IP address has been recently used by "DeniseWinning8". The reason given for DeniseWinning8's block is "Spamming links to external sites"_
I have no idea who denise is, but this is no longer their ip, hope you can unban my ip so I can create an account.
    Regards,
    -Gear

**Comment by MrTJP** [comment]
Hmm. Not sure why this is, but I don't have such control over the wiki. Either way, plans are to move the wiki to Github Pages anyway, so its not a big deal.
