### ISSUE TITLE
[Question/suggestion] Are we going to get framed colored bundled cable?

### ISSUE THREAD

**Issue by eisenburg** [MrTJP/ProjectRed#1500]
A bit silly, perhaps, but every other kind of cable has a framed version. We've had colored bundled cable, why not colored framed bundled cable? Is there a restriction, or a reason?  It's unnecessary, certainly, because you can just put microblocks between the cables, but it was a thought I'd had.

**Comment by MrTJP** [comment]
Its actually very easy to enable (less than a line of code) but the rendering was never set up for it. The colors don't align properly. And its not an easy fix. Will look into it, but not high priority.
