### ISSUE TITLE
Item Request System Deletion

### ISSUE THREAD

**Issue by Dash71101** [MrTJP/ProjectRed#1508]
The item request system deletes half of itself, seemingly at random. Its not like the invisible block glitch when mined blocks don't fully break and they remain as a solid block but invisible. This bug just deletes the pipes alongside with the chips placed inside.

I do not know how to reproduce the bug, it occurs at random. Though I believe it occurs after the chunk it is loaded on is unloaded

**Versions**
* CCL Version: 1.12.2-3.2.2.353-universal
* FMP Version:1.12.2-2.4.2.60-universal
* MrTJPCore Version: 1.12.2 (full file name MrTJPCore-1.12.2)
* ProjectRed Version: 1.12.2 

**Screenshots/Videos**
![2019-07-25_10 07 45](https://user-images.githubusercontent.com/44711177/61855501-d878d300-aec8-11e9-926b-fb01be67a6d3.png)

**Comment by MrTJP** [comment]
Please fix the versions for MrTJPCore and ProjectRed.

**Comment by Dash71101** [comment]
![2019-08-20_00 17 52](https://user-images.githubusercontent.com/44711177/63300211-5a99c300-c2e0-11e9-877c-c279a2dd02d6.png)

Nope
Versions
Project Red 1.12.2-4.9.1.92
MrTJPCore 1.12.2-2.1.3.35-universal

**Comment by Dash71101** [comment]
![2019-08-20_00 26 00](https://user-images.githubusercontent.com/44711177/63300627-53bf8000-c2e1-11e9-86a8-db8b2c0cc1aa.png)

This bug seems to revert after a relog. Still needs a fix.

**Comment by Dash71101** [comment]
Ever since I fixed the Project Red downloads, the problem seems to be getting worse.

**Comment by MrTJP** [comment]
Pipes are going to be rewritten for 1.15+
