### ISSUE TITLE
My Modpack is not working because of ProjectRed Core

### ISSUE THREAD

**Issue by FracxPlayz** [MrTJP/ProjectRed#1514]
When i try start the modpack it tells me in the loading screen ''ProjectRed Core is missing dependecies''
It leaves me this message: forgemultipartcbe : any

I have no idea what mod i have to install.
Modpack is 1.10.2

**Comment by MrTJP** [comment]
Install the required dependencies for Project Red, as stated on Curse:
MrTJPCore
CodeChickenLib
ForgeMultipartCBE
