### ISSUE TITLE
Other player gets forced disconnected from LAN world when placing/using frames or lamps.

### ISSUE THREAD

**Issue by AvarisLectros** [MrTJP/ProjectRed#1515]
Hi, like the title says, I would see the following error in the log along with a player disconnect whenever turning on (or sometimes just placing) lamps. The same error would also occur when moving frames using the frame motor:

NetworkDispatcher exception io.netty.util.IllegalReferenceCountException: refCnt: 0

I am using all the Project Red components, all at version 4.9.4.120, in MC 1.12.2

**Comment by AvarisLectros** [comment]
Not using that mod

**Comment by AvarisLectros** [comment]
Plus, I would get the issue with just Project Red mods installed

**Comment by MrTJP** [comment]
Unfortunately I can't help here without a full crash log.
