### ISSUE TITLE
Memory / Tile Entity Leak with Frames

### ISSUE THREAD

**Issue by randombk** [MrTJP/ProjectRed#1520]
**Describe the bug**
Each frame motion duplicates tile entities, leaving them dangling until server restart. Dangling TEs continue to tick, progressively slowing server down.

**To Reproduce**
1. Create a frame with a tile entity attached (i.e. an inchworm drive)
2. Measure number of tile entities
3. Move the frame
4. Measure number of tile entities again. Observe that the number has increased.

**Expected behavior**
Total tile entities in dimension should remain constant.

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 3.2.2.353
* FMP Version: 2.6.1.81
* MrTJPCore Version:  2.1.3.35
* ProjectRed Version: 4.9.1.92

**Screenshots/Videos**
https://gfycat.com/misguidedfamiliardugong

**Comment by MrTJP** [comment]
Maybe try this again after updating PR? You're using a version over a year old.

**Comment by randombk** [comment]
Updating fixed this issue, thanks.
