### ISSUE TITLE
Client crashes when opening Backpack that contains items.

### ISSUE THREAD

**Issue by D-Pterano** [MrTJP/ProjectRed#1522]
**Describe the bug**
Opening a backpack with items in it crashes the client.

**To Reproduce**
1. Put items in backpack
2. Close backpack
3. Attempt to open backpack
4. Client crashes

**Expected behavior**
I expected the backpack to open and allow me to move items in and/or out of it.

**Crash Log**
https://pastebin.com/M4vzKcRY

**Versions**
* CCL Version: 2.5.9.283
* FMP Version: 2.0.0.38
* MrTJPCore Version: 2.0.1.20
* ProjectRed Version: 4.8.4.49

**Screenshots/Videos**
N/A

**Comment by MrTJP** [comment]
Oh wait, sorry. After looking this over, I got the version numbers mixed up. This was applied for one of the newer builds, which is 4.9.4, not 4.8.4. Those older versions are no longer in development. You will have to update.

**Comment by D-Pterano** [comment]
Damn, that is a bummer. I guess that's what happens when you play older packs though. 
Any known way to extract from a backpack without the player opening it?

In any case, thanks for taking the time to look it over, keep up the good work!

**Comment by MrTJP** [comment]
Don’t think so, you would have to apply the patch and build a new version, but that’s not easy.
