### ISSUE TITLE
[Suggestion] Hollow covers and frames

### ISSUE THREAD

**Issue by NicoNekoDev** [MrTJP/ProjectRed#1524]
https://imgur.com/a/clxuQAI

Hollow covers on frames should make frames not sticky and should allow red alloy frames and tubes to go through (it already does go through, but the frames are still sticky).

**Comment by nicuch** [comment]
Also maybe add wood covers (or anything) to make frames to stick to levers and circuits? I would love to have levers placed and movable, without needing a non-covered frame next to it. :)

**Comment by ConnorTron110** [comment]
@nicuch you should change the Label... *(Its kinda misleading XD)*

**Comment by nicuch** [comment]
@ConnorTron110 I'd love to, but labels are automatically placed, and I can't edit them.

**Comment by equalssign003d** [comment]
> Also maybe add wood covers (or anything) to make frames to stick to levers and circuits? I would love to have levers placed and movable, without needing a non-covered frame next to it. :)

Doesn't panels already do this?

**Comment by nicuch** [comment]
> > Also maybe add wood covers (or anything) to make frames to stick to levers and circuits? I would love to have levers placed and movable, without needing a non-covered frame next to it. :)
> 
> Doesn't panels already do this?

They don't, unfortunately. And there's no wiki for frames and how they work. I don't know if in other versions they sticked to panels, but in latest version, it doesn't. (maybe this is a bug?)

**Comment by CraftSpider** [comment]
Last I checked with recent version of Project Red, they do

**Comment by equalssign003d** [comment]
Did some testing and it seems like both panels and hollow covers already behave like you want them to.
