### ISSUE TITLE
Fill command does not work with Lamps

### ISSUE THREAD

**Issue by ConnorTron110** [MrTJP/ProjectRed#1527]
**Description**
Cannot use `/fill` command to replace inverted lamps with normal lamps

**How To Reproduce**
Steps to reproduce the behaviour:
1. Fill an area with inverted white lamps
2. Type out Fill command `/fill <x1> <y1> <z1> <x2> <y2> <z2> projectred-illumination:lamp 0 replace projectred-illumination:lamp 16` (in this instance we are trying to replace inverted lamps with normal lamps)

**Expected behaviour**
The command should replace all inverted lamps with Normal lamps.

**Versions**
* CCL Version: 3.2.3.358
* FMP Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Screenshots/Videos**

__This is the Error that Pops up__
![image](https://user-images.githubusercontent.com/39780128/66340738-bf1aeb00-e93d-11e9-8abf-4c800c3f9123.png)

__Video just in case you cant reproduce__
https://streamable.com/4kph2

**Comment by ConnorTron110** [comment]
__To add onto this__
You cant even replace one inverted lamp with a normal lamp.

![image](https://user-images.githubusercontent.com/39780128/66350435-31e29100-e953-11e9-9ad2-5d4697c8a9f7.png)
I run this command...
![image](https://user-images.githubusercontent.com/39780128/66350454-40c94380-e953-11e9-8be3-2d64a27abb0b.png)
And nothing happens
![image](https://user-images.githubusercontent.com/39780128/66350529-766e2c80-e953-11e9-98c0-f99639f58863.png)

**Comment by MrTJP** [comment]
May work in 1.15+ due to block changes. Open another issue if it still happens.
