### ISSUE TITLE
JEI 4.15.0.291 incompatable with Minecraft Forge 14.13.5.2768

### ISSUE THREAD

**Issue by equalssign003d** [MrTJP/ProjectRed#1528]
**Describe the bug**
When following the Development section of README.md, and then launching the client the folowing message apears:
"You must include the right dependencies for Just Enough Items: Requires Minecraft Forge 14.23.2816 or above (you have 14.23.2768)"

**To Reproduce**
Follow the Development section of README.md then launch client.

**Expected behavior**
Minecraft starting without error/warning.

**Versions**
* CCL Version: 3.2.2.356
* FMP Version: 2.6.1.81
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4 (cloned as of today)

I'm guessing that "jei_version" needs to be changed in "build.properties", but when I do this it just craches instead.

**Comment by dyleighba** [comment]
I don't see how this is a bug or has anything to do with ProjectRed.
But the issue is pretty clear ProjectRed doesn't build against the latest Forge, which is not a bug.
To fix your issue simply use an older version of JEI that is compatible with Minecraft Forge 14.13.5.2768

**Comment by equalssign003d** [comment]
The issue is that "build.properties" is configured to use conflicting versions of JEI and Minecraft Forge.

**Comment by alex210-1** [comment]
I found a workaround. Change the JEI version to `jei_version=4.15.0.268` in build.properties.

**Comment by MrTJP** [comment]
Should not longer be an issue on 1.15+
