### ISSUE TITLE
[Suggestion] Allow placing wires and cables on hollow micro blocks

### ISSUE THREAD

**Issue by equalssign003d** [MrTJP/ProjectRed#1529]
It would be useful if it was possible to place Bundeled Cable on the Hollow Block of Iron Panels.

![demo](https://user-images.githubusercontent.com/48526740/67140414-be415d80-f249-11e9-8cab-b61902998b49.png)

**Comment by MrTJP** [comment]
This is a core wire mechanic that I have no interest of changing. It would require changing how the wires fundamentally work. There are plenty of ways to handle making this connection you showed above, such as using 2 framed cables.
