### ISSUE TITLE
Crash when placing lever in IC Workbench

### ISSUE THREAD

**Issue by equalssign003d** [MrTJP/ProjectRed#1530]
**Describe the bug**
Minecraft crashes when placing lever in IC Workbench in configuration:
![image](https://user-images.githubusercontent.com/48526740/67386428-7b062800-f584-11e9-91b1-a51854b9189a.png)

**To Reproduce**
Place lever according to image above.

**Expected behavior**
Lever being placed without the entire game crashing.

**Crash Log**
https://pastebin.com/77QfAvzQ

**Versions**
* CCL Version: 3.2.3.358
* FMP Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Comment by MrTJP** [comment]
No longer relevant. Fabrication is being rewritten.
