### ISSUE TITLE
IndexOutOfBoundsException on login and subsequently when moving frame machine

### ISSUE THREAD

**Issue by Nessiesson** [MrTJP/ProjectRed#1533]
**Describe the bug**
Random IOOBE when logging in. Furthermore, one of the framed wires attached to the machine broke and dropped two wires.

**To Reproduce**
1. I sadly have no idea. Had logged into that area many times without any issues.

**Expected behavior**
No crash not random popoff of framed wire.

**Crash Log**
https://paste.dimdev.org/giraqoyidu.mccrash

**Versions**
* CCL Version: 1.12.2-3.2.3.358-universal
* FMP Version: 1.12.2-2.6.2.83-universal
* MrTJPCore Version: 1.12.2-2.1.4.43-universal
* ProjectRed Version: 1.12.2-4.9.4.120

**Screenshots/Videos**
https://github.com/TheCBProject/ForgeMultipart/issues/70 (wasn't exactly sure where to report this. the linked issue contains screenshots and further crashlogs/list of other mods included in the pack.)

**Comment by MrTJP** [comment]
Closing because 1.12 support is outdated (and crashlog is expired). Once Relocation frames are ported to 1.15, if you see more crashes, please open another issue.
