### ISSUE TITLE
Crash when using projectbench

### ISSUE THREAD

**Issue by Krougal** [MrTJP/ProjectRed#1537]
This is a 1 off to me, I use the bench all the time, it works fine. Just felt I should report it.

**Describe the bug**
Was making a TF reinforced upgrade in the projectbench. 

**To Reproduce**
It seems to be a 1 time thing.

**Expected behavior**
Not to crash when crafting item

**Crash Log**
https://paste.dimdev.org/dusedabila.mccrash

**Versions**
Everything in the pastebin

**Comment by MrTJP** [comment]
Crash log link seems to be expired. This is probably fixed at this point anyway, since a lot has changed with the project bench. Open another issue of you see more crashes in 1.15+.
