### ISSUE TITLE
lag with emc generator

### ISSUE THREAD

**Issue by Ivar418** [MrTJP/ProjectRed#1538]
**Describe the bug**
Hi. im using project red to make an EMC farm using ic2classic and blaze rods. i have a gtx 1080 and an i5-9600k wich a pretty overkill for minecraft. but when i build a large emc farm my frames begin to drop tremendously. there is no problem with stuff lying on the ground. only with the emc farm up and running. i think the pipes need to be optimized.

if you still need a log. please let me know. i did not upload since there is no crash

to be specific. i used energy condensor. filter importer. item importer. macerator. pressure tubes. red alloy wire.

here is a picture. in the top left u can see my usages. if i use shaders the lag becomes even worse ( https://imgur.com/a/ijlcZmq )
Steps to reproduce:

build a "lagre" blaze emc farm. and look at it
What I expected to happen: to not cause so much lag.

What happened instead: a lot of lag was produced ( and low frames). tho when looking away. the lag disapears. it doesnt matter how far away i am or if i build bloks arround it.

CCL Version: sorry i dont know what this is and i cant find anything about "ccl"
FMP Version: ForgeMultipart-1.12.2-2.6.2.83-universal
MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal
ProjectRed Version:  ProjectRed-1.12.2-4.9.4.120-Base.  ProjectRed-1.12.2-4.9.4.120-compat.  ProjectRed-1.12.2-4.9.4.120-fabrication.  ProjectRed-1.12.2-4.9.4.120-integration.   ProjectRed-1.12.2-4.9.4.120-lighting.  ProjectRed-1.12.2-4.9.4.120-mechanical.  ProjectRed-1.12.2-4.9.4.120-world

Screenshots/Videos
 https://imgur.com/a/ijlcZmq

**Comment by BallOfEnergy1** [comment]
I think it "might" be the rendering of all the blaze rods in the pipes. I don't think this has to do with Project Red. Refer to either the IC2 bug reporting github or the mod that you use the pipes from.

**Comment by Ivar418** [comment]
I discovered it was related to the texture pack I used. Seems even tho you have beefy specks, Minecraft can't really take advantage of it.
