### ISSUE TITLE
Linear actuator doesn't receive signals until BUD

### ISSUE THREAD

**Issue by Heimdell** [MrTJP/ProjectRed#1540]
**Describe the bug**
Sometimes, linear actuator will not receive updates from framed cable, until you manually place a block near it.

**To Reproduce**
I have a world with a device that demonstrates the bug.
1. Device is floating in the air.
2. Press "Down" switch to start descending.
3. Observe device descending.
4. After device strikes the earth, it will dig 2-3 meters deep and stop descending.
5. At that point, the only thing that will make it descent is placing a redstone block near down-pushing actuator (I did not tried with other blocks).

**Expected behavior**
Device descending through superflat sandstone all the way to the bedrock.

**Crash Log**
-

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.12.2-3.2.3.358
* FMP Version: 1.12.2-2.6.2.83
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.4.120

**Screenshots/Videos**
[Ships.tar.gz](https://github.com/MrTJP/ProjectRed/files/3908395/Ships.tar.gz)

**Comment by Heimdell** [comment]
When Linear Actuator is moved into redstone-powered position, it doesn't start pushing things sometimes.

This happens in one direction per axis in certain constructions.

The Frame Motor, on contrast, when moved into powered position, always starts to do its thing.

I hope this helps. I also wonder, why aren't motor and actuator of the same class, differing only in direction of force.

**Comment by MrTJP** [comment]
Relocation module (including motors, actuators, frames, and movement mechanism) has been rewritten. This no longer applies.
