### ISSUE TITLE
ProjectRed gem issue with Dank Null

### ISSUE THREAD

**Issue by timmit99** [MrTJP/ProjectRed#1548]
**Describe the bug**
Upon placing a ProjectRed gem (Ruby, Sapphire, Peridot) into Dank/Null they are replaced with 4 Circuit Plates from project Red

**To Reproduce**
1. Acquire Gems
2. Open Dank Null
3. Insert Gems
4. *Don't* profit.. the expensive gems are converted to Circuit Plates

**Expected behavior**
Gems do not transmute upon storage

**Crash Log**
N/A no crash

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
#
* MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal.jar
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120-_______.jar

**Screenshots/Videos**
![ProjectRed Bug](https://user-images.githubusercontent.com/8399317/70489016-7a8c0700-1ac8-11ea-9b6a-204f3bf8f1c5.gif)

**Comment by piedpipr314** [comment]
It might help to check your dank null version as well, I have not seen this bug with the latest versions of that mod.  I can check later.

**Comment by MrTJP** [comment]
Highly doubt it was a bug on ProjectRed's side. And this is most likely gone now because Items are handled completely different in 1.15+ (separate items entirely instead of single item with different metadata values).
