### ISSUE TITLE
[Suggestion] Add gates to control and detect signal strengths

### ISSUE THREAD

**Issue by Smeaty-K** [MrTJP/ProjectRed#1549]
Since making redstone signal strength based contraptions on its own is complex and bulky, Project:Red makes this harder to manage with the fact that the strength is _way more stronger_ then conventional redstone, I recommend adding 2 logic gates to Project:Red and maybe even in the IC chip workbench :

**"Strength Controller Gate"** : This gate would act like a OR gate with the ability to control incoming signal strengths (Example: a input with a strength of 15 going into the gate can be reduced to 5), but can only reduce the signals strength to 1 and amplify it to 15, with addition to changing its inputs with a screwdriver (like all other project red logic gates). This could be useful for analog based redstone items in other mods or with vanilla redstone machines. Example: this would work well with Analog controller signal box in railcraft, where it communicates with other railcraft items based on a redstone inputs strength.

**"Strength Detector"** : This gate would have the ability to take redstone inputs and give an output based on a set limit, Example: if it you were to put in a signal strength of 5 for the input but the minimum was 6 or the max is 4, it wont give any output but say if it gives a strength was 10 and the minimum was 5 and the max was 15, it would give a output, take note that it would have restrictions such as making conflicting signal strengths (like a limit of 6 and a max of 5) and obviously will only work with the maximum/minimum strength possible (so no minimums of -1 and maximums of 100). this would be _very_ crucial for redstone machines using storage or other item based things, things like auto shutdowns for mobfarms can be possible with this gate where the mobfarm can shut off if a strength detector is activated.

**Comment by MrTJP** [comment]
You can use a bus converter gate to convert coloured wires into their corresponding vanilla signal strengths, and vice versa. Project Red wires themselves are suppose to be longer range version of wires, so if you want to harvest signal drop, you will very long wires. But that's not really an intended use case for them. 

Using the bus converter, you can run analog signals as colours through bundled cables, and convert back on the other side with another bus converter.
