### ISSUE TITLE
Item Barrel does not store over 1 stack

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#1550]
**Describe the bug**
> "Item Barrel", part of ProjectRed Exploration, is meant to hold 128 stacks of 64 of one type of item and display the item stored on its sides. After placing a stack of something in the barrel with right click, it does not display anything on its side and does not accept more than one stack. The item stack can still be removed with left click.

As reported in my modpack [here](https://github.com/xJon/The-1.12.2-Pack/issues/40), and also apparently reported in FTB Revelations [here](https://github.com/FTBTeam/FTB-Revelation-2/issues/163).

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.12.2-3.2.3.358
* FMP Version: 1.12.2-2.6.2.83
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.4.120

**Comment by MrTJP** [comment]
Hmm. Wtf? I thought I had deprecated the barrel long ago. Either way, its no longer being supported. I'll use this ticket to track the removal of recipe for the barrel.

**Comment by MrTJP** [comment]
As the of the 1.15/1.16 ports in progress, the Barrel has been removed.
