### ISSUE TITLE
Using backpack to duplicate items

### ISSUE THREAD

**Issue by TheRealKamisama** [MrTJP/ProjectRed#1551]
**Describe the bug**
Using PR's backpack to duplicate everything

**To Reproduce**
When there are two backpacks in the shortcut, one contains items and the other does not. While opening the backpack that contains the items, press the corresponding number key of the other backpack, and then take out the items in the GUI, there is a chance that they will leave a copy in the original backpack.
I'm a server administrator and I find that some players are using this method to copy items.
I've tested it. It works.

**Versions**
* Minecraft Version: Minecraft-1.7.10
* CCL Version: CodeChickenLib-1.7.10-1.1.3.138
* FMP Version:  10.13.4.1614
* MrTJPCore Version: MrTJPCore-1.7.10-1.1.0.33
* ProjectRed Version: ProjectRed-1.7.10-4.7.0pre12.95

**Screenshots/Videos**
![](https://user-images.githubusercontent.com/35005476/70999962-63c36100-2115-11ea-9f12-c9dc0ff12da5.png)
![](https://user-images.githubusercontent.com/35005476/70999968-64f48e00-2115-11ea-9d12-bc72dfc4095d.png)

**Comment by Avalkiz** [comment]
I also had that problem on 1.7.10 and also I'm having the exact same issue even on version 1.12.2 Had to completely block these backpacks on my server.

**Comment by CrankySupertoon** [comment]
+Avalkiz feel free to use this https://www.curseforge.com/minecraft/mc-mods/dupefix-project Server side only

**Comment by MrTJP** [comment]
These issues should be fixed in 1.15/1.16 versions.
