### ISSUE TITLE
Frame motor cannot drive the frame

### ISSUE THREAD

**Issue by shuh89005** [MrTJP/ProjectRed#1552]
* CCL Version:3.2.3.358
* FMP Version:2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version:4.9.4.120

description:Frame motor cannot drive the frame
![IMG_20200104_132807](https://user-images.githubusercontent.com/59284680/71760353-4e14b080-2ef7-11ea-9193-3527386ba012.jpg)

**Comment by shuh89005** [comment]
> * CCL Version:3.2.3.358
> * FMP Version:2.6.2.83
> * MrTJPCore Version: 2.1.4.43
> * ProjectRed Version:4.9.4.120
> 
> description:Sometimes Frame motor cannot drive the frame
> ![IMG_20200104_132807](https://user-images.githubusercontent.com/59284680/71760353-4e14b080-2ef7-11ea-9193-3527386ba012.jpg)

**Comment by Heimdell** [comment]
Check that the frame is no connected to blocks that can't be moved (including _the_ motor itself)

**Comment by Heimdell** [comment]
If you want the motor to move itself, put 2 motors, one to move construction and another to move first motor.

Notice that the motor is "glued" to the frame only by its back side.

**Comment by MrTJP** [comment]
You most likely have your motor trying to move itself, which does not work. Use 1 motor to move the whole thing, and then another to move the original motor back into place..
