### ISSUE TITLE
[Suggestion] Rework backpack texture to be consistent in visual style

### ISSUE THREAD

**Issue by jxu** [MrTJP/ProjectRed#1553]
Observe the higher resolution and shading does not match the visual style of vanilla and other mods blocks. I am not an artist but I can throw together a quick 16x16 texture.

![2020-01-10_02 25 31_crop](https://user-images.githubusercontent.com/7989982/72134001-d4dee880-3350-11ea-82e1-dbe3d0d99ec1.png)

**Comment by MrTJP** [comment]
Will definitely be reworked, along with several other textures that are now not fitting the vanilla style.
