### ISSUE TITLE
[1.12.2] Auto Crafting Bench does not require Electrotine power

### ISSUE THREAD

**Issue by Pulz-TCP** [MrTJP/ProjectRed#1555]
**Describe the bug**
As seen in the image below, Auto Crafting Benches do not seem to require power to function in a PR-Transportation network.
![](https://i.imgur.com/RY6kZpT.png)

**Expected power setup would look like this**
![](https://i.imgur.com/RIvPUUH.png)

**Versions**
* CCL Version: 3.2.3.357
* FMP Version: 2.6.1.81
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Comment by MrTJP** [comment]
Currently, the Auto-Crafting Bench functions as follows:
* Without power:
    * Crafts slow
    * does not cycle through plans

* With power:
    * Crafts much faster
    * cycles through all plans automatically

So you can get away with having a single plan in the crafter without power if you don't mind the wait. So i guess the real question is, does it make more sense to just not let it craft at all without power?

**Comment by Pulz-TCP** [comment]
Thank you for clarifying- then it is intended functionality and does make sense.
