### ISSUE TITLE
[1.12.2] Auto Crafting Bench ignores IC2 tool durability

### ISSUE THREAD

**Issue by Pulz-TCP** [MrTJP/ProjectRed#1556]
**Describe the bug**
This is basically a dupe of #968. I can only assume that an update reintroduced this bug.
An IC2 cutter or hammer can be used in an Auto Crafting Bench and will not lower the items 'uses'.

**Versions**
* CCL Version: 3.2.3.357
* FMP Version: 2.6.1.81
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120
* Industrialcraft 2: 2.8.125-ex112

**Screenshots/Videos**
I'm sure you don't need me to tell you how to set up auto crafting, but here is a picture of the setup anyway. Works as expected, just the items do not lose durability.
![](https://i.imgur.com/RY6kZpT.png)

**Comment by MrTJP** [comment]
Fixed on branch tracking 1.15 port: d2957e7c9d4f0d80ab16b6429efed16cf7f349a0
