### ISSUE TITLE
[1.12.2] Crashes with OpenComputers

### ISSUE THREAD

**Issue by Blast1113** [MrTJP/ProjectRed#1562]
Right clicking on a Computer Case causes the game to crash with this error:

java.lang.NoSuchMethodError: mrtjp.projectred.api.ITransmissionAPI.getBundledInput(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)[B

Full crash report: [https://pastebin.com/KWFCJ439](https://pastebin.com/KWFCJ439)

**Comment by Muha0644** [comment]
This looks like it's a problem with OpenComputers, not ProjectRed. Try using a different version (of both mods). 
I had no problems getting and setting redstone cables with OpenComputers on my PC.

**Comment by MrTJP** [comment]
Looks like a mismatch between project red api and the version that your particular install of OpenComputers was using. Shouldn't be an issue in 1.15+. Integration with OpenComputers is planned, and the API is more stable now.
