### ISSUE TITLE
[1.12.2] Wire rendering and breaking with CubicChunks

### ISSUE THREAD

**Issue by sa-shiro** [MrTJP/ProjectRed#1563]
error log cant be provided, because the game freezes and wont spit out any detail.

Behaviour:

When placing wires while having CubicChunks and CubicWorldGen installed, they disappear once you exit the world.

Breaking the wire and or the block where the wire is on leads to a freeze crash (specially below 0 and above 255, but it even appears between 0 and 255 y level)

Is it possible to fix this issue?

**Comment by MrTJP** [comment]
I don't think CubicChunks is a thing for 1.16, but if this still happens then please re-open
