### ISSUE TITLE
[Suggestion] Add options to the Sequencer to allow it to be disabled (GUI and redstone signal)

### ISSUE THREAD

**Issue by mahldcat** [MrTJP/ProjectRed#1564]
Use Case:  
I was using the sequencer to trigger a series of mechanical users as part of some automation.  I had the majority of the items placed and wired up but still had some bugs with this particular build.

Figuring out the issue proved to be challenging due to the sequencer triggering things automatically on me (and I wanted to avoid breaking/replacing it).

Current Behavior:  
Instead I was able to change the cycle time to a large value +20 minutes (this build only used 3/4 of the outputs

Quality of Life Change:
Add a feature in the gui that lets you manually disable the sequencer (either a button, or setting the cycle time to "0")?

**Comment by MrTJP** [comment]
The sequencer is a time-of-day synchronized gate. You can disable it with an external latch if necessary, or by simply using a regular timer instead. But since its main purpose is to always remain in sync with time of day, it doesn't make sense to allow it to be disabled.
