### ISSUE TITLE
Project Red Core crash during initialization.

### ISSUE THREAD

**Issue by TheJuiceFR** [MrTJP/ProjectRed#1565]
No mods, no crash. Just dependencies, no crash.
Just project red core and dependencies, crash.

**Crash Log**
https://pastebin.com/7vfD1Dph

The line that I think is the most relevant is
`Caused by: java.lang.AbstractMethodError: mrtjp.projectred.core.PRUpdateChecker.mrtjp$core$data$UpdateChecker$$messageDisplayed_$eq(Z)V`

**Versions**
CCL Version: 1.7.10-1.1.3.136
FMP Version: 1.7.10-1.2.0.345
MrTJPCore Version: 1.7.10-1.1.0.33
ProjectRed Version: 1.7.10-4.6.2.82

This issue might be setup related, but I don't think I have any way of knowing the reason for this issue without understanding the source code, Which is an issue in itself.

**Comment by iiSnewoNL** [comment]
Still not solved for me
