### ISSUE TITLE
Lamp halo not rendering at longer distances

### ISSUE THREAD

**Issue by Bagfil** [MrTJP/ProjectRed#1566]
**Describe the bug**
When moving further than 64 blocks away from a lit lamp (any form) the lamp halo will disappear and the lamp will visually look like it's turned off. 

**To Reproduce**
1. Place any lamp block.
2. Move at least 64+ blocks away from it.
3. Lamp halo will not render as if turned off

**Versions**
* CCL Version: 1.12.2-3.2.3.358
* FMP Version: 1.12.2-2.6.2.83
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.4.120

**Screenshots/Videos**
Video Detailing the issue: https://www.youtube.com/watch?v=5Gzu2NG7T6A
![2020-02-21_21 32 44](https://user-images.githubusercontent.com/26846054/75095768-d8dd6780-5598-11ea-9eba-469f9b621c2c.png)

**Comment by MrTJP** [comment]
Wasn't a 'bug' exactly, just a limit of the glow renderer. Should be much further in 1.15/1.16 versions, matching other tile entities.
