### ISSUE TITLE
Exception loading model for variant projectred-fabrication:ic_machine#inventory Forge1.12.2-14.23.5.2846 & Project red1.12.2-4.9.4.120

### ISSUE THREAD

**Issue by velocityraptor-real** [MrTJP/ProjectRed#1574]
Model loading exeption appeared in the latest log.

1. Run the game
2. Find the error in the latest log

Expected behavior:
This error not appearing

Error log (not entire log, just the error):
[model loading error.txt](https://github.com/MrTJP/ProjectRed/files/4392368/model.loading.error.txt)

Forge Version: 1.12.2-14.23.5.2846
CCL Version: 1.12.2-3.2.3.358-universal
FMP Version: 1.12.2-2.6.2.83-universal
MrTJPCore Version: 1.12.2-2.1.4.43-universal
ProjectRed Version: 1.12.2-4.9.4.120

**Comment by velocityraptor-real** [comment]
[loading error.txt](https://github.com/MrTJP/ProjectRed/files/4763135/loading.error.txt)

**Comment by covers1624** [comment]
Ignore these, they arent 'errors'
