### ISSUE TITLE
UPDATE README DEV SETUP INSTRUCTIONS

### ISSUE THREAD

**Issue by CodeArc13** [MrTJP/ProjectRed#1575]
I have been trying to setup ProjectRed in IntellIJ IDEA for a couple of days now and have deffinately followed the instructions in the read me correctly several times, but Minecraft gives multiple errors in the idea console when loading :- https://gist.github.com/CodeArc13/36c5848fddd41b2850a77f8d9affef77

**Comment by Sodierlow** [comment]
Hi, you have installed 2 version of JEI

**Comment by CodeArc13** [comment]
This is what I don't understand, I have simply followed the read me and not installed any versions of JEI my self, so I am not sure whats going on, when I remove the older version from the dependencies in the project code chicken and the microblockscbe (i think its called) complain that it is missing.

**Comment by MrTJP** [comment]
Instructions have been updated.
