### ISSUE TITLE
Crash from world generation

### ISSUE THREAD

**Issue by EnderMelody** [MrTJP/ProjectRed#1576]
**Describe the bug**
server runs fine until someone loads a specific area, which then crashes the server from the watchdog.

**To Reproduce**
1. Start world
2. Travel until game crashes

**Expected behavior**
Generate chunks

**Crash Log**
https://paste.dimdev.org/yozakihapu.mccrash
https://paste.dimdev.org/kiyewawoge.mccrash

**Versions**
* CCL Version: ?
* FMP Version: ForgeMultipart-1.12.2-2.6.2.83-universal.jar
* MrTJPCore Version: mcjtylib-1.12-3.5.4.jar
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120-Base.jar

**Comment by MrTJP** [comment]
World generation will be reworked in 1.15+
