### ISSUE TITLE
Project Red 2 and Hwyla 1.12.2

### ISSUE THREAD

**Issue by Harchvertelol** [MrTJP/ProjectRed#1579]
**Describe the bug**
Project red 2 version: ProjectRed-1.12.2-4.9.4.120-...

Hwyla-1.8.26-B41_1.12.2 not showing information about project red 2 schemes (pr.showio=true not working, unlike 1.7.10 version). The Project Red 2 module is not listed. In the comments on the Hwyla I was sent here. What can I do?

**To Reproduce**
1. Install Hwyla-1.8.26-B41_1.12.2.jar
2. Open game.
3. Set block gate.
4. Not showing information.

**Expected behavior**
Showing IO information and maybe states.

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: CodeChickenLib-1.12.2-3.2.3.358-universal
* FMP Version: ForgeMultipart-1.12.2-2.6.2.83-universal
* MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120-...

**Comment by MrTJP** [comment]
I currently don't and have not ever previously explicitly supported Hwyla. The integration was generously offered by the developers of Hwyla. Maybe that will change in 1.16, but for 1.12, this is not my problem.
