### ISSUE TITLE
Project bench IC2 tools durability bug

### ISSUE THREAD

**Issue by sidboy55555** [MrTJP/ProjectRed#1580]
**Describe the bug**
When having two or more forge hammers in the projecting table, while crafting with them,
the durability of those tools won't go down, either of them. And also for some reason,
if the durabilty of one hammer is 24, and the other 35. The hammer of 24 will go to 34
(one hammer has always 1 less durability then the other).

**To Reproduce**
Place 2 hammers in the project bench (one in the crafting grid).
Craft anything with it, like a stack iron plates, and you see the durability won't go down.

**Expected behavior**
The durability of the hammer to go down.

**Versions**
MrTJPCore: 2.1.4.43
PR Base: 4.9.4.120
PR Compat: 4.9.4.120
PR Integration: 4.9.4.120
PR Fabrication: 4.9.4.120
PR Lighting: 4.9.4.120
PR Mechanical: 4.9.4.120
PR World: 4.9.4.120
Codechicken lib: 3.2.3.358
Forge multipart CBE: 2.6.2.83
And at last, but not least.
IC2: 2-2.8.170

**Screenshots/Videos**
https://drive.google.com/file/d/1UGXV7sNZSm0pky00VyuB159OcC7ZOgNQ/view?usp=sharing

**Comment by MrTJP** [comment]
Fixed in d2957e7c9d4f0d80ab16b6429efed16cf7f349a0

**Comment by xJon** [comment]
@MrTJP This did not make it to any 1.12 release, right?

**Comment by Rayzeq** [comment]
The 1.12 version is not supported anymore, only the 1.16 (and maybe 1.15 I don't know) versions are supported.
