### ISSUE TITLE
ProjectRed-1.12.2-4.9.4.120-lighting AND Optifine

### ISSUE THREAD

**Issue by guojianmin** [MrTJP/ProjectRed#1584]
MC's Version:1.12.2 Forge-14.23.5.2845
Mod's Name:ProjectRed-1.12.2-4.9.4.120-lighting
Optifine's Version F5
shaderpacks:BSL Standard v7.0p1  ,   KUDA-Shaders v5.0.6 Extreme  ,  SEUS-v11.0
I've tried all of the shaderpacks,
But it doesn't work normal.
if i removed Optifine,then it works, 
![1](https://user-images.githubusercontent.com/38575831/80287176-93891200-8762-11ea-95e3-05855cdeae90.jpg)
![2](https://user-images.githubusercontent.com/38575831/80287177-94ba3f00-8762-11ea-93ad-2107d7eeebb4.jpg)

if you can't see the image,please try this link.
[](url)https://www.mcbbs.net/thread-1028605-1-1.html

**Comment by MrTJP** [comment]
Remove Optifine. Its not supported.
