### ISSUE TITLE
WirePropagator spamming IllegalArgumentException

### ISSUE THREAD

**Issue by ImMorpheus** [MrTJP/ProjectRed#1586]
**Describe the bug**
This:
https://github.com/MrTJP/ProjectRed/blob/b7fb77bbf17aea43e883e8958df0511635eac29d/src/mrtjp/projectred/core/propagation.scala#L28

is throwing IllegalArgumentException.

https://github.com/MrTJP/ProjectRed/blob/b7fb77bbf17aea43e883e8958df0511635eac29d/src/mrtjp/projectred/core/propagation.scala#L20

evaluates to the field:

`public static final PropertyEnum<BlockRedstoneWire.EnumAttachPosition> NORTH = PropertyEnum.<BlockRedstoneWire.EnumAttachPosition>create("north", BlockRedstoneWire.EnumAttachPosition.class);`

which is final and is not a boolean.

**To Reproduce**
The exception is suppressed you can only look at this in a dev env or in a .nps

**Expected behavior**
No exception

**Crash Log**
No crash. 

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: CodeChicken Lib v3.2.3.358
* FMP Version: Forge Multipart CBE v2.6.2.83
* MrTJPCore Version: MrTJPCore v2.1.4.43
* ProjectRed Version: ProjectRed Core v4.9.4.120

**Screenshots/Videos**
No screenshots, except the sampling which spotted the issue:

![](https://transfer.sh/pc1Mr/red.png)

**Comment by MrTJP** [comment]
That bit of code is no longer present, so this shouldn't happen anymore.
