### ISSUE TITLE
java.util.NoSuchElementException: key not found: 1 triggering when crack player moves on MP

### ISSUE THREAD

**Issue by 28Pollux28** [MrTJP/ProjectRed#1589]
**Describe the bug**
Each time a cracked version player moves in the server, that error is triggered in the console, but don't crash the server, just spamming the console. It stops when the player stop moving.

**To Reproduce**
Create a MP server
Join with a crack client
Walk

**Crash Log**
https://pastebin.com/9yNPz0qc

**Versions**

* CCL Version: CodeChickenLib-1.12.2-3.2.3.358-universal.jar
* FMP Version: ForgeMultipart-1.12.2-2.6.2.83-universal.jar
* MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal.jar
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120-Base.jar
* using Sponge Version : spongeforge-1.12.2-2838-7.2.1.jar

I'm available in case you need more informations or specifications,
With regards,
28Pollux28

**Comment by covers1624** [comment]
Buy the game.

**Comment by 28Pollux28** [comment]
> Buy the game.

Such a great mentality from you...
I hope you'll still look into it, because it is sad that mod creator behave this way when someone report an error.
With regards,
28Pollux28
