### ISSUE TITLE
[Wiki] Download links are 404 Fandom's home paged

### ISSUE THREAD

**Issue by ExDomino** [MrTJP/ProjectRed#1592]
Hello,
On the ProjectRed Wiki, all download links to curseforge are redirected to the Fandom's home page.
Wiki page affected: https://projectredwiki.com/wiki/Version_archive

For example, clicking on this link:
https://www.curse.com/mc-mods/minecraft/228702-project-red-base
Redirect to:
https://www.fandom.com/
Instead of:
https://www.curseforge.com/minecraft/mc-mods/project-red-base

**Comment by MrTJP** [comment]
Wiki is no longer maintained. You can find current download links on Curse.
