### ISSUE TITLE
[1.12.2] Gate models use too much memory

### ISSUE THREAD

**Issue by SoniEx2** [MrTJP/ProjectRed#1593]
**Describe the bug**

Gate models use too much memory.

**To Reproduce**

Grab a heap dump, notice 300MB being used for gate models.

**Expected behavior**

Gate models shouldn't be *quite* that hungry. For what it's worth, this seems to be scala's fault. Surely there's a way to optimize it?

**Crash Log**
*Required for crash.* **DO NOT** paste the entire crash log here. Use pastebin or similar. 

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version:
* FMP Version:
* MrTJPCore Version: 
* ProjectRed Version:

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

**Comment by MrTJP** [comment]
Switch to 2d models if it is causing performance issues. Its a config option.
