### ISSUE TITLE
[Bug] Possible Render Crash With JEI.

### ISSUE THREAD

**Issue by DarkAmbientNoise** [MrTJP/ProjectRed#1601]
**Describe the bug**
At what seems sort of random, JEI will crash when attempting to render a gate model from Pro. Red : Integration.

**To Reproduce**
-1. (Issue, it isn't always reproducible, I've had this crash multiple times, completely reloading the client seems to resolve it)

1. Search anything in JEI that would trigger the item in question to be rendered by JEI.
2. Instant client side crash.

Side note: The world can be loaded after this crash and you can still play the game, but opening any inventory or anything that would trigger JEI to render the item again, will result in another instant crash.

**Expected behavior**
Not crashing when viewing Project Red items from JEI.

**Crash Log**
https://pastebin.com/JjzP74JN

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.12.2-3.2.3.358
* FMP Version: 1.12.2-2.6.2.83
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.4.120
* JEI Version: 1.12.2-4.16.1.301

**Comment by MrTJP** [comment]
Cant reproduce this anymore in 1.15. Likely no longer an issue.
