### ISSUE TITLE
Project Red Expansion Won't run. Always crashing

### ISSUE THREAD

**Issue by Waffle1257** [MrTJP/ProjectRed#1603]
I have downloaded all the necessary mods to be able to run the project red mods but every time I run minecraft It crashes because it says Project Red Mechanical/Expansion had an error on initializing. The other Project Red mods initialize fine the only problem is the Project Red Mechanical/Expansion. 

Here is the crash logs: https://pastebin.com/Xre1r61B

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version:CodeChickenLib-1.7.10-1.1.3.138-universal.jar
* FMP Version:ForgeMultipart-1.7.10-1.2.0.345-universal.jar
* MrTJPCore Version: MrTJPCore-1.1.0.33-universal.jar
* ProjectRed Version: ProjectRed-1.7.10-4.7.0pre12.95

**Comment by Psy-Virus** [comment]
Hey @Waffle1257,

```
java.lang.IllegalArgumentException: Duplicate enchantment id! class mrtjp.projectred.expansion.EnchantmentFuelEfficiency and class mrcomputerghost.runicdungeons.ench.EnchantmentPoisonThorns Enchantment ID:80
```

This error says that there's a conflict between two enchantments. Maybe you can change the Id of the Runic Dungeons "Poison Thorns" enchantment in the config?

I don't think that Mr.TJP is willing to further support PR for 1.7.10.
Neither will the dev of Runic Dungeons, as this mod didn't get developed past 1.7.X

So I guess you have only two options: Either decide for one of the mods or find out, how to tinker with Enchantment IDs...

**Comment by Waffle1257** [comment]
> Hey @Waffle1257,
> 
> ```
> java.lang.IllegalArgumentException: Duplicate enchantment id! class mrtjp.projectred.expansion.EnchantmentFuelEfficiency and class mrcomputerghost.runicdungeons.ench.EnchantmentPoisonThorns Enchantment ID:80
> ```
> 
> This error says that there's a conflict between two enchantments. Maybe you can change the Id of the Runic Dungeons "Poison Thorns" enchantment in the config?
> 
> I don't think that Mr.TJP is willing to further support PR for 1.7.10.
> Neither will the dev of Runic Dungeons, as this mod didn't get developed past 1.7.X
> 
> So I guess you have only two options: Either decide for one of the mods or find out, how to tinker with Enchantment IDs...

I appreciate your help I will look into how to change the enchantment IDs
