### ISSUE TITLE
Update project configuration (gradle, java, project file generators for IDEs)

### ISSUE THREAD

**Issue by Rayzeq** [MrTJP/ProjectRed#1604]
Can you update the gradle version (gradle 2.x don't support java 1.8, and isn't supported by newer versions of IntelliJ) ?
You should also update the project generator, because it is no longer compatible (I only tested with IntelliJ, it still works but with a lot of manual configuration).
There is also a problem with JEI, two versions are downloaded, and the version that is in `build.properties` (4.15.0.+) needs a higher version of forge (which uses Userdev3)

I know this mod is no longer maintained, but I would like to add my own features, and I can't get the project to work.

**Comment by Rayzeq** [comment]
I'm also wondering if you've abandoned this mod, or if you just don't have the time to develop it ?
Also if you don't want to change the project for the moment, I'd like to know which version of IntelliJ it should be open with, and the right version of java (java 1.7 ?).

**Comment by covers1624** [comment]
Project Red is not abandoned. It is being actively ported to 1.15 by myself. 1.12 is not supported anymore. Gradle 2 absolutely supports Java 8, However, due to the newer version of Java used by later versions of Intellij, the project cannot be imported anymore.
