### ISSUE TITLE
Yabba Barrels not accepting large quantities

### ISSUE THREAD

**Issue by McfarlaneRob** [MrTJP/ProjectRed#1605]
YABBA barrels will only request a single stack of items at a time even if they have a large amount more free storage.

1. Create a storage network with a number of chests that have item responder chips set to an empty blacklist with priority 0, a YABBA barrel with an item responder chip set to receive a specific item with priority 5, and a single chest with an item extractor chip set to an empty blacklist.
2. Insert more than a stack of the item that the barrel is set to receive into the extractor chest
3. Many of the items will be routed to the chests in favour of the barrel even if the barrel has enough space for them all

I would expect in this scenario for the items to fill the barrel before being put into the chests

* CCL Version: CodeChickenLib-1.12.2-3.2.3.358-universal
* FMP Version: ForgeMultipart-1.12.2-2.6.1.81-universal
* MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120

**Comment by IB38** [comment]
I have the same issue.
@McfarlaneRob  Have you found a workaround? I tried priority -1 for general storage chests and priority 10 for the barrels, but it didn't help.
