### ISSUE TITLE
[Feature Request] Switch from ForgeMultipart to MCMultipart

### ISSUE THREAD

**Issue by juraj-hrivnak** [MrTJP/ProjectRed#1606]
**Yeah, this might be a little bit overkill request, but it's worth a try.**

**It would be very cool to have some compatibility with Chisels&Bit, EnderIO and other mods that support** [MCMultipart](https://www.curseforge.com/minecraft/mc-mods/mcmultipart).

`PS: This is probably not possible, but thanks anyway for such a great mod!`

**Comment by covers1624** [comment]
Not going to happen. Completely different api and MCMultipart is dead past 1.12.
