### ISSUE TITLE
Useless 7-segment display

### ISSUE THREAD

**Issue by kamik1979** [MrTJP/ProjectRed#1607]
I want do display a number represented by 8-bit binary value on a 7-segment display gate. I don't know how to do this. For me, this display is toatlly useless. Do something with this.

**Comment by MrTJP** [comment]
You can do this with a binary to 7-segment decoder circuit. It's purely combinational and all gates necessary to make one already exists.

Here is one of many tutorials out there: [BCD to 7-Segment Decoder](http://learn.electronics-course.com/#15)
