### ISSUE TITLE
[Enhancement] Apply Oredict itemSilicon to PR Silicon wafers

### ISSUE THREAD

**Issue by mikeloeven** [MrTJP/ProjectRed#1612]
Please apply the oredict name itemSilicon to Silicon wafers and the associated recipes so the mod will play nice with silicon generated by other mods such as Ender IO and AE2

**Comment by MrTJP** [comment]
The only silicon PR adds is part of a crafting chain, so it doesn't make sense to equate it to items called "Silicon" from other mods:

`Diamonds -> Diamond Saw -> Silicon Boule -> Silicon -> Compounds -> Advanced gates`

Unless an item is obtained the same way, I don't throw stuff into the Oredict simply for having the same name. Also I'm making changes to these items anyway, so this isn't going to be relevant anymore.
