### ISSUE TITLE
Buttons pop off of panels/covers/slabs when activated

### ISSUE THREAD

**Issue by Hawk777** [MrTJP/ProjectRed#1617]
**Describe the bug**
When an illumar button (feedback or not) is mounted on a cover, panel, or slab and activated, it blinks for a moment then pops off as an item.

**To Reproduce**
1. Craft a stone cover, panel, or slab.
2. Place the cover, panel, or slab on a side portion of a block, so it is standing up vertically.
3. Place the illumar button on the cover, panel, or slab so it occupies the adjacent block space.
4. Right-click the illumar button.

**Expected behavior**
The illumar button should press then unpress.

**Versions**
* CCL Version: 3.2.3.358
* FMP CBE Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Comment by MrTJP** [comment]
No longer happens on 1.15. Must've been fixed at some point since then.
