### ISSUE TITLE
Crash when interconnecting bundled with framed cables

### ISSUE THREAD

**Issue by NDev8** [MrTJP/ProjectRed#1622]
**Describe the bug**
When placing 3 framed bundled cables or colored framed cables in a row surrounded by bundled cables with different colors and interconnecting with them (see screenshot), an ArrayIndexOutOfBoundsException is thrown.

**To Reproduce**
1. Checkout bc91f0c89ff2ced2a1585504a57695106547c1fb
2. Start an empty world
2. Build structure as shown in screenshot
3. Enjoy the exception

**Expected behavior**
Cables interconnect with each other without crashing the game.

**Crash Log**
[crash-2021-04-29_20.01.29-client.txt](https://github.com/MrTJP/ProjectRed/files/6400880/crash-2021-04-29_20.01.29-client.txt)

**Versions**
ProjectRed at: bc91f0c89ff2ced2a1585504a57695106547c1fb

**Screenshots/Videos**
![2021-04-29_19 57 01](https://user-images.githubusercontent.com/36798969/116601877-45858c00-a92b-11eb-87ce-b7bcafaff87f.png)
It does not matter, if a blue framed cable or a bundled framed cable is used.

**Comment by MrTJP** [comment]
Nice find, taking a look..

**Comment by MrTJP** [comment]
Happens when any framed cable is connected on all 6 sides, it seems

**Comment by MrTJP** [comment]
Fixed with 287e99b61a997a6a52fa2b9af6a6498e4bb8aac0

**Comment by Somebodyisnobody** [comment]
> Happens when any framed cable is connected on all 6 sides, it seems

Ah that's the reason why it needed three framed wires. I woundered.
