### ISSUE TITLE
Crash while reloading resource packs on settings change

### ISSUE THREAD

**Issue by NDev8** [MrTJP/ProjectRed#1624]
**Describe the bug**
When loading the included programmer art resource pack (changing the resource pack), the game crashes while trying to update the resources.

**To Reproduce**
1. Open the game with ProjectRed at 287e99b61a997a6a52fa2b9af6a6498e4bb8aac0
2. Change resource pack settings
3. Click done
4. Game is crashing

**Expected behavior**
Game has reloaded all resources.

**Crash Log**
[crash-2021-05-01_16.51.17-client.txt](https://github.com/MrTJP/ProjectRed/files/6409772/crash-2021-05-01_16.51.17-client.txt)

**Comment by MrTJP** [comment]
This was because of a Scala compilation issue where the Java interface's default implementation was being removed. Fixed in #1625
