### ISSUE TITLE
Missing Project Red - Transmission on CurseForge website

### ISSUE THREAD

**Issue by Rayzeq** [MrTJP/ProjectRed#1627]
The `Project Red - Transmission` page is not present on the CurseForge site, and the link points to a 404 error

**Comment by MrTJP** [comment]
It’s still being reviewed by Curse moderators. Not sure how long this usually takes, but should show up some time today.

**Comment by Rayzeq** [comment]
Ok nice I thought it was deleted by accident, or something like that

**Comment by patc4** [comment]
I don't know if this is enough related but 1.12.2 downloads no longer exist on curseforge for transmission.

**Comment by MrTJP** [comment]
In versions before 1.15, Integration and Transmission were bundled together in the same jar.

**Comment by patc4** [comment]
ah thanks, I wasn't aware.
