### ISSUE TITLE
java.lang.NoClassDefFoundError: mrtjp/projectred/core/ItemScrewdriver

### ISSUE THREAD

**Issue by Endleon201** [MrTJP/ProjectRed#1629]
**Describe the bug**
Compiles perfectly fine, but when run in game I get that error in the title
`Error: java.lang.NoClassDefFoundError: mrtjp/projectred/core/ItemScrewdriver`

**To Reproduce**
Build the 1.12.x branch
Copy the output jarfile to the forge `mods` dir,
run the game

**Expected behavior**
The mod being, a mod, and launching non-erroneously.

**Crash Log**
[Click here](https://pastebin.com/djR5jbAK)

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: Newest
* FMP Version: Newest
* MrTJPCore Version: Newest
* ProjectRed Version: Newest (for 1.12.x)

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

**Comment by covers1624** [comment]
`Caused by: java.lang.NoClassDefFoundError: mrtjp/core/item/ItemCore` You do not have MrTJP Core installed.
