### ISSUE TITLE
Computercraft Compatability Issues (1.15.5)

### ISSUE THREAD

**Issue by jordan8396** [MrTJP/ProjectRed#1630]
Although the description page suggests the compatibility module is now part of the Core module for the 1.15.2 version, the bundled cables do not connect to computercraft ([CC: Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)) computers :( it used to work well with the separate compat module in 1.12.2, and would be great for this compatibility to return for 1.15.2.

**Comment by MrTJP** [comment]
Compatibility is still being ported. Computercraft interactions is highest priority.
