### ISSUE TITLE
[1.12.2] Project Bench crash

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#1631]
**Describe the bug**
A Project Bench crash, reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/687.

**To Reproduce**
>  I went to L-shift + L-click a snowball in a project bench from ProjectRed when the first crash happened. I logged back in after the first crash and did the same thing to the snowball, then the second crash happened.

**Crash Log**
https://paste.dimdev.org/kopoqejiqi.mccrash
https://paste.dimdev.org/fegikizelo.mccrash

**Versions**
* CCL Version: `3.2.3.358`
* FMP Version: `2.6.2.83`
* MrTJPCore Version: `2.1.4.43`
* ProjectRed Version: `4.9.4.120`

**Comment by MrTJP** [comment]
This crash has been fixed in 1.15+
