### ISSUE TITLE
[1.16.5] Crash on dedicated servers when using Multimeter on wires

### ISSUE THREAD

**Issue by ArcanoxDragon** [MrTJP/ProjectRed#1633]
**Describe the bug**
Using a multimeter on a dedicated server (or really doing anything else that would send a message to the player, apparently) will crash the server because it tries to load client-only classes.

**To Reproduce**
1. Just use a multimeter on a wire while playing on a dedicated server

**Crash Log**
https://hastebin.com/ocekucorol.log

**Versions**
* CCL Version: 4.0.2.427
* FMP Version: Custom build
* ProjectRed Version: Custom build

I plan on submitting a PR to fix this

**Comment by MrTJP** [comment]
Crash is fixed. Multimeter rendering still needs to be looked at.
