### ISSUE TITLE
Cell gates break the mod

### ISSUE THREAD

**Issue by ElNico56** [MrTJP/ProjectRed#1636]
**Describe the bug**
Wires stop working after placing one into a null cell (happened twice and haven't tested other gates)
note: works with any "cell"

**To Reproduce**
1. place null cell
2. place wire alongisde it
3. update wire with any input
4. wires no longer update until game restart

**Expected behavior**
i expected for the wires to keep working after placing them

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5 4.0.2.427
* FMP Version: 1.16.5-3.0.1.115
* MrTJPCore Version: MrTJPCore library and Compatibility module are now combined into Core
* ProjectRed Version: 1.16.5-4.10.0-beta-34

**Screenshots/Videos**
https://youtu.be/j_8DyU5Xook

**Comment by MrTJP** [comment]
Confirmed. Looking into it..

**Comment by MrTJP** [comment]
Uploading new build to Curse now...
