### ISSUE TITLE
Sequencers broke on last update

### ISSUE THREAD

**Issue by ElNico56** [MrTJP/ProjectRed#1638]
**Describe the bug**
Sequencer doesn't work

**To Reproduce**
1. Place sequencer
2. See error

**Expected behavior**
I expected the sequencer to work

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.2.427
* FMP Version: 1.16.5-3.0.1.115
* MrTJPCore Version: Included in PR
* ProjectRed Version: 1.16.5-4.10.0-beta-35

**Screenshots/Videos**
https://youtu.be/JqLxMaT7mDY

**Comment by MrTJP** [comment]
Not seeing the issue. Works fine for me:

<img width="1397" alt="Screen Shot 2021-07-03 at 10 33 30 AM" src="https://user-images.githubusercontent.com/1957405/124357570-343a5380-dbea-11eb-925a-f5d4d0141e25.png">

Perhaps your world has some kind of eternal day setting? Synchronizers are intended to sync with the in-game world clock.

**Comment by ElNico56** [comment]
yes, i turned dodaylightcycle off while testing other stuff on other mods

**Comment by ElNico56** [comment]
by the @MrTJP the comparators appear as repeaters https://youtu.be/ZyotUP9yIKc

**Comment by MrTJP** [comment]
Whoops. Fixed the Comparator/Repeater issue with #1640
