### ISSUE TITLE
[Suggestion] "bitwise" gates

### ISSUE THREAD

**Issue by ElNico56** [MrTJP/ProjectRed#1639]
Bundled versions of the logic gates that operate on each color individually, for example a bitwise and gate would output yellow and orange iff all enabled inputs get yellow and orange

**Comment by MrTJP** [comment]
It’s way too verbose to have a bundled version of every single gate. More complex gates will be possible to create yourself with Fabrication.

**Comment by ElNico56** [comment]
How deep into Fabrication development are you atm? Are we weeks, months or years from seeing it updated? (To 1.16, no one cares about 1.17)
