### ISSUE TITLE
NoSuchElementException when placing button or lever, null cell, and transparent latch in IC blueprint

### ISSUE THREAD

**Issue by Hawk777** [MrTJP/ProjectRed#1641]
**Describe the bug**
The existence of these three components, side by side, in an IC blueprint causes the game to crash.

**To Reproduce**
1. Place a null cell beside a transparent latch, as shown in the attached screenshot (both are in their default orientations and configurations).
2. Place a button or lever to the left of the null cell.

**Crash Log**
[crash-2021-07-03_16.09.39-server.txt](https://github.com/MrTJP/ProjectRed/files/6759156/crash-2021-07-03_16.09.39-server.txt)

**Versions**
* CCL Version: 3.2.3.358
* FMP Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Screenshots/Videos**
![2021-07-03_16 07 59](https://user-images.githubusercontent.com/365236/124368739-dffa9800-dc18-11eb-8aef-7dc353da5de9.png)

**Comment by MrTJP** [comment]
Unfortunately I no longer support older versions of the Mod. And the Fabrication module is being rewritten rather than ported, so this wouldn’t be relevant to that either.
