### ISSUE TITLE
Recipe conflict between circuit plates and the new vanilla smooth stone.

### ISSUE THREAD

**Issue by Dunkmania101** [MrTJP/ProjectRed#1645]
The title pretty much sums it up. The recipe for the circuit plates now conflicts with the new vanilla recipe for smooth stone, both of which consist of smelting regular stone.

1. Find a recipe that needs smooth stone.
2. Try to cook some regular stone in a furnace to get said smooth stone.
3. Get a circuit plate instead.

I'd suggest changing the recipe to be cooking smooth stone instead as nothing seems to use that (even in the modpack I assembled with 360+ mods).

Versions:
* CCL Version: 1.16.5-4.0.2.427
* FMP (now CBMP) Version: 1.16.5-3.0.1.115
* MrTJPCore Version: N/A
* ProjectRed Version: 1.16.5-4.10.0-beta-35 (core)

Happy programming!

**Comment by MrTJP** [comment]
Didnt know about that, I’ll change it later today.

**Comment by InuYasha86000** [comment]
I know this is closed but is there a chance for a backport for 1.12.2 of this fix due to mods like FutureMC which add the smoothstone in?
