### ISSUE TITLE
Project Red Exploration (1.16.5) world gen not working

### ISSUE THREAD

**Issue by dman52** [MrTJP/ProjectRed#1648]
I installed the latest "ProjectRed-1.16.5-4.10.0-beta-38-exploration.jar" and I started up the world with there being no ores, volcanos, etc. I have all dependencies installed correctly.
![recipe](https://user-images.githubusercontent.com/86332168/124526979-51317b00-ddd2-11eb-9c60-7466c2fe14e7.PNG)
The photo is the recipe for electrotine dust. The red circle is called "Empty tag: forge:storage_blocks/electrotine"

**Comment by MrTJP** [comment]
Fixed the incorrect tags in 05ffceeb. And looks like I totally forgot to even implement world generation :) I'll work on that next

**Comment by dman52** [comment]
> Fixed the incorrect tags in [05ffcee](https://github.com/MrTJP/ProjectRed/commit/05ffceeb82f9edf0a3ed710269a0eeb32b709bf2). And looks like I totally forgot to even implement world generation :) I'll work on that next

You da man

**Comment by Sakata-MC** [comment]
Not that it'll matter much until this issue is resolved, but worth noting that there appears to be no configuration generated for this either. Not sure if the config would be handled inside the code that does the generation, but figured I'd mention it.

**Comment by MrTJP** [comment]
Yes, that’s expected. The Config options are not generated yet in the released version.
