### ISSUE TITLE
language provider scorge:3.1

### ISSUE THREAD

**Issue by PxlLoewe** [MrTJP/ProjectRed#1649]
**Describe the bug**
When loading the Beta version, Minecraft crashes With the following log

> -- NO MOD INFO AVAILABLE --
> Details:
> 	Mod File: NO FILE INFO
> 	Failure message: Mod File ProjectRed-1.16.5-4.10.0-beta-38-core.jar needs language provider scorge:3.1 or above to load
> 		We have found none
> 	Mod Version: NO MOD INFO AVAILABLE
> 	Mod Issue URL: NOT PROVIDED
> 	Exception message: MISSING EXCEPTION MESSAGE

**To Reproduce**
Install ProjectRed-1.16.5-4.10.0-beta-38-core.jar
Start minecraft with the version and it shows the error

**Crash Log**
https://pastebin.com/2jJJtvLv

**Comment by covers1624** [comment]
As per the CurseForge page. [Scorge](https://www.curseforge.com/minecraft/mc-mods/scorge) is required.
