### ISSUE TITLE
Redstone cables, wires, bundled cables & wires causes crash game while loading world(1.16.5)

### ISSUE THREAD

**Issue by anrej0705** [MrTJP/ProjectRed#1651]
Hi there. Today i bumped into bug associated with Transmission mod which cause crash game while loading world after save game(just need quit and again join bugged world), most likely linked with wires(or cables, bundled wires, framed cables etc...) placed on the block-cover in difficult constructions from mod CBMicroblock and placed gates on this covers. Game crashes if i copy selected with wood axe region with bugged construction(//copy //paste = game crash)

exists a way to reproduce this bug:
1. Build a difficult construction according to screenshots(*) or:
1.a build a construction with many 1x1 tunnels, **necessarily** use covers from CBMultipart
1.b place a few cables, wires into tunnels
1.c build a walls use covers
1.d place a gates on covers, place gates on builded walls
1.e cover gates, wires
1.f place something from mod on this covers
2. Quit the world
3. Join world again
4. ???
5. profit))) (congratulations, now this world cannot be to load because game will crash if attempt)

* - screenshots(source, PNG) and bugged worlds here: https://drive.google.com/file/d/18yAmZjuMOMLSx1xa57NOVsssbyYZreBC/view?usp=sharing

Crash log here: https://pastebin.com/P00uwWg3

Mod list:
Forge 36.1.31
WorldEdit 7.2.5+57d5C9
CCL: 4.0.2.427
CBMultipart: 3.0.1.115
CBMicroblock: 3.0.1.115
ProjectRed-Core: 4.1.0-beta-38
ProjectRed-Transmission: 4.1.0-beta-38
ProjectRed-Exploration: 4.1.0-beta-38
ProjectRed-Integration: 4.1.0-beta-38
ProjectRed-Illumintaion: 4.1.0-beta-38

P.S pls sry my language and grammatic mistakes, I used a google translate in some places in this text

![2021-07-10_18 10 43](https://user-images.githubusercontent.com/56804640/125168120-7ba57e80-e1ac-11eb-8d6a-e9ee32b554f8.png)
![2021-07-10_18 10 51](https://user-images.githubusercontent.com/56804640/125168124-7ea06f00-e1ac-11eb-8468-a50cf7293b0a.png)
![2021-07-10_18 10 17](https://user-images.githubusercontent.com/56804640/125168127-8233f600-e1ac-11eb-99eb-b531dcfd68c1.png)
![2021-07-10_18 10 24](https://user-images.githubusercontent.com/56804640/125168132-8829d700-e1ac-11eb-917b-f1e06dadf540.png)
![2021-07-10_18 10 30](https://user-images.githubusercontent.com/56804640/125168137-8c55f480-e1ac-11eb-86a3-ed3986600357.png)

**Comment by covers1624** [comment]
I have literally just fixed this bug in CB Multipart :D
Grab it from Curse over here: https://www.curseforge.com/minecraft/mc-mods/cb-multipart/files/3383702

**Comment by anrej0705** [comment]
Thanks for your hard work ^^
