### ISSUE TITLE
Using ProjectRed for 1.16.5 and scorge version 3.1.3 (for Minecraft 1.16.x) results in a InvocationTargetException.

### ISSUE THREAD

**Issue by Contrean** [MrTJP/ProjectRed#1654]
**Describe the bug**
My friend and I tried to install Project Red 1.16.5 (beta) on a Forge Server. When starting the Server we first get this warning:
`[19:13:11] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: /home/container/mods/MrTJPCore-1.12.2-2.1.4.43-universal.jar is missing mods.toml file
[19:13:11] [main/WARN] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File /home/container/mods/MrTJPCore-1.12.2-2.1.4.43-universal.jar has been ignored - it is invalid`
and after this the error
`[19:13:20] [main/FATAL] [Loading/]: Unable to load ScorgeModContainer, wat?
java.lang.reflect.InvocationTargetException: null`

I've researched and found this:
https://githubmemory.com/repo/MinecraftForge/Scorge/issues/11

But I have no idea how to use this 'fix' on this problem.

**Crash Log**
https://pastebin.com/FsV2C6BU

**Versions**
* Scorge Version: 3.1.3
* CCL Version: 1.16.5-4.0.2.427
* FMP Version: 1.16.5-3.0.2.119
* MrTJPCore Version: 1.12.2-2.1.4.43 (yes 1.12.2, it's the newest on curseforge)
* ProjectRed Version: 1.16.5-4.10.0-beta-44

**Comment by ArcanoxDragon** [comment]
`/home/container/mods/MrTJPCore-1.12.2-2.1.4.43-universal.jar has been ignored`

it looks like you're trying to load a 1.12.2 mod on 1.16.5, which doesn't work...try removing that mod jar and see if it fixes the crash

**Comment by Contrean** [comment]
Well that is MrTJPCore, which according to Curseforge Project Red needs. I have removed it, but nothing changed, except for that the warning doesn't show anymore.

**Comment by Contrean** [comment]
I apologize for taking your time, my friend for what ever reason used the wrong scorge version (3.1.2 instead of 3.1.3) but told me used the correct one. Good day, night or what ever fits for you and again, sorry.

**Comment by MrTJP** [comment]
The issue was that you’re using a 1.12 version of MrTJPCore, which is no longer required for Minecraft 1.15+
