### ISSUE TITLE
[1.16.5] Textures of Wires and Logic Gates are glitching

### ISSUE THREAD

**Issue by DcZipPL** [MrTJP/ProjectRed#1658]
**Describe the bug**
Textures of Wires and Logic Gates are glitching when optifine installed. Camera movement changes textures of them.

**To Reproduce**
1. Install Optifine (also Optiforge)
2. Place any of wire (crafted with wool) or logic gate
3. See the problem

**Expected behavior**
See normal non-bugged models/textures

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.2.427
* Forge Version: 36.1.62
* ProjectRed Version: 4.10.0-beta-44

**Screenshots/Videos**
![Screenshot 2021-07-21 224219](https://user-images.githubusercontent.com/31044091/126557435-d30a6a4c-f2ff-42a9-b5ed-c35ea058dc3f.png)
![Screenshot 2021-07-21 224832](https://user-images.githubusercontent.com/31044091/126558155-6a1b2df3-21e3-4733-89e7-ae760773d33a.png)

**Comment by MrTJP** [comment]
Does this only happen with Optifine/Optiforge installed?
