### ISSUE TITLE
ProjectRed (4.10.0-beta-46) modules claim to need CodeChickenLib 4.0.2.429, but no such animal.

### ISSUE THREAD

**Issue by JillSwift** [MrTJP/ProjectRed#1660]
Re: Minecraft 1.16.5, Forge 36.1.65

ProjectRed (4.10.0-beta-46) modules claim to need CodeChickenLib 4.0.2.429, but no such animal.
Installed CodeChickenLib is version 4.0.2.427, and that's the latest version available on CurseForge.

Update ProjectRed to 4.10.0-beta-46 (from beta-44)
Start Minecraft. Boom. There it is!

Thanks for the marvelous mods!

**Comment by aaronhowser1** [comment]
"No such animal"? lol

but yeah, having this problem too:
![image](https://user-images.githubusercontent.com/15698722/126757666-156cba1e-4123-493b-a37e-8f91213bf859.png)

**Comment by MrTJP** [comment]
Whoops, fixing...

**Comment by MrTJP** [comment]
CCL 4.0.2.429 is now available on Curse.

**Comment by JillSwift** [comment]
Love ya MrTJP
