### ISSUE TITLE
[1.16.5] Lamps crash on removal if using shaders

### ISSUE THREAD

**Issue by seancrain** [MrTJP/ProjectRed#1664]
**Describe the bug**
If you try to remove a lamp while also running shaders, the game will crash.

**To Reproduce**
1. Make sure you have a shader enabled other than the internal one
2. Put lamp down in world
3. Attempt to remove said lamp
4. Game crash

**Expected behavior**
The game should just remove the lamp like a normal block removal. OptiFine's presence has no effect on placement when shaders are not enabled, everything works as it should. Even while shaders are enabled, the blocks can be used normally. They interact with redstone correctly, and they can be turned on and off. The only thing you can't do is remove them. I've tried to WorldEdit them as well as manually remove them by hand, but the end result is the same.

**Crash Log**
https://www.nosiphus.com/minecraft/crash-reports/crash-2021-08-03_09.51.59-client.txt

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.2.429
* CBMP Version: 1.16.5-3.0.2.119
* ProjectRed Version: 1.16.5-4.10.0

**Comment by covers1624** [comment]
Optifine is not supported.

Optifine is attempting to render the block after it has been removed, there is absolutely nothing that can be done ProjectRed side to resolve this.
