### ISSUE TITLE
game crash when I put the glowing white block in the Applied Energistics mod's annihilation plate

### ISSUE THREAD

**Issue by KiraLinux** [MrTJP/ProjectRed#1665]
I took the white block of the lamp in my hands and put it on the annihilation plate 

**Crash Log**
https://pastebin.com/UtzdTsv0

a piece of text from the latest logs file
https://pastebin.com/RtTUCqBD

after uninstalling the optfine mod everything works, almost everything works
the annihilation plate destroys this block and does not take it to its storage in the AE system

https://pastebin.com/rn8p6j3d

1.16.5-forge-36.2.0
ProjectRed-1.16.5-4.10.0-illumination
ProjectRed-1.16.5-4.10.0-core
CBMultipart-1.16.5-3.0.2.119-universal
appliedenergistics2-8.4.0
OptiFine_1.16.5_HD_U_G8

**Comment by covers1624** [comment]
Optifine is not supported.

**Comment by KiraLinux** [comment]
ты читать умеешь?
я провел пример что не работает и без OptiFine
