### ISSUE TITLE
Без OptiFine когда я поставил белый блок лампы на пластину аннигиляции appliedenergistics она его уничтожила на совсем

### ISSUE THREAD

**Issue by KiraLinux** [MrTJP/ProjectRed#1666]
АЕ сожрала блок и нет его в системе хранения, то данный блок уничтожается на совсем

журнал работы игры без OptiFine 
https://pastebin.com/rn8p6j3d

1.16.5-forge-36.2.0
ProjectRed-1.16.5-4.10.0-illumination
ProjectRed-1.16.5-4.10.0-core
CBMultipart-1.16.5-3.0.2.119-universal
appliedenergistics2-8.4.0

**Comment by anrej0705** [comment]
я бы тебе посоветовал добавить перевод на английский так как разраб русский не знает и будет переводить через гугл и что в итоге произойдет с твоим текстом никто не знает

**Comment by KiraLinux** [comment]
> я бы тебе посоветовал добавить перевод на английский так как разраб русский не знает и будет переводить через гугл и что в итоге произойдет с твоим текстом никто не знает

Я ему написал по английски и сделал логи работы игры с и без оптифайна и что я получил в ответ? закрытие вопроса и сказал что оптифайн не поддерживается 
ему просто лень было прочитать до конца

**Comment by anrej0705** [comment]
у него некоторые моды с оптифайном не дружат, у меня тоже глюки начинаются когда возвращаю оптифайн
тут надо ждать фикса одного из разрабов
