### ISSUE TITLE
Rendering Block Entity (Inverted Pink Lamp)

### ISSUE THREAD

**Issue by stachurr** [MrTJP/ProjectRed#1669]
**Describe the bug**
Destroying an existing Inverted Pink Lamp causes the client to crash. _This was only tested in creative._ I suspect this happens with any Inverted Lamp.
- Description: Rendering Block Entity

**To Reproduce**
1. Place Inverted Pink Lamp
2. Break it

**Expected behavior**
The block should break with no error/crash.

**Crash Log**
Error: _java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}_

[FULL LOG](https://pastebin.com/uc074pZ3)

**Versions**
Dependencies:
* CCL Version: 1.16.5-3.0.2.119-universal
* FMP Version: 1.16.5-forge-36.2.0
* ProjectRed Version: 1.16.5-4.10.0-beta-46 (core, exploration, illumination, integration, transmission)
* Scorge Version: 3.1.3

Additional:
* JEI Version: 1.16.5-7.7.1.116
* OptiFine Version: 1.16.5_HD_U_G8

**Comment by stachurr** [comment]
I discovered the bug does not occur when OptiFine is removed.

**Comment by MrTJP** [comment]
Unfortunately, Optifine is not supported. You’ll either have to remove it, or perhaps report this issue to them.
