### ISSUE TITLE
CTD When interacting with timer (1.16.5) (Enigmatica 6)

### ISSUE THREAD

**Issue by KindarConrath** [MrTJP/ProjectRed#1672]
**Describe the bug**
When right clicking on a timer, the game crashes to desktop.

**To Reproduce**
1. place a timer
2. right click on timer

**Expected behavior**
Timer GUI should open up

**Crash Log**
https://pastebin.com/gWYptk0N

**Versions**
* CCL Version: CodeChickenLib-1.16.5-4.0.2.429-universal.jar
* FMP Version: CBMultipart-1.16.5-3.0.2.119-universal.jar
* MrTJPCore Version: ProjectRed-1.16.5-4.10.0-core.jar
* ProjectRed Version: ProjectRed-1.16.5-4.10.0-integration.jar
* Pack: Enigmatica 6 (0.5.11) (MC1.16.5) 
* Extras: tombstone-1.16.5-6.5.1.jar|Corail Tombstone

**Comment by djmattyg007** [comment]
I just encountered this crash when using 4.11.0-beta6, also in Enigmatica 6 (0.5.21).

**Comment by djmattyg007** [comment]
Could be related to this?
https://github.com/BrassGoggledCoders/Transport/issues/46

**Comment by Ticker175** [comment]
> Could be related to this? [BrassGoggledCoders/Transport#46](https://github.com/BrassGoggledCoders/Transport/issues/46)

I would assume so as ive had the same issue in this pack and my own modified valhesia 3 pack
both contain transport and projectred and have the exact same crash
