### ISSUE TITLE
Version check fails

### ISSUE THREAD

**Issue by KastenKlicker** [MrTJP/ProjectRed#1673]
**Describe the bug**
Start client or server. The version check fails for all ProjectRed mods (FileNotFoundException).

**To Reproduce**
1. Start client or server (forge-36.2.2)
2. Look into the logs and see how FileNotFoundException is thrown

**Expected behavior**
Check the version successfully, I guess.

**Crash Log**
[Crash log](https://gist.github.com/KastenKlicker/b7f69917050eaad66cf352dd8015a4cf)

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.3.433
* FMP Version: ???
* MrTJPCore Version: ---
* ProjectRed Version: 1.16.5-4.10.0

**Screenshots/Videos**
---

**Comment by MrTJP** [comment]
We have not set up the backend for this version check yet, but will soon. It does not actually crash the game right?

**Comment by MrTJP** [comment]
Confirmed, this does not actually crash. The version checker will work once the backend is set up, so this is not an issue.

**Comment by KastenKlicker** [comment]
I just comment the version checks line out, so it's easy to add them again. It's very annoying if you are hosting a server with many mods and there are errors without "any" meaning.
