### ISSUE TITLE
Heavy Z-Fighting with 7-seg display

### ISSUE THREAD

**Issue by dojoman500** [MrTJP/ProjectRed#1675]
Chances are you won't make another update but if you do i have noticed the 7-seg display has Z-fights with the bundled cable on the gate, And its not minor i mean the ENTIRE display fights. A fix would be nice.

**Comment by MrTJP** [comment]
Tried placing the gate with all sorts of different orientations and cannot find any z-fighting. What versions are you running?

**Comment by MrTJP** [comment]
Re-open if you have more details to add. I cant repro this issue.

**Comment by dojoman500** [comment]
Sorry for the long delay, I didn't get any notifications about a response, The version I noticed it on was MC 1.12.2 project red modules from version 4.9.4.120, I am attaching some screenshots to show more: 
![image](https://user-images.githubusercontent.com/60892219/144721233-717774dd-b9a3-4176-bc0c-f8d853d81edf.png)
![image](https://user-images.githubusercontent.com/60892219/144721243-6c634cf4-a2ca-45e9-924a-5cd11499048a.png)
I have not ran a new version as of now _mostly because I am stuck in the past and prefer 1.12.2_ so I am unsure if this was fixed in newer versions
