### ISSUE TITLE
PR 4.11.0-beta-0 wants cb_multipart => 3.0.2.120

### ISSUE THREAD

**Issue by zISKo666** [MrTJP/ProjectRed#1677]
PR 4.11.0-beta-0 wants cb_multipart => 3.0.2.120 but only 3.0.2.119 is available.

cheers
zISKo

**Comment by MrTJP** [comment]
Whoops. Will have @covers1624 push it to curse asap

**Comment by zISKo666** [comment]
Hehe, that can happen :)

**Comment by MrTJP** [comment]
Done. Should be available on Curse once the file is approved.
