### ISSUE TITLE
Inverted lamps can crash the game (1.16.5)

### ISSUE THREAD

**Issue by Lordmau5** [MrTJP/ProjectRed#1684]
**Describe the bug**
For whatever reason the inverted lamps are causing crashes every now and then with some "BooleanProperty" checks that fail because the block in it's position appears to be `minecraft:void_air`?

**To Reproduce**
1. Place Inverted Lamp blocks
2. ... Wait? I have no idea how to best reproduce this...
3. Have the game crash with the attached crash-log

**Expected behavior**
I expect my game **not** to crash.

**Crash Log**
https://paste.ee/p/z6QvI

**Versions**
* CCL Version: 1.16.5-4.0.3.434-universal
* FMP Version: 1.16.5-3.0.2.120-universal
* MrTJPCore Version: N/A (1.16.5)
* ProjectRed Version: 1.16.5-4.11.0-beta-0

**Screenshots/Videos**
N/A

**Comment by Tander** [comment]
Another crash report from Above and Beyond modpack

https://paste.gg/p/anonymous/579ab06c3a99401db9c67594b8a56280

**Comment by legitswitch** [comment]
Does this crash servers or just the person's game?

**Comment by Lordmau5** [comment]
For me it only crashed my client, but it was a hard crash meaning I needed to restart the game

**Comment by MrTJP** [comment]
Hmm. Are tile entity renderers not allowed to base rendering on the corresponding block state at the tile's position? Lamps don't actually store their light state, they just check to see if the block in world has the `LIT` property set true.
