### ISSUE TITLE
Project Red Crashes on Startup (1.12.2)

### ISSUE THREAD

**Issue by willcaddy** [MrTJP/ProjectRed#1685]
**Describe the bug**
The game crashes after a few seconds on startup with an error message saying that it failed to start becuase of multiple Project Red modules. Seems to be a relocation API looking at the crash report. 

**To Reproduce**
1: Install all the modules from the curseforge client
(I made sure that the suggested api's and library's were also installed, however Scourge doesn't appear to be available for 1.12)
2: Run the game as normal. 

**Expected behavior**
Game runs and loads correctly.

**Crash Log**
https://pastebin.com/56ydBMPV

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.12.2-3.2.3.358-universal
* FMP Version: 1.12.2-2.6.2.83-universal
* MrTJPCore Version: 1.12.2-2.1.4.43-universal
* ProjectRed Version: 1.12.2-4.9.4.120 (all modules)

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/5645701/137786172-c886c8f9-8ab2-4a95-90fe-b440430b73e9.png)

**Comment by MrTJP** [comment]
Looks like you are running some other mod that has decided to build in an older and incompatible version of ProjectRed's api. You'll have to find it by uninstalling mods until the doesn't crash anymore. 

You may want to uninstall everything else just to make sure the game loads before you spend time trying to find the exact mod, just in case I'm wrong.
