### ISSUE TITLE
[Bug] 1.16.5 Project Red Integration Scala match error while rendering item in Refined Storage pattern

### ISSUE THREAD

**Issue by Raidobw2** [MrTJP/ProjectRed#1686]
**Describe the bug**
Some of the ProjectRed Integration item icons when rendered by a refined storage pattern seem to crash the game.
Modpack: FTB OceanBlock 1.3.0.
Using a refined storage pattern grid, make a pattern of a ProjectRed Integration Timer and make the item icon appear such as by holding shift or putting the pattern into a crafter.
Scala match error while rendering item.

**To Reproduce**
1. Download OceanBlock 1.3.0 with files `refinedstorage-1.9.15.jar` and `ProjectRed-1.16.5-4.11.0-beta-0-integration.jar`.
2. Setup a basic RS system.
3. Make a Timer pattern from ProjectRed for example.
4. Look at pattern by pressing Shift = crash.

**Expected behavior**
To not crash when looking at the pattern.

**Crash Log**
https://paste.feed-the-beast.com/view/d31fd56e

**Versions**
Latest version for 1.16.5.

* CCL Version: N/A
* FMP Version: N/A
* MrTJPCore Version: N/A
* ProjectRed Version: ProjectRed-1.16.5-4.11.0-beta-0-integration.jar

**Additional information**
Already filed another report on Refined Storage's issue tracker, but they said the error is on your side.
refinedmods/refinedstorage#3110

> Bug in project red. It assumes everything that will render it is a gate item

**Comment by Raidobw2** [comment]
Please do what you feel is needed, I will go back towards RS as well. Thank you very much for your reply on their end and here as well!

**Comment by VorpalLemur** [comment]
Am playing Oceanblock 1.8.0 and this issue has crashed my game a half dozen times so far.  Glad it's been reported.

**Comment by MrTJP** [comment]
Will be fixing this, but the real issue is the invalid itemstack that refined storage is trying to render. 

Fix will prevent crash but rendering of the item will still be broken.
