### ISSUE TITLE
Lamps light room regardless of redstone signal with optifine?

### ISSUE THREAD

**Issue by E-daw** [MrTJP/ProjectRed#1690]
Whenever I place down any lamp block, regardless of power or not, it lights the entire room. When I re-log and the lamp was off, there will be no light in the room unless the block is updated. If I re-log and the lamp is on, the light will still be there when I log back in. 

When dynamic lights are enabled the lamp will emit light in hand unlike a vanilla redstone lamp

 There are no crashes or instability issues.

![2021-10-31_03 46 59](https://user-images.githubusercontent.com/34014927/139575284-2f799d3e-ad0c-4aab-9cc2-d59324605640.png)
![2021-10-31_03 46 08](https://user-images.githubusercontent.com/34014927/139575286-7e4bc663-9e9d-49d3-98d6-f306448627e6.png)

Here's my mod list

![image](https://user-images.githubusercontent.com/34014927/139575444-6fa947cc-80a0-4e0f-be5b-72706bb9917b.png)

Removing optifine does fix the issue

**Comment by covers1624** [comment]
This is not a bug in ProjectRed, this is a bug in Optifine.
