### ISSUE TITLE
Project Red: Integration - Gui Crash

### ISSUE THREAD

**Issue by daneleo** [MrTJP/ProjectRed#1691]
**Describe the bug**
When placing down a timer or anything with a GUI when you right click it crashes the game in multiplayer, tested multiple times in my server 

**To Reproduce**
Steps to reproduce the behaviour:
1)Place anything with a GUI(Timer etc)
2)Right click it to edit configuration
3) crash to desktop

**Expected behaviour**
the GUI should open up to increase or decrease the time

**Crash Log**
*Required for crash.* **DO NOT** paste the entire crash log here. Use pastebin or similar. 
In minecraft launcher:
`The game crashed whilst rendering screen
Error: java.lang.UnsupportedOperationException: Unable to construct this menu by type
Exit Code: -1`

Full Crash Log:
https://pastebin.com/yRkjXz8p

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.3.434-universal
* FMP Version: 1.16.5
* MrTJPCore Version: Cant find 1.16 version
* ProjectRed Version: 1.16.5-4.10.0

**Comment by covers1624** [comment]
Please do not provide excerpts or trimmed-down Crash reports. The data in the report exists for a reason.

```
	at xyz.brassgoggledcoders.transport.screen.ModularScreenInfo.matches(ModularScreenInfo.java:49) ~[?:1.16.5-3.7.0] 
	at xyz.brassgoggledcoders.transport.event.ClientForgeEventHandler.renderModuleTabs(ClientForgeEventHandler.java:68) ~[?:1.16.5-3.7.0]
```

This is the mod responsible. Please report the issue to them.
