### ISSUE TITLE
[1.16.5] Multimeter not working

### ISSUE THREAD

**Issue by dkja** [MrTJP/ProjectRed#1695]
**Describe the bug**

When I click right mouse button on alloy wire nothing happens. Similar to other issue #1169 (show video).

Game output error: [minecraft/ClientPlayNetHandler]: Unknown custom packet identifier: mrtjpcore:network.

**To Reproduce**
1. In game: build alloy wire and click right mouse button on it using multimeter.
2. Game outputs shows error, furthermore nothing happens. 

**Expected behavior**
After click will display intensity of the redstone signal at the selected point of the wire for three seconds. 

**Versions**
* ProjectRed Version: 4.10.0
* minecraft 1.16.5

**Screenshots/Videos**
Similar as: https://youtu.be/JwZGB5KohT0?t=29

**Comment by dkja** [comment]
I am looking at the code and... wtf  o.O  if it has not been implemented ???

**Comment by MrTJP** [comment]
Not implemented, and is to be replaced at some point.
