### ISSUE TITLE
More info regarding 7-seg display z-fighting

### ISSUE THREAD

**Issue by dojoman500** [MrTJP/ProjectRed#1701]
Continuation in regards to issue "Heavy Z-Fighting with 7-seg display #1675"

Sorry for the long delay, I didn't get any notifications about a response, The version I noticed it on was MC 1.12.2 project red modules from version 4.9.4.120, I am attaching some screenshots to show more:
![image](https://user-images.githubusercontent.com/60892219/144721324-08296dcb-3a2e-496d-af1c-4338314f03a0.png)
![image](https://user-images.githubusercontent.com/60892219/144721329-2188e50e-a66e-44a2-bd74-76f7840566a6.png)
I have not ran a new version as of now _mostly because I am stuck in the past and prefer 1.12.2_ so I am unsure if this was fixed in newer versions

**Comment by dojoman500** [comment]
A few more screenshots and some more reliable ways to contact me:
![image](https://user-images.githubusercontent.com/60892219/144721429-14ec1362-7bc6-475b-b5b2-14ed7da3ef7e.png)
![image](https://user-images.githubusercontent.com/60892219/144721437-a83d98c9-f403-4ac9-9fc8-2f5af468be59.png)
![image](https://user-images.githubusercontent.com/60892219/144721443-fa4c641b-b192-461a-944a-022658b1a93d.png)
You can contact me through discord, Username is Dojoman500#4947

**Comment by MrTJP** [comment]
Thanks for the screenshots. Looks like this was caused by a bug that has already been fixed. Can't remember when, but it is for sure working in 1.16 (possibly 1.15 as well). Unfortunately, your only solution would be to update MC to 1.15 or 1.16.
