### ISSUE TITLE
NOT Gate - Refined Storage Pattern crushes the game

### ISSUE THREAD

**Issue by KeremKoksal** [MrTJP/ProjectRed#1702]
FTB OceanBlock 1.9.0 modpack has the following mods;
ProjectRed-1.16.5-4.11.0-beta-0-core.jar
ProjectRed-1.16.5-4.11.0-beta-0-illumination.jar
ProjectRed-1.16.5-4.11.0-beta-0-integration.jar
ProjectRed-1.16.5-4.11.0-beta-0-transmission.jar

I have created a refined storage pattern for NOT gate. Refined storage patterns show the item of the reciepe when clicking shift. But when I clicked shift, I got following error.

The game crashed whilst rendering item
Error: scala.MatchError: pattern (of class com.refinedmods.refinedstorage.item.PatternItem)
Exit code: -1

Also, "12x Red Alloy Wire" pattern doesn't render in the crafter but doesn't crush.

If it has been fixed with a later version than 4.11, please ignore this report.

Thank you for the great mods,
Cheers

**Comment by MrTJP** [comment]
Can you try with the latest beta that I uploaded last week? I’m pretty sure I fixed this

**Comment by MrTJP** [comment]
Closing because this has been fixed, and also Refined Storage should not be passing unknown items into another mod's item renderer.
