### ISSUE TITLE
Tconstruct compatibility issue

### ISSUE THREAD

**Issue by yeetdameat** [MrTJP/ProjectRed#1703]
**Describe the bug**
Looking at any object added by PR while having the newest version of tconstruct installed causes a crash. The game otherwise works with older versions of tconstruct.

**To Reproduce**
1. download the newest version of tconstruct
2. look at an object from PR

**Crash Log**
https://pastebin.com/SWyzn7Sf

**Versions**
* CCL Version: 4.0.4.435
* FMP Version: 1.16.5-3.0.3.122
* MrTJPCore Version: 1.16.5-4.10.0
* ProjectRed Version: 1.16.5-4.10.0
* tconstruct 3.3.0.308 for 1.16.5

**Comment by covers1624** [comment]
This is a bug in CCL: https://github.com/TheCBProject/CodeChickenLib/issues/384
