### ISSUE TITLE
Comparators not updating on inventory status change of droppers or hoppers.  (#1186 ?)

### ISSUE THREAD

**Issue by VorpalLemur** [MrTJP/ProjectRed#1705]
**Describe the bug**
Comparators don't seem to update correctly on inventory status changes when reading droppers or hoppers, while they do seem to work with vanilla chests.  May apply to other inventories, droppers and hoppers are just the ones I tested with.

This seems similar to [bug 1186](https://github.com/MrTJP/ProjectRed/issues/1186) which was marked as resolved by a tester who verified it worked with vanilla chests. 

(issue encountered in the Create Above & Beyond modpack)

**To Reproduce**
1. Hook a comparator up to read the inventory level of a dropper or hopper.    Hook a vanilla comparator up to the same block for comparison.
2. Change the inventory level of the block... note that the vanilla comparator reacts, while the projectred one does not.
3. In some instances I noticed the comparator suddenly did give a reading... it changed, but it didn't continue to react to inventory changes.  Seemed to update when I placed a redstone dust or wire next to it.  In no case was I able to get it to continuously update like a vanilla comparator.

**Expected behavior**
Projectred comparator reacts in real-time to changes in inventory status of the block its monitoring, just like vanilla comparator.

**Crash Log**
*Required for crash.* **DO NOT** paste the entire crash log here. Use pastebin or similar. 

**Versions**

(sorry, I'm unable to resolve some of these names by looking at my mods list.   I'm using the Create: Above & Beyond modpack (version 1.3.0))

* CCL Version:   1.16.5-4.0.5.438
* FMP Version:   unknown?
* MrTJPCore Version:  unknown?
* ProjectRed Version: 1.16.5-4.11.0-beta-6

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

**Comment by djmattyg007** [comment]
I'm experiencing a similar issue with the ProjectRed comparator working with the Factory Hopper from the Engineer's Decor mod. I'm playing the Enigmatica 6 modpack, where I've manually added Project Red.
