### ISSUE TITLE
Bug with lamps

### ISSUE THREAD

**Issue by nezna7787** [MrTJP/ProjectRed#1706]
Describe the bug
I use optifine and project red and I noticed when I wanted to use lamps from project red but when I wanted to use them they lit even without redstone. i know it does optifine but i can't remove it since my computer is very weak so i don't know what to do.

Crash Log
no crash

Versions
* CCL Version:1.16.5-4.0.5.438
* ProjectRed Version:1.16.5-4.10.0
* Optifine version:OptiFine_1.16.5_HD_U_G8 
![Screenshot_2](https://user-images.githubusercontent.com/97002549/147947427-2e4e3337-c3a0-4fc7-b61e-123afc597bfb.png)

Screenshots/Videos

**Comment by MrTJP** [comment]
If the issue occurs only with optifine, then you have to remove it. It’s the only solution.
