### ISSUE TITLE
Lamps do not drop. They are destroyed with any tool.

### ISSUE THREAD

**Issue by ShibeTemple** [MrTJP/ProjectRed#1707]
**Describe the bug**
When breaking a lamp, it gets destroyed. Additionally, wrenches and screwdrivers do nothing even when right-clicking or shift right-clicking.

**To Reproduce**
1. Break lamp with any tool including fists, screwdriver, or wrench.
2. Block breaks and does not drop.

**Expected behavior**
Block drops its corresponding item.

**Versions**
CBMultipart-1.16.5-3.0.3.122
CodeChickenLib-1.16.5-4.0.5.438
ProjectRed-1.16.5-4.10.0
Forge 36.2.20

**Comment by MrTJP** [comment]
This was fixed in 4.11.0-beta-6 (dfa3d5fd3180fc1d0be1d6e55eaf0ba9f9c260a5)
