### ISSUE TITLE
Bus Converters off by one

### ISSUE THREAD

**Issue by TaeoG** [MrTJP/ProjectRed#1709]
**Describe the bug**
Bus converters, when converting from analog to a bundled cable, are off by one

**To Reproduce**
1. Place two Bus converters with any length of bundled cable between them, even 0
2. Configure one to be a DAC, the other an ADC
3. Connect a red alloy wire or insulated wire to the ADC side, it must be at least length 2
4. Connect something to both converters to read their input and output on their respective analog side, I tried both the nixie tubes from Create and the analog voltmeter from Gauges and Switches
5. Give different input strengths and observe the output strength

**Expected behavior**
The output strength from the Digital to Analog bus should be the same as the input strength into the Analog to digital bus, and it is as long as the length of cable on the input side is <2. 

**Crash Log**
N/A

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5 4.0.4.435
* FMP Version: CBMultipart 1.16.5 3.0.3.122
* MrTJPCore Version: N/A
* ProjectRed Version: 1.16.5 4.11.0 beta 6

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.
![2022-01-07_23 15 37](https://user-images.githubusercontent.com/641633/148633886-d1abfa72-d4db-46eb-b4dc-c445476bb43b.png)
![2022-01-07_23 15 57](https://user-images.githubusercontent.com/641633/148633888-d2540cd1-6f90-4a30-9613-720435170296.png)

**Comment by BallOfEnergy1** [comment]
As the Redstone Signal Travels, It Loses One Redstone Power Every Block. This Explains Why It Would Be 1 Off.

**Comment by MrTJP** [comment]
Sorry for late reply. This is definitely a bug. The bus converter gate should be mapping all redwire signals 238 to 255 to full level 15 analog redstone signals, rather than only 255. Fixing...
