### ISSUE TITLE
Project Red - Transmission - Unable to Craft Colored Bundle Cable

### ISSUE THREAD

**Issue by DomanoSV** [MrTJP/ProjectRed#1713]
**Describe the bug**
I seem to have and issue with Project Red Transmission, I am running All the Mod 6 modpack, however I have been able to replicate the issue on a fresh instance with only the Project Red Mods. The recipe for colored bundle cable is not working correctly as I can't seem to progress from colored insulated wire to colored bundle cable. I can craft non-colored bundle cable just fine with 5 colored insulated wire and 4 string. However when trying to craft colored bundle cable from non-colored bundle cable and a dye color, the recipe is missing. I have checked Project Red github as well for issues relating to this and it appears that there is no mention of anything. There is no record of an issue on the ATM6 github either.

I also want to make a note, for future reference. There seems to be a bug with Project Red and Refined storage. When using patterns for auto crafting items from project red, they do not show up in the inventory when holding shift or they are not visible when placed in a crafter. There was a issue on the Project Red Github that could relate to this, which would make it mod related. If thats the case I just wanted to make a record of it so people were aware.

**To Reproduce**
1. Try to craft Colored bundle cable from 1 bundled cable and a dye. No recipe output.
2. Can craft colored bundle cable from other colored bundle cable with the desired color dye.

As stated, in survival there is no progression from Colored Insulated Wire to Colored Bundle Cable as I need to beable to craft from plain bundled cable.

**Expected behavior**
Be able to craft colored bundle cable from un-colored bundle cable.

**Crash Log**
N/a

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* Forge Version: 1.16.5-forge-36.2.22
* CCL Version: 1.16.5-4.0.6.443
* CBMultipart Version: 1.16.5-3.0.3.122
* MrTJPCore Version: N/a ? for versions after 1.12 is that correct?
* ProjectRed Version: 1.16.5-4.11.0

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

![Screenshot](https://user-images.githubusercontent.com/1592287/151745292-41f25e42-db3b-420d-97ee-32a698c59dd4.png)

I even tried the recipe listed here https://projectredwiki.com/wiki/Bundled_Cable

![Untitled](https://user-images.githubusercontent.com/1592287/151746054-9c6e3e6b-3050-4305-a5b9-ab3486970721.png)

As you can see you can change the color of bundled cable perfectly fine.

![Screenshot 2022-01-31 160118](https://user-images.githubusercontent.com/1592287/151746228-01a4e242-c9c0-42ea-bd60-05fbe618c987.png)

**Comment by oliverhunt19** [comment]
I also have this same issue in not being able to craft any coloured bundled cable

**Comment by MrTJP** [comment]
Thanks for the detailed report. Seems like the uncoloured bundled cable was left out of the recipe list. Fixing now...
