### ISSUE TITLE
[Crash Report] 1.16.5 Project Red mods cause crash on startup, fail to get version check

### ISSUE THREAD

**Issue by theLadyStardust** [MrTJP/ProjectRed#1725]
Basically title. When launched, freezes near end of mod loading. [Startup log](https://www.toptal.com/developers/hastebin/uyehizenif.yaml), removed Project Red mods, and launched as normal. Seems to be an issue with the version manifest at https://version-check.covers1624.net/check/?mod=ProjectRed&mc=1.16.5

**Comment by MrTJP** [comment]
The version check is expected to fail but does not cause the freeze in the mod loading process. There's probably some other stuff below it that's the real issue. But looks like the link to the log is no longer working. If this is still an issue, please post the logs again and re-open this.
