### ISSUE TITLE
Please enlighten me 

### ISSUE THREAD

**Issue by Ezoteric** [MrTJP/ProjectRed#1726]
Pun intended.
So we just put this mod into our pack and noticed unlit lamps are lit and saw you blaming optifine for it as it works without.
But why is it that MCs lamp work without any problem so does Adrons and so does RedstoneLampsPlus.

So saying the solution would be removing optifine isnt correct, the solution would be you fixing what causes it as Cleary other mods dont have this problem?

Im not mad or anything im just stating facts and i love you ported this as the other mods like the bundled cables as they are very much appreciated, are mandatory and work great. 

So a lot of thanks for your hard work and i truly hope you can look into this and fix it.

**Comment by MrTJP** [comment]
Yea, so there are a million different ways to implement lamps and lights in minecraft. None of them are more "correct" than the other. Currently, the smaller lights are implemented as Multiparts so they can co-exist with wires, gates, etc within the same block space. The regular full block lamps are more standard. Additionally, I believe the glowing halo around lamps are unique to Project Red, and have been kinda difficult to nail down. Admittedly still needs some work.

While its expected that the Multipart lights would have a more difficult time playing nice with Optifine, the standard ones too may not work well. I'd love to fix this, but I simply cannot find the time for this at the moment. If someone who knows their way around Optifine can point out exactly what is causing the issues, I would be more than happy to fix it.
