### ISSUE TITLE
Graphical issue with Rubidium

### ISSUE THREAD

**Issue by KrauzeBartek** [MrTJP/ProjectRed#1727]
**Describe the bug**

**To Reproduce**
1. Instal Rubidium and ProjectRed on 1.16.5
2. Place something from ProjectRed

**Expected behavior**
Some graphical incompatibility with Rubidium. 

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: Last
* FMP Version: Last
* MrTJPCore Version: Last
* ProjectRed Version: 1.16.5 4.11.0

**Screenshots/Videos**

https://imgur.com/KmD5HHc

https://imgur.com/kc79bcY

**Comment by covers1624** [comment]
<Insert graphics performance mod here> is not supported. Period.

These mods change and break the render pipeline in unforeseen ways.

Do not expect any mod to provide support for these mods.
