### ISSUE TITLE
Mod loading error on Blackstone Block modpack

### ISSUE THREAD

**Issue by EverNev** [MrTJP/ProjectRed#1731]
**Describe the bug**
Mod loading error, not letting the modpack launch.
Completely unsure of what is causing the error, modpack version is Blackstone Block V1.0.2
Modpack launched fine as of yesterday but today its giving 2 mod loading errors including this mod and CBMultiPart
Already tried restarting pc, restarting launcher and checked the java version to make sure it was correct

**To Reproduce**
1. Install Blackstone Block V1.0.2

**Expected behavior**
Game launches normally

**Crash Log**
*Required for crash.* **DO NOT** paste the entire crash log here. Use pastebin or similar. 
https://pastebin.com/s6XbfciE

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.16.5-4.0.7.445
* FMP Version: 1.16.5-3.0.4.123
* MrTJPCore Version: not installed in the pack
* ProjectRed Version: 1.16.5-4.12.0

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

**Comment by MrTJP** [comment]
Seems to be an issue with Microblocks, presumably trying to create a part for one of the blocks in the Blackstone Block mod. 

@covers1624 ?

**Comment by covers1624** [comment]
This has nothing to do with creating parts.

Java 17 is not supported.

Use Java 8-15.
