### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by DJj123dj** [MrTJP/ProjectRed#1732]
*this isn't a bug*

Hey sorry that I disturb, but I would like to have this mod in version 1.18.2. Because i'm trying to work with the Create mod & Computercraft. They are on 1.18.2.

It would be cool if these modules were updated!
- core
- transmission
- illumination

I'm not mad if this doesn't happen, but i would really like that one of my favourite mods are on 1.18.2!

**Comment by DJj123dj** [comment]
i didn't find any discord servers, so i posted my question here

**Comment by MrTJP** [comment]
It will be updated for sure. Waiting on some dependencies first. CCL is available for 1.18 but I believe CBMP is still in development.
