### ISSUE TITLE
Render optimization of 3D objects

### ISSUE THREAD

**Issue by MrMarlain** [MrTJP/ProjectRed#1734]
During the construction of a large project, an unexpected problem arose. Due to the large number of logic elements, wires, buses, my map began to render poorly. FPS drops from 500+ to 25-30. I guess it has to do with 3d models.

I see a solution to the problem in creating a lite version of the mod, where almost all models will be replaced with sprite counterparts.

* MrTJPCore version: 1.16.5-4.12.0
* ProjectRed version: 1.16.5-4.12.0

![2022-08-28_01 01 23](https://user-images.githubusercontent.com/64688357/187042477-b88ab931-e438-4d78-93d7-4339796f2cb9.png)
![2022-08-28_01 01 15](https://user-images.githubusercontent.com/64688357/187042480-56faa441-cf38-468a-868c-d0c0b6f13a88.png)
![2022-08-28_01 01 46](https://user-images.githubusercontent.com/64688357/187042482-ed64153f-792b-4585-b3a0-00d69caa925d.png)

**Comment by MrTJP** [comment]
Maybe its block update related? Does it happen if you were to freeze your circuit (i.e. no more signal changes that would trigger block updates)?

**Comment by MrMarlain** [comment]
The circuit is designed in such a way that the block signals do not change in it, that is, in these screenshots, the static circuit.

> Maybe its block update related? Does it happen if you were to freeze your circuit (i.e. no more signal changes that would trigger block updates)?
