### ISSUE TITLE
Occasional crash with Project Table

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#1736]
**Describe the bug**
Reported over https://github.com/xJon/Tekkit-2/issues/29
> Sometimes while crafting using a project table, the game will crash. upon re-entering the world, one of the stacks in the project table's inventory will be dropped on the ground, while everything else will simply be gone. There is no discernable pattern to when this occurs.

**Crash Log**
https://mclo.gs/Q9vwKu6
I'm not sure whether this is caused by Placebo's `FastShapelessRecipe` or not, will try to troubleshoot!

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: `1.12.2-3.2.3.358`
* FMP Version: `1.12.2-2.6.2.83`
* MrTJPCore Version: `1.12.2-2.1.4.43`
* ProjectRed Version: `1.12.2-4.9.4.120`

**Comment by Rayzeq** [comment]
The 1.12 version is not supported anymore.
@MrTJP I think you should write in full caps "The 1.12 version IS NOT SUPPORTED" in the bug report template to be sure people see it

**Comment by xJon** [comment]
@Rayzeq That'd be quite unfortunate, considering tens of thousands of active players, but it's not a decision up to me

**Comment by Rayzeq** [comment]
@xJon I think MrTJP doesn't have much time to develop the mod (he's the only one developing it), so he chose to update it to the new versions rather than maintain the old ones. Also, he is completely rewriting the chip creation mod, which is probably a lot of work.

**Comment by xJon** [comment]
Further troubleshooting shows this is probably caused by an incompatibility with a different mod's optimization (Placebo's `FastShapelessRecipe`, which can be disabled). Closing!
