### ISSUE TITLE
Crash On Interaction With Levers and Microblocks

### ISSUE THREAD

**Issue by leumas1960** [MrTJP/ProjectRed#1740]
**Describe the bug**
Flipping the lever in the screenshots a few times causes a crash. Amount before it crashes varies. It seems to be an interaction with the cells specifically, or to do with the lever according to the report. Note: if you want a demonstration of the bug, and the build it's happening on, message me through the redstone army discord server.

The problem seems to be caused by too many wires looping back at once.

**To Reproduce**
Hard to tell how to reproduce, but seems that a crash tends to happen more often when you connect many cables, and I'm using several in this build.

**Expected behavior**
Lever turning on 7 different colors through 7 different bundles doesn't lag then crash the game after a few flips.

**Crash Log**
[https://pastebin.com/5d1amw75]

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* Scourge 3.1.3
* FMP 3.0.4.123
* Project Red Core 4.12.0 (I have full set, all same version)
* CodeChickenLib 4.0.7.445

**Screenshots/Videos**
![2022-09-29_16 20 54](https://user-images.githubusercontent.com/27988312/193145891-8fc4fe45-116f-4db3-b472-a76e7d91739e.png)
![2022-09-29_16 20 57](https://user-images.githubusercontent.com/27988312/193145904-3cc67a42-8ae9-46ef-894a-9ea6048d13f0.png)

**Comment by MrTJP** [comment]
Crash log indicates this is an issue with placement conversion, the mechanism that takes normal Minecraft blocks and converts them into multipart blocks (such as when you place multiple torches in the same block space). A lot of that logic has been reworked in https://github.com/TheCBProject/CBMultipart/commit/ee4de5337c994f4b47b21c82e10ca60093366ede. It most likely fixes this issue.
