### ISSUE TITLE
Logic gates and circuts

### ISSUE THREAD

**Issue by Alina-crng** [MrTJP/ProjectRed#1742]
Hello. I tried to build 16bit computer using project red, but ran into a problem.
Circuts, logic gates and bus transceivers started to change outputs/inputs randomly(even icons in inventory sometimes). At first it was just visual problem, but later it affected their work. Can i fix this by changing versions, settings or something like that? Or it's mod problem?
Mods:
All project red 1.12.2
Structurize 1.12.2
Here is a video with this bug. (Circut is static, so it shouldn't change, but it does. Replacing blocks do not fix problem. Only last placed blocks bugged)
https://youtu.be/ASutfajOdig

**Comment by MrTJP** [comment]
Caused by non-thread safe model rendering code. Has already been fixed.
