### ISSUE TITLE
Backpack slot not accessible

### ISSUE THREAD

**Issue by MundM2007** [MrTJP/ProjectRed#1743]
**Describe the bug**
if using a backpack in the hotbar, you cannot drag or pull items from the top row of the backpack (where the backpack is in the hotbar)
![image](https://user-images.githubusercontent.com/85188362/201407429-7f3d3942-21e1-4fb1-a280-3ae38eae4c71.png)
so here you couldn't pull out the diorite from the backpack, if moving the backpack one left in the hotbar you couldn't pull out the Birch log.

**To Reproduce**
1. get a backpack (hotbar) and some items
2. Open Backpack, put items in (shift clicking still works normal)
3. if trying to take item out of the slot, where the backpack is, it doesn't work

**Expected behavior**
Expected, that you could take out from every slot in the backpack

**Versions**
* CodeChickenLib Version: 1.16.5-4.0.7.445
* Forge Version: 36.2.24
* ProjectRed Core Version: 1.16.5-4.12.0
* ProjectRed Exploration Version: 1.16.5-4.12.0

**Comment by MrTJP** [comment]
Found the issue. Thanks
