### ISSUE TITLE
1 peridot gem crafts to 9 gems, can't craft 1 block to 9 gems

### ISSUE THREAD

**Issue by MrMetric** [MrTJP/ProjectRed#1753]
**Steps to reproduce the behavior:**
1. Put a peridot gem in a crafting grid.
2. Observe that the result is 9 peridot gems. It's the magic multiplying mineral!
3. Put a peridot block in a crafting grid.
4. Observe that the result is... nothing!
5. Conclude that the recipes got mixed up.

**Versions:**
* CCL: 1.16.5-4.0.7.445
* CB Multipart: 1.16.5-3.0.4.123
* ProjectRed: 1.16.5-4.13.0-beta-22

**Comment by MrTJP** [comment]
Whoops. Fix will be on Curseforge in few mins

**Comment by MrMetric** [comment]
Thanks for the prompt response! That makes me more comfortable spending time reporting the other bugs I encountered.
