### ISSUE TITLE
Backpacks do not work in singleplayer, and crash the server in multiplayer

### ISSUE THREAD

**Issue by MrMetric** [MrTJP/ProjectRed#1755]
**Steps to reproduce the behavior:**
1. Acquire a backpack.
2. Select it in your hotbar.
3. Right click to open the backpack.
4. Observe that...
4a. SP: ...nothing happens.
4b. MP: ...the server instantly crashes.

**Crash Log**
https://stuff.thingies.site/minecraft/logs/crash-2023-01-31_18.11.51-server.txt

**Versions**
 * CCL: 1.16.5-4.0.7.445
 * CB Multipart: 1.16.5-3.0.4.123
 * ProjectRed: 1.16.5-4.13.0-beta-23

**Comment by MrTJP** [comment]
Your crash log link isn't working for me

**Comment by MrMetric** [comment]
Sorry, my router spontaneously cleared my port forwards. Should be fixed now.
