### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by MaskGuyBr** [MrTJP/ProjectRed#1773]
**Describe the bug**
The game does loads, but a error screen appears saying "java.lang.IllegalAccessError: no such method: mrtjp.projectred.compatibility.ComputerCraftCompatibility.init(Object)void/invokeStatic"

**To Reproduce**
1. Boot the game
2. wait the game to load
3. Error appears

**Crash Log**
https://pastebin.com/7YD46JSF 

**Versions**
* CCL Version: 1.16.5-4.0.7.445-universal
* ProjectRed Version: 1.16.5-4.13.1-beta4
* all the needed mods are up-to-date

**Comment by MrTJP** [comment]
This was fixed. Update pls
