### ISSUE TITLE
Tiles Invisible on Placement - 1.18.2 Forge 

### ISSUE THREAD

**Issue by Chassx2** [MrTJP/ProjectRed#1783]
Using Iris instead of Optifine 
Using Rubidium + Rubidium  Extras.

So after a bit of troubleshooting it looks like 
![image](https://github.com/MrTJP/ProjectRed/assets/56740526/a05e7d6a-81f4-426f-b7b5-d6f98eda2bb9)
Are the culprit. After removing these two the blocks show up normally. (Before they were invisible but the logic worked. Especially with the wires. )

Which means this beta does not support Rubidium

[https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4494903]

Oh.. looks like someone posted there as well.

https://github.com/Asek3/Rubidium/issues/515

**Comment by TheKidThatCodes** [comment]
temp fix in `rubidium-mixins.properties`
`mixin.features.chunk_rendering=false`

**Comment by MrTJP** [comment]
Thanks! That narrows down the problem to the chunk rendering hacks from Rubidium. I'll look into it. Also provided some details in the issue on Rubidium's end in case any of their devs know what's going on.
