### ISSUE TITLE
[Suggestion-Feature-1.12.2-Fabrication] Bundled Cable Null Cell

### ISSUE THREAD

**Issue by Shikifuyin** [MrTJP/ProjectRed#1794]
Not sure if there is still active development for Project-Red Fabrication in 1.12 since I see
a v2 is in progress and will probably target 1.18 ... but in the meantime, would it be
possible (simple/fast enough) to implement a NullCell for Bundled Cables in the IC Workbench ?

I cannot count how much time I have spent figuring out cable routing to fit a design
in a 64x64 grid (sometimes just being impossible !) and 99% of the time the issue is
the inability to cross bundled cables which basically act as walls. Such a shame when
there is obviously enough room left but no way to wire.

Thanks a lot for such a wonderful mod, I am currently using it to build a 16-bits
x86-like computer and it has been very good so far to keep designs compact and
well-organized !

Hope to see v2 soon ! Cheers !

**Comment by MrTJP** [comment]
Unfortunately, it is not possible without extensive work under the hood. This was one of the main motivations for rewriting the system. It was quite inflexible. Bundled gates in general are not east to create inside a circuit. 

This will definitely be supported in v2, plus other stuff like circuits-in-circuits, multiple layers, etc. 

I'm surprised you are able to create such complex this with the old system tbh, it was not very performant either.
