### ISSUE TITLE
DEDICATED_SERVER ENV GUIs do not work

### ISSUE THREAD

**Issue by marewey** [MrTJP/ProjectRed#1795]
**Describe the bug**
When playing with these mods in DEDICATED_SERVER environment you are unable to use GUIs for Timer or any other gates
Gate still functions correctly, but it not configurable

**To Reproduce**
1. Install mod on a Dedicated Server
2. Join Server
3. Try and set timer gate
4. Nothing happens, except some log spam on server log

**Expected behavior**
The GUI would open and set the timer to go off every 1 sec for example

**Crash Log**
This is not a crash, but this is the server log when you would try and click on a gate with a GUI
https://pastebin.com/BZKsh0iD
In Addition the server startup contains this bit of code, which probably should not be on the server side, I would guess?
[modloading-worker-0/INFO] [codechicken.mixin.forge.SidedGenerator/]: Trait: codechicken/multipart/trait/TAnimateTickTile
[modloading-worker-0/INFO] [codechicken.mixin.forge.SidedGenerator/]:     Marker: codechicken/multipart/api/part/AnimateTickPart, Side: CLIENT

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: CodeChicken Lib 1.18.2-4.1.4.488 Universal
* FMP Version: CB Multipart 1.18.2-3.1.0.137 Universal
* MrTJPCore Version: N/A
* ProjectRed Version: ProjectRed-1.18.2-4.16.0-beta-16-integration

**Comment by MrTJP** [comment]
Deployment started. Will be available on Curseforge in about 30 mins.

https://github.com/MrTJP/ProjectRed/actions/runs/5638128952
