### ISSUE TITLE
1.18.2 Rubidium Rendering Issue

### ISSUE THREAD

**Issue by Movetone** [MrTJP/ProjectRed#1801]
### Discussed in https://github.com/MrTJP/ProjectRed/discussions/1800

<div type='discussions-op-text'>

<sup>Originally posted by **Movetone** August 25, 2023</sup>
Wires and Logical elements do not render when using rubidium optimization mod. Is there any way to fix that?</div>

**Comment by Asek3** [comment]
https://github.com/Asek3/Rubidium/commit/3b9559ed1272d579349c757e7897b46bcfb88e87
Fixed in Rubidium's dev versions
