### ISSUE TITLE
Projectredp-transportation

### ISSUE THREAD

**Issue by eliteomg** [MrTJP/ProjectRed#1806]
J'ai un problème avec le mod projectred-transportation et j'aurais besoin du mod pour ma survie sauf que je ne le trouve pas.J'aimerais quond m'envoie le lien du mod car maitenant je ne peut plus accédé a ma survie un message m'apparait``Le jeu s'est écrasé alors qu'il y avait un problème grave lors du chargement du mod qui a provoqué l'échec du jeu. Erreur : net.minecraftforge.fml.common.LoaderExceptionModCrash : exception détectée de CodeChicken Lib (codechickenlib) ``

**Comment by MrTJP** [comment]
ProjectRed Transportation is part of the Expansion module. It is no longer available as of Minecraft 1.15+. It may be re-written in the future, but is not being ported forward.
