### ISSUE TITLE
[Bug] [1.19.2] Project Red exploration ores and other stuff not generating

### ISSUE THREAD

**Issue by spectre311** [MrTJP/ProjectRed#1830]
### Minecraft version

1.18.x

### CodeChickenLib version

1.19.2-4.3.2.490

### CBMultipart version

1.19.2-3.2.0.139

### ProjectRed version

1.19.2-4.17.0-beta+8-exploration

### What happened?

So i installed Project Red exploration and nothing from the mod generates.

### Crash log

There's no crashes

### How do you make it happen again?

Just install Project Red exploration on 1.19.2 it won't generate the stuff.

**Comment by James-P-Bennett** [comment]
Having this same exact issue now. 4.17.0-beta+8
