### ISSUE TITLE
Retriever from RedPower 2

### ISSUE THREAD

**Issue by Pyato4ka** [MrTJP/ProjectRed#1832]
Hello!
Could you add a Retriever that works with Pressure Tubes, similar to the one from the RedPower 2 mod? I tried searching for mods that add it, and I found BluePower and Teckle. However, in both mods, the Retriever is not working. There is a Retriever in Thermal Dynamics, but it works a bit differently. [Retriever wiki page](https://ftbwiki.org/Retriever_(RedPower_2))

**Comment by MrTJP** [comment]
This will be re-visited whenever pressure tubes are re-implemented
