### ISSUE TITLE
[Bug] Draw Plate not craftable in 1.19.x

### ISSUE THREAD

**Issue by djmattyg007** [MrTJP/ProjectRed#1838]
### Minecraft version

1.16.x

### CodeChickenLib version

1.19.2-4.3.2.490

### CBMultipart version

1.19.2-3.2.0.139

### ProjectRed version

1.19.2-4.17.0-beta+8

### What happened?

Crafting a Draw Plate requires a size 2 iron post, but it doesn't seem possible to make that.

### Crash log

N/A

### How do you make it happen again?

Just try to craft a Draw Plate.

**Comment by MrTJP** [comment]
Seems to work fine for me. If you were referring to the actual saw cutting recipes, the latest 1.19 beta fixes a bug where recipes with saws added by ProjectRed were not working.

<img width="691" alt="Screen Shot 2024-03-24 at 10 45 35 AM" src="https://github.com/MrTJP/ProjectRed/assets/1957405/bf8ba293-800f-42db-927d-706c8bacc975">
<img width="691" alt="Screen Shot 2024-03-24 at 10 46 12 AM" src="https://github.com/MrTJP/ProjectRed/assets/1957405/6744a092-7dcd-4e80-b772-ffca2b438ffb">
<img width="689" alt="Screen Shot 2024-03-24 at 10 46 35 AM" src="https://github.com/MrTJP/ProjectRed/assets/1957405/3166e9b1-778a-4b65-bfac-9ff71bcc583e">
