### ISSUE TITLE
[BUG] Setting false in config file for Silver and Tin ore isn't working (1.19.2)

### ISSUE THREAD

**Issue by drenough** [MrTJP/ProjectRed#1843]
Minecraft: 1.19.2
Forge version: 43.3.0
Project Red version: 1.19.2-4.17.0-beta+13

I wanted to disable worldgen of Tin and Silver ore, I've tried changing true to false, even setting vein size to 0 but the ores are still spawning

**Comment by MrTJP** [comment]
Known bug. Fixing it soon. Happens because Forge's built-in biome modifiers don't have any way to make the modification conditional as far as I know. I'll have to make my own

**Comment by MrTJP** [comment]
Trying to see if other mods are still doing Config-file based generation, because MC is pushing all worldgen configuration to be done only via datapack.

**Comment by drenough** [comment]
IC2 Classic still has config option, thermal has it via datapack (they have ready datapack for download on their discord server), Mekanism still has config option aswell (in 1.20.1 too) but other mods, no idea

**Comment by IIIap** [comment]
can confirm the problem
