### ISSUE TITLE
[Bug] Crash when hovering over logic gate in a blueprint with interact tool in 1.19.2

### ISSUE THREAD

**Issue by IroPlisk** [MrTJP/ProjectRed#1853]
### Minecraft version

1.19.x

### CodeChickenLib version

4.3.2.490

### CBMultipart version

3.2.0.138

### ProjectRed version

4.17.0-beta+34

### What happened?

When you hover over a placed logic gate of any kind on the project table with the interact tool, the game abruptly crashes. Happens both in a server and in SP

### Crash log

[2024-05-09-1.log](https://github.com/MrTJP/ProjectRed/files/15267605/2024-05-09-1.log)

### How do you make it happen again?

1) Place IC workbench down
2) Insert Blueprint in the bench
3) Place any logic gate down
4) Select interact tool
5) Hover over any of the placed logic gates

**Comment by MrTJP** [comment]
Can't reproduce on a clean install with just CCL, CBM, and all Project Red mods. May be some bad interaction with another mod you installed. Could also be an incompatible texture/resource pack.

Try to remove all resource packs and mods other than the 3 above and see if it still crashes. If not, start adding stuff back until you figure out what causes it. If you can narrow it down, please re-open this issue and I can help further.

**Comment by IroPlisk** [comment]
It seems it was indeed a problem with a texture pack, thanks a ton. But another problem seems to have popped up, as when i click on the sides or the rotation button (or also press r) of a placed logic gate, nothing happens. i can click however on the time setting thing of a timer and rotate it. So it seems to be a general problem with logic gates with their rotation and side disabling.

**Comment by IroPlisk** [comment]
i also have no clue how to reopen this issue, sry.

**Comment by MrTJP** [comment]
I also don't have any issues with rotation with either hotkeys or clicking on the buttons on the gate. Can you also re-check this with just ProjectRed and its dependencies installed?

**Comment by IroPlisk** [comment]
Ok, it seems that the interaction tool crashes with programmer art ON. And for the rotation and disabling the gates, it occours only in MP, in singleplayer with or without mods works perfectly fine. Might be a desync bug or error, idk. But yeah, the mod works fine with programmer art off and SP.

**Comment by MrTJP** [comment]
Thanks for those details! Found and fixed the issue. Will upload a new build to Curse in a little bit.
