### ISSUE TITLE
[1.18.2, forge 40.2.14] light sources from illumination that aren't illumar lamps (fixture lights, cage lamps, etc) only produce light for one tick

### ISSUE THREAD

**Issue by veccyboi** [MrTJP/ProjectRed#1860]
### Minecraft version

1.18.x

### CodeChickenLib version

4.1.4.488

### CBMultipart version

3.1.1.138

### ProjectRed version

illmunation 4.17.0-beta 4

### What happened?

mods folder: 
![image](https://github.com/MrTJP/ProjectRed/assets/85643556/3995abc4-e27c-4423-b759-2d01c4639293)

when placing any light source from Project Red: Illumination that isn't an illumar lamp, the block only emits light for one tick.
video: https://drive.google.com/file/d/1bDd5BP8jU4v1jzGZy22rTpVBcfotHKcw/view?usp=sharing

### Crash log

N/A

### How do you make it happen again?

bug is most easily demonstrated with inverted light sources:
1. get a light source from Project Red: Illumination that isn't an illumar lamp (the full-block ones) and place it down in a dark area. observe that light is only produced for one tick. if the f3 screen is opened, the block light level can be seen to change briefly, then immediately go back to 0

**Comment by MrTJP** [comment]
Please verify if the issue happens with PR alone. Most likely it’s some incompatibility with Rubidium.

**Comment by MrTJP** [comment]
Closing. Please re-open if you continue to have issues after removing all render optimization mods.
