### ISSUE TITLE
[Bug] 1.18.2 not display Integration mod's block image(image?)

### ISSUE THREAD

**Issue by 8MiYile** [MrTJP/ProjectRed#1861]
### Minecraft version

1.18.x

### CodeChickenLib version

4.1.4.488

### CBMultipart version

3.1.1.138

### ProjectRed version

4.17.0-beta-4

### What happened?

![截图_Minecraft* 1 18 2_20240520234343](https://github.com/MrTJP/ProjectRed/assets/25455400/1fd72286-63c1-4494-b90c-3fe7f05407f0)
![截图_选择区域_20240520234546](https://github.com/MrTJP/ProjectRed/assets/25455400/c34a1e63-fca1-4c16-a7dd-1ae1d55321b3)

`Project Red - Integration`
it's look like not found mod's assets

### Crash log

not crash

### How do you make it happen again?

it's easy and i'm not say detail

**Comment by 8MiYile** [comment]
oh wait
it's maybe CBMultipart's Bug

**Comment by MrTJP** [comment]
Are you using optifine, sodium, rubidium, etc? Does it happen with just PR installed?

**Comment by 8MiYile** [comment]
@MrTJP my client include rubidium mod
i'll try disable it

**Comment by MrTJP** [comment]
Looks like CCL's block render hook is not working. Its not working even with only ProjectRed installed? Did you try removing everything else to verify?

This was a known issue back in 1.18 but was fixed on Rubidium side. But it's possible that it came back or some other mod is having issues with it: https://github.com/MrTJP/ProjectRed/issues/1801

**Comment by 8MiYile** [comment]
how to download rubidium dev version?

**Comment by MrTJP** [comment]
Great. Yes, rubidium, sodium, optifine, etc. are not always compatible with many other mods.
