### ISSUE TITLE
[Bug] Cant use the handsaw in the inventory 2x2 crafting table + IC workbench crash

### ISSUE THREAD

**Issue by IroPlisk** [MrTJP/ProjectRed#1865]
### Minecraft version

1.19.x

### CodeChickenLib version

4.3.2.490

### CBMultipart version

3.2.0.139

### ProjectRed version

4.17.0

### What happened?

1. As it says in the title, the issue is simple as that, you cant use recipes with any saw in the inventory crafting table.

2. Also as a bonus, i found out the IC workbench's inspect tool crashes on X11 Linux machines, it does not happen on wayland and windows.

### Crash log

1. none, it's not a crash, it's perhaps a bug/not yet implemented feature at most.
2. Check the log attached:

[latest.log](https://github.com/user-attachments/files/15686845/latest.log)

### How do you make it happen again?

For the first issue:
1. Get any saw
2. Get any block compatible with the multiblocks mod
3. Put the saw on top of the block in the inventory 2x2 crafting table
4. No results in the output slot

For the second issue:
1. Have a linux machine
2. Set up minecraft with java 17
3. Have an X11 session
4. Boot up minecraft and go in either SP or MP
5. Place down the IC workbench with the blueprint
6. Place in the cartography table any logic gate (i tested with the NAND) (Not an IO)
7. Select the interact tool and hover over the aforementioned logic gate
8. Crash

**Comment by MrTJP** [comment]
I mentioned this in an issue I created on the CBMultipart repo: https://github.com/TheCBProject/CBMultipart/issues/159
