### ISSUE TITLE
[1.20.1] Lamp block halos not working on 1.20.1

### ISSUE THREAD

**Issue by guilomet** [MrTJP/ProjectRed#1868]
### Minecraft version

1.20.x

### CodeChickenLib version

4.4.0.512

### CBMultipart version

3.3.0.146

### ProjectRed version

4.19.0-beta+3

### What happened?

When I use the colored block (inversed or not), I don't have any colored light, but only a standard light (like a torch) with some strange shaders popping sometime.

Here some screenshots (no more mods are in this instance, only the dependecies and Project Red).

![2024-06-22_21 09 34](https://github.com/MrTJP/ProjectRed/assets/19349296/1fede155-6858-4229-8c9b-fdd189585dc0)
![2024-06-22_21 09 45](https://github.com/MrTJP/ProjectRed/assets/19349296/6decfe77-554a-474d-871f-af6de676df44)

### Crash log

https://gist.github.com/guilomet/13cde5088eb655c68d9921aabf99a1f5.js

### How do you make it happen again?

Just place some illuminated and colored block anywhere.

**Comment by MrTJP** [comment]
Confirmed bug with non-fabulous rendering mode. Will look into it

**Comment by MrTJP** [comment]
This is a bug in NeoForge. It was fixed in the `1.20.x` branch but has not been picked into `1.20.1`. I'll see if I can open a Pull Request for it.

https://github.com/neoforged/NeoForge/pull/231

**Comment by guilomet** [comment]
Arf, I got the bug with Forge to, and indeed Neoforged didn't backport some fixes. But I got this problem in Forge 47.3.1.
Just to know, have you some futur compat with Oculus shaders or not ?

**Comment by MrTJP** [comment]
Trying to throw together a mixin to path the bug at runtime.

There's no specific compatibility with Oculus shaders or any thing else. It might work though.
