### ISSUE TITLE
AutoCrafter not accepting items

### ISSUE THREAD

**Issue by Dissss1** [MrTJP/ProjectRed#1872]
### Minecraft version

1.20.x

### CodeChickenLib version

1.20.1-4.4.0.512

### CBMultipart version

1.20.1-3.3.0.146

### ProjectRed version

1.20.1-4.19.0-beta+3

### What happened?

the auto crafter does not accept items from hopper.
also the pnematic tubes and any other item transport
if this is a feature i would like the option to change it in config if possible as i think as it requires its own power it should be able to accept items.

Thank you

### Crash log

no crash

### How do you make it happen again?

any item transport to auto crafter

**Comment by MrTJP** [comment]
This is a bug. Auto Crafter block entity does not expose the Item Handler capability. Will fix
