### ISSUE TITLE
[Bug] Marble Spawns in the Air

### ISSUE THREAD

**Issue by Ghastly13** [MrTJP/ProjectRed#1874]
### Minecraft version

1.20.x

### CodeChickenLib version

4.4.0.512

### CBMultipart version

3.3.0.146

### ProjectRed version

4.19.0-beta+3

### What happened?

There is a large marble generation in the air.

![2024-07-10_20 08 55](https://github.com/MrTJP/ProjectRed/assets/83313692/b2df21ed-bd33-4b5d-a02d-43d70172fb78)

### Crash log

The mod did not crash.

### How do you make it happen again?

Create a new world, look for it to generate.

**Comment by vizthex123** [comment]
same here!

log:
[latest.log](https://github.com/user-attachments/files/16241327/latest.log)

![image](https://github.com/user-attachments/assets/92d8f7ec-c515-4e0b-a284-11cfdf2c3465)

**Comment by MrTJP** [comment]
Can I get some world seeds and locations where these are generating? I can't seem to find any just flying around random worlds.

**Comment by vizthex123** [comment]
> Can I get some world seeds and locations where these are generating? I can't seem to find any just flying around random worlds.

Had to make a new test world since I deleted the old one, but for me it was all around spawn in the seed `-8817395866575381316`.

Applies to every world I make. I am running [my new modpack](https://www.curseforge.com/minecraft/modpacks/hi-tech-revolution), so maybe it's another mod causing this issue? If I disable Marble Caves in the config, they don't appear anymore.

Here's the log from the new world I made:
[latest.log](https://github.com/user-attachments/files/16257428/latest.log)

**Comment by MrTJP** [comment]
I am still unable to repro this, even with the given seed (`-8817395866575381316`). Could be an interaction with another mod that is screwing up world-gen.

**Comment by Sgt1miler** [comment]
> Una vez que lo ejecutes, verás la primera página de valores. Luego, puedes presionar la `chat`combinación de teclas nuevamente y hacer clic en el `Elements: #`texto verde para copiar todas las páginas al portapapeles.

ad_astra:glacio_copper_ore
ad_astra:glacio_iron_ore
ad_astra:glacio_stone
ad_astra:mars_iron_ore
ad_astra:mars_sand
ad_astra:mars_stone
ad_astra:mercury_iron_ore
ad_astra:mercury_stone
ad_astra:moon_iron_ore
ad_astra:moon_sand
ad_astra:moon_stone
ad_astra:permafrost
ad_astra:venus_sand
ad_astra:venus_stone
ad_extendra:ceres_copper_ore
ad_extendra:ceres_iron_ore
ad_extendra:ceres_sand
ad_extendra:jupiter_sand
adastraextra:adrastea_rock
adastraextra:amalthea_rock
adastraextra:deimos_rock
adastraextra:jupiter_rock
adastraextra:metis_rock
adastraextra:neptune_rock
adastraextra:phobos_rock
adastraextra:saturn_rock
adastraextra:thebe_rock
adastraextra:uranus_rock
aether:aether_dirt
aether:aether_grass_block
aether:enchanted_aether_grass_block
biomesoplenty:black_sand
biomesoplenty:glowing_moss_block
biomesoplenty:mossy_black_sand
biomesoplenty:orange_sand
biomesoplenty:origin_grass_block
biomesoplenty:white_sand
botania:dry_grass
botania:golden_grass
botania:infused_grass
botania:mutated_grass
botania:scorched_grass
botania:vivid_grass
deep_aether:aether_coarse_dirt
deep_aether:aether_moss_block
deep_aether:aether_mud
deep_aether:golden_heights_grass_block
denseores:dense_copper_ore
denseores:dense_deepslate_copper_ore
denseores:dense_deepslate_iron_ore
denseores:dense_iron_ore
deserts_and_dunes:another_coarse_sand
deserts_and_dunes:another_sand
deserts_and_dunes:coarse_sand
deserts_and_dunes:dry_dirt
deserts_and_dunes:dry_red_sand
deserts_and_dunes:dry_sand
deserts_and_dunes:dune_sand
deserts_and_dunes:hard_red_sand
deserts_and_dunes:hard_sand
deserts_and_dunes:light_sand
dungeons_plus:granite_iron_ore
farmersdelight:rich_soil
minecraft:air
minecraft:amethyst_block
minecraft:andesite
minecraft:basalt
minecraft:black_terracotta
minecraft:blackstone
minecraft:blue_ice
minecraft:blue_terracotta
minecraft:brown_terracotta
minecraft:budding_amethyst
minecraft:calcite
minecraft:coarse_dirt
minecraft:copper_ore
minecraft:cyan_terracotta
minecraft:deepslate
minecraft:deepslate_copper_ore
minecraft:deepslate_iron_ore
minecraft:diorite
minecraft:dirt
minecraft:dripstone_block
minecraft:granite
minecraft:grass_block
minecraft:gravel
minecraft:gray_terracotta
minecraft:green_terracotta
minecraft:iron_ore
minecraft:light_blue_terracotta
minecraft:light_gray_terracotta
minecraft:lime_terracotta
minecraft:magenta_terracotta
minecraft:magma_block
minecraft:moss_block
minecraft:mud
minecraft:muddy_mangrove_roots
minecraft:mycelium
minecraft:netherrack
minecraft:orange_terracotta
minecraft:packed_ice
minecraft:packed_mud
minecraft:pink_terracotta
minecraft:podzol
minecraft:powder_snow
minecraft:purple_terracotta
minecraft:raw_copper_block
minecraft:raw_iron_block
minecraft:red_sand
minecraft:red_sandstone
minecraft:red_terracotta
minecraft:rooted_dirt
minecraft:sand
minecraft:sandstone
minecraft:smooth_basalt
minecraft:smooth_red_sandstone
minecraft:smooth_sandstone
minecraft:snow
minecraft:snow_block
minecraft:soul_soil
minecraft:stone
minecraft:suspicious_gravel
minecraft:suspicious_sand
minecraft:terracotta
minecraft:tuff
minecraft:water
minecraft:white_terracotta
minecraft:yellow_terracotta
mynethersdelight:resurgent_soil
mynethersdelight:resurgent_soil_farmland
nethersdelight:rich_soul_soil
proxima_plus:proxima_b_sand
proxima_plus:proxima_b_sandstone
proxima_plus:proxima_b_stone
quark:jasper
quark:limestone
quark:shale
regions_unexplored:alpha_grass_block
regions_unexplored:argillite
regions_unexplored:argillite_grass_block
regions_unexplored:ash
regions_unexplored:ashen_dirt
regions_unexplored:chalk
regions_unexplored:chalk_grass_block
regions_unexplored:deepslate_grass_block
regions_unexplored:deepslate_prismoss
regions_unexplored:deepslate_viridescent_nylium
regions_unexplored:mossy_stone
regions_unexplored:peat_coarse_dirt
regions_unexplored:peat_dirt
regions_unexplored:peat_farmland
regions_unexplored:peat_grass_block
regions_unexplored:peat_mud
regions_unexplored:peat_podzol
regions_unexplored:prismoss
regions_unexplored:silt_coarse_dirt
regions_unexplored:silt_dirt
regions_unexplored:silt_farmland
regions_unexplored:silt_grass_block
regions_unexplored:silt_mud
regions_unexplored:silt_podzol
regions_unexplored:stone_grass_block
regions_unexplored:viridescent_nylium
regions_unexplored:volcanic_ash
thermal:phytosoil
twilightforest:trollsteinn
twilightforest:uberous_soil
undergarden:ashen_deepturf_block
undergarden:coarse_deepsoil
undergarden:deepsoil
undergarden:deepturf_block
undergarden:depthrock_iron_ore
undergarden:frozen_deepturf_block
undergarden:shiverstone_iron_ore
underground_jungle:jungle_grass
valhelsia_structures:coarse_dirt
valhelsia_structures:dirt
valhelsia_structures:grass_block
vintagedelight:lush_grass_block
xycraft_machines:planter

![image](https://github.com/user-attachments/assets/6ba55c77-be3e-4bea-8e95-cf3b3097152b)

**Comment by MrTJP** [comment]
Here lies the problem. Some mod has added air to the list of stuff that cave generators should carve out:

```
minecraft:air
```

That tag does not belong on `minecraft:overworld_carver_replaceables`. We need to figure out which mod is doing that.

The marble cave generator works by first carving the hollow space, then surrounding the exterior walls with marble. This is tricking the carver to think the air surrounding the carved regions is a diggable material that should be replaced with marble. 

Additionally, it is going to cause all cave generators from any mod to run on air, which is likely causing a massive hit to performance (i.e. all cave carvers are not only running underground, but in mid-air as well, even though you can't see their effects as easily as the marble cave carvers).

**Comment by vizthex123** [comment]
> I am still unable to repro this, even with the given seed (`-8817395866575381316`). Could be an interaction with another mod that is screwing up world-gen.
> 
> Can you run the following command in your world and get me the output?
> 
> ```
> /forge tags minecraft:block get minecraft:overworld_carver_replaceables
> ```
> 
> Once you run it, you'll see the first page of values. You can then press the `chat` keybind again and click on the green `Elements: #` text to copy all pages to the clipboard.

Tested with Exploration v4.19.0-beta+11

```ad_astra:glacio_copper_ore
ad_astra:glacio_iron_ore
ad_astra:glacio_stone
ad_astra:mars_iron_ore
ad_astra:mars_sand
ad_astra:mars_stone
ad_astra:mercury_iron_ore
ad_astra:mercury_stone
ad_astra:moon_iron_ore
ad_astra:moon_sand
ad_astra:moon_stone
ad_astra:permafrost
ad_astra:venus_sand
ad_astra:venus_stone
ad_astra_proxima_plus:proxima_b_sand
ad_astra_proxima_plus:proxima_b_sandstone
ad_astra_proxima_plus:proxima_b_stone
ad_astra_proxima_plus:vicino_sand
ad_astra_proxima_plus:vicino_stone
alexscaves:galena_iron_ore
biomesoplenty:black_sand
biomesoplenty:glowing_moss_block
biomesoplenty:mossy_black_sand
biomesoplenty:orange_sand
biomesoplenty:origin_grass_block
biomesoplenty:white_sand
essentials:fertile_soil_acacia
essentials:fertile_soil_birch
essentials:fertile_soil_brown_mushroom
essentials:fertile_soil_dark_oak
essentials:fertile_soil_jungle
essentials:fertile_soil_oak
essentials:fertile_soil_red_mushroom
essentials:fertile_soil_spruce
excavated_variants:andesite_copper_ore
excavated_variants:andesite_iron_ore
excavated_variants:argillite_copper_ore
excavated_variants:argillite_iron_ore
excavated_variants:basalt_copper_ore
excavated_variants:basalt_iron_ore
excavated_variants:biomesoplenty_black_sandstone_copper_ore
excavated_variants:biomesoplenty_black_sandstone_iron_ore
excavated_variants:biomesoplenty_orange_sandstone_copper_ore
excavated_variants:biomesoplenty_orange_sandstone_iron_ore
excavated_variants:biomesoplenty_white_sandstone_copper_ore
excavated_variants:biomesoplenty_white_sandstone_iron_ore
excavated_variants:calcite_copper_ore
excavated_variants:calcite_iron_ore
excavated_variants:chalk_copper_ore
excavated_variants:chalk_iron_ore
excavated_variants:chalkstone_copper_ore
excavated_variants:chalkstone_iron_ore
excavated_variants:chert_copper_ore
excavated_variants:chert_iron_ore
excavated_variants:diorite_copper_ore
excavated_variants:diorite_iron_ore
excavated_variants:dripstone_copper_ore
excavated_variants:dripstone_iron_ore
excavated_variants:granite_copper_ore
excavated_variants:granite_iron_ore
excavated_variants:kivi_copper_ore
excavated_variants:kivi_iron_ore
excavated_variants:marble_copper_ore
excavated_variants:marble_iron_ore
excavated_variants:mudstone_copper_ore
excavated_variants:mudstone_iron_ore
excavated_variants:pastel_pink_salt_copper_ore
excavated_variants:pastel_pink_salt_iron_ore
excavated_variants:pink_salt_copper_ore
excavated_variants:pink_salt_iron_ore
excavated_variants:quark_jasper_copper_ore
excavated_variants:quark_jasper_iron_ore
excavated_variants:quark_limestone_copper_ore
excavated_variants:quark_limestone_iron_ore
excavated_variants:quark_shale_copper_ore
excavated_variants:quark_shale_iron_ore
excavated_variants:red_sandstone_copper_ore
excavated_variants:red_sandstone_iron_ore
excavated_variants:rose_pink_salt_copper_ore
excavated_variants:rose_pink_salt_iron_ore
excavated_variants:sandstone_copper_ore
excavated_variants:sandstone_iron_ore
excavated_variants:smooth_basalt_copper_ore
excavated_variants:smooth_basalt_iron_ore
excavated_variants:tuff_copper_ore
excavated_variants:tuff_iron_ore
galosphere:lichen_moss
minecraft:air
minecraft:andesite
minecraft:black_terracotta
minecraft:blue_ice
minecraft:blue_terracotta
minecraft:brown_terracotta
minecraft:calcite
minecraft:coarse_dirt
minecraft:copper_ore
minecraft:cyan_terracotta
minecraft:deepslate
minecraft:deepslate_copper_ore
minecraft:deepslate_iron_ore
minecraft:diorite
minecraft:dirt
minecraft:dripstone_block
minecraft:granite
minecraft:grass_block
minecraft:gravel
minecraft:gray_terracotta
minecraft:green_terracotta
minecraft:ice
minecraft:iron_ore
minecraft:light_blue_terracotta
minecraft:light_gray_terracotta
minecraft:lime_terracotta
minecraft:magenta_terracotta
minecraft:moss_block
minecraft:mud
minecraft:muddy_mangrove_roots
minecraft:mycelium
minecraft:orange_terracotta
minecraft:packed_ice
minecraft:packed_mud
minecraft:pink_terracotta
minecraft:podzol
minecraft:powder_snow
minecraft:purple_terracotta
minecraft:raw_copper_block
minecraft:raw_iron_block
minecraft:red_sand
minecraft:red_sandstone
minecraft:red_terracotta
minecraft:rooted_dirt
minecraft:sand
minecraft:sandstone
minecraft:snow
minecraft:snow_block
minecraft:stone
minecraft:suspicious_gravel
minecraft:suspicious_sand
minecraft:terracotta
minecraft:tuff
minecraft:void_air
minecraft:water
minecraft:white_terracotta
minecraft:yellow_terracotta
quark:jasper
quark:limestone
quark:shale
regions_unexplored:alpha_grass_block
regions_unexplored:argillite
regions_unexplored:argillite_grass_block
regions_unexplored:ash
regions_unexplored:ashen_dirt
regions_unexplored:chalk
regions_unexplored:chalk_grass_block
regions_unexplored:deepslate_grass_block
regions_unexplored:deepslate_prismoss
regions_unexplored:deepslate_viridescent_nylium
regions_unexplored:mossy_stone
regions_unexplored:peat_coarse_dirt
regions_unexplored:peat_dirt
regions_unexplored:peat_farmland
regions_unexplored:peat_grass_block
regions_unexplored:peat_mud
regions_unexplored:peat_podzol
regions_unexplored:prismoss
regions_unexplored:silt_coarse_dirt
regions_unexplored:silt_dirt
regions_unexplored:silt_farmland
regions_unexplored:silt_grass_block
regions_unexplored:silt_mud
regions_unexplored:silt_podzol
regions_unexplored:stone_grass_block
regions_unexplored:viridescent_nylium
regions_unexplored:volcanic_ash
thermal:phytosoil
xycraft_machines:planter```

**Comment by Sgt1miler** [comment]
I fin one of the mods bug the generation "Ad Astra Extra"

**Comment by vizthex123** [comment]
I don't have that installed, so perhaps something else does it too?

**Comment by MrTJP** [comment]
@vizthex123 Yea and in your case, it is also adding `minecraft:void_air`. Both are incorrect as far as I understand. I'll add a workaround to ignore these tags. But it really should be fixed in whatever mod is adding these.
