### ISSUE TITLE
[Bug] Project Red: Exploration 1.20.1 - Tin Block and Raw Silver texture bug

### ISSUE THREAD

**Issue by Jiro2301** [MrTJP/ProjectRed#1890]
### Minecraft version

1.20.x

### CodeChickenLib version

1.20.1-4.4.0.512

### CBMultipart version

1.20.1-3.3.0.146

### ProjectRed version

ProjectRed-1.20.1-4.19.0-exploration

### What happened?

Hi, I'm pretty new to making posts in here (and new in general) so apologies if I make some mistakes.

I was playing in my world where I was putting down ore blocks from different mods so I could make a resource pack to make them easier to find. Then I came across that the texture for the tin block and the raw silver block were swapped when they are placed down. When they are in their item form, the textures are normal.

I'm not using a resource pack in this screenshot, and it can be seen with the Jade mod that the item texture is right, but the tile texture isn't.
![2024-08-21_15 10 05](https://github.com/user-attachments/assets/e2b24693-7a6f-4142-98d2-1d07962a3d2d)
![2024-08-21_15 10 15](https://github.com/user-attachments/assets/5bce9e34-8c90-4481-9053-1c46df4d715c)

The mod in question is the (current) latest version of Project Red: Exploration for 1.20.1 [ProjectRed-1.20.1-4.19.0-exploration], which was last updated on Aug 10th, 2024.

Once again I apologize if I made any mistakes or leaved out important information that I'm no aware off. Please let me know if there is anything more needed. Also on a quick search, I didn't find other open issues about this but just in case sorry for a repeat bug report. Hope this can be addressed soon enough.

Best Regards

### Crash log

No Crash

### How do you make it happen again?

Simply Placing down the Tin Block and the Raw Silver Block in the world. Item texture does not match with tile texture

**Comment by MrTJP** [comment]
Confirmed bug. Will look into it
