### ISSUE TITLE
[Bug] ProjectRed intergration startup issue with Codechicken Lib

### ISSUE THREAD

**Issue by border999** [MrTJP/ProjectRed#1893]
### Minecraft version

1.20.x

### CodeChickenLib version

4.4.0.512

### CBMultipart version

3.3.0.146-universal

### ProjectRed version

4.20.0-beta+4

### What happened?

Crash at startup.

### Crash log

https://bytebin.lucko.me/fABdQ07KL1

### How do you make it happen again?

Attempt to start the game again.

**Comment by MrTJP** [comment]
Your crash log link is invalid. Please edit the link and re-open the issue if needed.

**Comment by border999** [comment]
https://gist.github.com/border999/4dc16011d0c9481c153c0680ed51db84

**Comment by border999** [comment]
It doesn't give me an option to reopen this issue.
