### ISSUE TITLE
Is the license change to MIT Retroactive?

### ISSUE THREAD

**Issue by RainbowTabitha** [MrTJP/ProjectRed#1896]
Im asking for forks like the GTNewHorizons mod if they can be relicensed to MIT aswell.

Also if not do you give permission for all packs to include Project Red and its forks on CurseForge. Techionally this is up to you as per the license for No Redivided works.

**Comment by MrTJP** [comment]
Sorry for late response. Yes, the license change is retroactive to all past branches of Project Red.
