### ISSUE TITLE
[Bug] [Visual] Framed power cables don't connect.

### ISSUE THREAD

**Issue by Heimdell** [MrTJP/ProjectRed#1909]
### Minecraft version

1.20.x

### CodeChickenLib version

4.4.0.516

### CBMultipart version

3.3.0.146

### ProjectRed version

4.19.0

### What happened?

When placed, framed power cables do not appear connected until you exit the SP world and load it back it.

### Crash log

No crash log.

### How do you make it happen again?

Place two framed power cables next to each other.

**Comment by MrTJP** [comment]
Will check again, but should've been fixed in 4.19 (267d11ba5159085e7b053b24e6118e6bfd2a2bd2)

**Comment by MrTJP** [comment]
Apparently I only fixed the non-framed wires. Framed wires fixed in #1904
