### ISSUE TITLE
Questions about Licensing Change and non-CurseForge modpacks

### ISSUE THREAD

**Issue by seancrain** [MrTJP/ProjectRed#1911]
I noticed that Project Red's license had recently been changed, and that some code was added to the CI for Modrinth uploads in the future. As my friend group's modpack maintainer, I use Packwiz to put together packs that are updated through MultiMC. For CurseForge mods, the only way it works without manually getting the URLs for each individual file is using CF's own API to do so. I noticed that the third-party API switch must've been turned off recently, because Project Red files would no longer download.

However, this change only seemed to affect the currently used ones like Expansion and Exploration, but it seemed that older ones like Compat were unaffected. I just have a couple questions.

1. Was this an intentional change, or a by-product of the upload process changing in the CI?
2. If it wasn't intentionally turned off, could it be re-enabled? (It's a per-submod basis if the CI changes did it automatically)

Thank you so much for the work you've done on this. I figure you knew about this but wanted to bring it to your attention if it was not.

On a final note, I note that the Project Red downloads only go back to 1.7.10. I still possess what I believe is the latest version for 1.6.4 if you would like to upload them.

**Comment by MrTJP** [comment]
Hey. You are correct, the third party API option was unintentionally disabled. Will have this fixed in a few hours.

**Comment by seancrain** [comment]
Thank you! What about the 1.6.4 files?

**Comment by IntegerLimit** [comment]
Any update on this? This poses some issues to my pack's CI/CD workflows. Thank you for your previous quick response, and appreciate the work you do here!

**Comment by MrTJP** [comment]
Artifact access via Curse API has been fixed in all modules (let me know if I missed any). Modrinth projects should be available soon.

As for 1.16 artifacts, only way I will consider uploading those again is if I or someone else gets around to back-porting the Github Actions workflows to that branch and the build is fixed (I'm not sure if it even still builds at this point).

**Comment by IntegerLimit** [comment]
Thank you!
