### ISSUE TITLE
[Request] Deployer

### ISSUE THREAD

**Issue by roemba** [MrTJP/ProjectRed#337]
![208px-deployer](https://f.cloud.github.com/assets/2606940/2253159/5bc93eee-9db7-11e3-943f-14787ab1e1c5.png)
It would be nice to have a Deployer block, similar to the original RedPower Deployer block, which simulates a right-click by a user on the items in its inventory. Basically, its inventory would consist of a 3x3 grid in which items can be placed which, when the deployer receives a redstone signal, will be placed in front of the deployer by simulating a right-click on an item. Similar to vanilla dispensers this will, for example, allow for a bucket to be emptied but because vanilla dispensers don't allow every item to be handled in such a way, the deployer will. http://tekkitclassic.wikia.com/wiki/Deployer

**Comment by ErrorCraftLP** [comment]
This issue should be closed because the deployer is now implemented.

**Comment by MrTJP** [comment]
Added via 7ee5d6430f9d729ed18bf4e497d09d31b45f6f9a

**Comment by nycki93** [comment]
Is there a deployer equivalent in a 1.12.2 mod? I'm making a throwback pack and neither ProjectRed nor Thermal Expansion has one.
