### ISSUE TITLE
Lamp Halo Glitch

### ISSUE THREAD

**Issue by NoMoSnacks** [MrTJP/ProjectRed#401]
Lamps have visual artifacts that increase in strength the further you are away from spawn. If I teleport to 100000 150 100000, lamps start having flickering halos and other visual artifacts. Tested on Latest Version of Forge and Project:Red. 

Visible in my personal modpack and Direwolf20 1.6.4 FTB.

**Comment by MrTJP** [comment]
No point of keeping this open.
