### ISSUE TITLE
Update notification for unstable/dev builds

### ISSUE THREAD

**Issue by Ionaru** [MrTJP/ProjectRed#415]
I've noticed that in-game Project:Red give a message that there's an update available.
However, this update (4.3.7) is marked red which means: "Red builds can be unstable. Very unstable.".

Will there be an option to disable the update-message for unstable builds or in it's entirety?

**Comment by ExDomino** [comment]
One thing you can do: changing the update check address for new versions in order to old versions see an empty changelog, so they will display nothing in the chat.
