### ISSUE TITLE
0-Tick Repeater

### ISSUE THREAD

**Issue by KevinMackenzie** [MrTJP/ProjectRed#467]
I am creating this because the old topic was closed, but afterwards another viable idea was brought up to resolve the issue.  

I would like to request a 0 tick repeater to would amplify the signal like a repeater, but does not take any time (almost like a null cell that amplifies).  I think it would look just like a repeater, except there is no way to change the delay.  I would not think this would be very hard compared to my idea, which MrTJP claimed would be too time consuming.

**Comment by MrTJP** [comment]
Cant find a solution to this that doesn't require a massive overhaul of signal propagation. Gonna close it for now..
