### ISSUE TITLE
Remove upgrade nag.

### ISSUE THREAD

**Issue by Marx1** [MrTJP/ProjectRed#503]
I'm running 4.3.5 build #30 for 1.6.4; and I'm getting nag screens to upgrade to 4.4.x; but that version is built for 1.7.4; not 1.6.4.

Please modify the existing 4.3.x builds to disable update checking.

**Comment by ExDomino** [comment]
I don't know how to explain it, but when the mod trys to see if there is a new version, it checks on internet at a specific address? You could change that address for new versions and set the changelog at the old adress blank, so like that, old versions will see an empty changelog and will display nothing. Or, at least, make that only the new version number is shown, not the entire changelog.
