### ISSUE TITLE
[Feature Request] Merging multiple D latches into one register with single clock input

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#569]
Hello. I want to make a feature request. The subject of this request is simple - allow stacking transparent latch to make a register. Possible implementation - add new mode that do not have two data outputs, but have data output and clock output. This mode can be activated with a screwdriver.

             data out
                 |
    clock in ---[ ]--- clock out
                 |
              data in

Clock-in/clock-out may be replaced with bidirectional clock wire

**Comment by MrTJP** [comment]
Added via 8c31f3dbeb1604a39c6fa19ee9d4b2761112217b
