### ISSUE TITLE
(Feature Request) Deep Storage Unit / JABBA Barrel Support

### ISSUE THREAD

**Issue by Vaygrim** [MrTJP/ProjectRed#585]
Minecraft 1.7.10 / Forge 1208 / ProjectRed 4.5.0.50 (Latest?)

So I've been delving into your wonderful ProjectRed-Transportation module, and the piping system that is contained within it. I've got one big question.. and one minor question.

BIG QUESTION: At present your Request Pipe interface only shows up to 1 stack worth of contents from a JABBA barrel. I have spoken briefly to ProfMobius about this, to which he replied that this 'bug' was due to ProjectRed not calling the "Mass Storage Interface" (I think. I hope I'm remembering this correctly). Apparently if ProjectRed used the same method supported by MFR's Deep Storage Units.. or JABBA's Barrels, this issue would go away and your Request Pipes interface would register the full contents of a barrel.

SMALL QUESTION: Since NotEnoughItems is currently broken in regards to searching ("@Mod.ProjectRed" only shows the contents of the "ProjectRed" module and not ANY mod with that string in it's ModID), could we perhaps get the other chip upgrade parts for the Transportation System moved OVER to that module? At present I have to bounce back and forth between modules and that's basically asking for trouble. The NEI search function will stop working entirely and quits responding to search results requests. Only solution at that point is to fully restart your client. So when building Project Red stuff.. I have to restart my client a TON just to look up the recipes. Thoughts?

I eagerly await your response in regards to my "Big Question", and thank you in advanced for your time spent reviewing this request.

**Comment by InvaderAZ** [comment]
Any chance of this being addressed soon?  Would be awesome to see entire inventory numbers when using Jabba with the pipe system.

**Comment by MrTJP** [comment]
Got a list of a few things to finish. The routing system is the third one.  I know I've said that Id fix this long time ago, but I keep not liking the way the routing pipes are set up and keep rethinking the whole thing...

**Comment by MrTJP** [comment]
Added via b11f599e1b017fd5111434bb13385acad84753be
