### ISSUE TITLE
Broadcast/Stock Keeper/Crafting system is really weird.

### ISSUE THREAD

**Issue by kenzierocks** [MrTJP/ProjectRed#639]
A few things in this issue:

- Stock Keeper chips are really way too expensive. I have plenty of gold to make broadcast chips, but I can't even make a good system with them until I have a bunch of diamonds.
- Stock Keeper chips are inconsistent. I have one which I upgraded from fill with Block A to fill with Block B, and it still got Block A. Possibly due to crafting pipes.
- Crafting pipes require a broadcast system, which kinda makes sense except that I could do this with Buildcraft when I barely have logs.
- Stock keeper chips need a "stock infinite" function, or there needs to be a new chip, because trying to fill a gold or diamond chest is impossible.
- Crafting currently bugs out when the network changes, and you pretty much have to tear down everything and start fresh.

**Comment by MrTJP** [comment]
Gonna close this for now. Stock infinite has been added.  Crafting has been fixed slightly.  Network state save/load will be added in the future.

**Comment by kenzierocks** [comment]
Thanks~
