### ISSUE TITLE
Particles in pipes are quite laggy

### ISSUE THREAD

**Issue by kenzierocks** [MrTJP/ProjectRed#641]
Every single pipe more complex than a transport has the occasional moving particle effect through the pipes, which is really cool looking and I don't want to get rid of it. However, it's trail is composed of many individual entities, and these die **every** tick and a new one is created. This may have been efficient before the switch to entities having `UUID`s, but now that every new entity creates a new `UUID` the secure random function to generate a new `UUID` just takes up way too much time. Is there a way to rewrite that so it just moves an entity or two along the pipe path?

**Comment by MrTJP** [comment]
Addressed in 85237be0abe6d76365bb8e900c34160787a3da0a.
