### ISSUE TITLE
Some gate request(s)

### ISSUE THREAD

**Issue by Wuerfel21** [MrTJP/ProjectRed#644]
1. Bus logic:
Basic logic gates(AND,OR,XOR) that operate on busses rather than single signals.
This would be very useful where compactnes is important
2. Register:
This one has a bundled i/o, and two single signals: read and write.
when write is on, the contents of the bundled io are stored inside the gate.
when read is on, the contents of the gate are put onto the bus.
This is useful in building computers and such

**Comment by Wuerfel21** [comment]
yes, i love that one, might try doing a 16k ram in a single block space!

**Comment by MrTJP** [comment]
You can create these yourself now with Fabrication.
