### ISSUE TITLE
ProjectRed Compat .jar is bundled with a version of the ComputerCraft API

### ISSUE THREAD

**Issue by ghost** [MrTJP/ProjectRed#652]
As of version 4.5.6, build 57, the ProjectRedCompat jar includes a version -- an outdated version -- of the ComputerCraft API. This interferes with the real version of the API, as included in the ComputerCraft 1.65 jar, and causes crashes in conjunction with mods that depend on that API, like OpenPeripherals.

Original bug report on OpenPeripherals issue tracker: https://github.com/OpenMods/OpenPeripheral/issues/206

**Comment by dan200** [comment]
Project:Red 4.5.12.64 still includes the ComputerCraft API.

**Comment by MrTJP** [comment]
I've actually spent several hours digging though logs and such, but I can't find why. If I don't include them, I get crashes despite the use of @optional annotations.
