### ISSUE TITLE
Block breaker

### ISSUE THREAD

**Issue by Redplayer09** [MrTJP/ProjectRed#653]
I'm not a modder, but something so usseful like the block breaker for automation and easy is not bad at all.
There is NO mods that add breakers only, and i don't want to install big mods like TE or BC just for 1 block.
I think that how this breaker works is when recieves a redstone signal it place a block of air right in front to it, that is my codder-mind idea.
Just give us a little bit of your time to work  on this block ,a lot of people request it, don't we?

**Comment by Respresar34** [comment]
So this will be added?
