### ISSUE TITLE
When blutricity will be added?

### ISSUE THREAD

**Issue by Respresar34** [MrTJP/ProjectRed#660]
I see that you add the cables, but they can't be placed on the ground, also, there is no solar panels or battery boxes, can you add them?.
Just a little part of blutricity:
-Blutricity cable.
-Solar panel.
-Batbox.
-Blulectric furnace.
-Blulectric pulverizer.

**Comment by CubeWrench202** [comment]
@MrTJP Ejem, do you mean Blutricity right?, and why it will never be added?Just because all the tech mods have they own power or use RF/EU whatever is not a reason to don't bring BLUTRICITY to us.
Also, you are NOT making your own power, you are bringing back a part of Redpower, which is the objective or this mod, isn't it?.
"PROJECT : RED
THE OPEN-SOURCE REDPOWER2 SUCCESOR".

**Comment by kenzierocks** [comment]
"Extending redstone functionality to FMP"
"It brings vastly improved redstone control via compact wiring and integrated logic gates."
What says successor? This is not said to be one by the authors.

**Comment by CubeWrench202** [comment]
![project__red___banner_2_by_kasenth-d74i607](https://cloud.githubusercontent.com/assets/8869399/5674108/253f4e14-9784-11e4-9c6c-18fbb56cb78c.png)

**Comment by kenzierocks** [comment]
I see. Successor != Equivalent.

**Comment by CubeWrench202** [comment]
Well, fuck off, don't wanna fight anymore, i'll go to play 1.4.7 to feel good with myself like i always do when a RP2 replacement dev doesn't wants to add RP2 stuff.

**Comment by kenzierocks** [comment]
You have not given very good reasons why @MrTJP should add a random electricity system that has no reason to be here, and also has no real explanation of how it works internally. There will be electricity if it is needed for the future of this mod.

There's also no comparable pipes for RP's pipes, but no one complains about that. Blutricity will end up the same way probably.

**Comment by CubeWrench202** [comment]
It isn't a random electricity system, it is one of the most popular electricity systems of 1.4.7 and lower versions, a little bit of respect please, we are not talking about more swords mod, you are talking about the Redpower electricity, ok?.
Now, a lot of people is requesting a Redpower-like pipes, maybe not so much in the Projectred forum, but yes in other forums, check in google : 
"Redpower replacements", "Redpower tubes replacement" and you will found a lot of threads of poeple searching for a good replacement.
And how this works is too simple, FOR NOW just a simple way to generate power *solar panels*, a way to transfer it *100v power line*, a way to use it *Blulectric furnace*, and a way to save it *battery box*.

**Comment by UndeadZeratul** [comment]
Boy, that escalated quickly...  Jeez.  You know it's very possible to make a Project RED addon for Blutricity.  Project RED doesn't have to add in yet another energy system if it doesn't want to.  Hell, Buildcraft even stopped using MJs.

**Comment by kenzierocks** [comment]
"most popular": Only used by RP.

**Comment by CubeWrench202** [comment]
Well, @UndeadZeratul, you gave a very good idea, i'll see how to start and i'll do it, any ideas for names?, those are mine:
-ProojectTricity.

**Comment by kenzierocks** [comment]
Why not Blutricity if that's what you want. Don't hide the inspiration!

**Comment by CubeWrench202** [comment]
Ha!I'll do it.
