### ISSUE TITLE
Unable To Save World after entering Nether with Multipart/PR

### ISSUE THREAD

**Issue by conker87** [MrTJP/ProjectRed#669]
With Project Red (Base) and ForgeMultipart (with my personal custom modpack), entering the Nether will result in the Nether being unable to save. Entering the Nether portal back into the Overworld results in a crash. This is with Forge 1264.

This only happens with Project Red installed along with Multipart, without PR there is no issue/crash.

Logs, stack and mod list here:
* [FML Log](https://dl.dropboxusercontent.com/u/12803417/fml-client-latest.log)
* [Console Log](https://dl.dropboxusercontent.com/u/12803417/latest.log)
* [Crash](http://pastebin.com/VUFKxkU0)
* [Modlist](https://dl.dropboxusercontent.com/u/12803417/mod.png)

**Comment by MrTJP** [comment]
1) Created new world.
2) Entered Nether.
3) Left Nether.
4) Edited world.
5) Save+Quit
6) Reloaded world.

No issue found.  And don't see any way PR could be causing world problems like this.  Im gonna say its not PR.
