### ISSUE TITLE
Exploration Backpacks: Strange behaviour

### ISSUE THREAD

**Issue by mindforger** [MrTJP/ProjectRed#670]
When the Backpacks are opened, the inventory behaviour gets glitchy, after several moved items by D&D soemtimes the item gets stuck at the cursor and can only be dropped and not beplaced back into any slot

**Comment by simon816** [comment]
Is there a reliable way to reproduce this?

**Comment by MrTJP** [comment]
Cant reproduce. Seems fine to me

**Comment by AnrDaemon** [comment]
It happens intermittently, but items aren't "stuck", you have to click multiple times to get the item off the cursor. I only encountered it in MP so far.

**Comment by AnrDaemon** [comment]
I think I've found somewhat reliable case to reproduce the issue.
Try to pick and place the same item between backpack and inventory. Not shift-click, but exactly pick-put-pick-put.

**Comment by MrTJP** [comment]
I will rewrite container code asap.

**Comment by MrTJP** [comment]
Fixed via aa190f3d63207e845ebd8ab69b57adddff5cf278
