### ISSUE TITLE
Suggestion: Add option to disable automatic FMP download

### ISSUE THREAD

**Issue by ScarecrowKrone** [MrTJP/ProjectRed#673]
I can understand why you've done it; you've built Project Red against a specific version of FMP and unless it was downloaded automatically people would complain. However, when using Project Red in a modpack, especially a Technic Solder modpack, this feature becomes irritating to say the least. Several mods need a new version of FMP and if I try to add a new version through Solder, the launcher won't remove the previous version because it didn't put it there. Ergo, we end up with duplicate FMP's. Adding a config option to disable this from happening would be great for advanced users like myself.

**Comment by simon816** [comment]
The downloading is done by CodeChickenCore's [DepLoader](https://github.com/Chicken-Bones/CodeChickenCore/blob/master/src/codechicken/core/launch/DepLoader.java) which does not have a disable setting. It should download the latest version that any mod requests and remove older versions, if it fails to delete it will mention that in the client log, which may be useful.

If you really need to stop it downloading, open the ProjectRed .jar, open dependancies.info and remove the FMP entry, and make sure the JSON is valid afterwards.

**Comment by MrTJP** [comment]
It doesn't download older versions, and if it does its ChickenBone's bug, probably.  Newer versions are suppose to be accepted.
