### ISSUE TITLE
Bus Input Panel constantly notifying its neighbors

### ISSUE THREAD

**Issue by Victorious3** [MrTJP/ProjectRed#675]
So apparently the Bus Input Panel is constantly notifying its neighbors when enabling the black frequency. Just place it down, toggle black, and see the chunk updates rise.
It's creating some unnecessary load. Tested with 4.5.8.59

**Comment by MrTJP** [comment]
Fixed via 8a469756afe1c6069dba60f5ff5c3e1030d8b6fc

**Comment by Victorious3** [comment]
Thanks a lot! Now I don't have to rewrite my system to check for actual changes ^^
