### ISSUE TITLE
Block breakers and Deployers:

### ISSUE THREAD

**Issue by CubeWrench202** [MrTJP/ProjectRed#677]
To help with automation, requested before, but not implemented yet, the block breaker is easy to code, the deployer a little bit more hard IMO, but you can request help /check other mod's code to get a little help.
This can be useful to this:
https://www.youtube.com/watch?v=jNx2HqaHJGA&index=12&list=PLYvPjygmdL6UVQKmMqlu-qZY9p6Q5Kv3W.
Or this(Your mod doesn't have flax but there is a flax mod out there):
https://www.youtube.com/watch?v=g3Tp2gLtjEM&index=8&list=PLYvPjygmdL6UVQKmMqlu-qZY9p6Q5Kv3W
Or for this tree farm:
https://www.youtube.com/watch?v=FEXRUYE-aJU&index=9&list=PLYvPjygmdL6UVQKmMqlu-qZY9p6Q5Kv3W.
Or for this cobble generator:
https://www.youtube.com/watch?v=_qDaicOwuLc&index=10&list=PLYvPjygmdL6UVQKmMqlu-qZY9p6Q5Kv3W.
Please, we have been requesting for this a lot, you can expend a little bit of your time working on this instead frames or other big thing?We really want it.

**Comment by kenzierocks** [comment]
Why not just get Extra Utilities?

**Comment by CubeWrench202** [comment]
2 Things:
1 - Extra utilities doens't have breakers/deployers, you probably mean open blocks (I think).
2 - Is always the same, "go with other mod", but if you wanna have a RP2 replacement you need the basic, gates and wires are done, so what's next? Basic redstone machines, not frames, frames are something hard to do.

**Comment by kenzierocks** [comment]
Sorry, I just work with a modpack close to Direwolf20 on FTB and OpenBlocks and ExtraUtilities are a bit merged in my head. I guess we'll wait for @MrTJP.

**Comment by simon816** [comment]
There's already a request for both these blocks
#653 Block Breaker
#337 Deployer
