### ISSUE TITLE
More dev(s?) search

### ISSUE THREAD

**Issue by CubeWrench202** [MrTJP/ProjectRed#679]
@MrTJP :
I just note that you are a little bit bussy with school and whatever, have you think in talk to someone to get a new ProjectRed dev?, when the project starts it was you and @Chicken-Bones, but he hasn't been around in PR the latest time, if you will have some free time soon, ok no problems, tell me and i will close this, but if you will be bussy for a long time ,you should search for a new dev.
Don't mind me, you are such an awesome guy/dev, same for Chickenbones, but doesn't matter who good a mod is when there is no an active developer.
Thanks anyways for bring us this mod!.

**Comment by MrTJP** [comment]
k
