### ISSUE TITLE
Set min Timer

### ISSUE THREAD

**Issue by Tencao** [MrTJP/ProjectRed#683]
Currently, there's no way to set the min seconds a timer can go at, resulting in people spamming it on the lowest possible setting on servers which results in a large amount of lag. I've checked everywhere for a setting, and I've found nothing, so I'm putting it here as a suggestion

**Comment by MrTJP** [comment]
Ok, I see the need for this..

**Comment by MrTJP** [comment]
Added via c26254b9f7ace357900516fcd701b433aea71d64
