### ISSUE TITLE
"Gate" request: Bundled Cable color interchanger(?)

### ISSUE THREAD

**Issue by MalkContent** [MrTJP/ProjectRed#684]
Back in RP2 I occasionally came into a situation where I would build a big setup where I had bundled cable A and bundled cable B and i simply needed some cabled to be a different color. Say yellow in A had to be red in B and of course all others had to change, too. You could call it a design flaw, but I would love a small gate or wad-of-wires block that let's you reconnect the colors without having to make 16 interconnections.  
I probably used a bunch of wrong words, but I hope the idea gets across ^^

**Comment by MrTJP** [comment]
I see the use for this in some cases, but this is not a big enough issue to require a separate gate..  Its a design flow, like you said. Sorry mate, afraid not...
