### ISSUE TITLE
Feature Request: Neon Signs

### ISSUE THREAD

**Issue by MalkContent** [MrTJP/ProjectRed#686]
Basically Red Alloy Wire coated in Illumar. That is all :)  
Edit: I would like a detail request to the texture: You should not see the wire in the middle of the Illumar, unlike with insulated wires. This way it could also be used to build flourescent tubes on the ceiling without looking odd.

**Comment by kenzierocks** [comment]
Sounds like a good idea to me.

**Comment by MrTJP** [comment]
Don't think the MC Lighting system would allow for this very easily...  But ill see about it in the future

**Comment by MrTJP** [comment]
Don't think this is feasible without major changes to the lighting system. If a time should come when i want to rewrite it, i will keep this in mind.

**Comment by MalkContent** [comment]
> Don't think this is feasible without major changes to the lighting system. If a time should come when i want to rewrite it, i will keep this in mind.  

Why is that? I mean you already got non fullblock light blocks in the illumination tab.
