### ISSUE TITLE
Crash on startup [v4.5.9.60]

### ISSUE THREAD

**Issue by masterzh** [MrTJP/ProjectRed#691]
Client crash when loading MC. No other mods installed.
crashlog: http://pastebin.com/yikdzSwG

**Comment by simon816** [comment]
@MrTJP has linked the dev version of MrTJPCore instead of the obfuscated version. Hopefully this will be amended soon.

**Comment by CubeWrench202** [comment]
Same crash, we'll have to wait for @MrTJP

**Comment by ate0ate** [comment]
Yup, same here. At least its just a silly little mistake:P

**Comment by CubeWrench202** [comment]
Yes, is funny that a big job can be fucked up by a little mistake xD, atm i'm i download the latest commit of the MrTJPCore, extract it, and i'm making a build using gradlew, not sure if'll work.

**Comment by MrTJP** [comment]
Will have the new one uploaded later today.

**Comment by CubeWrench202** [comment]
Oh, thanks ;)

**Comment by ate0ate** [comment]
I tend to have a terrible time building with gradle.

**Comment by CubeWrench202** [comment]
Anyway it didn't work, we'll have to wait :).

**Comment by ate0ate** [comment]
While we patiently wait, any idea what the deviating lily mentioned in the changelog is?

**Comment by CubeWrench202** [comment]
Patiently?Come on, i want the release NOW, but anyway, i really don't know, my first idea was that the lily is the new way to get flax, but doesn't seems to, i think that is the new indigo flower, but from what i see there is no utility for it :P

**Comment by ate0ate** [comment]
Yeah, I'm feeling pretty impatient myself. Looking through the recent commits further, it seems that the deviating lily is the new method for renewable dye farming. Wonder how that works.

**Comment by MrTJP** [comment]
Temporary download link for MrTJPCore:

http://adf.ly/wVu7v

**Comment by Respresar34** [comment]
Thanks!
