### ISSUE TITLE
[Gate Proposal] Minimum/Maximum Gate

### ISSUE THREAD

**Issue by CollinEddy** [MrTJP/ProjectRed#692]
Minimum/Maximum gate:

This gate has three inputs on the left, right, and bottom. It will take the minimum or maximum analog value of these inputs and reproduce it at the top output. The face of the gate shall be maximized to show a bar graph display indicating the output value. The selected function of the gate can be toggled with a right-click, and would be denoted by a '+' or '-' at the output terminal.

This gate would be useful in applications such as monitoring storage levels, selecting power sources, and acting as a graphical readout for an analog signal.

There exists a complication in that having only two sides connected while in minimum mode will return 0 at all times. This can be overcome by connecting one of the inputs to the remaining input, much like using the 'and' gate with two inputs.

![min_max_gate](https://cloud.githubusercontent.com/assets/8091445/5842180/15c9ee36-a160-11e4-843d-f14919d4f8e6.jpg)

**Comment by kenzierocks** [comment]
I don't understand that complication, it seems that would work fine? This doesn't occur with the AND gate either, unless you haven't screwdriver'd it.

**Comment by MrTJP** [comment]
Min/max. There are many ways of implementing this using current gates.  For example, here is a maximizer using 3 digital converters.
![max](http://puu.sh/eQgxn/959a9b2ee4.png)
