### ISSUE TITLE
Bug Report Time:

### ISSUE THREAD

**Issue by Respresar34** [MrTJP/ProjectRed#694]
First i know that the new release is red (unstable), but if nobody post bugs how you will know that they exist?So this is the list of "Important" bugs that we have:
- You can walk inside Block Breakers/Item Importers, they can be place and work fine, but you can walk cross it like a ghost.

 - Pressure/Resistance tubes can't be placed on the ground.

 - Is a little bit tricky to place a machine (breaker/importer), when you place it on the ground they are not facing to you, always look up, the only way to make them look for you is placing a base block and place the machine in that block.

 - Output face of the Breaker can't be connected to interface pipes, i don't know if the machines are created to work with pressure tubes only, if that is the case, this is intended and not a real bug.

**Comment by Respresar34** [comment]
- The third bug maybe is also intended, if that is the case the next "bug/unimplemented feature" will be usefull:
 - Screwdriver can't rotate PR's expansion machines.

**Comment by Respresar34** [comment]
- Also regular lamps, the full block lamps, are missing the halo on them, they also have the same bug that the expansion machines, you can walk on them like a ghost.

**Comment by MrTJP** [comment]
Crap. This is what happens when I have to build manually. All the files get mixed up.  Pretty much all these are fixed in code again, except the machines are actually only suppose to connect to pressure tubes.

**Comment by Respresar34** [comment]
Well, thanks MrTJP, but you probably need to rest a little bit from modding for today, i mean, all what you have done in 1 day is too much, just rest, thanks anyway :D
