### ISSUE TITLE
Crash during new chunk generation in latest build...

### ISSUE THREAD

**Issue by ate0ate** [MrTJP/ProjectRed#695]
http://pastebin.com/CyxXF9dA

Using forge 1286 and a ton of mods in a new world, crash shortly after world loads.

**Comment by kenzierocks** [comment]
That error means that `BlockLily.canBlockStay(Lnet/minecraft/world/World;III)Z` (also `boolean BlockLily.canBlockStay(World, int, int, int)` in source) was not implemented when it should have been. A bit strange.

**Comment by kenzierocks** [comment]
Got the problem: MrTJPCore isn't refactored for `TPlantBlock.canBlockStay`, meaning that the actual method is missing at runtime. Somehow that method needs to be refactored so that it exists, which may require some hacks.

**Comment by ate0ate** [comment]
I see, thanks! I just experienced the same crash about two minutes into a new world. I found what I'm assuming is the new lilly. Its kind of odd how it displays the light level, water level, and growth stage above it at all times. Sticks out like a sore thumb.

**Comment by MrTJP** [comment]
Some debug code I forgot to remove...

**Comment by Respresar34** [comment]
@MrTJP now you are connect i have to ask if you disable the pressure tubes for now or is a bug that you can't place them?

**Comment by ate0ate** [comment]
I'm still getting this crash, though infrequently, using MrTJPCore 1.0.4.9

**Comment by Respresar34** [comment]
I didn't get any crash, i have to say that @MrTJP did a great job, i'm realling enjoying new tubes, if i have some crash i'll report it.

**Comment by ate0ate** [comment]
I'm no code expert by any means so perhaps its not exactly the same crash. It looks similar ro my untrained eye So far after a couple hours of play I've had it happen only twice when wandering into new chunks. I am using a rather heavily modded instance of 1.7.10, but nothing too exotic. One crash report mentions BoP and fastcraft along with PR, the second is just PR...

first crash...
http://pastebin.com/xv1AdppU

second crash...
http://pastebin.com/uQvhxrHv

**Comment by Respresar34** [comment]
I have a survival world that i created AFTER the last release, with the bugfixes and all that, i generate a lot of chunks and i see lily(s) plants without any crash.
The first crash is a lily seed, make sure of have the latest version of MrTJPCore and PR, because i have them, with a new world after the latest release as i said, and everything runs fine.
The second crash, same, lily, if update versions and create new world doesn't works i don't know, because works fine for me.
I have only Factorization and ProjectRed installed.

**Comment by MrTJP** [comment]
Investigating...

**Comment by ate0ate** [comment]
I appreciate the suggestions, but I also started a new SSP world after the most recent PR updates. I actually started with a fresh instance of 1.7.10 si I'd guess it isn't from the configs since they were all generated new. I have a ton of mods installed though so it may well be a conflict. The crash is rather infrequent and doesn't seem to be caused by the lilly's I find in world. It seems more to happen in areas where the foliage is often lying on the ground in item form due to flowing water or lava or other such world gen events that uproot plants. Other than that, I'm loving the update.

**Comment by Respresar34** [comment]
Same here :), i'm loving it, i whould like to play a server with ProjectRed only with other people :P.

**Comment by HadesDurin** [comment]
get the same crash using latest version of mr tjp core and project red
http://pastebin.com/07j0Fr9c
just exploring an existing world and generating new chunks

**Comment by simon816** [comment]
The problem is that `canBlockStay(Lnet/minecraft/world/World;III)Z` gets remapped to `func_149718_j(Lnet/minecraft/world/World;III)Z` in the obf version and so no longer implements `TPlantBlock#canBlockStay`
So either the canBlockStay signature should be changed in TPlantBlock or there is an error with the srg remapper thing not changing TPlantBlock

**Comment by MrTJP** [comment]
But its an override, I can't simply change the method..

**Comment by kenzierocks** [comment]
@simon816 It's in MrTJPCore and it isn't the same method. Probably should be refactored somewhere else.

**Comment by RAWRwins254** [comment]
@MrTJP Any plans for a fix within the next week or two? If so, I'll let the server owner know (he's having me investigate server crashes) to stick with it for now. We're experiencing this crash as well.

**Comment by MrTJP** [comment]
Yea tomorrow

**Comment by RAWRwins254** [comment]
Alrighty thanks!

**Comment by EXOgreen** [comment]
Heh, was just coming here to report this. I guess ill just give my thanks and leave then :p

**Comment by chloeprince** [comment]
I'm having the same crash.

Here is a crash log:
https://gist.github.com/chloeprince/e2a3b63c7d9500beb5a2

**Comment by MrTJP** [comment]
Attempted fix via 3366dcd93358c84585a1fa01b4093af7a68f7f05
