### ISSUE TITLE
Sequenzer doesn't work

### ISSUE THREAD

**Issue by Reyls** [MrTJP/ProjectRed#697]
Sorry, if this is a duplicate issue. I browsed through the issues but I didn't find any comparable issue.
if I place a sequenzer in my current world this happens: https://www.youtube.com/watch?v=eUTTkFroYtI
It is curious that the sequenzer works fine in a new world.
modlist: http://pastebin.com/3h1kc9Df

**Comment by Respresar34** [comment]
Correct, same bug, PR and FZ installed only and i have that bug, it is a visual/functional bug.

**Comment by MrTJP** [comment]
Nope, working fine for me.  You must be in some type of world with weird timing, like a Mystcraft eternal day age, or its likely another mod doing it.  The sequencer's code wasn't changed...

**Comment by Reyls** [comment]
I'm such an idiot.
/gamerule doDaylightCycle true
thank you for the hint "eternal day"

**Comment by simon816** [comment]
@MrTJP I see you use `world.getWorldTime()` to calculate the angle of the pointer ([`gaterenders.scala:774`](https://github.com/MrTJP/ProjectRed/blob/master/src/mrtjp/projectred/integration/gaterenders.scala#L774)). How about using `world.getTotalWorldTime()` instead.
The total time is incremented regardless of what the `doDaylightCycle` rule is.

**Comment by MrTJP** [comment]
Back when CB and I were designing this gate, we ultimately came to the decision to leave it at world.getWorldTime() because the gate is suppose to be synchronized with world time, as one of its major uses is as a pseudo clock.  RP2's sequencer was purposely created as so as well.

**Comment by Respresar34** [comment]
I actually forget to remove that command, i was on a testing world, so yeah, sorry MrTJP.
