### ISSUE TITLE
Time for alloy smelter now?

### ISSUE THREAD

**Issue by Redplayer09** [MrTJP/ProjectRed#698]
Hey, i know you'll hate me asking this again, but with machines and all that, there is a chance of bring the smelter combiner back?(alloy smelter).
What i mean, is 4 redstone + 1 iron ingot = Red alloy ingot(Red alloy ingots, and other recipes).
1 iron ingot + 1 gold ingot = 2 Brass ingots(Tubes, future frames).
1 iron ingot + 3 lapislazuli = 1 Blue alloy ingot (maybe a use in the future).

**Comment by MrTJP** [comment]
Im working on the progression system, if i think it calls for it, then yes.  But i was hoping to use something completely new.

**Comment by Redplayer09** [comment]
I don't even know what are you planning, but hopefully we'll gate an alloy smelter back.
