### ISSUE TITLE
Block Breaker doesn't output the item buffered in some inventory directly.

### ISSUE THREAD

**Issue by Respresar34** [MrTJP/ProjectRed#699]
Simply it doesn't, you can place tubes down and it will work ok, also you can place nothing and it will push it to the ground, but when you place some inventory (chests, furnaces) it doens't detects them and it still buffering the item.

**Comment by MrTJP** [comment]
Yes, this just wasn't implemented yet.
Added via 3366dcd93358c84585a1fa01b4093af7a68f7f05
