### ISSUE TITLE
Volcano generation strangeness (PR 4.5.10.61)

### ISSUE THREAD

**Issue by ate0ate** [MrTJP/ProjectRed#700]
I'm using  the latest Project Red builds with forge 1291 in a BoP World type and I've noticed that volcanoes seem to be generating oddly. They are much wider than they were in prior versions, which honestly looks pretty decent, but they are so wide that the lava cannot reach the sides to run down ever. So far, all of the volcanoes I have encountered have been like this so it doesn't seem to be an unusual side case. 

Also, completely unrelated and very very minor, but lily seeds are using their unlocalized names.

Pictures in the link below...

http://imgur.com/a/KFrLF/all

Thanks!

**Comment by MrTJP** [comment]
They aren't designed to always have lava running down the side.  The volcano generation isn't perfect always.
