### ISSUE TITLE
Crash when placing enderio redstone conduit above inverter cell

### ISSUE THREAD

**Issue by BBoldt** [MrTJP/ProjectRed#703]
Happened when I updated to latest version of project red, wasn't happening in previous versions.

http://pastebin.com/tc2Atjde

It happens when you place a redstone conduit at the blue spot in this image:
![](http://i.imgur.com/69PQRHA.png)

Mods used:
ForgeMultipart-1.7.10-1.1.1.320-universal
MrTJPCore-1.7.10-1.0.5.11-universal
CodeChickenCore-1.7.10-1.0.4.35-universal
ProjectRed-1.7.10-4.5.10.61-Base
ProjectRed-1.7.10-4.5.10.61-Compat
ProjectRed-1.7.10-4.5.10.61-Integration
ProjectRed-1.7.10-4.5.10.61-Lighting
ProjectRed-1.7.10-4.5.10.61-Mechanical_beta
EnderIO-1.7.10-2.2.7.325

**Comment by MrTJP** [comment]
Fixed via 69ab16d331b6de1a6497fa39fd4612f2b43292cb
