### ISSUE TITLE
Fluid Registry Names Contain Spaces, Can't Reference with MineTweaker

### ISSUE THREAD

**Issue by UndeadZeratul** [MrTJP/ProjectRed#705]
I'm trying to tweak some smeltery recipes with Project:RED's conductive redmetal, but I keep getting issues because the fluid registry name that molten redstone and conductive redmetal are stored under are "molten redstone" and "conductive red metal", respectively.  This is a problem, as when trying to reference those fluids in my scripts, as shown below:

```
var moltenConductiveRedMetal = <liquid:molten conductive redmetal>;
var moltenRedstone           = <liquid:molten redstone>;
```

I get an error stating it can't find the liquid.  I've tried adding quotes around the name, as well as replacing the spaces with other characters such as underscores or periods, but to no avail.  Is it possible to change the fluid registry names (or allow someone else to do so via a config option) to remove the spaces?

For reference, I am using:
* Forge v10.13.2.1286
* MineTweaker v3.0.9C
* Project:RED v4.5.8.59

**Comment by simon816** [comment]
Seems more like an issue with MineTweaker.
Have you tried using upper case? Maybe it's case-sensitive.
The exact names are "Molten Conductive Redmetal" and "Molten Redstone"

**Comment by UndeadZeratul** [comment]
![](https://i.imgur.com/WViaFM2.png)

Nope, I changed it to \<liquid:Molten Conductive Redmetal\> and it still didn't find it.

I can see how this could be a problem on their end, not parsing the text correctly, however it's just as easy to change the name it's registered under, as this is the only mod who's fluids I'm having trouble grabbing due to it being the only on in my pack that uses spaces, which is why I came here.

**Comment by MrTJP** [comment]
Changed names to:
redstone.molten
redmetal.molten

by a6a6d5900826d8400bb106976f95c834f0f23ca8
