### ISSUE TITLE
Trying to Upgrade ProjectRed in Bevos Tech Pack 11 Full

### ISSUE THREAD

**Issue by moltar512** [MrTJP/ProjectRed#708]
I've put the mods in the /mod directory, and i'm getting the following crash report.
I've tried two other versions of Project Red, but for some reason it always crashes.

The following is the crash report for the latest version of Project Red:

http://pastebin.com/8AYsfxsF

**Comment by kenzierocks** [comment]
You've somehow corrupted something. Delete all the PR jars and redownload.

**Comment by MrTJP** [comment]
The problem is you didn't bother to read the instructions on the downloads page.  Mechanical won't work without Integration.

**Comment by moltar512** [comment]
MrTJP, i don't know what you mean:

http://i.imgur.com/5cCPiWv.png

I have both mechanical and Integration?

kenzierocks, i'll try redownloading

**Comment by MrTJP** [comment]
Well, thats very strange. It doesn't show up in the logs at all. I don't think its being loaded..

**Comment by moltar512** [comment]
Don't know why, but I redownloaded and was able to get it to boot up.
Thanks kenzierocks and MrTJP for your time!!

**Comment by simon816** [comment]
Definitely a failed download. `ProjectRed-1.7.10-4.5.10.61-Integration.jar` is 3.33MB, not 20KB as listed in that screenshot.
In future, check the FML log too, it will say something like "Cannot read from jar file"
