### ISSUE TITLE
Minecraft Crash upon startup (1.7.10)

### ISSUE THREAD

**Issue by Maavina** [MrTJP/ProjectRed#712]
I'm starting up a new world (and thus new mods) for a 1.7.10 world with some friends, and I have gotten every other mod we would like to be installed and stable, but Project:Red seems to cause a crash upon loading. At this point, MrTJP core being installed works, but when I add the base mod, there's a crash. I've tried a couple different versions, and always get the crash.

The crash report is here: 
https://www.dropbox.com/s/qzwyz4qps6v1rwi/Crash%20Report.txt?dl=0

**Comment by simon816** [comment]
That version of ProjectRed is incompatible with that version of MrTJPCore
Either update ProjectRed to `4.5.10.61` or downgrade MrTJPCore to `1.0.3.5`

**Comment by Maavina** [comment]
That was the problem. I must have tried every combination except the one that works. Thanks, closing this.
