### ISSUE TITLE
Issue with segment gate rendering

### ISSUE THREAD

**Issue by cdogg111** [MrTJP/ProjectRed#713]
I'm not sure what to expect here i just don't think the segment textures are rendering properly.
here is a picture of what i'm seeing:
![2015-02-07_00 32 22](https://cloud.githubusercontent.com/assets/5360652/6091525/cdee9e1a-ae64-11e4-82cd-63f9c924427a.png)

**Comment by Gwani** [comment]
You should probably add some information on what you expect to see here and how it differs from what you actually get. Otherwise, at least people like me have a hard time seeing whats wrong here.

**Comment by MrTJP** [comment]
Perhaps its a texture pack issue, or the downloads are bad. No such problem on my end. We'll see if it persists in the next version.
