### ISSUE TITLE
Server crash when placing lamps.

### ISSUE THREAD

**Issue by ScarecrowKrone** [MrTJP/ProjectRed#714]
Consistently, whenever I place lamps in multiplayer, the server hangs shortly afterwards and restarts itself. It's not a crash per se, since there is no reference to it in the logs and no crash report is generated. The only message I get is when I am kicked from the server, and it just says this:

http://gyazo.com/ccfea2e97665520b96d7f7a3ec327b72

The relevant versions I am using are:

Project Red: 1.7.10-4.5.10.61.
MrTJPCore: 1.7.10-1.0.5.11.
FMP: 1.7.10-1.1.1.320.

**Comment by ScarecrowKrone** [comment]
UPDATE: Immediately after one of the crashes, the following log printed itself into my server directory:

http://paste.ubuntu.com/10161777/

From what I can understand, Java itself has run out of memory and cannot continue. This makes no sense to me because its a 6 GB server, fairly new, and at the time I was the only player on it. Hopefully this helps you resolve the issue.

**Comment by kenzierocks** [comment]
That's a nearly impossible error. Somehow the VM thread (not any Minecraft bit, bit the actual JVM) has reached a memory limit. Are you on Java 8?

**Comment by kenzierocks** [comment]
Oh, I see you're on 7. Try increasing the PermGen space?

**Comment by ScarecrowKrone** [comment]
It's a rented server. Do I refer this to the technical support team?

**Comment by kenzierocks** [comment]
You can try, I don't know for sure that it's the cause however.

**Comment by ScarecrowKrone** [comment]
Apparently, an SQL server had crashed the node and was using up all the RAM. Fixed now.
