### ISSUE TITLE
Crash with the latest Thermal Expansion

### ISSUE THREAD

**Issue by Neodark7** [MrTJP/ProjectRed#717]
http://pastebin.com/wrY6PFx8

**Comment by simon816** [comment]
It seems a recent version of Thermal Expansion has changed the root package for its classes.
Project Red expects `thermalexpansion.util.crafting` but in that version of TE it's `cofh.thermalexpansion.util.crafting`. You need to backdate TE to `4.0.0B8-23`

**Comment by MrTJP** [comment]
I will fix this once TE is out of beta.

**Comment by KingLemming** [comment]
You should fix this now. You should not be reflecting into that class to register your recipes. Use

https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/modhelpers/ThermalExpansionHelper.java

instead.

**Comment by Neodark7** [comment]
"I will fix this once TE is out of beta." seriously ? the last stable release was like 9 month ago and it was for 1.6.4 ! >.<

**Comment by MrTJP** [comment]
In which case I will fix it now

**Comment by Tsyklop** [comment]
ProjectRed #62 Not Fix this(

**Comment by MrTJP** [comment]
Fixed via 5e5f0de776db8d86d2d7e583a600192db8397dae

**Comment by ate0ate** [comment]
Thanks MrTJP! I appreciate the quick fix.

**Comment by Tsyklop** [comment]
How to apply this fix ? Download source corrected the desired files and then what?
