### ISSUE TITLE
[Feature Suggestion] Relays and faster/filtered Importers

### ISSUE THREAD

**Issue by Paul17041993** [MrTJP/ProjectRed#719]
- Relays should have 9 inventory slots and try to import as much as 4 or 8 itemstacks a second. Internal clock that is on by default and disabled when given a redstone signal.

- Filtered Importers should have 9 slots for filtering and should be able to do 2 or 4 itemstacks a second when given a clock, alternatively could have an internal clock the same as the relays.

**Comment by MrTJP** [comment]
I already have an entire set of machines in mind that includes said functionality.
