### ISSUE TITLE
[Feture Request] Signal Attenuator

### ISSUE THREAD

**Issue by GuestEG** [MrTJP/ProjectRed#720]
I want to suggest a gate to control some analog signal machinery.
There is some mod blocks, that can change their state depending on level of redstone signal they receive. For example: Reika's RotaryCraft Multi-Directional Clutch can change it's output direction dependent on 4 levels of redstone signal.
But there is no compact method to provide different levels of redstone signal to them.
You can actually use comparator in substraction mode, but you need to lower signal for secondary input somehow, and only way I know is to make a long redstone dust wire.
What I suggest is to make a gate which can lower input signal by fixed amount. Basically it is Output = Clamp( (Input - Setting), 0, 15 ).
Function examples:
1) back input is level 15 (usual in digital circuits), setting is 5, front output is level 10.
2) back input is level 7, setting is 9, front output is level 0.
Setting can be changed in gate's GUI or just by Repeater-like click control.

Alternatively, this can be integrated in a comparator gate.

**Comment by MrTJP** [comment]
Bus converter.

**Comment by GuestEG** [comment]
OK, but there is no info about that gate, even search engines shows nothing aside from changelog.
