### ISSUE TITLE
Auto Crafting blocked

### ISSUE THREAD

**Issue by kingjpc** [MrTJP/ProjectRed#723]
Process to  reproduce:
1. Set up one machine that can craft two items. I used a Metal Former from IC2 Experimental, set up with the ability to make Iron and Tin Plates
2-4 Must be done quickly or use a crafting method that takes time like the Metal Former/Auto Crafting Bench from Build Craft
2. Request 1 of Item 1
3. Request 1 of item 2
4. Request 1 of Item 1
![setup](https://cloud.githubusercontent.com/assets/11088332/6286284/9e4caad2-b8fd-11e4-8799-aad1e25a322b.png)

Result:
Item 1 is created and left in the output of the machine
Item 2 ingredients are pulled to the machine ready to be crafted.
Because the output has the result of crafting Item 1 in it the process stops
![metalformerblocked](https://cloud.githubusercontent.com/assets/11088332/6286285/9e4db0b2-b8fd-11e4-82f1-89de418fa005.png)

**Comment by MrTJP** [comment]
If the crafting pipe is configured right, that piece should also be extracted.. (And, I know, very delayed response. Forgot about this..)

**Comment by MrTJP** [comment]
Crafting logic has been fixed slightly.  See if it works correctly now.
