### ISSUE TITLE
Update ThermalExpansion

### ISSUE THREAD

**Issue by shadowfacts** [MrTJP/ProjectRed#724]
ProjectRed|Comaptibility uses a class (thermalexpansion.util.crafting.SmelterManager) which does not exist in ThermalExpansion 4.0.0RC1-119, causing a [crash][log].

CC @KingLemming say something if I'm wrong. This is just my interpretation of the crash report, might be wrong.

[log]: http://pastebin.ubuntu.com/10350093/

**Comment by MrTJP** [comment]
Update PR.
