### ISSUE TITLE
Crash: Registering texture  java.lang.ArrayIndexOutOfBoundsException: 143

### ISSUE THREAD

**Issue by digger5** [MrTJP/ProjectRed#725]
Hi, when i try to start my minecraft instance i receive a crash.

Since it's screaming project red I will post it here and let you take a look.

http://pastebin.com/6WD5RC3N

**Comment by 3Pixel** [comment]
Same problem here, it is only crashing with projectred activated.

**Comment by unpure** [comment]
I got the same crash and its not realy a user error.
The problem seems to be:
B:3Dlogicwires=false

If you set this to true (atleast with build #64 and #65) the game starts fine.
If this is set to false the game will crash with the given error message.

**Comment by warezit** [comment]
@digger5 I can confirm I was having this same issue

@unpure I can also confirm changing this value to "true" fixed the problem for me.

Thanks!

**Comment by MrTJP** [comment]
Fixed with cc4bbb01c03eab7fedf47a3148816c6926cce702
