### ISSUE TITLE
edge connection support for TileEntities

### ISSUE THREAD

**Issue by moTechPlz** [MrTJP/ProjectRed#730]
I would like to ask for the addition of edge connection support for tileEntity'ies. So we can have something like this; 
![2015-03-01_23 54 06](https://cloud.githubusercontent.com/assets/11203133/6446968/254a8a2c-c10f-11e4-98ee-e621fa921a6e.png)![2015-03-01_23 54 11](https://cloud.githubusercontent.com/assets/11203133/6446969/2672ea84-c10f-11e4-928e-b5ff493b34ef.png)
instead of this;
![2015-03-01_22 17 41](https://cloud.githubusercontent.com/assets/11203133/6446978/3b572b86-c10f-11e4-8195-4ddce476f7c4.png)![2015-03-02_18 57 11](https://cloud.githubusercontent.com/assets/11203133/6446982/3eb81c86-c10f-11e4-8f28-4cd3f470608d.png)
![2015-03-02_19 02 59](https://cloud.githubusercontent.com/assets/11203133/6446983/3fc8a334-c10f-11e4-8f3a-458e16c52503.png)![2015-03-01_22 14 58](https://cloud.githubusercontent.com/assets/11203133/6446973/32758616-c10f-11e4-8e3d-6054195544a0.png)

**Comment by MrTJP** [comment]
They already connect to other parts such as gates.  They can only connect around corners if the tile is specifically made that way.
