### ISSUE TITLE
Inverter Gates Not updating with a Cell input

### ISSUE THREAD

**Issue by BlackMesa23** [MrTJP/ProjectRed#731]
It appears that in the current stable version as of now of Project:Red (4.5.13), the Invert gates NOR and NOT do not update correctly when an input is applied through any of the cell gates (null cell, invert cell, buffer cell, and the AND cell). I have tested them all with the same results.

Invert cell with the input lever toggled off
![2015-03-02_20 19 55](https://cloud.githubusercontent.com/assets/11286272/6456561/e14a44fa-c11a-11e4-9498-9bdb5dee88ca.png)

Invert cell with the input lever toggled on
![2015-03-02_20 19 59](https://cloud.githubusercontent.com/assets/11286272/6456570/fea975a2-c11a-11e4-9048-aff15fe9305d.png)

As you can see, the Invert gate updates initially, however if you pull the lever, it doesn't update. I found that in order for the Invert gate to update, you have to put a block next to it or put a wire in between the cell and the Invert gate. This did not happen in previous versions of Project:Red. It is also not a problem with the resource pack (I tested it and I'm not sure why it would be a problem with the resource pack, but still tested it anyway). This is on a custom modpack which only has Project:Red, Forge, Forge Multipart, Not Enough Items (with CodeChicken Core of course), and Optifine installed.

The map I was playing on was actually taken from a modpack with a previous version of Project:Red so I decided to create a new creative world to test it and see if it was just a problem with the map. In the new world the problem was still there so I figured that it was a problem with Project:Red and not a problem on my end.

**Comment by MrTJP** [comment]
Fixed via 642c0e9a190671655de44f46ff8bc8b0b4139de2
