### ISSUE TITLE
Are colored trees coming back...

### ISSUE THREAD

**Issue by krovex101** [MrTJP/ProjectRed#732]
... or are they now replaced by the coloured flowers?
I loved the effect of having a pastel coloured forest in my worlds. I am finally updating my server to 1.7.10 but I am worried I will have to add something like ChromatiCraft just to get the trees (too excessive in my opinion!). Is this just temporary (to be returned "Soon™")  or permanent? if so could a config setting be added to restore them?
Thanks in advance
Krovex101

**Comment by MrTJP** [comment]
They are replaced for good, because the trees couldn't really be farmed without the help of other mods.

**Comment by ThEpicFail** [comment]
Can You give "us" me and "krovex101" a private link so you don't have to deal with others saying "WE HAVE A BUG" or say "i'm no longer responsible for bugs of the trees" then distribute the tree version!

Hope this works!
