### ISSUE TITLE
Project Red wiki bug

### ISSUE THREAD

**Issue by wsb9** [MrTJP/ProjectRed#734]
Project Red wiki does not allow me to upload images (registered user). I'm sorry posting it here, but I did not found any support contacts on the wiki and just don't know where to report a bug. Thanks!

Error report:

[0bde4a19] /wiki/Special:Upload Exception from line 1871 of /home/galenhan/public_html/projectredwiki/w/includes/filerepo/file/LocalFile.php: Could not acquire lock for 'CPT_basic_setup.png.'

Backtrace:

#0 /home/galenhan/public_html/projectredwiki/w/includes/filerepo/file/LocalFile.php(1174): LocalFile->lock()
#1 /home/galenhan/public_html/projectredwiki/w/includes/upload/UploadBase.php(738): LocalFile->upload(string, string, string, integer, array, boolean, User)
#2 /home/galenhan/public_html/projectredwiki/w/includes/specials/SpecialUpload.php(467): UploadBase->performUpload(string, string, boolean, User)
#3 /home/galenhan/public_html/projectredwiki/w/includes/specials/SpecialUpload.php(186): SpecialUpload->processUpload()
#4 /home/galenhan/public_html/projectredwiki/w/includes/specialpage/SpecialPage.php(363): SpecialUpload->execute(NULL)
#5 /home/galenhan/public_html/projectredwiki/w/includes/specialpage/SpecialPageFactory.php(584): SpecialPage->run(NULL)
#6 /home/galenhan/public_html/projectredwiki/w/includes/MediaWiki.php(275): SpecialPageFactory::executePath(Title, RequestContext)
#7 /home/galenhan/public_html/projectredwiki/w/includes/MediaWiki.php(584): MediaWiki->performRequest()
#8 /home/galenhan/public_html/projectredwiki/w/includes/MediaWiki.php(435): MediaWiki->main()
#9 /home/galenhan/public_html/projectredwiki/w/index.php(46): MediaWiki->run()
#10 {main}

**Comment by Mastergalen** [comment]
Some misconfigured file permissions were the problem.

Thanks for reporting this :)

You should now be able to upload images without issues now.
