### ISSUE TITLE
Bug Segment Display Gate ID4516:32

### ISSUE THREAD

**Issue by Andre2511** [MrTJP/ProjectRed#736]
Hello
when i put ALL Insulated cable at 1 Bundled Cable and all activate then Grey insulated and Black insulated Wire isn't used but in the Segment Display Gate i just get shown that all Segments activated out of the right Segment the top middle one 
i load some screenshots up
https://www.dropbox.com/sh/6ymd20gltawr0kg/AABb7qvhC90LkBaGvr1m4c3ta?dl=0

Hope you can fix it :+1:

**Comment by MrTJP** [comment]
Your textures are messed up. You are either using a texture pack that is messing it up or the mod files are messed up and need to be downloaded again. Make sure you grab the latest version.

**Comment by Andre2511** [comment]
I Downloaded it again (again 4.5.14 build #66 built on 05-03-2015
I downloaded Base integration Mechanical_beta Lighting world and Compat and put them in Mods folder but again the same :( i dont use a texture pack/ressource pack) is it possibile that you Upload all Jars in a zip folder that i can download and know that they are ok?

**Comment by Andre2511** [comment]
Ok with the new build everything Works fine ty
