### ISSUE TITLE
Fix harvest requirement on pipes

### ISSUE THREAD

**Issue by kenzierocks** [MrTJP/ProjectRed#737]
[WALIA Harvest Data](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1295067-waila-harvestability-how-can-i-harvest-what-im) reports that I can't harvest Item Transport Pipes by hand, even though I can.

1.7.10, PR 4.5.14.66.

![image of non-harvest bug](http://i.imgur.com/4mC0pMz.png)

**Comment by MrTJP** [comment]
Does this occur even with other multiparts such as framed wires?

**Comment by MrTJP** [comment]
Going to assume this is a WAILA/Harvest Data problem.
