### ISSUE TITLE
Incomplete Volcano Worldgen

### ISSUE THREAD

**Issue by Carbon-Key** [MrTJP/ProjectRed#738]
Hello,

No crash here, just some weirdly formed volcanoes that happen quite often and don't look so hot.  I'll include screenshots of what I mean down below.  I am running build 4.5.14 #66 of Project Red and 1.0.5.11 of of the core.  As per Player from the IC2 team's instructions I am also obligated to mention that I am running FastCraft version 1.19.  A full modlist can be found at http://pastebin.com/igU63Sjy. It is also worth mentioning that this issue started as early as 4.5.12 build #64 for me.

Here are two screenshots of an affected volcano, one with chunk boundaries highlighted and one without:
![2015-03-08_16 05 39](https://cloud.githubusercontent.com/assets/10481639/6547428/4300f4d6-c5ae-11e4-86f9-865e4fc71d86.png)
![2015-03-08_16 05 50](https://cloud.githubusercontent.com/assets/10481639/6547429/4a1420f4-c5ae-11e4-8485-95970a625955.png)

Let me know if you'd like any additional information on my end and I hope to hear from you soon.  Keep up the good work!

**Comment by Serejai2** [comment]
Same issue here. Happens without any other mods running, using the latest version of Forge and PR #66. Regenerating the chunks does not help.

Most volcanoes appear to have one good side and three sides that fail to generate.

**Comment by BionicFelps** [comment]
I've seen this as well, not sure if it's related, but I've also seen trees generated on top of the volcanoes.  The first log is missing, but the rest of the tree is still there.  (so there's a 1 block space between the bottom log and the volcano).  Happens with both vanilla trees and mod trees.

**Comment by MrTJP** [comment]
Volcanoes fail to generate when the chunk literally doesn't exist yet, which is why there are entire sections just missing. It would be difficult to check all chunks before starting generation, because the size of the volcano is determined during generation. Hard fix...

**Comment by katzenpapst** [comment]
Have that issue, too. Would some kind of check on chunk generation be possible, like, "if currently generating chunk is next to a volcano, run that part of volcano generation again, with the same seed"? Whenever a volcano generates, it could save a list of chunks it should generate on, to make this easier

**Comment by lilrichy** [comment]
Same problem on the server I am running. I have flown around a lot and have not seen any properly formed volcanos. These used to work just fine and were a great addition to the world. Now they are ugly flat sections of basalt with 1 lava source in the center.

**Comment by MrTJP** [comment]
Was fixed in latest MrTJPCore.
