### ISSUE TITLE
Comparator never stops sending signal

### ISSUE THREAD

**Issue by FireSight** [MrTJP/ProjectRed#739]
Hooking a Comparator up to a Witches Cauldron so that it sends a redstone signal when water is put in the cauldron. The signal triggers a repeater that activates a fluiduct that then drains the cauldron. After the cauldron is drained, the Comparator SHOULD stop sending a redstone signal, but my testing shows that the signal will continue to be sent until either the cauldron or comparator are removed.

**Comment by bookerthegeek** [comment]
Perform a block update next to the comparitor.

I assume the cauldron is no performing a block update upon inventory change

**Comment by MrTJP** [comment]
Does this issue occurs even with the vanilla comparator?
