### ISSUE TITLE
Crafting Pipes/Chips and IC2 RE-Battery BUG

### ISSUE THREAD

**Issue by marcus-garvey** [MrTJP/ProjectRed#740]
Hey, 

I think I found BUG
Something goes wrong with the RE-Battery detection if you build a crafting chain with the pipes and crafting chips
You can reproduce the problem if you try to build a IC2 Generator.
I have one regular chest and 2 Auto Crafting Tables from Buildcraft.
The chest and crafting tables are connected like this
```
- = Transport Pipe
IP = Interface Pipe
CP = Crafting Pipe
RP = Request Pipe

         Chest      Table 1       Table 2
 RP ----- IP----------CP-------------CP
```
The interface pipe of the chest has only the broadcast chip
The chest stores all ingredients for the RE-Battery and all ingredients for the Generator except the RE-Battery.

Table 1 and also the crafting chip of table 1 is configured to build a RE-Battery
http://wiki.industrial-craft.net/index.php?title=RE_Battery
Table 2 and also the crafting chip of table 2 is configured to build a Generator
http://wiki.industrial-craft.net/index.php?title=Generator

Now if you use the request pipe to fetch a generator you get always the message "Missing Item RE-Battery" but when I request a RE-Battery, I get an RE-Battery. If I put this RE-Battery into the chest, I can also request a generator.

In a bigger setup I also saw, that the RE-Battery will be build but then the crafting pipe of the generator doesnt grab it, so that the generator never get build because of the missing item.

I hope this are enough information to reproduce this error.

Best Regards

**Comment by MrTJP** [comment]
I remember RE batteries having the same problems with other crafting systems. Its because when you use them, their internal id changes, meaning that a used RE battery is essentially a different item then an unused, fresh one.  So, when you configured the two crafting pipes, one of them is configured for a new battery, while the other one is for a used one.

**Comment by marcus-garvey** [comment]
I didn't used them, I created new ones and used them for the setup up.
I had the same behavior in creative modus. IDs was always the same
