### ISSUE TITLE
Some gate request

### ISSUE THREAD

**Issue by AY-28** [MrTJP/ProjectRed#742]
Bundled Latch / Relay / Multiplexer: Latch, upon receiving a pulse from the right or left, or both, to output held in other Bus output of Bus.
Relay only while receiving an RS signal from the right or left or both, the output of Bus other Bus.
Multiplexer, when not receiving an RS signal, and outputs the output of the left Bus other Bus, when receiving RS signal, the output of Bus other Bus.
(Since Japanese English is poor.)

**Comment by moTechPlz** [comment]
Until they include these parts, try making your own with this; http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2352247-integrated-circuits-alpha-ics-for-minecraft

**Comment by AY-28** [comment]
Thank you

**Comment by MrTJP** [comment]
Something is currently in the works, will allow you to make your own gates. This won't be necessary.
