### ISSUE TITLE
[BUG] "Different" Data Cards

### ISSUE THREAD

**Issue by TomShkurti** [MrTJP/ProjectRed#743]
Data cards appear to take on some sort of additional NBT tag or some other element when placed in a player inventory versus when they are crafted. This makes supplying them with LogisticsPipes difficult, as automatically-crafted cards will run through the system WITHOUT acquiring the tags, cards put in a supplier pipe will have been in the player's inventory and WILL have acquired the tag, and LogisticsPipes will not use one to supply a demand for the other. This may affect other inventory-management or logistics systems that discriminate based on NBT information.

**Comment by TomShkurti** [comment]
Update: It is apparently possible to move data cards in and out of the player inventory without altering their metadata, but I am unable to do this reliably or determine the conditions which causes one or the other thing to happen.

**Comment by MrTJP** [comment]
NBT is added when the card is used. Before that it isn't suppose to be.. Can you verify this?

**Comment by TomShkurti** [comment]
Was able to reliably reproduce the change. Having a data card in the player's hand and right-clicking it will cause ALL data cards in the player inventory to change NBTs.

There may be other conditions during which this may appear, will continue testing.

**Comment by MrTJP** [comment]
Cannot reproduce.  All cards remain docile and unchanged until put into something that adds data to them, such as an Extension pipe.
