### ISSUE TITLE
Backpacks latency issues

### ISSUE THREAD

**Issue by SirWilli** [MrTJP/ProjectRed#744]
hey,

there are some ways to dupe items with the backpacks if you have a high ping on the server.
For example you right click in the air and click again on a barrel. It will open the backpack and place it in to the barrel. This doesn't work with a low ping as you have not enough time to click twice.

There are few other ways with the same issue which I don't want to make public here as it can get abused.

**Comment by MrTJP** [comment]
This is important: The gui opens, then the backpack is placed into the barrel. Does the bag also remain in the players hand?

**Comment by SirWilli** [comment]
No, the bag goes in to the barrel and only the gui stays.

**Comment by TheBatski** [comment]
what?

**Comment by bookerthegeek** [comment]
Steps to reproduce:

1. With bag in hand,  right click on anything that let's you store the held item on A right click.  (i.e. jabba barrel)
2. Before the item is removed from your hand, right click to open the bag gui.
3. Transfer anything from gui into your inventory.
4. When exiting the gui, there will be no bag in hand. The bag is in the barrel.
5. All items removed from gui are still in the players inventory. 
6. All items are also still in the bag, the one stored in the inventory from step one.

**Comment by MrTJP** [comment]
Patched with 2efea537e55d6629f33b52c3a4292494852c8fe7
