### ISSUE TITLE
Extra broadcast chips on same inventory show duplicates to the network

### ISSUE THREAD

**Issue by kenzierocks** [MrTJP/ProjectRed#747]
An example of this is: One chest, containing `1` dirt block. Attach `4` broadcaster chips with default configuring, add a request pipe somewhere, and open the request pipe. The GUI displays `4` dirt blocks. Now add `3` more dirt blocks to the chest (total: `4`), and you'll notice `16` dirt blocks in the GUI. Try requesting `1` dirt block, and you'll end up with all of them.

**Comment by MrTJP** [comment]
Intentional (sort of).  Its not the network's job to check for and negate improper setups like the one you described. Technically, its working correctly, as it is asking each broadcaster for what they see.

**Comment by kenzierocks** [comment]
That's slightly annoying then, I was hoping to get faster retrieval speeds.

**Comment by MrTJP** [comment]
Have you played with the upgrades?

**Comment by kenzierocks** [comment]
What upgrades? *digs through wiki*

**Comment by MrTJP** [comment]
Wont find on wiki yet, system isn't finished yet. (Right-click with the Router Utility)

**Comment by kenzierocks** [comment]
Alright, will poke.

**Comment by kenzierocks** [comment]
@MrTJP I think my last point about extracting 1 item brings out 4 might be a problem, but it doesn't occur on a "normal" system.
