### ISSUE TITLE
Segment Display Gate: Visual Bug.

### ISSUE THREAD

**Issue by Kasatome** [MrTJP/ProjectRed#749]
I have a slight issue with the Segment display.  I have all the Project:Red mods as well as the Thermal series (Thermal Expansion, Thermal Foundation, Thermal Dynamics) and their dependencies.  I have redownloaded the Red mods several times now, clearing my browser cache each time.  I am using version 4.5.14.66 of Project:Red.

Screenies:
http://i190.photobucket.com/albums/z34/Kasatome/2015-03-20_14.17.23_zpscjsjnpml.png
http://i190.photobucket.com/albums/z34/Kasatome/2015-03-20_14.30.21_zpstzquozv6.png
http://i190.photobucket.com/albums/z34/Kasatome/2015-03-20_14.17.31_zpsrcrnkrhi.png

As you see, I have no Resource Packs, so there is no issue with bad/missing graphics.  This happens on my Laptop (AMD APU Graphics) and on my desktop (nVidia 750).  

Running Java 7 and latest Display drivers. (If this helps at all)

I looked in the jar, and the textures look nothing like what is being displayed.
Any Ideas?

**Comment by MrTJP** [comment]
Was fixed, wait for next version.
