### ISSUE TITLE
Redstone Powered Pipes

### ISSUE THREAD

**Issue by TheBatski** [MrTJP/ProjectRed#751]
I saw on your wiki page a framed red alloy wire going into transport pipes like the redstone pipes from red power.  I can't seem to get that working in v4.5.14.66.  Should I get a later version, or am I doing it wrong?

**Comment by MrTJP** [comment]
Probably missed this step.  You have to right click them with a Redstone Block strip.  It is outlined in the wiki..

**Comment by TheBatski** [comment]
Oh.  Thank you so much Mr. TJP
