### ISSUE TITLE
[Feature Suggestion] Blutricity and Frames

### ISSUE THREAD

**Issue by TheBatski** [MrTJP/ProjectRed#752]
I remember from RP2 the frames, and blutricity.  I loved them so much that I would have made an addon to Project Red to do so.  I know that there are replacements for frames, just not blutricity.  I would very much like you to add those.

**Comment by simon816** [comment]
https://github.com/MrTJP/ProjectRed/issues/660
To quote from MrTJP
> _Bluetricity_ will never be added.

I _think_ there are plans for some sort of electricity system if it would be useful for the mod, will see what @MrTJP says.

**Comment by MalkContent** [comment]
credit where credit is due. blutricity was a genius name for a system that ran alongside a redstone focused mod

**Comment by MrTJP** [comment]
Not any time soon.
