### ISSUE TITLE
[craft issue] Can't craft Anodes

### ISSUE THREAD

**Issue by psoftware** [MrTJP/ProjectRed#754]
Hi, I'm using ProjectRed in a single player survival mode map. I tried to craft some of ProjectRed items and I need Anode item. I saw crafting mode here: http://projectredwiki.com/wiki/Anode , see the screenshoot, I can't get it :/  Can be this a mod issue?

![2015-03-28_01 17 09](https://cloud.githubusercontent.com/assets/9152027/6878984/02ade50c-d4e9-11e4-86e1-f3f77abb52bc.png)

**Comment by kenzierocks** [comment]
According to the code, the recipe is the inverse of that. Swap plates for redstone, redstone for plates.

**Comment by kenzierocks** [comment]
@MrTJP I'm fixing it right now on the wiki.

**Comment by kenzierocks** [comment]
Fixed!

**Comment by psoftware** [comment]
Ok, now it works! Thanks (:
