### ISSUE TITLE
Project Red not compatible with latest Thermal Expansion

### ISSUE THREAD

**Issue by maxim3210** [MrTJP/ProjectRed#756]
http://pastebin.com/qSWSesZH (Log)

I updated a few Cofh mods that were compatible before but when I updated them to any other version they crashed my launcher every time I launched.

**Comment by kenzierocks** [comment]
Update PR.

**Comment by maxim3210** [comment]
Thank you so much, I read the error log before and tried updating but got another error log but this time I did it it was fixed. :D
