### ISSUE TITLE
[CurseForge] Client only downloads Base module

### ISSUE THREAD

**Issue by pennywis3** [MrTJP/ProjectRed#757]
Disclaimer: I hope this is the right place to put it, but I couldn't think of a more suitable one.

The way the CF project is currently set up, the Curse Client will only install the Base module, and there is no way of getting the rest from within the client. I don't suppose Curse will fundamentally change this, as the additional files are usually used for source, API and documentation purposes.
Instead, I would suggest setting up different projects for each module and configuring them as related projects.
Also, MrTJPCore is not listed as a required library.

**Comment by kenzierocks** [comment]
IIRC MrTJPCore is handled by DepLoader or whatever.

**Comment by MrTJP** [comment]
I am aware of both issues. Working on the auto upload for the build script.

**Comment by MrTJP** [comment]
Fixed.
