### ISSUE TITLE
No favicon on website

### ISSUE THREAD

**Issue by TriforceOfKirby** [MrTJP/ProjectRed#758]
There is no favicon on the [website](http://projectredwiki.com/wiki/Main_Page). There is a `<link>` to favicon.ico in the `<head>` element, but it results in a 404 (Not Found) error.

Could an icon be added?

Alternatively, consider using `<link rel="icon" href="data:;base64,iVBORw0KGgo=">` if there is no icon to prevent HTTP requests.

**Comment by MrTJP** [comment]
Resolved.
