### ISSUE TITLE
ProjectRed issues with FMP

### ISSUE THREAD

**Issue by NovusTheory** [MrTJP/ProjectRed#760]
ProjectRed will crash Minecraft if any version other then the automatically downloaded ForgeMultipart is used. Some mods in a modpack require a higher FMP version and ProjectRed refuses to co-operate with that version of FMP. Please enable compatibility with other versions.

**Comment by MrTJP** [comment]
FMP may have changed things in newer versions that make PR incompatible. Simply wait for another version of PR.
