### ISSUE TITLE
The integration mod make my game so laggy!!

### ISSUE THREAD

**Issue by Sam5s** [MrTJP/ProjectRed#766]
Hello!
First, I love your project red mod!
I play on minecraft 1.7.10, the project red mods can run perfectly on 1.7.10 without the integration mod. I can't find any incompatible 

My mod list is so basic:

industrialcraft-2-2.2.710-experimental
ProjectRed-1.7.10-4.5.15.75-Lighting
ProjectRed-1.7.10-4.5.15.75-Base
ThermalDynamics-[1.7.10]1.0.0RC8-105
ThermalExpansion-[1.7.10]4.0.0RC7-141
ThermalFoundation-[1.7.10]1.0.0RC7-62
CoFHCore-[1.7.10]3.0.0RC7-211
IC2NuclearControl-2.2.0a-Yolo
[1.7.10]DamageIndicatorsMod-3.2.3
Reis-Minimap-Mod-1.7.10
CraftGuide-1.6.8.1
Railcraft_1.7.10-9.5.0.0
[1.7.10]Treecapitator-universal-2.0.4
InventoryTweaks-1.58-147
buildcraft-6.4.5
WR-CBE-1.7.10-1.4.1.9-universal
NotEnoughItems-1.7.10-1.0.4.94-universal
CodeChickenCore-1.7.10-1.0.4.29-universal
AdvancedSolarPanel-1.7.10-3.5.1

And ProjectRed-1.7.10-4.5.15.75-Integration

It's wierd, I don't really think it's the problem of my computer performance.

I can't wait for using your mods!

Looking forward to your answers, thank you very much in advance.

**Comment by MrTJP** [comment]
If it is lagging simply by installing the mod, then it is a problem with your setup. You either have too much going on and your computer can't handle it, or another mod is interfering. Try removing some to narrow down the problem, and then I can help you.
