### ISSUE TITLE
Request: Lanterns on Microblocks

### ISSUE THREAD

**Issue by speakerrob** [MrTJP/ProjectRed#771]
I've seen that compatibility was added to allow lanterns on fence posts, but it would be nice to also impart that ability on posts made via the Forge Microblocks API, so that you can take advantage of different block types from other mods.

ATLauncher: Resonant Rise 3 (v3.2.4.3)
MC: 1.7.10
Forge: 10.13.2.1291

**Comment by MrTJP** [comment]
FMP issue, fixed by 8f1787441267418301085205fb6e70270aa07d80

**Comment by speakerrob** [comment]
I'm using PROJECTRED-1.7.10-4.5.15.75 in the Resonant Rise 3 pack and it doesn't allow me to post lamps on microblocks. What release version was this fixed in?

**Comment by MrTJP** [comment]
One of the recent few versions of FMP, i believe.

**Comment by speakerrob** [comment]
Noted, thank you.
