### ISSUE TITLE
Cannot add Upgrades to Chips

### ISSUE THREAD

**Issue by klangg** [MrTJP/ProjectRed#772]
With forge-1.7.10-10.13.2.1291-universal, ProjectRed-1.7.10-4.5.16.77-Compat.jar, ProjectRed-1.7.10-4.5.16.77-Lighting.jar, ProjectRed-1.7.10-4.5.16.77-World.jar, ProjectRed-1.7.10-4.5.16.77-Base.jar. ProjectRed-1.7.10-4.5.16.77-Integration.jar, ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar, CodeChickenLib-1.7.10-1.1.3.127-universal.jar, ForgeMultipart-1.7.10-1.1.2.331-universal.jar, and MrTJPCore-1.7.10-1.0.5.12-universal.jar installed.

When using the Router Utility to upgrade any Chip with any type or number of Upgrade, the Upgrade are consumed and the slot in the Router Utility does not turn green. Using shift to examine the Chip displays a Chip with no upgrades. Using the Chip in a Pipe the behavior is consistent with a non upgraded Chip.

No relevant entries appear in the client log. The only ProjectRed error in the Server log is:
``` [07:16:17] [Server thread/INFO] [FML]:   Unknown recipe class! mrtjp.projectred.core.ShapelessOreNBTRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter ```

I can include the full logs if requested.

With forge-1.7.10-10.13.2.1291-universal, ProjectRed-1.7.10-4.5.15.75-Compat.jar, ProjectRed-1.7.10-4.5.15.75-Lighting.jar, ProjectRed-1.7.10-4.5.15.75-World.jar, ProjectRed-1.7.10-4.5.15.75-Base.jar. ProjectRed-1.7.10-4.5.15.75-Integration.jar, ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar, CodeChickenLib-1.7.10-1.1.3.127-universal.jar, ForgeMultipart-1.7.10-1.1.2.331-universal.jar, and MrTJPCore-1.7.10-1.0.5.11-universal.jar installed, behavior is as expected and works properly.

**Comment by MrTJP** [comment]
Fixed via 082411886f9fadbef0d9dd214d7c9cbb6e56cd1c
