### ISSUE TITLE
Suggestion: Ignore/check Meta/NBT/Oredict options for Stock Keeper Chips

### ISSUE THREAD

**Issue by Gwani** [MrTJP/ProjectRed#773]
Hi there!

For some automation setups it would be of advantage to be able to configure the aforementioned options.

As a use case example: I'm currently running a ComputerCraft controlled IC2 nuclear reactor which always keeps certain quantities of reactor components and fuel rods in a chest used for automatic refilling. The items are requested from the component/fuel storage using Stock Keeper Chips. This works quite well, except that damaged components (e.g. partially used fuel rods) are not requested from the storage. In my setup i'd like to use up damaged components first before using brand new ones - the ComputerCraft script already takes care of that, but it doesn't get any damaged items to select from, since the attached Stock Keepers don't provide them.

**Comment by MrTJP** [comment]
I will have to do something about this, since as of now, requests have to be very specific. You can't request something and have it pull an item that doesn't match EXACTLY.  Its a current limitation to how requests work.

**Comment by MrTJP** [comment]
Added via b11f599e1b017fd5111434bb13385acad84753be
