### ISSUE TITLE
Tinker's Construct Smeltery Issue

### ISSUE THREAD

**Issue by SacredTomba** [MrTJP/ProjectRed#774]
In the recent updates of TiC, you can smelt redstone into Destablized Redstone from Thermal Foundation. The problem lies with your recipe for redstone. It actually overrides it, which honestly isn't useful in the slightest because I wanted to make Signalum in the Smeltery, which as of right now is impossible.

**Comment by MrTJP** [comment]
Seems like many mods want redstone liquified..  I wish TC would add it themselves.  Im pretty sure I had my recipe in long before TF, but I am open to suggestions about what to change it to..

**Comment by SacredTomba** [comment]
Last time I checked it was TiC adding it themselves in a recent update for total Thermal Foundation compability.

**Comment by MrTJP** [comment]
I don't see TC's own liquid redstone block in the code, they might have merely added the recipe, but the actual block (destabilized redstone) is from TF.  (In which case, I can't use it)

**Comment by bochen415** [comment]
Had that issue today. Removed PR-compat and everything works in the smeltery... but I lost cc/te/other compatibility.

**Comment by kutschkem** [comment]
Same problem here, maybe a section in the config for enabling/disabling compatibility with different mods would do?

**Comment by kutschkem** [comment]
Also, not being myself a mod developer, isn't there something like a fluid dictionary, similar to ore dictionary?

**Comment by usafphoenix** [comment]
it's called the fluid registry, i believe.

**Comment by MrTJP** [comment]
You can now disable each compatibility module independently in the configs. For now, disable TC if it is problematic. I will see about registering the fluids another time.
