### ISSUE TITLE
Block Breaker will not break Osmium Ore (Mekanism)

### ISSUE THREAD

**Issue by thorjelly** [MrTJP/ProjectRed#775]
Osmium ore has a low mining level, iron I think. The ProjectRed-Expansion block breaker doesn't destroy it at all, for some reason. It does work with the OpenBlocks block breaker. Should be easy to test. The Block Breaker should be able to break this ore.

**Comment by MrTJP** [comment]
Cannot reproduce.  Block breaker has no problems breaking an Osmium ore.
