### ISSUE TITLE
[BUG} Lamps and Inverted Lamps let sky light through

### ISSUE THREAD

**Issue by tweak42** [MrTJP/ProjectRed#776]
Both the normal and inverted colored lamps let sky light (SL) pass through after powering on/off using a lever.  Forcing a block update will stop SL from passing through.  Vanilla Redstone Lamps do not have this behavior.

FTB Infinity 1.4.1 / ProjectRed 1.7.10-4.5.15.75

**Comment by MrTJP** [comment]
Fixed with commit to MrTJPCore
