### ISSUE TITLE
pipe isuess

### ISSUE THREAD

**Issue by Redd56** [MrTJP/ProjectRed#777]
whenever I request a item in a pipe it crashes my single-player server (but not my game) it outputs this error: Exception in thread "PR RoutingThread #0" [11:15:23] [PR RoutingThread #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: mrtjp.projectred.core.lib.LabelThrowable 
and before if i had requested a item that was in a chest 200 blocks away It DESPAWNS :,(

**Comment by MrTJP** [comment]
I need the full log.

**Comment by Redd56** [comment]
that is all that happens and i dont know how to get more detail. Is there a way to get a more in depth way of looking at what my singleplayer server is doing?

**Comment by Redd56** [comment]
and also I had an idea on why the item disappears/despawns. could it be that the pipes are out of my chunk distance

**Comment by MrTJP** [comment]
Could be, try chunk loading it, and if it works, then theres your problem.

**Comment by Redd56** [comment]
also the microblocks sometimes scratch that Always crash me. was that just a 4.4.5.44 bug?

**Comment by Redd56** [comment]
kk il try it next chance i get*

**Comment by Redd56** [comment]
XD it number 777 XD first issue and it picks a triple triple
