### ISSUE TITLE
Feature Request - Delete items after x seconds

### ISSUE THREAD

**Issue by Tencao** [MrTJP/ProjectRed#778]
On my server, I've seen some pretty messy setups involving the pipes, to the point where the pipes get filled with hundreds of items, and they never go away, causing immense client and server lag that cant be cleared up until the entire pipe network is deleted. Is there anyway to add a config option where if an item has been inside the pipe for x amount of seconds, they will be deleted? This would solve this problem entirely and keep servers healthy.

**Comment by MrTJP** [comment]
If the pipes were configured correctly, this will not happen.  This problem can easily be solved by providing a last-resort path for all items to travel to.

**Comment by Tencao** [comment]
The issue is, players on a server don't do this, and it's hard to expect admins to check every single pipe system created, hence this been a quick easy solution

**Comment by abaw7** [comment]
As opposed to dealing with time, it might be easier to give an option to remove an item in transit if it has bounced more then X Times. It'd be simple to add an int value to the item's metadata, and keep counting everytime it bounces. If it goes over the configurable limit, delete or do something with it (Possibly throwing it into the world).

**Comment by MrTJP** [comment]
Okay yea that's an easy solution. The network can keep track of how long it's been wandering without a destination.

**Comment by abaw7** [comment]
Couldn't help but notice that the issue hasn't been removed from it's closed state, if you want to do this, might be best to leave it open and add a flag for a reminder

**Comment by abaw7** [comment]
Just wanting to make sure this didn't get forgotten

**Comment by MrTJP** [comment]
Added via aa190f3d63207e845ebd8ab69b57adddff5cf278
