### ISSUE TITLE
[suggestion] Semi Conductive wire

### ISSUE THREAD

**Issue by Ianaver** [MrTJP/ProjectRed#781]
I always loved redstone wire however I think it would be nice if you added one little tiny thing.....

Description: Unlike their pure redstone counterparts made to go the distance, this wire is semi                     conductive and is mainly used for measuring signal strength/or for strength control max distance is 16 blocks like redstone powder/dust. If followed through with the suggestion only 2 wires which are completely compatible with gates etc which are Framed and normal.... Suggested materials for crafting are semi-conductive redstone (3 lapiz + 1 redstone = 4 semi-conductive redstone) then semi-conductive ingots which are crafted like normal red iron ingots (I think that's what its called) and the wire recipes which are the same as their pure counterparts... I suggest that the wire is blue not only because I believe it looks nice but also to easily distinguish it from normal redstone wire, also I think making it give off a light level of like 3 or 4 when lit would look cool or just to make it kind of have that neon lit look like the buttons but with varying intensities of blue to make it look like it gives off a fake light source, plus it looks nice

P.S. this is kinda useless but also I think that a variable strength lever (gives off a varied amount of redstone current 1-16 based on the user's specific imput on what it should be) would be nice. :)

**Comment by MrTJP** [comment]
Use a Bus Converter gate.

**Comment by Ianaver** [comment]
ok
