### ISSUE TITLE
Dev env does not start

### ISSUE THREAD

**Issue by dbazim** [MrTJP/ProjectRed#785]
Got en error on MC start
CodeChickenCore : minimum version required is 1.0.6
and
The mod NotEnoughItems (Not Enough Items) requires mod versions [CodeChickenCore@[1.0.6,)] to be available
in logs/fml-client-latest.log
I have 
.gradle/caches/modules-2/files-2.1/codechicken/CodeChickenCore/1.7.10-1.0.2.9/bf496d4b599f16ef55703c3942f86e317aac6520/CodeChickenCore-1.7.10-1.0.2.9-dev.jar
after ./gradlew --refresh-dependencies setupDecompWorkspace

How to get the dev env started?

**Comment by MrTJP** [comment]
Simply do setupDecompWorkspace first. Then unlink the 1.0.2.9 manually (NEI deps seem to be be messed up) then download the required dev version for CCC and put it in the mods folder.

**Comment by dbazim** [comment]
Ok. I will try.
thanks
