### ISSUE TITLE
[BUG] Block Breaker changes blocks 

### ISSUE THREAD

**Issue by MySt1k** [MrTJP/ProjectRed#786]
https://youtu.be/52mJVixR5mE

ProjectRed v4.6.0
ThermalExpansion-[1.7.10]4.0.1-182
forge 1.7.10-10.13.3.1388

It works not only with TermalExpansion, but also with other blocks that have meta data

**Comment by MrTJP** [comment]
ThermalExpansion's blocks don't properly implement the getDrops method.  Perhaps someone should let them know...

**Comment by MySt1k** [comment]
All right. Now I'll tell them about it.

But what about the other modes? With some of them the exact same problem.
BlockBreaker remove meta data in the destruction, and it is very scary.

**Comment by MrTJP** [comment]
Yes, if other mods are having the same problem, then it is the same cause. There is something I can do to to 'catch' all the dropped items like TE's terrain smasher does (instead of actually asking the block for what it should drop), but it is not an ideal solution.

**Comment by MySt1k** [comment]
I think you need to solve a problem on the side of the fashion ProjectRed, for other modders are not quite agree edit your fashion just be one mechanism from another fashion responded well.
Sorry for my english, I'm from another country ...

**Comment by MySt1k** [comment]
A response was received from the KingLemming, please read the topic.

**Comment by MrTJP** [comment]
Fixed via 4ae7e52a06d315484426d9d019962b7b43b7a20e
