### ISSUE TITLE
microblock crash

### ISSUE THREAD

**Issue by zortag** [MrTJP/ProjectRed#787]
PROJECT RED 1.7.10-4.6.0.79 (all modules)
FORGE 10.13.3.1403-1.7.10
CODECHICKENCORE 1.7.10-1.0.6.44

holding a microblock (glass cover in my situation) in hand will crash the game

Crash report
http://pastebin.com/PTwYJMF7

removing project red will solve the problem, so it is involved (or the cause) in the issue

**Comment by MrTJP** [comment]
Currently investigating source of this crash...

**Comment by MrTJP** [comment]
Seems like this issue was caused by a bad file of either ForgeMultipart or CodeChickenLib.  I was able to reliably fix the issue by deleting both FMP and CCL and then starting minecraft and letting the DepLoader re-download them for you.
