### ISSUE TITLE
Lag spike/crash after placing red alloy wires

### ISSUE THREAD

**Issue by Droideka30** [MrTJP/ProjectRed#788]
OSX Yosemite v 10.10.3
MC 1.7.10
Forge 10.13.2.1291
MrTJPCore-1.7.10-1.0.6.13
Project Red 1.7.10-4.6.0.79 [all components]
Other mods: Baubles, CodeChickenLib, ForgeMultipart, buildcraft, buildcraft-compat, chicken chunks, codeChickenCore, CoFHCore, ender storage, gravity gun, ichunutil, minefactory reloaded, netherores, NEI, portal gun, Redstone Arsenal, Thermal dynamics, thermal expansion, thermal foundation, translocator, WR-CBE

This issue is triggered by placing one of the ProjectRed: Integration components. It has happened with red alloy wire, XOR gates, and NOR gates so far. This only happens sometimes when placing one of these components; it seems fairly random. Immediately after placing the piece, all game audio stops and MC freezes for about 3 seconds. For the next minute or so, gradually increasing lag spikes occur every few seconds. Ultimately, the game freezes, necessitating a force quit.  Sometimes it displays the "shutting down internal server" screen, but then freezes on that screen instead of closing. I suspect this might be due to the interaction of Project Red with another mod or set of mods, since I haven't been able to replicate this in an instance running solely project red.

Log: http://pastebin.com/fvpgC7kx

**Comment by kenzierocks** [comment]
`Caused by: java.lang.OutOfMemoryError: PermGen space`

You have a lot of mods, and Java has ran out of room to store them. Increase your permgen space (google it) or use Java 8 instead.

**Comment by Droideka30** [comment]
Will 128m suffice?

**Comment by kenzierocks** [comment]
It depends, trial and error is the best way to figure it out. 128 will probably be good, but test.

**Comment by Droideka30** [comment]
Thanks for the help!
