### ISSUE TITLE
Close opened backpack when picked up instead of blocking the pick.

### ISSUE THREAD

**Issue by AnrDaemon** [MrTJP/ProjectRed#790]
It would be highly convenient to be able to pick opened backpack.

**Comment by MrTJP** [comment]
Cant do that. It would let people duplicate their items.

**Comment by AnrDaemon** [comment]
Could you please explain, how picking up closed backpack could lead to item duplication?

**Comment by MrTJP** [comment]
When the stack is moved the inventory can't be saved. So you could pull items out, move the stack and then open it again with those same items still inside. And besides, if the gui were to close, you would end up dropping the bag anyway, not more convenient at all.

**Comment by AnrDaemon** [comment]
Not "gui close", but "backpack close. I often need to sift through multiple bags in a line, and constantly closing inventory isn't pleasing.
Anyway, if it is not possible to detect, if the cursor is free or is dragging someting, then it is a showstopper indeed. Also, ouch for Mojang. I though such idiotic practices are long since gone in the early days of MMO development.

**Comment by AnrDaemon** [comment]
On a related issue, [Tinker's Construct](/SlimeKnights/TinkersConstruct) implements something that works up to a desired mechanics, while solving the issue described by you - moving items when switching backpack will drop moved items.
