### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by THEVOLCO** [MrTJP/ProjectRed#791]
Hi,
im getting this Crash Report when i try to Launch my game.

Crash R-eport:
http://pastebin.com/t30empQq

**Comment by simon816** [comment]
The problem is in the error message
>  Invalid id 9555 - maximum id range exceeded.

You have too many mods. Remove a mod that adds block to the game.

**Comment by THEVOLCO** [comment]
isn´ there a different way? :(

**Comment by simon816** [comment]
Nope. It's likely that mod authors are not being efficient with creating block IDs, they should use the meta value but a lot of mods don't :(

**Comment by THEVOLCO** [comment]
is there a way to increase the Maximum id range?

**Comment by simon816** [comment]
No, that would mean changing the save file format and only Mojang are the ones to do that.

**Comment by THEVOLCO** [comment]
is this still a Problem in 1.8?

**Comment by simon816** [comment]
The format was not changed so it will be the same. Hopefully modders will take advantage of the block state system to not waste IDs.

**Comment by MrTJP** [comment]
It will continue to be a problem until such a time comes when Mojang/Microsoft increases the ID range, which will likely not happen.
