### ISSUE TITLE
Framewire can't use with wire on lamp block

### ISSUE THREAD

**Issue by YueLengM** [MrTJP/ProjectRed#794]
I found that framewire can't be connected to alloy wire on lamp block.
![2015-05-24_11 49 44](https://cloud.githubusercontent.com/assets/11801894/7786615/127a2cba-020d-11e5-976f-4773618a945c.png)

**Comment by MrTJP** [comment]
Fixed via aa190f3d63207e845ebd8ab69b57adddff5cf278
