### ISSUE TITLE
Issue with microblocks

### ISSUE THREAD

**Issue by Roversword** [MrTJP/ProjectRed#797]
Hi all

Sorry for bothering, however, I think this might need some attention from your side as well (at least "maybe").
There is an issue at Chicken-Bones concerning microblocks and in the trace there are information about project red. So I am not sure this is isolated to Chicken Bones:

Issue: https://github.com/Chicken-Bones/ForgeMultipart/issues/335

My text:
See: http://pastebin.com/kMmTuVA4
Using the same version of Forge and ForgeMultipart (Forge 10.13.3.1408-1.7.10 and ForgeMultipart 1.7.10-1.2.0.344) and Project Red 4.6.1-80 and MrTJPCore 1.0.7-14

We found out on our own modded server using glass panels. You can make the glass panels. But once you want to drop then into the "hot bar" from your inventory the launcher crashes.

Additional info:
We made the glass panels using the stone saw provided by project red.

Thanks for looking into it.

**Comment by kenzierocks** [comment]
You want FMP 334. See #796 and #789.
