### ISSUE TITLE
Control Redstone Torch with wire or make Redstone Repeater coverable

### ISSUE THREAD

**Issue by NitroxydeX** [MrTJP/ProjectRed#805]
Hey Mr_TJP,

I wondered why you made wires that can't turn on or off a redstone torch through a block. I thought wires replace redstone in a better way?!
You can control it via you PJ Redstone Repeater but you cant place microblocks around it. Any solutions?!

**Comment by MrTJP** [comment]
1) They do.
![pic1](http://puu.sh/ifWNb/d58bf42538.png)

2) You can.
![pic2](http://puu.sh/ifWRY/86b70c4384.png)

**Comment by NitroxydeX** [comment]
You can't control it in the Minecraft-Style... Thats the Problem:

![2015-06-07_19 53 45](https://cloud.githubusercontent.com/assets/9305576/8025267/488a8ae6-0d4f-11e5-9b3b-161a96efe04c.png)

And FMP:

![2015-06-07_19 54 36](https://cloud.githubusercontent.com/assets/9305576/8025266/483dab86-0d4f-11e5-90e9-b16e1ca9f503.png)

**Comment by NitroxydeX** [comment]
Okay.... Why the heck you can't use insulated wires for that? Alloy Wire works... But. WHY?

**Comment by MrTJP** [comment]
Because they are insulated...
And you obviously can't use a cover in places that would intersect the gates.

**Comment by NitroxydeX** [comment]
But they are not insulated at the side they are connectet to the block.

**Comment by MrTJP** [comment]
These mechanics have been in place since RP2 and will not be changing.

**Comment by NitroxydeX** [comment]
I don't know where the logic is but okay. Your choice
