### ISSUE TITLE
Relatively high memory overhead compared to other mods

### ISSUE THREAD

**Issue by Uristqwerty** [MrTJP/ProjectRed#806]
I was looking at what used memory in a FTB infinity instance, and it appears that Project red - Integration uses nearly 140 million bytes to store gate model data (visualvm reports mrtjp.projectred.integration.RenderGate$#1 as having a retained size of 139,986,407; this correlates with a similarly large memory difference in average heap usage when Integration (and Mechanical) are removed from a test Minecraft instance)

While this does not make the game unplayable, the only other mod in infinity with comparable heap usage is decocraft, and increases the appeal for pack creators to use mods other than PR if they wish to reduce overall pack requirements (and thus reach a slightly larger playerbase, or scale to larger base complexities).

**Comment by MrTJP** [comment]
It is far better than pulling them from disk when needed. If a reduced size is necessary, use the flat gates flag in the configs.  Don't see anything else that can be done.
