### ISSUE TITLE
Wiki text is incorrect for NOT gate

### ISSUE THREAD

**Issue by cperepelitsa** [MrTJP/ProjectRed#808]
The **Usage/Logic** section says:
*"The outputs are disabled by default. When the input receives a signal, all the enabled outputs are powered."*

Obviously, this is precisely the opposite of how the NOT gate works; the outputs are *enabled* by default, and *disabled* when the input receives a signal.

**Comment by MrTJP** [comment]
Whoops.  Obviously, that entry was meant for the OR gate. Fixed.
