### ISSUE TITLE
stone bricks cant be crafted

### ISSUE THREAD

**Issue by SkinHeadBaby** [MrTJP/ProjectRed#809]
the latest version of the mod ProjectRed-1.7.10-4.7.0pre1.84-XXX_beta not sure which part of it breaks crafting stone bricks 
it makes the recipe say stone bricks with ID -001 or something like that
and the textures is one side of stone bricks the actual name is null when you press F3 + H
when i craft the said item the game crashes

**Comment by MtnDrew** [comment]
I can second this. I have singled it out to being a problem with either Project Red or it's dependency FMP. 4 stone crafts Stone Bricks with ID -1.

**Comment by kikisp** [comment]
+1.. new version mess stone badly.. one of the bricks cant be crafted..it gives them id of -1.
its definitely project red because i have tested without mod and all its ok..

**Comment by SkinHeadBaby** [comment]
downgrade to the previous version until fixed :)

**Comment by Joshwoo69** [comment]
Project red is the culprit. I have this issue too with NEI. Checken bones sent me here.

**Comment by MrTJP** [comment]
Will fix, disable spreading moss in the configs in the mean time.

**Comment by MtnDrew** [comment]
Ahh. Ok it's working now. Thank you.

**Comment by McJty** [comment]
I had an issue in RFTools due to this too. Mossy cobblestone dimlet failed to register and crashed the game.

**Comment by Wolf68k** [comment]
version: 4.7.0pre1.84

I haven't tried crafting them but I do know that for me they replaced stone bricks with AE2 wooden cranks.

These first 2, there should be stone bricks for the walls
http://i.imgur.com/Cqkb6Mt.jpg
http://i.imgur.com/YV5BJHS.jpg

These last 2, I'm standing on what should be stone brick, oddly enough unlike the first 2 images there are no wooden cranks on the ground.
http://i.imgur.com/JV8khqO.jpg
http://i.imgur.com/pIYfREO.jpg

**Comment by CubeWrench202** [comment]
@Wolf68k That's kind of funny xD!

**Comment by ate0ate** [comment]
Haha, my witchery town walls were made entirely out of certus ore! Before that it was Kiparis planks from ancient trees. Seems to be whatever block gets assigned to ID 255. Took forever to narrow it down to project red as the culprit.

**Comment by MrTJP** [comment]
Fixed via d131a8d28c41b65241f9e05a015984ca071a3ce2
