### ISSUE TITLE
Stone Bricks substituted

### ISSUE THREAD

**Issue by nightmare2018** [MrTJP/ProjectRed#812]
When you enable moss spread in the configs for project red it disables the normal stone brick block. Also disabling blood magic's blood altar from working.
And we had resolved the issue realizing the issue is moss spread.
Case here
https://github.com/WayofTime/BloodMagic/issues/356#issuecomment-112578254
and he referenced code
here
https://github.com/MrTJP/ProjectRed/blob/d69f7ee0575b111b7c0cb00bd6a99e1082acd778/src/mrtjp/projectred/exploration/proxies.scala#L55
and here
https://github.com/MrTJP/ProjectRed/blob/d69f7ee0575b111b7c0cb00bd6a99e1082acd778/src/mrtjp/projectred/exploration/proxies.scala#L47

**Comment by WayofTime** [comment]
Adding to this, I believe the route cause is this as well: https://github.com/MrTJP/ProjectRed/issues/809

**Comment by MrTJP** [comment]
Again, this is caused by the broken alias system in forge. It has since been fixed.
