### ISSUE TITLE
Server tick loop crash with new Version

### ISSUE THREAD

**Issue by MtnDrew** [MrTJP/ProjectRed#813]
I'll preface with the fact that I'm not sure this is even a problem with ProjectRed. The reason I'm creating an issue here is because the game started crashing when I updated to today's new version, and it seemed to be resolved when I disabled spreading moss in the config again. 

I got the crash three times with the same issue before I configured it. The first one happened a bit after starting my world, and the two after that happened immediately when I tried to load it up again.

Everything is working now, but I'm posting this crash report anyway just in case it could be helpful.

http://pastebin.com/wEP2PYQ8

**Comment by halvors** [comment]
I think this is a MrTJPCore issue, see MrTJP/MrTJPCore#9.

**Comment by halvors** [comment]
@MtnDrew You should downgrade to the previous version for now, there seems to be a crash that needs a bugfix release. So downgrade in the meantime :+1:

**Comment by Dream-Master** [comment]
I get the same error. Stay with the previous Version until it is fixed.

**Comment by MrTJP** [comment]
Fixed with MrTJPCore.  Will be uploaded shortly.

**Comment by halvors** [comment]
@MrTJP Will you update Project Red so that this version is automatically downloaded?
