### ISSUE TITLE
Electrotine Thermal Expansion Integration Issue

### ISSUE THREAD

**Issue by oitsjustjose** [MrTJP/ProjectRed#816]
So, it's hard to describe, but here's the flaw that I've found:

![ss 2015-06-18 at 01 15 06](https://cloud.githubusercontent.com/assets/3887324/8238578/53f703f8-15bc-11e5-874e-75fa61991283.png)

This is because you've registered Electrotine Alloy as "ingotElectrotine" and Electrotine Dust "dustElectrotine". Thermal Expansion automatically puts 2 and 2 together and assumes the dust is a pulverized version of the ingot. My only thought / suggestion is changing "dustElectrotine" to "powderElectrotine" or just plain "electrotine".

**Comment by MrTJP** [comment]
But then it would go against the naming conventions. The solution here is to have Thermal Expansion include a way to blacklist certain dusts in their API.

**Comment by EXTER7** [comment]
Suggestion: change the name of 'Electrotine Ingot' to something like 'Blue Alloy Ingot' (ingotBlueAlloy) or 'Electrotine Alloy Ingot' (ingotElectrotineAlloy), since currently the dust and the ingot are made of different materials, but have the same name.

**Comment by MrTJP** [comment]
Electrotine *Alloy* Ingot.

![genius](https://cloud.githubusercontent.com/assets/1957405/8422081/d18326e4-1ea4-11e5-8958-7908a175a28c.jpg)

Will do. It actually is an alloy anyway, you mix it with iron...

**Comment by MrTJP** [comment]
Fixed via 57cded5ca6f448727f635256e81bc20a1429b4ba.
