### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by Sunconure11** [MrTJP/ProjectRed#818]
Um, this weird error pops up in a rather large modpack I am trying to develop with the aid of another user, and we think it might be connected to an issue with Project Red and OpenComputers.

http://pastebin.com/KurYJeD8

It happens without Fastcraft as well.

It appeared after all of the utility mods were added.

**Comment by MrTJP** [comment]
Duplicate of #817, #815, #814, #813, #812
