### ISSUE TITLE
Gate request: 7-segment decoder

### ISSUE THREAD

**Issue by flarn2006** [MrTJP/ProjectRed#822]
Since we have the 7-segment display, I think it would be useful to have a block that works like the real-world 4511 IC--that is, it takes a binary signal, and turns it into something that can be fed to a 7-segment display for a hexadecimal output. (The letters A, b, C, d, E, and F all have obvious 7-segment representations.)

The built-in 7-segment display has room for two digits, so this gate should support that as well. Since two hexadecimal digits is only 8 bits, and the bus has room for 16 bits, maybe it would make the most sense to have each gate support decoding 4 digits, so as to make use of the entire bus width. This way, two 7-segment display gates can be hooked up to give a 4-digit display.

When I first saw the 7-segment display, I looked for a gate like this, and when I couldn't find one, that seemed like something that was sorely missing.

Let me know if you need any more information.

**Comment by MrTJP** [comment]
I understand the need for such a thing. However, it seems more suited if such a gate was left for the user to implement themselves with the IC fabrication mechanic coming Soon.
