### ISSUE TITLE
Are the copper/tin ores suppose to only be minable with an Iron pickaxe?

### ISSUE THREAD

**Issue by Jade2311** [MrTJP/ProjectRed#824]
The ores get destroyed when using a stone pickaxe. There is not an itemed dropped, but if I use an Iron pickaxe the copper/tin ores are dropping the corresponding ores. Is this working as intended? I thought that copper/tin could be mined with stone pickaxes, at least in the other mods like Galacticraft and Thermal Expansion?

**Comment by MrTJP** [comment]
You are correct. Fixed via d802c3eb6953d9b9b10c8dd8fb4a1d206afdac35
