### ISSUE TITLE
More configuration options for the Exploration module

### ISSUE THREAD

**Issue by JakobOvrum** [MrTJP/ProjectRed#825]
When using ProjectRed with other mods, it would be nice to be able to disable certain items from the Exploration module, such as the backpacks, the item barrel and the wool gin.

It would also be nice to be able to disable the various gem tool recipies, so NEI doesn't make it seem like they're obtainable in worlds with disabled generation of gems.

Disabling the Exploration module in its entirety is not much of an option anymore now that electrotine has been introduced.

**Comment by Dream-Master** [comment]
With Minetweaker you can disabled items an blocks too.

**Comment by JakobOvrum** [comment]
> With Minetweaker you can disabled items an blocks too.

Thanks for the tip, I'll look into that.

**Comment by Dream-Master** [comment]
I disabled many things too. Look in my repository newhorizons.

**Comment by JakobOvrum** [comment]
I see mostly recipe changes, but I see that items can be hidden from NEI too, so I guess that combination is a decent substitute for disabling an item.

**Comment by Dream-Master** [comment]
I don't disabling Items in NEI now but when my scripts are done i will do this too.

**Comment by MrTJP** [comment]
There can't be a config option for everything. Use MineTweaker or something.

**Comment by JakobOvrum** [comment]
Will do, thanks
