### ISSUE TITLE
What happend with the volcanos?!?

### ISSUE THREAD

**Issue by icke2002** [MrTJP/ProjectRed#826]
Sorry but wtf is happend with the volcanos.
before:  http://i.imgur.com/3GGnZrJ.jpg    huge and pretty
now:     http://i.imgur.com/EI9Z5eb.jpg      small and ugly

I use the 4.6.2.82 version. 
Is that intentional or a compatibility problem with other mods???

**Comment by CubeWrench202** [comment]
Thats because is volcano junior, the son of the original volcano.

**Comment by MrTJP** [comment]
They are more diverse. It is not as common for them to be very high anymore, though it is still very much possible.
