### ISSUE TITLE
Transparent Hand with Project Red and Clay Soldiers Mod.

### ISSUE THREAD

**Issue by GamerM** [MrTJP/ProjectRed#827]
The mod Project Red 4.7.0pre2.87 and Clay Soldiers 2.0.0-beta.2 makes a weird bug. If you run both mods at the same time. It will make your hand transparent. Is there any way you can fix this? Ask me if you need a log and I'm also going to report this issue to the creators of Clay Soldiers. Thanks!

Proof that it does make your hand transparent:

![](http://i.imgur.com/vv7lVtv.png)

**Comment by MrTJP** [comment]
Try to figure out which module causes it.

**Comment by GamerM** [comment]
Update: Bug has been fix with the help of the creator of Clay Soldiers Mod. Seen here https://github.com/SanAndreasP/ClaySoldiersMod/issues/104

Thanks for your help though.
