### ISSUE TITLE
PR:Fabrication server crash upon placing an IO

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#830]
I get a fatal error when placing an Analog IO, when reconnecting however the Analog IO is placed.

Log: https://drive.google.com/file/d/0B090g8mHJkCWY0ZCd0tTSjgtWHM/view?usp=sharing

Edit: I managed to create an IC Chip, but I have no idea what to do with it.

**Comment by MrTJP** [comment]
Fixed via 8b6110375bb6867fce5282e127a2cf4adb29b8cf.

The fixed file was uploaded as a hotfix, so just download the same version again after about 10 minutes and you should be good. (If it still crashes, then that means curse hasn't excepted the new file yet, just try again after a few minutes)

Surround an IC Chip with circuit plates to create your gate.
