### ISSUE TITLE
NoClassDefFoundError - Project Red - Fabrication

### ISSUE THREAD

**Issue by spannerman79** [MrTJP/ProjectRed#831]
All current Project:Red mods
Forge 1448
MC 1.7.10

When attempting to create IC server throws the following error and client disconnect;
http://hastebin.com/oyecenijig.avrasm

On client side only possible errors are;

    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[18 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[18 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[19 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[19 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[20 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[20 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[21 13]
    [Client thread/ERROR] [Project Red]: client part stream couldnt find part Point @[21 13]

**Comment by MrTJP** [comment]
Fixed via a4e99bee4e4630568523a7a8a1f938fbdf65fccf

**Comment by spannerman79** [comment]
Thanks :+1: 
I hate to be a pain but would you consider updating curse with this updated commit?
