### ISSUE TITLE
ic printer not always recognizing components

### ISSUE THREAD

**Issue by JillSwift** [MrTJP/ProjectRed#834]
![2015-06-30_20 44 28](https://cloud.githubusercontent.com/assets/5390031/8446520/13352de8-1f69-11e5-99af-c22ab5979f17.png)

Wants vanilla lever, haz vanilla lever, won't see vanilla lever.

**Comment by MrTJP** [comment]
Strange... Screenshot of blueprint please?

**Comment by JillSwift** [comment]
![2015-07-01_01 20 57](https://cloud.githubusercontent.com/assets/5390031/8449555/a8cc99f6-1f8f-11e5-9f16-16e98e5002ad.png)

**Comment by MrTJP** [comment]
Fixed via 57cded5ca6f448727f635256e81bc20a1429b4ba
