### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Wolf68k** [MrTJP/ProjectRed#835]
CB's DepLoader was unable to download required library ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar Check your internet connection and try restarting or download it manually from http://projectredwiki.com/maven/mrtjp/ForgeRelocationFMP/1.7.10-0.0.1.2//ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar and put it in your mods folder.

This is also followed by the other files also required

I get this with MrTJPcore 1.1.0.24 and 1.1.0.26

**Comment by MrTJP** [comment]
My web server is having issues. Download it manually from curse.

**Comment by Wolf68k** [comment]
Yeah I found that later. Can you add something that would use both curse and your site as optional download locations?

**Comment by lipki** [comment]
I downloaded this in 'curse', but:
CB's DepLoader claims : ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
if I put it, he asks me: ForgeRelocation-1.7.10-0.0.1.2-universal.jar

**Comment by Wolf68k** [comment]
You need both

**Comment by halvors** [comment]
Yeah also experiencing this...

**Comment by MrTJP** [comment]
Just download them manually for now, won't be fixed until my mods are updated with the new links in the deploader code. You've all survived before the cb's dep loader existed :)

**Comment by Sharprow** [comment]
I downloaded it manually tried both versions and still the same message. When I checked the mods folder the file was gone.

**Comment by Wolf68k** [comment]
@Sharprow 
Did you put them in the mods folder or the mods/1.7.10 folder?

**Comment by MrTJP** [comment]
Fixed via 57cded5ca6f448727f635256e81bc20a1429b4ba

**Comment by Wolf68k** [comment]
I'm still getting the same error with 1.1.0.27
