### ISSUE TITLE
ProjectRed Mechanical and Forge Relocation issue.

### ISSUE THREAD

**Issue by mattymatny** [MrTJP/ProjectRed#836]
Hey I posted a quick bit about this on the forum, but figured I should explain it here as well.
So with ProjectRed being labeled the "RedPower2 Successor" I would expect it to work fairly similar, however I have found something that is not working as I would expect.

When using a Block Placer to deploy a Frame in the world next to a Frame Motor or Frame Linear Actuator, I would expect that when activating the motor it would move the Frame and not the Block Placer along with it. However that is just what its doing. And in the case of the Frame Linear actuator is has the same effect. I know that what I am trying was possible back in RedPower2, so I am wondering if you have decided to change the way these blocks work together, or if this is a bug/oversight. If it is a bug, you probably just need to make the deployment face of the Block Placer not interact with Frames.

Let me know if you need a further explanation or more information.

**Comment by MrTJP** [comment]
This was a design choice, because it doesn't make sense for some machines not to stick on the face while others do.  What you are trying to do is still very much possible, you just need one more motor to put the deployer back in place when it is moved by the frames.

**Comment by mattymatny** [comment]
Thanks for the reply. I understand it was a choice and appreciate the suggestions on how to deal with it. My only concern now is that doing it this way makes it kinda hard to keep the Block Placer wired up properly as it will be moving constantly.
