### ISSUE TITLE
ticking screen

### ISSUE THREAD

**Issue by Corvorosso** [MrTJP/ProjectRed#837]
i have a crash when placing blueprint on "ic printer"

java.lang.NullPointerException: Ticking screen
        at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
        at mrtjp.core.item.ItemKey$.get(itemident.scala:19)
......
...

full crash log : http://pastebin.com/znMNHLLN

**Comment by FinalZZ** [comment]
You should probably explain when you got the error

**Comment by MrTJP** [comment]
Caused because some mod is being stupid and adding a recipe with a null ingredient. Technically not my fault, but I can add a check to prevent this...

**Comment by MrTJP** [comment]
Fixed via 57cded5ca6f448727f635256e81bc20a1429b4ba
