### ISSUE TITLE
cells (and, null, buffer, invert) in fabrication design

### ISSUE THREAD

**Issue by cdogg111** [MrTJP/ProjectRed#838]
crossing wires is a must have

**Comment by MrTJP** [comment]
I agree. That's why they have been in development :)

**Comment by cdogg111** [comment]
oh nice

**Comment by cdogg111** [comment]
would you be willing to make a bundled cell?

**Comment by MrTJP** [comment]
Null, buffer, and invert cell added by 57cded5ca6f448727f635256e81bc20a1429b4ba. And cell coming next update.
