### ISSUE TITLE
IC Workbench needs more inventory space

### ISSUE THREAD

**Issue by cdogg111** [MrTJP/ProjectRed#839]
I'm trying to build an 8-bit ksa and there are not enough slots to put the required items.
in my opinion 2 more rows would be sufficient. if it takes up too much space on the GUI
you could make it scrollable... just some random suggestions. your work is greatly appreciated, and Project Red is an ingenious mod and can be pretty educational.

**Comment by MrTJP** [comment]
I've thought a fair bit about how to add more slots without actually making the Gui larger. I think I will make it pull items from an adjacent chest.

**Comment by cdogg111** [comment]
that's even better

**Comment by MrTJP** [comment]
Printer can now pull items from inventories on any side (except top) as of 57cded5ca6f448727f635256e81bc20a1429b4ba

**Comment by cdogg111** [comment]
you're the best.

**Comment by vistoyn** [comment]
Hello! 
Can it work with Applied Energistics 2: ME Chest and ME Interface?
