### ISSUE TITLE
Blueprint cloning recipe

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#840]
Currently there is no way to clone blueprints, but it's too hard to redraw them by hand. Please, add some cloning recipe, for example, with filled blueprint in center and some empty blueprints around it.

**Comment by MrTJP** [comment]
Added via 57cded5ca6f448727f635256e81bc20a1429b4ba.

Place empty blueprint with existing blueprint in crafting table.
Written blueprint can also be emptied now by placing it in crafting table alone.
