### ISSUE TITLE
Unclean shutdown, can't start server

### ISSUE THREAD

**Issue by thisischrys** [MrTJP/ProjectRed#842]
Server spams on startup https://www.dropbox.com/s/d4mgyb7q5fl1t0u/fml-server-latest.log?dl=0
removing mrtjpcore and redpower lets it start cleanly, but obviously I want to avoid that.
Is there some file I need to delete? Kind of like how you need to fix world.dat for vanilla servers?

**Comment by MrTJP** [comment]
Link is unreachable.

**Comment by thisischrys** [comment]
already solved by updating
