### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by RedsaphirCZ** [MrTJP/ProjectRed#844]
Hello. I have some strange problem with missing textures of items. It is not happening with only Project red installed but something, maybe some other mod interaction, causing the problem.
I am not really sure, what it can be.

Here are some pictures: 
http://imgur.com/iN8MMn0
http://imgur.com/i9UYwzJ
http://imgur.com/a3PTWzw
http://imgur.com/VUX5ibX

Here is log:
http://ulozto.cz/xcDfuaZv/fml-client-latest-log
(hope you can open it, it was actually too big for pastebin)

Keep up awesome work!:)I am really glad, where this mod is going :)

**Comment by MrTJP** [comment]
Remove texture packs, and try with just PR.  If it works, keep adding mods one by one until you figure out which one is causing it.

**Comment by RedsaphirCZ** [comment]
Its SquidUtils. What now? Are you going to solve it with CoolSquid?

**Comment by MrTJP** [comment]
Report it to them, I'm not doing anything special with those textures. And be sure to include a full log.
