### ISSUE TITLE
Blueprints in an item frames

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#845]
Despite of fact that blueprints behaves like a maps when held in a player hand, blueprints behaves like usual items when placed into item frame. Is it possible to make them display their contents as maps do?

![2015-07-08_14 57 06](https://cloud.githubusercontent.com/assets/1329592/8569604/f6cc2548-2581-11e5-8aca-fe209ee2f3d3.png)

**Comment by MrTJP** [comment]
That is controlled by the actual item frame. Cant make them render like that, unfortunately..

**Comment by makkarpov** [comment]
Isn't event `net.minecraftforge.client.event.RenderItemInFrameEvent` exactly what is needed for hook? It takes as parameters `ItemStack` and `EntityFrame`, and allows to cancel it to prevent vanilla processing.

**Comment by MrTJP** [comment]
You're right, will do.

**Comment by MrTJP** [comment]
After looking at the results, Ive decided not to implement this, for two reasons.

1) It is cpu expensive to load the entire logic circuit from the item's nbt every frame.
2) Event the smallest 16x16 circuit is too big to clearly see any of the components on the item frame.
