### ISSUE TITLE
copy/paste in IC Workbench

### ISSUE THREAD

**Issue by cdogg111** [MrTJP/ProjectRed#848]
would it be possible to implement region selection copy/paste tool like the eraser?

**Comment by MrTJP** [comment]
I originally intended to, but ended up scraping it because it made the code too messy, and I ultimately decided that it wasn't necessary, especially after adding the ability to use the 'pick block' key to auto-select the part your cursor is on.

**Comment by cdogg111** [comment]
i didn't even know that, thanks
