### ISSUE TITLE
Recipes do not use ore dictionary

### ISSUE THREAD

**Issue by twothe** [MrTJP/ProjectRed#851]
I just noticed that most of the recipes do not use the ore dictionary. This makes it a bit difficult to adjust compatibility with other mods. Especially the silicon recipes should be using the ore dictionary, as those are present as well in the often combined Galacticraft and AE2 mods.

**Comment by MrTJP** [comment]
The silicon added by PR is not equivalent to other types of silicon. Therefore, I don't want it to be exchangeable. For example, mine requires diamonds (for the saw) before you are able to create it. Its important for the way the progression works.
