### ISSUE TITLE
Lamps look like they're off but not

### ISSUE THREAD

**Issue by 23Link89** [MrTJP/ProjectRed#853]
I have a mob farm that spawns mobs really fast (in a few seconds(modded)) and when I turn off the lights it doesn't start spawning mobs with the PR lamps. But if I use vanilla Minecraft lamps it works just fine.

**Comment by MrTJP** [comment]
Which version are you using? There was a bug with the lamps that caused this, but it was fixed a long time ago.

**Comment by 23Link89** [comment]
ProjectRed-1.7.10-4.7.0pre5.89

**Comment by MrTJP** [comment]
Fixed via 2a850ab23879070147af4da2d923e3782c58b53c
