### ISSUE TITLE
Integrated Circuit Gate

### ISSUE THREAD

**Issue by Sj3t** [MrTJP/ProjectRed#854]
Hey there!
I have my own Minecraft compilation, and P:R is one of the biggest parts of it.
Currently im working on ComputerCraft+OpenComputers automated society(full minecraft automatisation - robots mine, build, craft new robots, craft and build, and have limited independence options, with a kind of money, society, and real player emulation).
And for those purposes I use gates a lot, but I want to make them more compact.
So, here is the list of what I am interested in:
1) More info on IC circuit fabrication and usage, info on its outputs and inputs, especially bundled ones.
Im working on a kind of 16 bit processor based on IC gate, but im not sure if i am doing all right, and if it will work with bundled connection at all.
2) Kind of analog/bundled wireless signal transmitter, if it is not present now(My AI tower currently has a lot of cables and wires coming out of it, and it looks pretty, but it uses too much redstone and resourses to transmit signals in 300-400 blocks city. It is cheaper to build another control, then to build wires all the way.
3) If it is possible to create routers(i mean a box/gate with a lot of outputs and 1-2 inputs, to create a connection between computers and mechanisms(not the RedNet one I use, but wired redstone signaling. It is hard to explain why do i need this, lets just say for automatisation issues .
4)Currently Im trying to make  turtles do all things themselves, but they can't create blueprints themselves, as they have functions to interact with inventories, but nothing to interact with blueprint creation screen, as it is not bnventory based. Any way for making blueprint table use 2 modes - human mode for us to make blueprints with our own hands, and automatic mode, which uses cind of big crafting grid or so for turtles to make circuit blueprints themselves, by pre-made algorythm.
By the way, ComputerCraft is very integrative thing, so IC Blueprint Turtle and IC Printer Turtle can be integrated if it makes any sense.
Currently that is all, but i have more and more ideas and questions as I use P:R.
Yours sincerely,
Mikle Higaran

**Comment by Sj3t** [comment]
Addition: Gate Request Policy based editing of request #3 
Router Gate
Router Gate is a kind of the gate which supports both Analog and Bundled IO, has 1(2) inputs and some 6 (8) outputs. Used for remembering signal strength in 1st mode (each signal change is transfered by the next color) and transfering it to devices (mostly ComputerCraft computers). And having same analog signal transferred by all bundled connections at a given time.
Example:
Turtle Refueling Post.
3 Refueling "Pads", each controlled by the computer. We can refuel a turtle using 3 different ways - give it IC2 electricity through a peripheral, give it some coal for it to automaticaly refuel, or call a special refueling turtle.
Most commonly we use coal refueling, and computers are set to coal by default. But the situation - no coal left! The storage system starts a signal to a router, and 1 router sets all refueling computers to **electricity** mode, and if router has 2 inputs on - to the **turtle** mode.
So, summing it up - Router Gate is the gate that is sending states to multiple devices at a given time.
It surely can be done by a bunch of gates, or a single IC gate, but this gate itself is really better.
Refueling is not a single use, and currently I have multigate structures to solve such problems.

**Comment by MrTJP** [comment]
1) Will document soon.
2) WR-CBE
3) You can make it yourself with ICs.
4) Blueprints will always have to be made by hand.
