### ISSUE TITLE
Startup-Initial-crash with newest TE? (moved)

### ISSUE THREAD

**Issue by accessdenied0** [MrTJP/ProjectRed#856]
Dear @MrTJP,

I think this issue is more right here because it seem to be not the MrTJP-Core. Instead it seem to be the Compat part. (Sorry for the maybe double post but I don't know how to move this)
https://github.com/MrTJP/MrTJPCore/issues/10

I hope you can help me,

access_denied

**Comment by ate0ate** [comment]
I'm not sure what is happening here, but Minecraft loads properly, with no crashing, for me using the most recent downloads of all CoFH mods and all of Project Red. If it makes a difference, I used the files provided by curseforge in both instances.

**Comment by accessdenied0** [comment]
Dear @ate0ate,

This report is a bit older, in the mean time I until I posted it I updated all depending mods. No difference. No, the mod actuality is not the reason...

access_denied

**Comment by MrTJP** [comment]
Remove mods one by one until you find which one is causing it. (Hint: it's not TE)

**Comment by accessdenied0** [comment]
@MrTJP,

Was already working on this. I checked every mod for API or Thermal Smeltery - Handlers but I didn't find one... at the end: The real cause was ender_ores. I will talk to the mod developer soon.

Sorry for stealing your time,

access_denied

**Comment by ate0ate** [comment]
I was just curious if you made any progress hunting down the culprit? I use many of the same mods myself. Looking at your updated list of mods that you suspect, the ones I do not use are Tinker's IO, Open Peripherals, Endores, Mystcraft, or Reika's Mods. I suspect Endores honestly. Simply because it would most likely add recipes for TE which when called improperly cause that InductiveFurnace Crash. Just guessing though...

**Comment by MrTJP** [comment]
Inductive Furnace, not Induction Furnace, as in the furnace added by ProjectRed.

This crash is caused by some mod doing weird things with the vanilla furnace recipe registration.  I will fix this on my end, even though its technically not my fault.

**Comment by accessdenied0** [comment]
@ate0ate,

It was EndOres 1.2.1 out of some reasons he changed more than in the changelog was written. Anyway: 1.2.1 seem to have more then this single Issue, stick on 1.1.1 until it is fixed.

It was be a bit difficult to send the mod-author the issue because he doesn't use the usual sides like github. I send him a PM with the issue, no answer jet.

access_denied
