### ISSUE TITLE
Remove Infused Ender Pearl from the creative inventory

### ISSUE THREAD

**Issue by JBYoshi** [MrTJP/ProjectRed#858]
By having it in the creative inventory, it can mislead people to think it can be used without any extra data, which is not true.

**Comment by MrTJP** [comment]
Yes, will do.

**Comment by JBYoshi** [comment]
Thanks.

**Comment by MrTJP** [comment]
Addressed in 85237be0abe6d76365bb8e900c34160787a3da0a

**Comment by JBYoshi** [comment]
Thanks!
