### ISSUE TITLE
NO I DONT WANT ForgeRelocation

### ISSUE THREAD

**Issue by loordgek** [MrTJP/ProjectRed#859]
KEEP YOUR SHIT YOUR SELF

**Comment by UnRealDinnerbone** [comment]
I 2ND IT

**Comment by MrTJP** [comment]
Then don't install Mechanical.

**Comment by UnnamedPlyaer** [comment]
Maby You Should Not Steal Ideas From Blue Power Then

**Comment by SuperSandro2000** [comment]
And why did you not include the FMP plugin in the main download?
