### ISSUE TITLE
Crafting pipes and furnaces

### ISSUE THREAD

**Issue by Swift17** [MrTJP/ProjectRed#860]
Not sure if the functionality of crafting pipes is supposed to be fully operational, or if it's still a work in progress, but I have created a pipe system consisting of a chest with an interface pipe, a vanilla furnace with a crafting pipe and an extension pipe, and a request pipe. Tested using cobblestone>stone, and when stone is requested, it moves into the furnace and is cooked, but is not pulled back out. Is there something I am doing wrong? Is there a bug? Or is it simply that the crafting pipe functionality is not yet complete?

**Comment by MrTJP** [comment]
They are working as they should.  You have to put crafting pipes on the side of the furnace that can allow extraction of the output (I think the sides will work).

Note that in the next update, crafting and extension pipes will be removed, and all of their functionality will be moved into the crafting chips, for use in any interface pipe.

**Comment by Swift17** [comment]
Thank you for the prompt reply - however, it still does not appear to be working. I am probably doing something incorrectly, but I can't seem to figure out what. Would you mind explaining further?
I appreciate that if you are working on an update that removes these pipes, then an explanation might be bothersome, so I understand if you would rather I just wait till the next update. That being said, if you wouldn't mind giving an explanation, more info is below.

                                                                                                                  >>Extension Pipe |
It looks something like [Chest>Interface Pipe>>>Request Pipe>>>Crafting Pipe>>>Furnace] with an crafting pipe going into the side and an extension pipe on top. When requested, it announces a success, but does nothing. If I switch it so that the crafting pipe is on top and the request pipe is at the side, the cobble is pulled and cooked, but is not pulled out.

**Comment by MrTJP** [comment]
The crafting pipe can't insert items on the side. Also, it cannot pull items from the top.  So you must use an extension to send items to the top, while using a crafting pipe on the side to actually pull them out. Link the crafting ingredient to the extension pipe.

**Comment by Swift17** [comment]
Got it! The part I was missing was linking the ingredient to the extension pipe - I had it in the wrong place in the grid.
Thanks for the help - and just so you know, it seems that the correct face to extract items from a furnace is the bottom. Did not work from the side, but the bottom works fine.
