### ISSUE TITLE
IC Workbench GUI

### ISSUE THREAD

**Issue by cdogg111** [MrTJP/ProjectRed#861]
the buttons shouldn't move around when selected, it makes it really confusing to pick the next color of wire or part

**Comment by makkarpov** [comment]
It's not so confusing, but allows you to pick same wire colors or same gate types when you are building your circuit.

**Comment by MrTJP** [comment]
Buttons no longer change positions in 85237be0abe6d76365bb8e900c34160787a3da0a

**Comment by cdogg111** [comment]
noice!
