### ISSUE TITLE
PNG rendering of IC blueprints

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#863]
It would be nice to have a button in blueprint GUI that will render entire blueprint into PNG file placed in _screenshots_ directory. This will allow users to easily save complex 64x64 ICs and, for example, create public IC design libraries.

**Comment by MrTJP** [comment]
ICs are much more than just images. Saving their png wouldn't allow you to re-import them. But I do plan on having a mechanism to allow you to share them, and even take them into other worlds or servers. 

Don't see a need for pngs when you could just look down on it and take a screenshot, but I'll see what I can do.

**Comment by makkarpov** [comment]
>ICs are much more than just images. Saving their png wouldn't allow you to re-import them

IC is completely described with screenshot of it's contents (and with tooltips for some components like timers). Yeah, image will not allow users to import IC, but it will allow them to learn it's structure and operation and, at least, redraw it by hand with this image as a reference.

**Comment by makkarpov** [comment]
Also, exporing and importing ICs is pretty simple - just deflate + base64 encode it's NBT tag, display it to user with some GUI, allow user to copy this encoding and paste it back. But some rendering mechanics will be useful even in this case because user will see what he is copying.

**Comment by NarigudoBR** [comment]
It would be nice if it can be like bc blueprints,because you can share with the comunity

**Comment by Chicken-Bones** [comment]
We'll probably make a block that allows importing and exporting of blueprints (saving as an nbt file), and we can add a feature to said block to export an accompanying png.

**Comment by makkarpov** [comment]
>as an nbt file

Maybe it should export as clipboard string? Importing a files would require server administrator rights, so usual server players would not be able to use this feature. Also, useful feature at import will be possibility to enter an URL to download from.

**Comment by Chicken-Bones** [comment]
I was intending for it to be client side, and import from a folder on your machine, like BC blueprints were the last time I checked.

**Comment by MrTJP** [comment]
Not sure how long those nbt strings can get, but if copy-paste is feasible, it will be included in addition as an easy way to import without messing with files.

**Comment by Shuudoushi** [comment]
I'm so glad I searched before posting for a change. Has any headway been made on this feature yet?

**Comment by MrTJP** [comment]
There has been some progress on the new backend for integrated circuits. If I had to say, I would say it is about 20% finished. Until it is done, features such as this will not be worked on.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
