### ISSUE TITLE
filtered importer stacking items that are not stackable

### ISSUE THREAD

**Issue by NarigudoBR** [MrTJP/ProjectRed#869]
I was testing in my test world the filtered importerto import and export pickaxes to a arcane bore(yes,to my frame quarry)and when activated the filtered importer, imported all items from the chest and when they entered the inventory they stacked like the screenshots bellow:
in chest:
![2015-07-18_00 20 30](https://cloud.githubusercontent.com/assets/5056170/8760158/74abfaa2-2ce3-11e5-9529-6cb6c4109299.png)
out chest:
![2015-07-18_00 20 44](https://cloud.githubusercontent.com/assets/5056170/8760159/82ccd656-2ce3-11e5-9a01-928ae2a9a63f.png)
the two ways that I tested i(the results were the same):
![2015-07-18_00 22 19](https://cloud.githubusercontent.com/assets/5056170/8760161/9c8be14a-2ce3-11e5-96cf-52dfc8140b5a.png)
![2015-07-18_00 22 16](https://cloud.githubusercontent.com/assets/5056170/8760162/a39edbe0-2ce3-11e5-9ac3-b8116dad8c8a.png)
I hope that you will fix it.I like very much your mod and the way that you did it :).

**Comment by MrTJP** [comment]
Fixed via 24d252d3bc7accd609a92a76c2d2634ba80b453c

**Comment by NarigudoBR** [comment]
thanks :)
