### ISSUE TITLE
(Feature Request) Thermopile(from RP2)

### ISSUE THREAD

**Issue by NarigudoBR** [MrTJP/ProjectRed#870]
I was a very fan of RP2 machines and the way that blutricity works , and i like the idea of having a alternative source to produce energy(at low rates,but producing), because i don´t want to do a system of replacement of batteries.thermopile works with lava at one side and water in other sides(one suggestion:make the possibility of using liquid Pyrotheum and liquid Cryotheum .

**Comment by CubeWrench202** [comment]
Nice, i agree.

**Comment by NarigudoBR** [comment]
yep and the option of using pyrotheum and cryotheum will generate 5x more power because of the bigger difference of temperature

**Comment by MrTJP** [comment]
I have a few different methods of generation in mind, to be added in the future.  This may or may not be added.
