### ISSUE TITLE
make the option(can be config option or right clicking option) to frame motor works in redstone ticks(1 redstone tick=1 move)

### ISSUE THREAD

**Issue by NarigudoBR** [MrTJP/ProjectRed#871]
the title says everything.it would be nice.like it was in redpower2. The thing is if you put a button and actvate it moves more than 1 block,and when you try to move only one block with a lever some times it goes wrong and it mess with everything

**Comment by MrTJP** [comment]
I made it continuous because I thought thats how it was in RP2. Fixed via 42c77a48a25bdc475a4a42811914745ca17dac2b
