### ISSUE TITLE
Inverse feedback button

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#873]
Basically just another type of button. It operates as described:

1. When button is not pressed, it constantly emits redstone signal
2. When button is pressed, it lights and stops emitting signal. Button do not "pop out" automatically.
3. When another part of circuit emits signal to that button, button stops glowing and pops out.

**Comment by MrTJP** [comment]
Don't want to have yet another type of button. I have a basic one included, if you need some logic for them, use gates.

**Comment by Chicken-Bones** [comment]
Just use a toggle latch
