### ISSUE TITLE
Variety of Feature Requests in Illumination Module

### ISSUE THREAD

**Issue by TheVoltrex** [MrTJP/ProjectRed#876]
Greetings developers of Project Red! In my opinion, the illumination added by this mod is one of the things this mod absolutely shines in (Pun intended)!!. As a map maker and modpack player, I have gathered up some innovative ideas over time to add to this mod's potential... I decided to make one issue post of them all due to relevancy instead of making several... Nevertheless, I apologize for the bombardment of sugguestions...
1. Multi-Colored Lamp ADVANCED MODE

I realise this was already a feature requested by C-P... If I may ask, what's your progress? I am extremely eager for this new addition because it'd be possible to build: Pixel art animations, notification panels, dance floors lol.
1. Multi-Colored Lamp SIMPLE MODE

Aside from the advanced mode which works on bundled cables and has the ability to display all colors... this simple mode works on the redstone state and is only able to to display 2 colors... The most popular example: Redstone signal=Green... No Redstone signal = Red (Instead of turning off)... I cannot tell you how many times I wish for this in my regular playthroughs!!! For example: Having a single lamp to light blue when my energy cell is charging and light yellow when it's fully charged! The reason why this is needed aside from the ADV MODE is for compactness... Having a NOT Gate, 2 insulated wires, and a bundled cable to preform this simple task is extremely redundant. 
1. Lumen Pressure Plates, Levers, and Tripwire

Because.... Why not?. It seems rather odd to me that the button is the only redstone-input device that is luminant out of all the redstone-input devices of Vanilla.. I believe all methods of inputs should be able to give off light when activated for unity, cosmetic, and pratical purposes. Though, some 3D new models might be needed to make the lighting fixtures look realistic and modern (Because a lime-green Vanilla lever just looks silly)... Thus.. Here are my ideas:
-Lever: http://payload62.cargocollective.com/1/7/250467/3551617/IO-switch.jpg
-PressurePlate: I think the current 3D model works... There might be some adjustmemts to be made though, like some sort of in-fillet border?? To make the appearance look like a really big button.
-Tripwire Hook: My idea for this one is to replace the function of strings for a LAZAH BEAM!!!.. I haven't fully formalised my concept of this one yet.. But here's what I got so far: Instead of the big bulky tripwire hook, the laser shall be emitted from something probably with the resemblance of this: http://img2.wikia.nocookie.net/__cb20130527012716/starwars/images/e/e6/AutomatedLaserTrap-TC.png ... Also, the color of the laser depends on the color of the lumen (for cosmetic purposes, the transparency of the laser beam can be set in GUI) .. When acrivated , the emitter shall shine the color of lumen... This addition will be PERFECT for PVP servers & builds... All while unifying illumination for redstone-inputs... (:
1. Lamp Bar Fixture

This Lamp Fixture is about 1/3 or 1/2 tall, 1/1 long, but 1/2 or 1/3 wide which is centered... Perhaps if possible, may connect to other fixured on both axis?? ... Anyways, this is the modern-day typical light fixture that will mimic those found in supermarkets, office buildngs, bowling alleys, and factories.. A 1x1 lamp block just looks too bulky for these purposes . This will be perfect (: ... 
1. Dimming Feature for all Fixtures

Okay.. Okay.... I can see how this request is a bit massive.. But please consider this because for how much potential this will bring for eeveryone especially cinematic map-makers like myself... (: .... This feature will be perfect for how amazing this module already is!! (: ... Here's my idea: An option (or seperate crafting recepie )for a "Dimming Mode"... In this mode, the amount of light-level emitted from the lamp is dependant upon the Redstone Signal going into the lamp... (As well as the opacity visual of the brightness of the color).... This is the ALL-TIME perfect cosmetic feature needed... Especially for Horror-Maps... Using this along with a comparator: you now have a visual appealing indication of (e.g. how full a quarry chest is).. Thus, this is a huge pragmatic appeal; not only cosmetic... 
1. Ability to MicroBlock Lamps (and YGC chisel comparability) 

This one is extremely massive, and the one I'm least worried about.. Though, it'd be an EXTREMELY pleasant fearure to have (: ... I'm not sure how possible this will be, but the ability to micro block fixtures to create slab lamps, or outlines would be GREAT... (Even though they lose their ability to be activated to turn off)... This will suit well for neon lights and neon posts, etc... Pure cosmetic....

Thank you for taking your time to readmy ideas and for your  consideration. Please let me know if you have any confusion and if you need me to re-word or clarify something (: ... Please share me your opinions as well.. I know you are currently busy with your IC maintenance, but at least if you plan to someday turn my ideas into reality, that'll surely mean a lot to me... I absolutely love and admire your work. Thank you so much for it!...  (:

**Comment by Chicken-Bones** [comment]
I'll start by saying this is all MrTJP's domain, and dependent on his timeframe, but here are my thoughts.

ADVANCED MODE: sure, dunno on progress or timeframe

SIMPLE MODE: nay, you'll be able to make a cheap IC for this purpose, one that takes in a single redstone signal and outputs the required bundled colours to an ADVANCED MODE light
Other lumen inputs: I think it's a good idea, laser sensor included

Lamp bar: depends if MrTJP wants to expand illumination to be a more all purpose lighting solution, though ultimately, may be better as an extension mod that adds all manner of lighting fixtures

Dimming: sounds good, perhaps just make a dark dust item and have you apply it 1-3 times to reduce the brightness

Microblock Lamps: is definitely possible, even having them respond to redstone as of recent FMP changes, but there are 2 questions.
1. How much light should they give off? Should a cover corner emit a full 15? probably
2. What would the redstone connection logic be for various shapes of microblock? (irrelevant if no redstone)

As for chisel, I have no idea, it's probably possible.
Ultimately it will depend on how much time MrTJP has and how much he wants to expand the illumination package, though there's nothing stopping an addon mod (say Blue Power) from adding them.
Thanks for your suggestions

**Comment by MrTJP** [comment]
I sort of started multicolored lamps a while ago, but never finished because of a bundled cable connection bug (which has since been resolved). Haven't picked it back up yet, will try and do it soon.

As CB said, simple mode is unnecessary, especially with ICs.

I'll be adding pressure plates eventually, but not very sure about the other stuff. Switches might look cool if i can think of a good design.  Laser trip wires... maybe down the road, only because the new particle library I've been working on already has lasers in it, use for routing pipe effects.

Not sure how to handle dimming.  Since all parts use the same base class, its possible to add dimming to all lights, but I'd have to think about how to actually dim them, a GUI is a bit overkill.

Microblock lamps is a nice idea, would like to add them.  However, I'd rather not add redstone mechanics to them, unless something has changed in FMP that I am unaware of that would easily allow this. Also, I think light should be proportional to their size. (slab emits half the light, etc.) If that is too much of a light drop-off, we can have a minimum limit.

**Comment by amadornes** [comment]
I can confirm that adding microblock lamps would be an easy task thanks to a feature I requested for FMP about a month ago.
You can now define traits which can be applied to microblocks, allowing you to extend their functionality. This would allow rendering the halo around the lamp parts as well as allowing it to interact with redstone.
I'm quite happy about having asked CB for it, I knew it would come in handy in more cases than mine :P
And CB, some of those things were indeed in our roadmap and will hopefully be added soon, though I'm pretty much the only BP dev and I also have to maintain other mods so I don't have that much time to work on any of them :(

**Comment by TheVoltrex** [comment]
One thing I forgot to address is that the Simple Multi-Color Lamp and Advanced should each be their own seperate block. Please consider the following two contentions: 
1:Balance: I believe that a block with the ability to emit two colors should be a little less expensive to craft than a block with the ability to emit all of them... 
2:Accessibility and Redundancy: I'm sorry, but I just don't agree that an IC chip (which requires extra steps even in creative mode) should be required to preform such a simple task :/ ... You see, the Adv MultiColor operates from insulated and bundled cables.. Whereas, the Simple only operates whether any redstone signal is present or not.. There shouldn't be any additional steps converting from Advanced==>Simple.. And I envision it working like this: Craft Simple MultiColor, Place it, open its GUI, place my 2 lumen from my inventory to REDSTONE SIGNAL and NO REDSTONE SIGNAL, place a lever to block, and Done.... Simple. (:

By the way, I have no idea why I said "Lamp Bars" lol xD.... The correct term is "(Architectural) Linear Lamps".. lol. I hope this clears up confusion.

Here's how I would execute dimming lights:  the Fixure will function on an Analogue Redstone signal instead of Digital. The Light Level Output (0-15) will be emitted from the fixure based on its Redstone Signal Input (0-15)... For Example: A light fixture will emit a light level of 4 when it recieves a Redstone signal of 4... This will allow for Dynamic Horror lights when I want to slowly dim the lights of a room. Spooky..

This will ultimately lead me to leaving a suggestion for WR-CBE for an option to transmit and receive analogue signals :p

Regarding the FMP lights... Is it possible for FMP to function like the microblocks in TierraFirmaCraft or Algorithm's Chisel and Bits?! D: .... The potiential from the ability to place my strips or nooks wherever I want in space is absolutely revolutionary! This feature shall disregard the need for my linear lamp suggestion as you can easily make your own... Anyways, I concur with MrTJP that the light values should be scaled according to size. Also, I think that the most easiest solution for redstone is this: Every FMP part within a block of space  turns on when that space recieves a redstone signal..

I thank you for your consideration.. (: .. In accordance to CB's statements, please work in your time frame and don't feel rushed or hurried due to my sudden flood of sugguestions and requests. (:
