### ISSUE TITLE
CPU devourer

### ISSUE THREAD

**Issue by stickhead** [MrTJP/ProjectRed#877]
Hello, first off love your mod.
We're trying to run a private server with a custom pack for your mod but the odd thing is, project red is taking up 43% of the cpu.
http://i.imgur.com/x3x2VZD.png
It's a fairly good server, never run into anything like this before. Any ideas?

**Comment by Ianaver** [comment]
that is quite strange, I will also go and see if I can find any clues as to whats going on

**Comment by MrTJP** [comment]
Attempted to lower CPU usage. Report back if its still a problem.
