### ISSUE TITLE
[Enhancement] Could you consider splitting P:R Mechanical from the the relocation mechanics?

### ISSUE THREAD

**Issue by utoc** [MrTJP/ProjectRed#878]
I have updated to the newest ProjectRed and intentionally decided against using the mods `ForgeRelocation-1.7.10-0.0.1.3-universal` and `ForgeRelocationFMP-1.7.10-0.0.1.2-universal` since I already have two block-moving mods in my pack.  Unfortunately, Forge keeps redownloading them as ProjectRed:Mechanical has a dependency on them.  Is there any way to disable this behavior while still keeping the mechanical part of the mod?  Would you consider this in the future?  Thank you!  Love you mod!

**Comment by MrTJP** [comment]
If ForgeRelocation wasn't offered as a separate package, its code would be included in the mechanical jar file anyway. Just ignore them, and use something like MineTweaker to disable recipes of the frame stuff added by PR.

**Comment by Chicken-Bones** [comment]
Is it not possible to have Mechanical without forge relocation just not add frame recipes?

**Comment by MrTJP** [comment]
It would require using optional tags to remove interfaces and method calls (which Ive had a hard time getting it to play right with scala in the past), not to mention that it would still crash if it was placed from creative-mode.  Extra work for scrubbing some VERY lightweight code, imo.
