### ISSUE TITLE
Crash whit NEI and Project Red

### ISSUE THREAD

**Issue by Dream-Master** [MrTJP/ProjectRed#881]
I get a crash when my inventory i full and i try to spawn in more items in creative.

Crash Report
https://gist.github.com/Dream-Master/a3cb823e85318346bac2#file-gistfile1-txt

Open Eye
http://openeye.openmods.info/crashes/a85291bdd058040cd52a51d98e681952

**Comment by MrTJP** [comment]
Which inventory do you have opened?

**Comment by Dream-Master** [comment]
I think i play with the new Auto Crafting Bench and the Project Bench. I get some error like that before open only NEi.

**Comment by MrTJP** [comment]
Cant reproduce this at all. Include steps and reopen.
