### ISSUE TITLE
Solar Panel… Bug?

### ISSUE THREAD

**Issue by PaperTriangle** [MrTJP/ProjectRed#885]
So, I noticed that solar panels could be placed in any orientation on a block. This means it is possible to place a bunch of them in the same (x, z) with varying y to create a long underground line of functioning solar panels, as long as the top is open to the sky.

I'm not sure if this is the intended operation, but it seems a tad odd.
![2015-07-26_21 24 11](https://cloud.githubusercontent.com/assets/10346216/8893669/855c5c92-33dd-11e5-9282-fd82636e055b.png)

**Comment by MrTJP** [comment]
The side they are placed on, the light available, and the depth at which they are placed are all factors on how much energy they produce. 

That works but it's very inefficient.

**Comment by MrTJP** [comment]
I do see the oddness of this though. I will drastically scale down the speed of the panels when placed as such

**Comment by Chicken-Bones** [comment]
iirc RP2 panels could only be placed on the top of a block
