### ISSUE TITLE
Dark guis

### ISSUE THREAD

**Issue by nikita488** [MrTJP/ProjectRed#886]
All guis in ProjectRed are dark. I think you need to add GL11.glColor4f(1, 1, 1, 1) to all guis :)
![image](https://cloud.githubusercontent.com/assets/6237881/8894025/9541d0b0-33b0-11e5-9575-82e8ba84cda9.png)
![image](https://cloud.githubusercontent.com/assets/6237881/8894027/a1d4b0a4-33b0-11e5-98e1-cbd8cd088f7a.png)
P.S. I think i fix dark guis, but only in Mechanical :P

**Comment by MrTJP** [comment]
Attempted fix with update to MrTJPCore

**Comment by nikita488** [comment]
Thanks, it fixed now :)
