### ISSUE TITLE
"Analog strength gate" and "Analog invertion gate"

### ISSUE THREAD

**Issue by RedsaphirCZ** [MrTJP/ProjectRed#887]
Hello, once again, very nice work with your updates!

I have one request. Is it possible to make 
1. Gate with gui to insert analog output value (to use with comparators, co i dont have to set it with opencomputers or run like 15 block long signal etc...)
2. Gate with ability to invert signal strength (output = max strength - input strength) if possible to be able select vanilla redstone/project red wire.

if you can look at it it would be great.
Keep up the good work!

**Comment by makkarpov** [comment]
2. Use comparator in subtraction mode

**Comment by MrTJP** [comment]
There are several ways to do this already. Bus converter with a bus input panel, just to name one.
