### ISSUE TITLE
Attempting to craft an IC gate with an IC containing an IO crashes the client.

### ISSUE THREAD

**Issue by jarredglickstein** [MrTJP/ProjectRed#890]
I drew up a simple blueprint with an input and an output.  I can make it into an IC with the IC printer but completing the recipe on the input side of a crafting table crashes the client.  In the second screenshot I included with this issue report, adding the last circuit plate results in a client crash.  If on a server, the client crashes still but does not harm the server.  Player leaves without reporting errors to the server. 

Here is an error log from a multimc instance containing ONLY Forge build 10.13.3.1388 and Project Red 1.7.10-4.7.0pre7.91: 1.7.10-4.7.0pre7.91: http://pastebin.com/swhkDkbP

I tried with Forge build 10.13.4.1448 as well and had the same issue. 

![blueprint1](https://cloud.githubusercontent.com/assets/3357434/8896285/e357e834-33c4-11e5-922a-80512f57dcb1.png)
![blueprint2](https://cloud.githubusercontent.com/assets/3357434/8896286/e3593126-33c4-11e5-83ce-bcbfc91e662a.png)

**Comment by MrTJP** [comment]
Fixed via b11f599e1b017fd5111434bb13385acad84753be
