### ISSUE TITLE
Suggestion: Addition of a Binary Counter and 7 Segment Display driver/converter

### ISSUE THREAD

**Issue by Legless1000** [MrTJP/ProjectRed#893]
With the current dual 7 segment display as a gate, there is currently no easy way to operate it without creating complex and large logic circuits (either ingame or as a blueprint and custom IC). I have constructed a 4 bit binary counter base on D type flip flops (also created from scratch), and have found it to work flawlessly as a single IC, but for someone with less knowlegde of digital circuits such as this, creating one from scratch would be very difficult (a single flip flop uses 5 gates on it's own, and chaining them together for a counter requires an additional 3 gates per flip flop). An addition of a 4 bit (or higher) counter would be very useful for more complex systems that require any form of counting (where the output value is required to be sent to another circuit), while also reducing the delay for manually created circuits.

The second suggestion I have follows on from this. By creating a binary coded decimal to 7 segment display converter, the binary counter could then be used with the current display gate very easily and would work easily with another system that required precise counting. An alternate possibility would be to combine these two ideas, to give a single chip that takes a pulsed input as a counting trigger, and a bundled output designed to match up to the display gate. This then allows users who are less knowledgable of electronics to effectively use the display without needing lengthy research to create the appropriate circuit. The amount of gates required for this circuit (especially for a dual display showing up to 99) is extremely large and not possible to be made on a single custom IC ingame. The only use for this would be to drive the display, but as this chip is more of an extension to the display, any uses the display has then become far easier to implement.

**Comment by makkarpov** [comment]
>someone with less knowlegde of digital circuits such as this

Maybe then someone should learn digital circuits before trying to build one.

If you do not need a reloading feature (assigning counter value), you probably should not build counters on D latches, use T-latches. I also think that you can fit single 4-bit counter + display on 32x32 IC (it's compact event with decoders), so you can easily place two-digit counter on 64x64 one.

**Comment by MrTJP** [comment]
Not really gonna add any more gates. ICs are available for use, and implementing them will only be easier as the system improves.
