### ISSUE TITLE
Weird IC behaviour

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#895]
![image](https://cloud.githubusercontent.com/assets/1329592/8954052/ba51c7f6-35eb-11e5-9b50-fd8026cc7ab6.png)

Look at NOT gate. It should power both sides, but powers only right one.

Mod versions:
```
MrTJPCore-1.7.10-1.1.0.30
ProjectRed-1.7.10-4.7.0pre7.91
```

Full IC blueprint:
![image](https://cloud.githubusercontent.com/assets/1329592/8954105/0538b16c-35ec-11e5-9cb4-a73be3a449b9.png)
*(it's a decimal counter implemented inside 32x32 IC, because in previous tickets there were some claims that it cannot be implemented in 64x64)*

**Comment by Legless1000** [comment]
It would appear my skills at designing compact circuits are poor at best. I'm incredibly impressed.

**Comment by cdogg111** [comment]
i experienced this same issue with a not gate

**Comment by jarredglickstein** [comment]
Do you have any trouble placing this chip on a gate?

**Comment by makkarpov** [comment]
When I place chip as a gate, it does not work and becomes absolutely useless due to fact that placing it as a gate do not fix broken NOT.

**Comment by MrTJP** [comment]
Fixed via b11f599e1b017fd5111434bb13385acad84753be
