### ISSUE TITLE
(Feature Request) Chip upgrades as a config option

### ISSUE THREAD

**Issue by Teteros** [MrTJP/ProjectRed#896]
#894
I liked how the chips needed upgrades for them to be fast, and I had custom recipes for each upgrade in my modpack. May this functionality be added for now as a config option, off by default?

**Comment by MrTJP** [comment]
Wont do that.  There *may* be a new system in the future, but for now, the speeds of all chips are balanced at a reasonable level, so as to not be too slow or too fast (and cause a lot of lag).
