### ISSUE TITLE
Weird IC behaviour (x2)

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#898]
The first bug was just the beginning :D

![image](https://cloud.githubusercontent.com/assets/1329592/8989639/1bb613de-36f6-11e5-9847-4240217d45a9.png)

Look at the white wire. Do you see any power source?
ProjectRed version - `1.7.10-4.7.0pre8.92`

**Comment by MrTJP** [comment]
Remove that line of bundled cable and place it down again, it should fix that ghost signal. 

Might be caused by an actual bug, or just some glitch in the Matrix, but until you give me steps to reproduce, can't really fix it.

**Comment by makkarpov** [comment]
I can give you exact IC BP where it is reproductible. This ghost signal does not stay constantly. It appears and disappears at reproductible conditions. Unfortunately I do not know what _exactly_ causes this signal to appear, but in my IC it can be reproduced very easily.

**Comment by MrTJP** [comment]
Ok, give me the IC diagram and what causes it, and let me try to reproduce it.

**Comment by makkarpov** [comment]
I what format? I can dump NBT, can take PNG screenshot, can set up test server.

**Comment by MrTJP** [comment]
The world file will be the most accurate/easy.

**Comment by makkarpov** [comment]
[Here it is](1)
(you can remove the link when you will download file)

To reproduce: open blueprint in editor, give some pulses to input and look to 4x4 array of cells. When counter state changes from 1 to 2, white wire remains active thus giving '3' output.

**Comment by MrTJP** [comment]
Bug is related to very intricate timing differences, which determine the order in which signals travel through wires.  Might not bother fixing it, because once the circuit compiler is finished, this won't be an issue.

**Comment by makkarpov** [comment]
Heh. When I moved repeater to top, two ghost signals ('1' and '2' wires) appeared :)
