### ISSUE TITLE
Visual bug with frames

### ISSUE THREAD

**Issue by nikita488** [MrTJP/ProjectRed#902]
I have only 2 double chests on my frame machine. But sometimes appear ghosts chests.
This is a normal chests:
![2015-08-01_12 50 32](https://pp.vk.me/c628125/v628125305/b2ac/Gdwj2BTAofA.jpg)
![2015-08-01_12 50 45](https://cloud.githubusercontent.com/assets/6237881/9021491/d370947a-384c-11e5-8308-a332eb758669.png)
![2015-08-01_12 50 50](https://cloud.githubusercontent.com/assets/6237881/9021492/d387e404-384c-11e5-8578-39c6ddad4ce1.png)
![2015-08-01_12 50 55](https://cloud.githubusercontent.com/assets/6237881/9021493/d3924ae8-384c-11e5-900c-d3bb69620d44.png)
This is a ghost chests:
![2015-08-01_13 00 45](https://cloud.githubusercontent.com/assets/6237881/9021509/8b45d13c-384d-11e5-8072-ec22dd1156c9.png)
![2015-08-01_13 00 59](https://cloud.githubusercontent.com/assets/6237881/9021510/8b495a96-384d-11e5-961a-cad404868179.png)
![2015-08-01_13 01 04](https://cloud.githubusercontent.com/assets/6237881/9021511/8b4e4c72-384d-11e5-82d5-10bc636ed1f2.png)
This happens rarely

**Comment by MrTJP** [comment]
I've seen this happen before on a server, but was unaware that it was caused by frames. Does this happen on single player as well?

**Comment by nikita488** [comment]
Yes, this is a singleplayer.
