### ISSUE TITLE
Random frames disappearance with Thermal Expansion

### ISSUE THREAD

**Issue by nikita488** [MrTJP/ProjectRed#903]
https://www.youtube.com/watch?v=oCilndqSqKQ&feature=youtu.be

**Comment by MrTJP** [comment]
Is there a reliable way to reproduce this?

**Comment by nikita488** [comment]
I don't know :D Maybe try to install Energy cells on frames and run it.

**Comment by nikita488** [comment]
Another bug, but with Thermal Dynamics, i install 5 redstone energy fluxduct and i get crash on 3 move.
http://pastebin.com/V1YCyeUR

**Comment by Pi-Co** [comment]
I just wanted to add that after some testing. I came up with the conclusion that it is primarly happening for me while moving upwards with the machine. It also seems to happen in frames that are not touching other project red blocks besides frames. Another thing that disappears quite often are transfer pipes from extra utlities.
