### ISSUE TITLE
Dupe microblocks

### ISSUE THREAD

**Issue by MySt1k** [MrTJP/ProjectRed#912]
http://youtu.be/RHnSPwtzb_w

**Comment by alfw** [comment]
Is this with or whout KCauldron ? If it's with KCauldron, test it with pure forge. 

And this shuld be reported at https://github.com/Chicken-Bones/ForgeMultipart/issues

**Comment by MySt1k** [comment]
No, it's forge
Thanks. wrong section

**Comment by MrTJP** [comment]
This is a ForgeMultipart issue, as @alfw said.  Please open this issue there.
