### ISSUE TITLE
Block Placer crash with horses

### ISSUE THREAD

**Issue by MalkContent** [MrTJP/ProjectRed#913]
http://pastebin.com/harxNyAL

When block placers are used on tamed horses the game crashes.
Doesn't happen when using chests on donkeys with the placer. Pretty sure it's because it tries to open the gui.

Sidenote: Thanks for making fishing rods work :) can't see the entity but it triggers tripwires and allows for automated fishing

**Comment by covers1624** [comment]
Yee 1.7 is no longer supported and this may have been fixed.. Just don't let your pokey block poke horses.
