### ISSUE TITLE
Framed Red Alloy Wire Recipe Glitch

### ISSUE THREAD

**Issue by oitsjustjose** [MrTJP/ProjectRed#914]
Rather difficult to find any explanation for this one since I'm not very familiar with how FMP uses Tile Entity NBT Data to store what type of microblock a microblock is, but I ran across this recipe glitch today, and it's not just client-sided, it worked when I tried to pull the output item:

![2015-08-11_12 40 44](https://cloud.githubusercontent.com/assets/3887324/9205261/bc31f39e-4026-11e5-9080-9cb59b1a9d89.png)

![2015-08-11_12 40 47](https://cloud.githubusercontent.com/assets/3887324/9205268/c4550b56-4026-11e5-8992-6cbb2567d129.png)

**Comment by MrTJP** [comment]
Fixed via 0524708d53384ef0e1c50f5c51c76d061c4faef6
