### ISSUE TITLE
Ask for Repost Permission

### ISSUE THREAD

**Issue by 23235599** [MrTJP/ProjectRed#917]
Hello,I am 23235599.I really like your mod.But in China, this mod is not very popular.Your mod is very powerful, especially new entrants some machinery. Add your mod logic gates greatly simplifies the original Redstone system.I want to publish your mod in MCBBS, namely China minecraft unofficial forum, I will give them put your curseforge Download link.and I will be your mod Chinese language translation.I will be really appreciate if you can give me the permission.Thank you for bringing us such a wonderful mod.

**Comment by MrTJP** [comment]
You may post links to curse forge, but you may not rehost and distribute the jar files.

**Comment by 23235599** [comment]
so,I have your Permission?
