### ISSUE TITLE
map permanently crashes, states block is interface pipe

### ISSUE THREAD

**Issue by Liquidmasl** [MrTJP/ProjectRed#918]
Hi guys, i am desperate, 
I built a huge factory, with a ton off interface pipes, I had some problems with the hugeness of the network, i cut down half of it then everything went fine, for a while..

Now every 2-15 minutes the singleplayer map crashes, to be honest, its a modpack, attack of the b-team, so it might be some interference with some other mods.. but as i stated, the error report gives me a block location, and this block is an interface pipe connected to a deep storage unit. I had some problems with this setup, it seems that when i just restart the game its always the exact same block that causes the crach, if i delete the block, after some time, another interface pipe causes a crash.. I was trying to figure out what it is that produces the crashes, maybe if some other interface pipes request sand (thats in the deep storage) alltogether.. (4 furnances connected via interface-pipes request sand all the time)..

Also if i break a pipe the game crashes, sometimes, like 1 in.. 2 to 3 times..

I love this mod, and i love my facility, i would be very very greatful for any advise you could give me.

Please help me out guys!

Error-log on pastie: http://pastie.org/10351753

**Comment by Liquidmasl** [comment]
Also, i ust remembered, i had the same problem with birch wood deep storage-interface pipe.

Had to remove it for the time beeing

**Comment by MrTJP** [comment]
That is a very old version of PR.  Even if I knew what the problem was the only solution would be to update.
