### ISSUE TITLE
Need some assistance on crafting with crafting chips

### ISSUE THREAD

**Issue by jcotton42** [MrTJP/ProjectRed#919]
I have tried every venue for support, namely IRC and private message and neither have worked. I am wondering how crafting now works with the crafting chip, the wiki contains no documentation on them

**Comment by MrTJP** [comment]
Crafting pipes are deprecated.  Use crafting chips in an ordinary interface pipe.

**Comment by jcotton42** [comment]
I said I used crafting chips, not the pipes
