### ISSUE TITLE
[Mechanical] Verify Error 

### ISSUE THREAD

**Issue by edenprojectde** [MrTJP/ProjectRed#920]
As soon as i put in Mechanical this error is thrown:
http://pastebin.com/eFN5hSX7

These Mods are installed and work without RP Mechanical like a charm:
http://pastebin.com/kdrUMuGr

I updated from about 88~ to 92 because my world in which i used Pressured Tubes, failed to load correctly the second time i entered. It was the same error message as here, i already found 2 other people who had this problem and not posted it on the Issue tracker here.
Hope anybody can help, i couldn't get a clue what the error is all about, even tough im a programmer too, i really want my pressured Tubes back :'( *reallysadface*

**Comment by evg-zhabotinsky** [comment]
It looks really weird.
The first thing I noted is that it crashes on *achievement icon* rendering, while P:R does not add any. Also, there is nothing P:R-related on crash log.
My guess is P:R is *not* the direct *cause* of crash, but rather some other faulty mod trips on it. Something like incompatible changes to base classes maybe.
Updating forge *might* help, but most likely you will have to find the other mod involved in that crash. Updating it might also help, otherwise it should be possible to find out what the exact conflict is.

**Comment by edenprojectde** [comment]
https://github.com/MrTJP/ForgeRelocation/issues/12
Same Error as here; 
Problem solved tough; deleting Truss Mod helped <- A mod which adds Motors and Frames from RP2 too.

But after getting rid of the error i got this:
http://pastebin.com/9W7nid6H || This is the Setup: http://pastebin.com/bfPneGyq

Even with minimal setup, with ONLY Redpower(MrTJP Mod Core and Multipart)
And the newest Forge, results in this last mentioned Error.

The Latest Setup i tried atm:
Folder PATH listing for volume Main
Volume serial number is F85F-16A3
C:.
|   gentree.bat
|   gentree.txt
|   ProjectRed-1.7.10-4.7.0pre8.92-Base.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar
|   ProjectRed-1.7.10-4.7.0pre8.92-World.jar
|   
\---1.7.10
        CodeChickenLib-1.7.10-1.1.3.136-universal.jar
        ForgeMultipart-1.7.10-1.2.0.345-universal.jar
        ForgeRelocation-1.7.10-0.0.1.3-universal.jar
        ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
        MrTJPCore-1.7.10-1.1.0.31-universal.jar

**Comment by evg-zhabotinsky** [comment]
This time it is caused by old configs.
I got the same crash log by adding `mod:ProjRed|Compatibility -> coordpush` line to `config/ForgeRelocation.cfg`.
Whether it should be there or not and how it appeared there is another question. I don't know yet.

**Comment by edenprojectde** [comment]
Had to delete RedPower and ForgeRelocation config; but works fine now :100: 
Thank you evg-zhabotinsky :D

**Comment by MrTJP** [comment]
If you are crashing when adding PR mod ids to the configs, update Relocation.
