### ISSUE TITLE
Crash on server startup relating to ForgeRelocation and ProjectRed|Compatibility, possible bug

### ISSUE THREAD

**Issue by ajthemacboy** [MrTJP/ProjectRed#921]
I recently had this crash when starting my custom modpack server...: http://pastebin.com/6CGnYq9F

I solved it by deleting ForgeRelocation.cfg and letting it regenerate. I'm not sure why it happened in the first place, I didn't think to make a backup of the config before deleting it, but this may be a bug.

**Comment by MrTJP** [comment]
Update ForgeRelocation.
