### ISSUE TITLE
Crash when placing IC gate

### ISSUE THREAD

**Issue by Starhero** [MrTJP/ProjectRed#924]
I made an IC gate that has 2 counters and one timer in it along with an input and 3 out puts.

When placing this gate in the game, my client crashes. The server has no issues, besides a Network Dispatcher exception.

Log file is as follows: 

http://paste.ubuntu.com/12133004/

its quite big. This was the only pastebin that let me paste.

Sometimes when placing the IC gate, there is no crash, at that time though I think i had my input for turning off the timer, on, as a debug thing and hence that IC gate was a dud, it never flipped that even with a torch on that end of the IC gate.

Sometimes, it took multiple tries, but the server does let you place the block, as long as the packet that states to place said block reaches the server before the null pointer exception (assuming its a packet). I crashed 4 times before it actually placed the IC gate.

The gate works, so its very odd to me why placing the block is an issue.

**Comment by CarsonF** [comment]
This is the same error as #915

**Comment by Starhero** [comment]
+1 for experiencing then, my apologize for the double post.

**Comment by CarsonF** [comment]
@Starhero no worries. Just trying to make it easier for @MrTJP

**Comment by darth62969** [comment]
i noticed this one after i posted on #926 think they may be related, as i am crashing on Single Player,
