### ISSUE TITLE
Weird behavior when placing IC gate

### ISSUE THREAD

**Issue by peronix** [MrTJP/ProjectRed#926]
I built a 4 bit to 7 segment decoder as shown below:
![issue1](https://cloud.githubusercontent.com/assets/3010595/9430872/3c1e8992-49b8-11e5-9633-6b132f8fcd1e.jpg)

However, when the gate is initially placed, it does not produce any outputs as expected:
![issue2](https://cloud.githubusercontent.com/assets/3010595/9430873/5b3f5482-49b8-11e5-9a6f-29b8d8f235ad.jpg)

Half of the time the issue is resolved with one button press, half of the time it takes two. After that the gate works as expected.

When placing the gate down with inputs already pressed, half of the time it works right away, half of the time it does something like this:
![issue3](https://cloud.githubusercontent.com/assets/3010595/9430885/b36c9eee-49b8-11e5-979e-efc34e7aa912.jpg)

That should be a 6, but it appears 3 of the outputs failed to turn on. It can be fixed by turning off all of the buttons.

**Comment by MrTJP** [comment]
The IC engine is temporary.  It will be rewritten soon.  If this really is a bug, then thats when it will be fixed.

**Comment by darth62969** [comment]
it also crashes when placed without changing anything it that gui, while in creative mode. after the error(it does not crash the game) it opens the Multiplayer Screen. 

my Paistbin (output log from MultiMC)

http://pastebin.com/WpJE9n13

**Comment by Techokami** [comment]
Question to @peronix - I tried to replicate the presented circuit, but when it came time to assemble it, the IC Printer didn't have enough inventory slots for the materials required. How did you do it?

**Comment by hroatgar** [comment]
@Techokami You probably do not want to test this mod in survival. There is a creative chip that let you create IC gates without any materials. And besides, I think that the printer can take mats from side inventories (i haven't tested that myself tho).

**Comment by MrTJP** [comment]
Am currently working on a circuit compiler right now. You might want to just ignore such issues for now. The current system works great but for complex circuits it can get a little wonky.
