### ISSUE TITLE
a NPE

### ISSUE THREAD

**Issue by therealericbj** [MrTJP/ProjectRed#927]
I was told that this information might be useful to you.

http://openeye.openmods.info/crashes/10651f79858c5b795eb5090e17f53c61

I wasn't doing anything particular.  I was standing on a short obsidian wall, that was attached to the side of a tower.  I was looking down toward the ground and some EnderIO Capacitor Banks were in my field of view.  Other than that, there was just ground.

If there is any other information I can get for you, please say so and I will do my best.

Happy Hunting.

**Comment by MrTJP** [comment]
Will have to look into the way EnderIO does some of its rendering, it is interfering with Relocation hacks...

**Comment by MrTJP** [comment]
Fairly certain that Relocation has nothing to do with this crash.
