### ISSUE TITLE
[request] the old rp 65EL02 based forth computer?

### ISSUE THREAD

**Issue by iame6162013** [MrTJP/ProjectRed#928]
Will the redpower's 65EL02 (forth) computer be reimplemented?
I can not find any information about if this will be implemented, since we already have 2 major computer mods (computercraft and opencomputers) but those are both lua based and not a microprocessor. 
The forth based computer was for me always more fun to program in and I wanted to know if you guys are also going to implement a proper computer system.

**Comment by MrTJP** [comment]
For now, I don't plan on it. Also, 65EL02 is a custom system that eloraam designed, it's probably copyrighted.
