### ISSUE TITLE
Server thread hangs when you try to configure some gates in IC Workbench

### ISSUE THREAD

**Issue by Meegooo** [MrTJP/ProjectRed#930]
ProjectRed - [Snapshot from this commit](https://github.com/MrTJP/ProjectRed/tree/0524708d53384ef0e1c50f5c51c76d061c4faef6)
All deps were downloaded by gradle. I updated those ones:
CCL - 1.1.3.140
CCC - 1.0.7.47
NEI - 1.0.5.111

If you try to press "configure" on  XOR, XNOR, Multiplexer or Pulse Former (maybe i missed some), server thread goes into infinite loop at gatepartcomb.scala:129.

Seems related to https://github.com/MrTJP/ProjectRed/issues/925. Same gates, same loop, same bug

**Comment by MrTJP** [comment]
Fixed via db4f5574b663b36118c87fec5569f69d4f4a0f57
