### ISSUE TITLE
Crash when adding Inverted Lamps to FMP

### ISSUE THREAD

**Issue by Sandriell** [MrTJP/ProjectRed#931]
I tried adding the Inverted Lamps to the microblocks config on my server/client and it crashes when trying to view the recipe, either in NEI or in a crafting table.

Line added: "ProjRed|Illumination:projectred.illumination.lamp":0-31

Crash Log: https://gist.github.com/Sandriell/a76e7f6d63a52e033510

Forge: 1448
ProjectRed: 4.6.2.82
FMP: 1.2.0.344

**Comment by MrTJP** [comment]
Related to some NEI plugin that @rwtema made.

**Comment by Sandriell** [comment]
What plugin?

**Comment by Dream-Master** [comment]
@MrTJP 
So i want to know also which mod do you mean comes from rwtema.
