### ISSUE TITLE
Multipart Lights don't determine lighting state correctly

### ISSUE THREAD

**Issue by jpfx1342** [MrTJP/ProjectRed#932]
The problem is simple. Multipart lights determine their power level only on a per block basis, instead of using the proper FMP method to determine "face redstone part" power. This causes some incorrect behavior regarding when lights should be lit, as well as making it impossible to change lights in the same block individually.

(In the following images, all lights are Inverted to correspond with the torches: they darken when they receive a signal.)

This image shows the core of the problem. 
* The redstone torch on the left not extinguished, because it is receiving *no* signal.
* The redstone torch on the right is extinguished, because it *is* receiving a signal.
* Essentially, the torches extract the signal from the block behind them.
* The first set of fixtures are both extinguished, apparently because the block containing them is powered.
* The second fixture on the left is extinguished as well, even though the power doesn't seem to have any way to reach it.
* The third fixture on the left is not extinguished, because it is receiving *no* signal.
* The fixtures seem to draw their power from their own block, instead of the block behind them.
![2015-08-28_03 11 03](https://cloud.githubusercontent.com/assets/2425554/9541932/7142d524-4d32-11e5-8a43-a702bfea0a81.png)

This image shows another interesting side effect of this:
* The redstone torch is not extinguished, because the signal from the lever cannot reach it.
* The fixture *is* extinguished, even though it shouldn't be.
![2015-08-28_03 11 30](https://cloud.githubusercontent.com/assets/2425554/9542107/8899adc8-4d33-11e5-98b7-7ad9c471447e.png)

Looking at the code, the crucial difference seems to be this:
* [illumination/lightpart.scala](https://github.com/MrTJP/ProjectRed/blob/master/src/mrtjp/projectred/illumination/lightpart.scala) uses "world.isBlockIndirectlyGettingPowered(x, y, z)" to determine power state.
* [RedstoneTorchPart.java](https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/minecraft/RedstoneTorchPart.java) uses "RedstoneInteractions.getPowerTo(this, side) > 0" to determine power state.

**Comment by MrTJP** [comment]
Will look into this...

**Comment by MrTJP** [comment]
Fixed via 8bcc5dc4a5f6e3e92c7a849e4082a3a6a5d58841
