### ISSUE TITLE
Jetpack crashes client when flight is disabled on server

### ISSUE THREAD

**Issue by jojoxd** [MrTJP/ProjectRed#933]
running kcauldron/craftbukkit (I should test if this is the case on default forge + project:red too)

the server console just says 'flight is disabled on this server' and the client crashes with a Nullpointer instead of kicking me out the server

log: http://pastebin.com/LmkWzD0a

I'll add another post with the results on forge+project:red in a minute

**Comment by jojoxd** [comment]
can confirm, also happening on default forge (1403) install with only project:red;

server log of kicking: http://pastebin.com/nfQXu8SL
client does the same: http://pastebin.com/uKKYkYc1

can also confirm on clean forge 1492 (latest as of now)

**Comment by MrTJP** [comment]
will try and fix this, but can't make any guarantees. Don't want to use any hacks like other jetpack mods do.  If it comes down to it, I will make the jetpack uncraftable and unusable if flight is disabled..

**Comment by MrTJP** [comment]
Fixed with 78a4181436b8a76e3a20f3c1c85a71461e749e6c
