### ISSUE TITLE
Mechanical crashes the game upon installation

### ISSUE THREAD

**Issue by IndustrialGuy1** [MrTJP/ProjectRed#934]
As the title implies, I'm installing all the different sub-mods for project red and when Mechanical is put it, it crashes the game. Everything else seems to work just fine but I'm not sure what the problem is. Any help is appreciated, thank you!

![image](https://cloud.githubusercontent.com/assets/14032046/9563363/19148436-4e47-11e5-86f9-183bd0b7a9af.png)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 195420480 bytes (186 MB) / 344449024 bytes (328 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 12 mods loaded, 12 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized
	Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.0.0.244} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.3.7.32} [ProjectRed] (ProjectRedBase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation] (ProjectRedMechanical-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Errored
	ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility] (ProjectRedCompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination] (ProjectRedLighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion] (ProjectRedMechanical-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Errored
	McMultipart{1.0.0.244} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.0.0.244} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized

**Comment by makkarpov** [comment]
There is no crash report in your ticket. Please attach full crash report. Wrap it in triple backticks so Github will show it in readable form.

````
`` ` (remove space)
crash
`` `
````

**Comment by simon816** [comment]
You need Project Red Integration for Mechanical to work.

1.6.4? that's 2 years out of date. Update.

**Comment by IndustrialGuy1** [comment]
I use gregtech and traincraft and the best version is on 1.6.4 so that is where I will stay until they decide to go forward.

**Comment by amadornes** [comment]
You shouldn't expect to get support from most developers, then. As you said, everyone else has moved forward, which means 1.6 builds of most mods aren't supported anymore, just 1.7/1.8, so don't expect much.
Also, GregTech is available for 1.7.10. Granted it's not the same one as the one you're playing with, but no version of GT is even close to the one before it. Traincraft seems to have been abandoned, though. They had plans for 1.7 but an update was never released, so I don't know what you could do in that regard...

**Comment by MrTJP** [comment]
Can't offer support for such an outdated version
