### ISSUE TITLE
Crash on Client Server Join

### ISSUE THREAD

**Issue by Redlotus99** [MrTJP/ProjectRed#936]
My client loads fine, but when connecting to the server I run it bombs out with the error below.

http://pastebin.com/Sbd7XDJR

Pastebin couldn't handle the full log so here it is:

https://www.dropbox.com/s/h5k96c9hanskude/fml-client-latest.log?dl=0

**Comment by Redlotus99** [comment]
I believe this is the same issue listed here:

https://github.com/MrTJP/ForgeRelocation/issues/10

I will remove Rotatable Blocks and close this if this was the issue.

**Comment by MrTJP** [comment]
If you have rotatable blocks, then yes, that is the issue. I will get around to fixing that eventually.

**Comment by Zethalion** [comment]
Hi, I am encountering the same problem. Have you had the issue tackled by now maybe? I'd like to keep Rotatable Blocks if possible.

Thanks!
