### ISSUE TITLE
[request] New Gate

### ISSUE THREAD

**Issue by anar4732** [MrTJP/ProjectRed#937]
the following block is added if it will work like a gate

mod: Draconic Evolution
item: Potentiometer

function:
this gate will work as a counter
+ when it receives a signal from the output power level will increase each side
- when it receives the signal from the side will be reduced to a power level

-----------------------------------------------------------
 this text has been translated into English language by translator yandex

**Comment by MrTJP** [comment]
Not really going to be adding any more gates... Will most probably be possible in the future with ICs.
