### ISSUE TITLE
Issue with Router Utility and Routed Crafting Pipe

### ISSUE THREAD

**Issue by Nabilcon** [MrTJP/ProjectRed#939]
Hey, i'm having 2 issues, one with the Router Utility not showing GUI when right clicking(No error shows). And With Routed Crafting Pipe when trying to place it get's me the error( [Server thread/ERROR] [ForgeMultipart]: Missing mapping for part with ID: pr_rcrafting ).
I'm currently running the Karma mod pack 1.5.3.2.
All other PR pipes works as it should, only Routed Crafting Pipe and Router utility that is not working for me.

I've tried to solve the problem by using different versions of Forge without any sucess. Still same issues.
Also tried different versions of Project Red. 

Finally i tried installing Vanille minecraft with only Forge + Project Red, resulting in the same Issue and Error Message.
Only way i got it to work was when i tried Vanilla minecraft with PR version .82 then everything worked fine. 

Sidenote: Tried it on 2 different computers to eliminate the chance of it being my computer only with the issue.

Sorry for long post. I just love PR and i really wish i could somehow get it to work.

Thanks in Advance..

**Comment by MrTJP** [comment]
Crafting pipes have been deprecated. You can now just place a crafting chip inside of an interface pipe. 

Also, if you are talking about the upgrade gui when right clicking the router utility in the air, that has also been removed to favor a simpler system where each chip comes fully optimized out of the box.
