### ISSUE TITLE
Bundled cables don't connect to CC computers

### ISSUE THREAD

**Issue by Kaikaku** [MrTJP/ProjectRed#942]
Putting together a mod pack, using those three doesn't let the cables connect to ComputerCraft (1.74) computers:
ProjectRed-1.7.10-4.7.0pre9.92-Base
ProjectRed-1.7.10-4.7.0pre9.92-Integration
ProjectRed-1.7.10-4.7.0pre9.92-Lighting

In Direwolf20's 1.7.10 pack (v1.6.1) it's fine. He has:
ProjectRed-1.7.10-4.6.1.80-Base
ProjectRed-1.7.10-4.6.1.80-Compat
ProjectRed-1.7.10-4.6.1.80-Integration
ProjectRed-1.7.10-4.6.1.80-Lighting
ProjectRed-1.7.10-4.6.1.80-World

Not sure, is this rather a multipart issue?

**Comment by JBYoshi** [comment]
It only works if you have the Compat module installed.

**Comment by MrTJP** [comment]
Yes, compat is required for this.
