### ISSUE TITLE
[Issue] Crafting Pipes Are Broken - [Transportation]

### ISSUE THREAD

**Issue by chudders1231** [MrTJP/ProjectRed#943]
I was messing around with the pipes in the Transportation addon to ProjectRed. I wanted to craft the crafting pipe and discovered that it doesn't have a recipe. 
I was messing around and spawned it in to test whether it was just the crafting recipe that was broken, but no, i could not placed the crafting pipe down.

Has it been purposely removed? Does it need another addon to work? 

thanks
Chad

**Comment by MrTJP** [comment]
They are no longer necessary. Just place crafting chips into an interface pipe.

**Comment by chudders1231** [comment]
OK thanks dude. Was quite confused!!
