### ISSUE TITLE
Textures not displaying with recent update, Project Red ResourcePack error

### ISSUE THREAD

**Issue by CraftyGenius** [MrTJP/ProjectRed#950]
Playing on a DW20 server, and Project Red was recently updated to "4.6.1.80 - 4.7.0pre8.92", per the change log (http://www.feed-the-beast.com/modpacks/direwolf20_17/changelog/170).  Since then, none of the Sphax Direwolf resource packs are displaying Project Red textures.  Everything else is working fine, just not the Project Red items.

I believe this may be an issue with the update, since it was working fine prior to that, and I've tested every Sphax texture pack to see if it made a difference, which it didn't.

**Comment by MrTJP** [comment]
Texture packs need to be updated since the assets were moved around in ProjectRed.

**Comment by CraftyGenius** [comment]
Is there a breakdown of the updated file structure or changes that were made on how assets are now configured?

**Comment by MrTJP** [comment]
You can find it on this repository.
