### ISSUE TITLE
Daylight Sensor stays on ALL the time. 

### ISSUE THREAD

**Issue by jamjarxd** [MrTJP/ProjectRed#952]
Daylight sensor stays on all the time but on different moments they sometimes work properly but when a second one is placed then it'd be on all the time... Is there something I am doing wrong or is this a really bug that you have overlooked? A broken ,jar maybe?

**Comment by MrTJP** [comment]
The sensor has different modes, you probably aren't using it right.

http://projectredwiki.com/wiki/Light_Sensor
