### ISSUE TITLE
ProjectRed Exploration block dupe

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#953]
Hi,
I got a dupe report lately from someone using my [modpack](http://the-1710-pack.com/), and the ProjectRed mod v4.7.0pre8.92.
You can [craft](http://i.imgur.com/RFrdUQi.png) ProjectRed's silver blocks in the default crafting grid with **4 silver ingots**.
You can also craft other silver blocks using the crafting table with **9 silver ingots**.
You can change the silver blocks using Chisel.
I got now reports that it's not just working with silver, but with other ingots too.
Is this fixed in v4.7.0pre9.92 of the mod? If not, there's anything you can do about it?
Thanks!

**Comment by MrTJP** [comment]
This was already fixed.
