### ISSUE TITLE
Ticking Block Entity

### ISSUE THREAD

**Issue by darth62969** [MrTJP/ProjectRed#954]
http://pastebin.com/fMwc9AVR

don't quite know why this is happening it was working a few days ago but i keep on crashing when i try to load my world.

i built a couple of 4 bit registers that were supposed to move what ever i entered into them to down a register, and then tested it, it did not work and then closed the game as i ran out of time in class. after that i tried to reopen the level and it keeps crashing with a ticking block entity error. so i would like to find a solution to this. going to download mcedit and delete the light blocks that could be causing the issue.

**Comment by MrTJP** [comment]
Likely a non-issue as of now. Report back if this is still a problem. The error was caused by micro blocks.
