### ISSUE TITLE
Trying to smelt signalum creates molten conductive redmetal

### ISSUE THREAD

**Issue by Zaflis** [MrTJP/ProjectRed#958]
This is related to addon mod ProjectRed Compatibility, which makes ProjectRed compatible with TiC. Simply put:
(2 copper ingot)+(3 redstone dust) makes (1 conductive redmetal) and
(1 silver)+(3 copper)+(10 redstone) would make (4 signalum).

So could you perhaps combine the conductive redmetal with molten silver to make signalum? For now i could just disable the compatibility mod.

PS. Also related is that redstone dust smelts into Liquid redstone, instead of Destabilized redstone.

**Comment by MrTJP** [comment]
Yes, TC compatibility needs a lot of work :_

**Comment by MrTJP** [comment]
For now, 897d861805701e3c2e1834e7f7f111b37df0a324 adds a config option to disable each compatibility plugin. If the recipes are conflicting, just disable the TC one for now...
