### ISSUE TITLE
IC Printer's inventory too small

### ISSUE THREAD

**Issue by Yggdrasil128** [MrTJP/ProjectRed#960]
I love playing around with Fabrication, but today i encountered a problem:
Especially with large blueprints using many cable colors, it is not possible to fit everything the printer needs to print the IC into the printer's inventory.
The printer only has 18 slots, but there are already 16 kinds of insulated wires, 17 kinds of bundled cables, several types of plates (conductive plate, cathode, anode, etc).

Thus, it is not possible to print those blueprints without using a creative IC chip.

But:
A possible solution for this would be making the IC printer's inventory work like the Decobench from Decocraft.
I've played around with the GUI and this is what I came up with:

The first panel shows the stuff needed for printing, as usual.
The second panel shows the stuff that is currently stored inside the printer.
You can add items to the printer by placing them in slot 3.
And if you click on an item on panel 2, it will be removed from the printer and appear in slot 4.

The empty space at the bottom right may be filled with a start/stop button or something.

![projectred ic printer](https://cloud.githubusercontent.com/assets/13046780/10597379/9ace7e12-76ee-11e5-94f4-e3a9b8657a09.png)

How does that sound?

**Comment by MrTJP** [comment]
You can put a chest next to the printer and put materials in there.

**Comment by Yggdrasil128** [comment]
Thank you :)

**Comment by Synergyst** [comment]
This does not work anymore in the 1.12.2 versions.
