### ISSUE TITLE
Stacking Latch missing for IC Workbench

### ISSUE THREAD

**Issue by cubinator** [MrTJP/ProjectRed#962]
The IC Workbench doesn't offer a Stacking Latch.

![screenshot2](https://cloud.githubusercontent.com/assets/6325082/10711305/2ea2a826-7a77-11e5-96c5-0acbca224c56.png)

Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1448
MrTJPCore 1.1.0.27
Forge Multipart 1.2.0.345
Forge Relocation 0.0.1.3
PR Core 4.7.0pre5.89 (+ Integration, Fabrication, Mechanical, Lighting, World, Compat)

(Other mods: TooManyItems, BuildCraft, ComputerCraft, IndustrialCraft 2, NBTEdit, Forge Microblocks)

**Comment by MrTJP** [comment]
The IC Workbench doesn't offer many gates. They have not been implemented yet.
