### ISSUE TITLE
Paths on Redstone Integration Tiles aren't the right direction

### ISSUE THREAD

**Issue by ranger135xp** [MrTJP/ProjectRed#963]
Hello, I just want to start by saying that I love this mod and thank you for your version of RP2!

From what I've seen in my 1.7.10 world, the redstone integration tiles appear to have their paths rotated clockwise one too many.
![2015-10-27_23 50 33](https://cloud.githubusercontent.com/assets/15115164/10779330/99298fb2-7d05-11e5-9ba7-ee0e2ad87df9.png)

From the image, the truly disabled line is the East "IN" closest to me. The line that is receiving power from the torch is the South "IN".

I noticed this while trying to disable lines on a NOT gate and I saw that the only IN line appeared disabled and the one OUT line I wanted out never appeared out. Functionally, it works correctly and this is only visual.

http://pastebin.com/sA7wne3a is my mod list.

**Comment by MrTJP** [comment]
This might be some residual effects after an update, but currently, if i place down a new tile and try, everything is correct. Does this happen when you place down a new tile?

**Comment by ranger135xp** [comment]
Yes this happens directly after placement. It doesn't correct itself or develop over time. Maybe one of the other mods is causing this?

**Comment by MrTJP** [comment]
The thing to do is to try with just PR, and then add mods until you find the one causing it. I'm not getting this issue..

**Comment by ranger135xp** [comment]
I'll try that and see what happens. I'll get back to you with any findings.
