### ISSUE TITLE
Block Breakers cannot break Lantea Craft ores.

### ISSUE THREAD

**Issue by Shuudoushi** [MrTJP/ProjectRed#964]
Lantea Craft ores are diamond levels ores. The rest is pretty self explanatory from the title.

A Lantea Craft dev requested this to be included http://git.io/vW9MF

**Comment by MrTJP** [comment]
Block breaker doesn't break blocks that require diamond pickaxe. There will be a version crafted with a diamond pick instead of iron that will do this.
