### ISSUE TITLE
Request : Config for removing the bubbles and other effects when autocraft is active

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrTJP/ProjectRed#966]
^ Because like Logistics pipes, when I look at the direction of the pipes, I experience fps drops :/

Nvm if it's here and I accidently missed it in configs. 

PS : Is the bug Vaygrim talked about half a year ago was fixed ?

**Comment by MrTJP** [comment]
A separate config option for this makes sense. Will add.

**Comment by Carbon-Ghost** [comment]
thx, what about that bug ( just out of curiosity ) ? It has been fixed right ( well game seems smoother now at least, a large mechanical system seems working better than before as my game is less slower when near one ).

**Comment by MrTJP** [comment]
Which bug are you referring to? Can you link it?

**Comment by Carbon-Ghost** [comment]
Dunno if I can link it, but Vaygrim evoked it in his let's play, saying about a memory leak thingy.

**Comment by MrTJP** [comment]
Oh yes. There have been a few memory leaks reported before. I fixed a few of them, and there don't seem to be anymore..

**Comment by Carbon-Ghost** [comment]
Haven't experience any issues with them so I thought you fixed them, and so I was right :D

**Comment by MrTJP** [comment]
Added via c23276814b3084a29b1559c56f7bdee7e70c1a01

**Comment by Carbon-Ghost** [comment]
Yay thanks :D
