### ISSUE TITLE
Problems with the Mechanical logistic system

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrTJP/ProjectRed#967]
1 : The autocrafting system seems to not be fuzzy even if I set the config to blacklist, so it specifically requests jungle wood even though it can use oak ones. Gonna retest that to see if it's not on my side but that was weird..
2 : The autocrafting system forgets the recipes it had been assigned after world reload and sometimes after chunk reload, this is problematic, if possible may you add a list for it to remember ?

**Comment by Tej1996** [comment]
If you want fuzzy, you have to configure it to do so. 

And I have not implemented saving and loading current operations yet. So all chunks need to be active always.

**Comment by MrTJP** [comment]
I admit, it is a bit confusing right now, but it is possible to use fuzzy crafting. In the crafting chip, you have to set that slot to be fuzzy.

**Comment by Carbon-Ghost** [comment]
1 : Mmh, gonna recheck but I was pretty sure I set it to ignore everything...
2 : Will you implement it ?

Update : Oh kk, also may you check my previous issue about large mechanical systems please :/

**Comment by MrTJP** [comment]
Take a screenshot of your configuration. I will try to help. 

And I have plans to implement it.

**Comment by Carbon-Ghost** [comment]
Gonna do it tomorrow, also very cool mod, I remember older issues making it unfortunately hard to play with but now it's awsome :D  ( I prefer this to the new AE xD and LP as there is no item leaks :) ).

**Comment by Carbon-Ghost** [comment]
Kinda old issue now, but gonna see if the mod updated and retry if the problems are still here ^-^ ( sorry had a lot of work to do for lycée ).

**Comment by Carbon-Ghost** [comment]
back, just out of curiosity, did updates add functionality :3 ?

**Comment by MrTJP** [comment]
The next update will fix some issues. But this particular case, fuzzy crafting works. Just need to configure it properly.

**Comment by Carbon-Ghost** [comment]
kk thx :D
