### ISSUE TITLE
[1.7.10]Industrial Craft 2 Experimental Forge Hammer item and Project Bench

### ISSUE THREAD

**Issue by kolbka96** [MrTJP/ProjectRed#968]
Hello!
I have a bug using with Forge Hammer item in Project Bench.
When I create any plates on Project Bench after the expiration strength(default 80) this item become a infinite uses. Wire-cutter works correctly.
Screenshot: 
![2015-11-17_19 20 36](https://cloud.githubusercontent.com/assets/15887188/11208057/99ef54ee-8d64-11e5-8694-e1dc9e98bd23.png)
It's can be fixed?

P.S.
Forge: 10.13.4.1517
IC2: 2.2.766-experimental
PR: all 4.7.0 pre9.92

**Comment by MrTJP** [comment]
Fixed via 63fc6e95058e11d59a035209abd7ea161d252b0d
