### ISSUE TITLE
Red Alloy Pressure Tube?

### ISSUE THREAD

**Issue by Morketh** [MrTJP/ProjectRed#970]
Was wondering if it could be a possibility with the addition of frames, motors, and actuators it would be nice to be able to move block breakers around with there own wire (or Block placers for that matter). would be a great addition to bringing back Tunnel Boring Machines that can place out blocks in a pattern.

**Comment by MrTJP** [comment]
Take a strip of redstone block and right click on the tube.

**Comment by Morketh** [comment]
O_e i cant believe its that simple. your a genus @MrTJP
