### ISSUE TITLE
Request: new features for fabrication

### ISSUE THREAD

**Issue by hroatgar** [MrTJP/ProjectRed#971]
This is a copy of my post on the curse forum. You asked to post it here instead.

So here is a list of the features i would really like to see implemented in the fabrication mod :

1- The ability to copy and rename blueprints
Sometimes we need to make similar blueprint that require a simple modification to make it unique and its impossible at the moment. It would be nice to be able to reuse previous blueprint and modify them to create a new one and saving a lot of useless work. Also, the name you give to a blue print is never final. It may seem unnecessary but... gosh i'm perfectionist and i would like the name of my blueprint to reflect whats on it.

2- The ability to backup/transfer/share blueprints
I looked everywhere in my save folder and, correct me if i'm wrong, but my blueprints are nowhere to be found. Last day a crash to main menu occurred and when i reloaded my save, guess what, i big part of what i made disappeared along with my 10 hours work blueprint (which i was kinda proud of and that is why i'm writing this post). Obviously i'm not mad because i lost everything, i perfectly understand the risk of using a mod (i'm a software engineer). So, it would be nice to write the blueprints in a separated file in the save folder.

3- The ability to copy/paste/move/delete/undo/redo parts in a blueprint
When i first used this mod i was surprised that this feature was missing knowing that similar mods have already implemented it (maybe it is there but its well hidden). I will not really elaborate on this one because is it simply mandatory and fundamental.

**Comment by MrTJP** [comment]
A lot of these are planned for the future.

**Comment by Voxel-Friend** [comment]
Question about this (glad I wasn't the only one who wanted these.) Will these changes be in 1.7.10, or only higher versions?

**Comment by Savallator** [comment]
What is the status on this? About 7 months have passed since then, are there any news on copy/rename?

**Comment by MrTJP** [comment]
Ability to rename a blueprint is now native in the ic workbench. Import/export should be done through another block, copy/paste is still pending but won't require too much work, simply not priority over testing the new circuit compiler.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
