### ISSUE TITLE
Missing gates in fabrication

### ISSUE THREAD

**Issue by hroatgar** [MrTJP/ProjectRed#972]
Since this is more of a problem than a request i separated it from my other post.

I found that the AND CELL and the DATA CELL are missing in the fabrication part. These gates are simply amazing and shouldn't be left aside. Please include them ASAP.

**Comment by hroatgar** [comment]
OK a little bump here today. This issue is a "repost" from a month+ old post from the curse forum as requested by mrTJP because he stated that he is more active here. I don't know if i'm missing something or i'm simply being ignored. A Little sign of life would be greatly appreciated.

**Comment by MrTJP** [comment]
Not ignoring you, I think I've answered this somewhere before. The backend of the circuit platform is being rewritten, so there's no point of writing more gates at the moment. I know it's been a while, but I'm not finding much time as of late to work on this..

**Comment by hroatgar** [comment]
Alright thank you, please keep us updated on your progress.

**Comment by MrTJP** [comment]
Fabrication rewrite is done. Just adding a few features for beta release now. Only few gates will be included at first for engine testing
