### ISSUE TITLE
Sequencer gate acting different than the page specifies it should be.

### ISSUE THREAD

**Issue by realflow100** [MrTJP/ProjectRed#974]
Placing a sequencer down . immediately i see an issue. It flickers wildly back and forth in one spot at one specific output no matter what i set the timing of it to.. it does change output to a random output if i change the timing but it doesnt go around in a circle like the wiki says it should be... odd?
Is that normal and intended function? It sure doesn't seem like it.
Nothing obvious seems to be causing the weird erratic behavior. it just does it.
tried with no other mods installed besides project red (no optifine either)
still seems odd.
Any idea's? There's no errors in the console or game log.

**Comment by MrTJP** [comment]
Are you in some type of eternal day world or something?

**Comment by realflow100** [comment]
What do you mean? The gamerule for daylight cycle?
 

    On Friday, January 8, 2016 2:11 PM, MrTJP <notifications@github.com> wrote:
 

 Are you in some type of eternal day world or something? —

**Comment by MrTJP** [comment]
Yes, that or in a mystcraft eternal day age.
