### ISSUE TITLE
Missing data cell and AND cell in IC blueprint

### ISSUE THREAD

**Issue by ExcitedPlayer** [MrTJP/ProjectRed#979]
hello MrTPJ, i started to work on 8 bit computer using 4 IC, i tested all using normal way, but when i started to build processor part schematic, i found that Data cell and AND cell is missing in IC blueprint workbench, please try to add them soon as possible, thanks :)

**Comment by MrTJP** [comment]
Again, they will be added later on, everything is going to be reworked.
