### ISSUE TITLE
Project/Auto benches consume GT tools.

### ISSUE THREAD

**Issue by Teteros** [MrTJP/ProjectRed#980]
Gregtech tools in Project/Auto workbenches are now consumed since 63fc6e9.
Items crafted using GT tools before the update worked fine and crafting used up tool durability as expected.

[Here is a demonstration of the issue](https://i.imgur.com/nARoYh6.gifv)

**Comment by Teteros** [comment]
c9467d4 works, if anyone is having the same issue.

**Comment by MrTJP** [comment]
GT must be using NBT data to keep track of damage. Your patch might fix this issue but it causes this same behavior on all other tools such as saws.  

I'll try and find another solution...

**Comment by Teteros** [comment]
>Your patch might fix this issue but it causes this same behavior on all other tools such as saws.

@MrTJP
All tools I tested including saws added by projectred appear to take damage as intended in the ProjectBench.
Is there anything more to it?

![projredgtsawprojectbench.gif](https://cloud.githubusercontent.com/assets/5067989/12834918/7646f984-cba3-11e5-86e2-9f07124a09a5.gif) ![projredredsawautobench.gif](https://cloud.githubusercontent.com/assets/5067989/12835053/9a4d9fb2-cba4-11e5-81ee-0b9c520aafa3.gif)

**Comment by MrTJP** [comment]
Im guessing its the way gregtech handles damaged items. It works for all things including bucket recipes, wrenches, etc.

Maybe GT items are storing damage stats in NBT instead of the item damage parameter. Or the item classes might not properly be reporting themselves as container items.

**Comment by TedKnudsen** [comment]
@MrTJP, I see you were unable to find a resolution for this issue.  Is there any information you could be provided that might help isolate a working solution?

GregTech is a rather large and popular mod, and your Project Bench (typically) provides ideal logistical approaches to solving its in-game problems.

**Comment by JasonMcRay** [comment]
To add... GT is indeed storing its damage as NBT. Every crafting takes different chunk of the damage depending on what is crafted

**Comment by MrTJP** [comment]
I just haven't had the chance to look into this as much as I would've liked. I'm very busy at the moment...
