### ISSUE TITLE
Integrated circuits don't like signals produced by other integrated circuits

### ISSUE THREAD

**Issue by raycar5** [MrTJP/ProjectRed#983]
I'ts described best by this gif of the issue: https://gfycat.com/IdioticShoddyBobwhite

**Comment by Hexicube** [comment]
Try putting a lamp on the end of the far cable, I've come across a similar issue with a block from my own mod. Seems like the alloy wire state isn't updating if the signal comes from bundled wires.

**Comment by HunterTBragg** [comment]
I am experiencing the same issue, however, I've found a temporary fix by having the outputs of the bundled cables from one gate be passed though or gates outside of the IC. This is still a very annoying bug. Recently, I made seven different chips that were meant to be placed directly next to each other but I couldn't get it to work because of this glitch specifically.

Here is an example of the temporary fix I was able to come up with.
http://i.imgur.com/D9vVUMd.png

**Comment by psoftware** [comment]
News about this issue? I'm working with multiple ICs and seems that bundled cables won't update their state correctly near other ICs, so I think it's the same issue.
I crafted some ICs, that can be "selected" by a 8-bit address (a bundled cable). If I use the bundled "keyboard" there are no problems, but if I use another circuit composed by other ICs, the devices are not selected correctly, even if lamps (connected to the bundled cable) report the correct address.
Sometimes breaking and placing the bundled cable changes the ICs status.
I tried a lot of fixes but they won't work.

If it can be useful, I can make a video or gif related to the issue

**Comment by MrTJP** [comment]
No need. Still knee deep in figuring out the new IC system, these bugs will be nonexistent then. I hate giving ETAs, but don't expect it until the summer. 

Other bugs and stuff not related to ICs will be worked on soon though.

**Comment by Tahvohck** [comment]
So, it's now a month into fall and this is still affecting ICs. Any news, particular annoyances? I have this 5x3 power cell configuration that really needs the density of IC-to-IC.
![2016-10-20_14 31 22](https://cloud.githubusercontent.com/assets/1668722/19572845/e239f71e-96d1-11e6-823c-c5da98fc00fa.png)

**Comment by psoftware** [comment]
Hi, can I ask you why is this marked as Invalid? Is this issue resolved?
I'm waiting for about a year a fix for this problem.

Thanks for your work
