### ISSUE TITLE
SextiarySector2 somehow used wire textures...

### ISSUE THREAD

**Issue by Nikslg** [MrTJP/ProjectRed#985]
![2016-01-17_18 15 05](https://cloud.githubusercontent.com/assets/15956980/12378343/9c7f937e-bd4b-11e5-8f50-168767a2d253.png)
![2016-01-17_18 10 35](https://cloud.githubusercontent.com/assets/15956980/12378344/9c9b7e5e-bd4b-11e5-8ea3-49f5d2e6ab25.png)

It started happening since last ProjectRed update.
Anything to fix it?

**Comment by Nikslg** [comment]
Sorry, somehow reason of i was in... Immersive Engineering mod ._.

**Comment by MrTJP** [comment]
Perhaps talk to the other mod's author.
