### ISSUE TITLE
Item barrel crash

### ISSUE THREAD

**Issue by devryb** [MrTJP/ProjectRed#987]
http://pastebin.com/mSE4ATYW

Not sure how to recreate this issue but noticed there were a bunch of corrupted barrels on the map that I had to remove in order for people to go to that area again.

Version: ProjectRed-1.7.10-4.7.0pre10.93

**Comment by devryb** [comment]
I'm guessing those barrels held items from mods that were removed from the server and client as we recently did a major update to the modpack.

**Comment by MrTJP** [comment]
This is being looked into...

**Comment by MrTJP** [comment]
Invalid. Barrels are slated to be removed in 1.11.
