### ISSUE TITLE
Copper Ore Generates Even When Disabled

### ISSUE THREAD

**Issue by CandiceJoy** [MrTJP/ProjectRed#989]
The title says it all...I have copper ore generation disabled in the config and it generates in the world anyway.  I'm using CofH generation, but that shouldn't make a difference, I wouldn't think.

"world generation" {
    B:"Copper Ore"=false
    I:"Copper Ore resistance"=0
    B:"Copper Ore retrogen"=false

**Comment by Monstrel** [comment]
The key for the "world generation" group recently changed to "World Gen".  Instead of altering the existing config, a new World Gen block was created in the config files with default values.  I was caught out by this too :-/

**Comment by MrTJP** [comment]
Yes. As I've said before, you should delete your configs and generate a new one, then copy over your settings.
