### ISSUE TITLE
4.7.0pre11 - no download available

### ISSUE THREAD

**Issue by walkerjonny** [MrTJP/ProjectRed#990]
Within Minecraft I'm told that v4.7.0pre11 is available. However there is no download available for it on your website and on curse. All downloads point to v4.7.0pre10.
The only v4.7.0pre11 download I have found so far comes from a fork of your master by Tetero and is 24 days old.
https://github.com/Teteros/ProjectRed/releases

**Comment by MrTJP** [comment]
I guess there was a glitch in the matrix. I've reuploaded the files to curse. 

Also @Teteros might want to consider removing the public builds that he has available, because the build numbers are different from my own and it may confuse people.

**Comment by Teteros** [comment]
Apologies, I'll use your build numbers from now on.

I'll keep the fork updated till solution arises for https://github.com/MrTJP/ProjectRed/issues/980.
