### ISSUE TITLE
FakePlayer/Permissions support

### ISSUE THREAD

**Issue by MrNice007** [MrTJP/ProjectRed#991]
I am using a mod serwer with plugins enable i found that protection plugin are disabling functionality of machines

The issue is same type like that is https://github.com/BuildCraft/BuildCraft/issues/2224

Manly Block placeevent is stopped and Block Placer, Braker don't work tested on them.
Is going Project red to have a support of Permissions or what co called fakeplayer.. or it has and we don know it :)

**Comment by MRebhan** [comment]
This is not Project Red's fault as it only tries to place blocks, if it doesn't have permission to it will obviously fail. Use a mod that protects your blocks like the security station of PneumaticCraft
