### ISSUE TITLE
Project Bench Bucket Duplication

### ISSUE THREAD

**Issue by johneddcooper** [MrTJP/ProjectRed#992]
When crafting some recepies that have buckets containing fluids, the empty bucket will appear in the players inventory and remain in the crafting table. Setup: FTB Infinity Evolved Expert Mode, crafting minefactory reloaded plastic sheets. The Ender IO Fuel bucket duplicated.

**Comment by Dream-Master** [comment]
We have the same problem with Buckets.

**Comment by Teteros** [comment]
@johneddcooper 
If you are using minetweaker you have to use `.transformReplace` instead of `.giveBack` method, but judging from your comment that's not it.
