### ISSUE TITLE
Wire not turning off.

### ISSUE THREAD

**Issue by NightOps007** [MrTJP/ProjectRed#994]
I was doing some playing around with your mods and quickly discovered that the wires are bugged.
Mods installed are as follows:
  Forge(7.99.36.1558)
  ForgeRelocation-0.0.1.4-universal
  ProjectRed-1.7.10-4.7.0pre11.94-Compat
  ProjectRed-1.7.10-4.7.0pre11.94-Base
  ProjectRed-1.7.10-4.7.0pre11.94-Mechanical
  ProjectRed-1.7.10-4.7.0pre11.94-World
  ProjectRed-1.7.10-4.7.0pre11.94-Fabrication
  ProjectRed-1.7.10-4.7.0pre11.94-Lighting
  ProjectRed-1.7.10-4.7.0pre11.94-Integration
  multipart(1.7.10-1.2.0.345)
  MrTJPCore(1.1.0.33)
After red alloy wire or insulated wire were turned on, if they had more than 1 wire, they would not turn off again without updating the wire as shown in vid: https://youtu.be/mh4jUPtRGxE

**Comment by NightOps007** [comment]
Did some further testing and discovered that this problem is new to the latest version; did not exist in pre11.93 version.

**Comment by MrTJP** [comment]
Lol, major derp on my part. Fixed with c9e29a7a9809061bf5893d454a6080e5bb3b2995.

**Comment by DrakoAlcarus** [comment]
Yeah, same. Thanks for the fix!
