### ISSUE TITLE
Redstone Wire self powering other redstone wires causing infinite loop of "power"

### ISSUE THREAD

**Issue by KJP12** [MrTJP/ProjectRed#995]
When you power a redstone wire then unpower it, it will still be powered. Mod version is 4.7.0 pre 11.94. Gotten from the wiki.

Here is how to reproduce:
1. Place any redstone wire next to each other(doesn't matter what type as long they connect)
2. Power the wire
3. Unpower it.
4. Have the wire still have "power" from nowhere.

**Comment by kenzierocks** [comment]
This looks like #994.

**Comment by MrTJP** [comment]
It was just fixed. I'm gonna push this version now because this is a fairly extreme issue.
