### ISSUE TITLE
Redstone signal does not shut off

### ISSUE THREAD

**Issue by TheNumenorean** [MrTJP/ProjectRed#996]
I present the following 4 pictures. Redstone signal does not seem to propagate properly around corners.

Notably, there is no input redstone signal to the cable at any point, and the visible cable is connected to a bundled cable, which is also giving off a signal when connected that does not have any source.

![2016-02-09_14 22 03](https://cloud.githubusercontent.com/assets/809047/12932744/2549ee4e-cf39-11e5-93c2-7c3415b072b1.png)
![2016-02-09_14 23 54](https://cloud.githubusercontent.com/assets/809047/12932741/2548b290-cf39-11e5-9d29-36c83a130173.png)
![2016-02-09_14 23 59](https://cloud.githubusercontent.com/assets/809047/12932743/2549aede-cf39-11e5-9c7d-4be787e922ad.png)
![2016-02-09_14 24 04](https://cloud.githubusercontent.com/assets/809047/12932742/25493530-cf39-11e5-938e-8522aaa44682.png)

**Comment by MrTJP** [comment]
Update to the latest version.

**Comment by TheNumenorean** [comment]
Ah. Thanks
