### ISSUE TITLE
Bus transiever causes signals to persist

### ISSUE THREAD

**Issue by TheNumenorean** [MrTJP/ProjectRed#997]
My setup involves a red wire hooked up to a output, connected to a bundled cable which goes through the bus transceiver. on the other side, 3 outputs are hooked up to the bundled cable. The transceiver has signal high on both sides. Once the red wire is turned on, it cannot be turned off, excepting switching off one of the sides of the Transciever. Replacing it with just a bundled cable makes it work just fine.

**Comment by MrTJP** [comment]
Sounds like you are not on the latest version...

**Comment by TheNumenorean** [comment]
It is, in fact, updated to the newest version. Thus why other cables actually work.
