### ISSUE TITLE
Issue with Computercraft/Bundled Cable

### ISSUE THREAD

**Issue by jakendrick3** [MrTJP/ProjectRed#998]
Version: Minecraft 1.7.10, Computercraft 1.7.5, Project Red 4.7.0
The bundled cables are simply not registering with computercraft. Redstone works fine, the code isn't the problem as I used print() to make sure it was working as well as testing it with standard Redstone. It's simple setBundledOutput() not working with the cables.

I have RedPower Compat so, I expected it to work. I tryed the load order change as well, however no change.

I've already filed the issue on the CC forums, they told me to report it to you. 

EDIT: Was using Pre12, Reverted to pre9 and it worked.

**Comment by hpwebcamABLE** [comment]
Possibly related to changes in this file:
https://github.com/MrTJP/ProjectRed/commit/897d861805701e3c2e1834e7f7f111b37df0a324#diff-3dd929504ee21ea54941339465352306L1

**Comment by ChristianLW** [comment]
Since you got it to work, why not close the issue?

**Comment by ranger135xp** [comment]
can we re-open and possibly get a bugfix? This is killing me, lol. I reverted CC to 1.74 and everything works with Pre12 as for CC and bundled output goes. CC itself likes to throw NPE errors and 1.75 fixes that. Hence the issue, 1.75 bundled output and Pre12 don't seem to get along for some reason.

@MrTJP your precious input is much appreciated if you can fix this.
